/**
 * Build-only: bundle the compiled Wildlands CLI into one dependency-free CommonJS executable.
 *
 * The result runs with plain Node.js 22+ and no node_modules or .generated directory. Every
 * runtime resource the CLI reads is embedded: content JSON as exact text parsed at first use,
 * and two integrity-checked raw-deflate payloads: the trusted Godot runtime bundle (the runtime
 * closure only) and the opt-in engine-source bundle, inflated only when an operation asks for
 * engine sources (engine export, compile --with-engine-sources). They are compressed with the pinned pure
 * JavaScript pako, not Node's zlib, so the bytes do not depend on the Node release or CPU.
 * Output is byte-deterministic for a given .generated tree: no timestamps, absolute paths or
 * source maps. Run `npm run build` first.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {inflateRawSync} from 'node:zlib';
import {spawnSync} from 'node:child_process';
import {build, type Plugin} from 'esbuild';

// pako ships no declarations; this is the one deterministic encoder entry point used here.
const pako = require('pako') as {deflateRaw(data: Uint8Array, options: {level: number}): Uint8Array};
const PROJECT = path.resolve(__dirname, '../..');
const GENERATED = path.join(PROJECT, '.generated');
const ENTRY = path.join(GENERATED, 'tools', 'wildlands-cli.cjs');
const ENGINE_PATH = 'runtime/engine-source-bundle.json';
const EMBEDDED = 'wildlands-embedded-resources';
const BANNER = '// Generated by source/wildlands/source/tools/cli-bundle.cts - do not edit.\n' +
  '// Rebuild: cd source/wildlands && npm ci && npm run build:cli. Handbook: docs/reference/wildlands-cli.md\n';

interface RuntimeBundle {format: string; schemaVersion: number; files: {path: string; encoding: string; content: string}[];}
export interface BundleResult {bytes: Buffer; sha256: string;}

const sha256 = (value: string | Uint8Array): string => createHash('sha256').update(value).digest('hex');
const readGenerated = (name: string): string => fs.readFileSync(path.join(GENERATED, name), 'utf8');
/** Deterministic payload; the runtime module verifies size and SHA-256 after inflating. */
function payload(text: string): string {
  const raw = Buffer.from(text, 'utf8'), data = Buffer.from(pako.deflateRaw(raw, {level: 9}));
  if (!inflateRawSync(data).equals(raw)) throw Error('Embedded payload does not round-trip.');
  return JSON.stringify({bytes: raw.length, sha256: sha256(raw), data: data.toString('base64')});
}

/** The runtime bundle never carries engine sources: they are a separate, lazily inflated payload. */
function embeddedModule(): string {
  const engineText = readGenerated('engine-source-bundle.json'), runtimeText = readGenerated('wildlands-runtime-bundle.json');
  const runtime = JSON.parse(runtimeText) as RuntimeBundle;
  if (runtime.files.some(file => file.path === ENGINE_PATH)) throw Error('Runtime bundle unexpectedly carries the engine sources. Rebuild Wildlands.');
  return [
    '"use strict";',
    'const {inflateRawSync} = require("node:zlib"), {createHash} = require("node:crypto");',
    `const RUNTIME = ${payload(runtimeText)};`,
    `const ENGINE = ${payload(engineText)};`,
    'function inflate(item) {',
    '  const raw = inflateRawSync(Buffer.from(item.data, "base64"), {maxOutputLength: item.bytes});',
    '  if (raw.length !== item.bytes || createHash("sha256").update(raw).digest("hex") !== item.sha256)',
    '    throw Error("Embedded Wildlands resource integrity failed. Rebuild bin/wildlands.");',
    '  return new TextDecoder("utf-8", {fatal: true}).decode(raw);',
    '}',
    'exports.engineSourceText = () => inflate(ENGINE);',
    'exports.runtimeText = () => inflate(RUNTIME);',
    ''
  ].join('\n');
}

/** Replace the two large generated JSON reads with lazy embedded loaders; keep all other JSON exact. */
function resources(used: Set<string>): Plugin {
  const lazy: Record<string, string> = {
    'engine-source-bundle.json': `module.exports = JSON.parse(require(${JSON.stringify(EMBEDDED)}).engineSourceText());`,
    'wildlands-runtime-bundle.json': `module.exports = JSON.parse(require(${JSON.stringify(EMBEDDED)}).runtimeText());`
  };
  return {name: 'wildlands-cli-resources', setup(context) {
    context.onResolve({filter: new RegExp('^' + EMBEDDED + '$')}, () => ({path: EMBEDDED, namespace: EMBEDDED}));
    context.onLoad({filter: /.*/, namespace: EMBEDDED}, () => ({contents: embeddedModule(), loader: 'js'}));
    context.onLoad({filter: /\.json$/}, args => {
      const relative = path.relative(GENERATED, args.path).replaceAll(path.sep, '/');
      const replacement = lazy[relative];
      if (replacement) { used.add(relative); return {contents: replacement, loader: 'js'}; }
      // Match Node's require(): strip one BOM, then JSON.parse the exact text when first required.
      const text = fs.readFileSync(args.path, 'utf8').replace(/^\uFEFF/, '');
      JSON.parse(text);
      return {contents: `module.exports = JSON.parse(${JSON.stringify(text)});`, loader: 'js'};
    });
  }};
}

export async function bundleCli(): Promise<BundleResult> {
  if (!fs.existsSync(ENTRY)) throw Error('Compiled CLI is missing. Run npm run build first.');
  const used = new Set<string>();
  const result = await build({
    absWorkingDir: PROJECT, entryPoints: [path.relative(PROJECT, ENTRY)], bundle: true, write: false,
    platform: 'node', format: 'cjs', target: 'node22', charset: 'ascii', legalComments: 'eof',
    sourcemap: false, minify: false, treeShaking: true, logLevel: 'silent', banner: {js: BANNER},
    outfile: 'wildlands', plugins: [resources(used)]
  });
  if (result.warnings.length) throw Error('esbuild warnings: ' + result.warnings.map(warning => warning.text).join('; '));
  for (const name of ['engine-source-bundle.json', 'wildlands-runtime-bundle.json']) if (!used.has(name)) throw Error('CLI no longer loads ' + name + '; update tools/cli-bundle.cts.');
  const output = result.outputFiles[0];
  if (!output || result.outputFiles.length !== 1) throw Error('Expected exactly one bundled CLI output.');
  const bytes = Buffer.from(output.contents);
  if (!bytes.subarray(0, 20).toString('utf8').startsWith('#!/usr/bin/env node\n')) throw Error('Bundled CLI lacks its node shebang.');
  const text = bytes.toString('utf8');
  if (text.includes(PROJECT)) throw Error('Bundled CLI contains an absolute build path.');
  return {bytes, sha256: sha256(bytes)};
}

/**
 * Run the candidate from an empty directory with no node_modules. Where Node's permission model is
 * available, file reads are confined to that directory, proving no resource comes from the checkout.
 */
function smoke(bytes: Buffer): void {
  const directory = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'wildlands-cli-smoke-'))), cli = path.join(directory, 'wildlands');
  const confine = process.allowedNodeEnvironmentFlags.has('--permission') ? ['--permission', '--allow-fs-read=' + directory, '--allow-fs-write=' + directory] : [];
  const manifest = JSON.parse(fs.readFileSync(path.join(PROJECT, 'package.json'), 'utf8')) as {name: string; version: string};
  try {
    fs.writeFileSync(cli, bytes, {mode: 0o755});
    const run = (...args: string[]): Record<string, unknown> => {
      const child = spawnSync(process.execPath, [...confine, cli, ...args], {cwd: directory, encoding: 'utf8', timeout: 120000, maxBuffer: 64 * 1024 * 1024});
      const parsed = child.error || child.status !== 0 || child.stderr ? undefined : JSON.parse(child.stdout) as Record<string, unknown>;
      if (!parsed || parsed.ok !== true) throw Error(`Bundled CLI smoke failed: wildlands ${args.join(' ')} (exit ${child.status}) ${child.error?.message ?? (child.stderr + child.stdout).slice(0, 2000)}`);
      return parsed;
    };
    const version = run('--version');
    if (version.name !== manifest.name || version.version !== manifest.version) throw Error('Bundled CLI reports the wrong version.');
    for (const args of [['--help'], ['discover'], ['scenarios'], ['create', '--output', 'smoke.json'], ['validate', '--project', 'smoke.json']]) run(...args);
    // Both embedded payloads: the default runnable project and the explicit engine-source opt-in.
    for (const withSources of [false, true]) {
      const compiled = run('compile', '--project', 'smoke.json', '--output', withSources ? 'godot-sources' : 'godot', ...(withSources ? ['--with-engine-sources'] : []));
      if (compiled.engineSources !== withSources) throw Error('Bundled CLI compile does not honor the engine-source opt-in.');
    }
  } finally { fs.rmSync(directory, {recursive: true, force: true}); }
}

function writeExecutable(file: string, bytes: Buffer): void {
  fs.mkdirSync(path.dirname(file), {recursive: true});
  const temporary = file + '.' + process.pid + '.tmp';
  try { fs.writeFileSync(temporary, bytes, {flag: 'wx', mode: 0o755}); fs.chmodSync(temporary, 0o755); fs.renameSync(temporary, file); }
  finally { fs.rmSync(temporary, {force: true}); }
}

async function main(argv: readonly string[]): Promise<void> {
  const usage = 'Usage: node --import tsx source/tools/cli-bundle.cts (--output FILE | --check FILE); run npm run build first';
  if (argv.length === 1 && ['--help', '-h'].includes(argv[0]!)) { process.stdout.write(usage + '\n'); return; }
  const [mode, target] = argv;
  if (argv.length !== 2 || !target || (mode !== '--output' && mode !== '--check')) throw Error(usage);
  const file = path.resolve(target), built = await bundleCli();
  smoke(built.bytes);
  if (mode === '--output') {
    writeExecutable(file, built.bytes);
    process.stdout.write(`Built ${file} (${built.bytes.length.toLocaleString('en-US')} bytes, sha256 ${built.sha256})\n`);
    return;
  }
  const current = fs.existsSync(file) ? fs.readFileSync(file) : undefined;
  const executable = current === undefined || process.platform === 'win32' || (fs.statSync(file).mode & 0o111) === 0o111;
  if (!current || !current.equals(built.bytes) || !executable) {
    throw Error(`${file} is stale (checked-in ${current ? current.length + ' bytes, sha256 ' + sha256(current) : 'missing'}${executable ? '' : ', not executable'}; ` +
      `rebuilt ${built.bytes.length} bytes, sha256 ${built.sha256}). Run npm run build:cli and commit bin/wildlands.`);
  }
  process.stdout.write(`${file} is current (${built.bytes.length.toLocaleString('en-US')} bytes, sha256 ${built.sha256})\n`);
}

if (require.main === module) {
  main(process.argv.slice(2)).catch(error => {
    process.stderr.write('CLI bundle failed: ' + (error instanceof Error ? error.message : String(error)) + '\n');
    process.exitCode = 1;
  });
}
