/**
 * Build-only: bundle the compiled Wildlands CLI into one dependency-free CommonJS executable.
 *
 * The result runs with plain Node.js 22+ and no node_modules or .generated directory. It is the
 * engine alone: it carries no game. The transitional game installers resolve to the engine-only
 * installer (tools/engine-installer.cts), only engine-owned JSON is embedded (an allowlist below),
 * and the engine-source payload drops the build's game folders. Games are
 * folders the CLI reads at run time (`--game DIR`) or that schemaVersion 2 projects embed.
 *
 * Embedded resources: engine JSON as exact text parsed at first use, and three integrity-checked
 * raw-deflate payloads: the trusted Godot runtime bundle (the runtime closure only), the opt-in
 * engine-source bundle (inflated only for engine export, compile --with-engine-sources and studio
 * builds) and the engine kit (tools/engine-kit.cts: templates and precomputed, minified inserts),
 * so `build-game` needs no esbuild. They are compressed with the pinned pure JavaScript pako, not
 * Node's zlib, so the bytes do not depend on the Node release or CPU. Output is byte-deterministic
 * for a given .generated tree: no timestamps, absolute paths or source maps. Run `npm run build` first.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {inflateRawSync} from 'node:zlib';
import {spawnSync} from 'node:child_process';
import {build, type Plugin} from 'esbuild';
import {cachedEngineKit} from './engine-kit.cjs';
import {engineOnlySources} from './engine-sources.cjs';

// pako ships no declarations; this is the one deterministic encoder entry point used here.
const pako = require('pako') as {deflateRaw(data: Uint8Array, options: {level: number}): Uint8Array};
const PROJECT = path.resolve(__dirname, '../..');
const GENERATED = path.join(PROJECT, '.generated');
const ENTRY = path.join(GENERATED, 'tools', 'wildlands-cli.cjs');
const ENGINE_INSTALLER = path.join(GENERATED, 'tools', 'engine-installer.cjs');
const ENGINE_PATH = 'runtime/engine-source-bundle.json';
const EMBEDDED = 'wildlands-embedded-resources';
const KIT = 'wildlands-engine-kit';
const BUILD_ONLY = 'wildlands-build-only';
const BANNER = '// Generated by source/wildlands/source/tools/cli-bundle.cts - do not edit.\n' +
  '// Rebuild: cd source/wildlands && npm ci && npm run build:cli. Handbook: docs/reference/wildlands-cli.md\n';
/** Engine-owned JSON the CLI may embed, relative to .generated; anything else is game content or a mistake. */
const ENGINE_JSON = [/^\.\.\/package\.json$/, /^content\/[a-z0-9-]+\.schema\.json$/, /^wildlands-godot-templates\.json$/];
/** Build tools that must never reach the bundle (the CLI runs without node_modules). */
const BUILD_DEPENDENCIES = /(?:^|\/)node_modules\/(?:esbuild|typescript|playwright|ajv|tsx)\//;

interface RuntimeBundle {format: string; schemaVersion: number; files: {path: string; encoding: string; content: string}[];}
export interface BundleResult {bytes: Buffer; sha256: string; embeddedJson: string[];}

const sha256 = (value: string | Uint8Array): string => createHash('sha256').update(value).digest('hex');
const readGenerated = (name: string): string => fs.readFileSync(path.join(GENERATED, name), 'utf8');
/** Deterministic payload; the runtime module verifies size and SHA-256 after inflating. */
function payload(text: string): string {
  const raw = Buffer.from(text, 'utf8'), data = Buffer.from(pako.deflateRaw(raw, {level: 9}));
  if (!inflateRawSync(data).equals(raw)) throw Error('Embedded payload does not round-trip.');
  return JSON.stringify({bytes: raw.length, sha256: sha256(raw), data: data.toString('base64')});
}

/** The runtime bundle never carries engine sources or game content; engine sources are a separate, lazily inflated payload. */
function embeddedModule(): string {
  const engineText = engineOnlySources(readGenerated('engine-source-bundle.json')), runtimeText = readGenerated('wildlands-runtime-bundle.json');
  const runtime = JSON.parse(runtimeText) as RuntimeBundle;
  if (runtime.files.some(file => file.path === ENGINE_PATH)) throw Error('Runtime bundle unexpectedly carries the engine sources. Rebuild Wildlands.');
  const gameData = runtime.files.filter(file => file.path.endsWith('.json') && !/^runtime\/content\/[a-z0-9-]+\.schema\.json$/.test(file.path)).map(file => file.path);
  if (gameData.length) throw Error('Runtime bundle carries non-engine JSON: ' + gameData.join(', ') + '. Rebuild Wildlands.');
  return [
    '"use strict";',
    'const {inflateRawSync} = require("node:zlib"), {createHash} = require("node:crypto");',
    `const RUNTIME = ${payload(runtimeText)};`,
    `const ENGINE = ${payload(engineText)};`,
    `const KIT = ${payload(JSON.stringify(cachedEngineKit(PROJECT)))};`,
    'function inflate(item) {',
    '  const raw = inflateRawSync(Buffer.from(item.data, "base64"), {maxOutputLength: item.bytes});',
    '  if (raw.length !== item.bytes || createHash("sha256").update(raw).digest("hex") !== item.sha256)',
    '    throw Error("Embedded Wildlands resource integrity failed. Rebuild bin/wildlands.");',
    '  return new TextDecoder("utf-8", {fatal: true}).decode(raw);',
    '}',
    'exports.engineSourceText = () => inflate(ENGINE);',
    'exports.runtimeText = () => inflate(RUNTIME);',
    'exports.kitText = () => inflate(KIT);',
    ''
  ].join('\n');
}

/**
 * Replace the large generated JSON reads with lazy embedded loaders, the game installers with the
 * engine-only installer and the build-only kit computation with the embedded kit; keep engine JSON exact.
 */
function resources(used: Set<string>, embeddedJson: Set<string>): Plugin {
  const lazy: Record<string, string> = {
    'engine-source-bundle.json': `module.exports = JSON.parse(require(${JSON.stringify(EMBEDDED)}).engineSourceText());`,
    'wildlands-runtime-bundle.json': `module.exports = JSON.parse(require(${JSON.stringify(EMBEDDED)}).runtimeText());`
  };
  return {name: 'wildlands-cli-resources', setup(context) {
    context.onResolve({filter: new RegExp('^' + EMBEDDED + '$')}, () => ({path: EMBEDDED, namespace: EMBEDDED}));
    context.onLoad({filter: /.*/, namespace: EMBEDDED}, () => ({contents: embeddedModule(), loader: 'js'}));
    context.onResolve({filter: new RegExp('^' + KIT + '$')}, () => ({path: KIT, namespace: KIT}));
    context.onLoad({filter: /.*/, namespace: KIT}, () => { used.add(KIT); return {contents: `module.exports = JSON.parse(require(${JSON.stringify(EMBEDDED)}).kitText());`, loader: 'js'}; });
    // The checkout computes the kit with esbuild; the distribution never does.
    context.onResolve({filter: /^\.\/engine-kit\.cjs$/}, () => ({path: 'engine-kit', namespace: BUILD_ONLY}));
    context.onLoad({filter: /.*/, namespace: BUILD_ONLY}, () => ({contents: 'exports.cachedEngineKit = () => { throw Error("The engine kit is embedded in this distribution."); };', loader: 'js'}));
    context.onResolve({filter: /(?:^|\/)content-installers\/(?:littlewild-game|template-games)\.cjs$/}, () => { used.add('engine-installer'); return {path: ENGINE_INSTALLER}; });
    context.onLoad({filter: /\.json$/}, args => {
      const relative = path.relative(GENERATED, args.path).replaceAll(path.sep, '/');
      const replacement = lazy[relative];
      if (replacement) { used.add(relative); return {contents: replacement, loader: 'js'}; }
      if (!ENGINE_JSON.some(pattern => pattern.test(relative))) throw Error(`The CLI would embed ${relative}, which is not engine-owned JSON; games are read from their folders.`);
      embeddedJson.add(relative);
      // Match Node's require(): strip one BOM, then JSON.parse the exact text when first required.
      const text = fs.readFileSync(args.path, 'utf8').replace(/^\uFEFF/, '');
      JSON.parse(text);
      return {contents: `module.exports = JSON.parse(${JSON.stringify(text)});`, loader: 'js'};
    });
  }};
}

export async function bundleCli(): Promise<BundleResult> {
  if (!fs.existsSync(ENTRY) || !fs.existsSync(ENGINE_INSTALLER)) throw Error('Compiled CLI is missing. Run npm run build first.');
  const used = new Set<string>(), embeddedJson = new Set<string>();
  const result = await build({
    absWorkingDir: PROJECT, entryPoints: [path.relative(PROJECT, ENTRY)], bundle: true, write: false, metafile: true,
    platform: 'node', format: 'cjs', target: 'node22', charset: 'ascii', legalComments: 'eof',
    sourcemap: false, minify: false, treeShaking: true, logLevel: 'silent', banner: {js: BANNER},
    outfile: 'wildlands', plugins: [resources(used, embeddedJson)]
  });
  if (result.warnings.length) throw Error('esbuild warnings: ' + result.warnings.map(warning => warning.text).join('; '));
  for (const name of ['engine-source-bundle.json', 'wildlands-runtime-bundle.json', KIT, 'engine-installer']) if (!used.has(name)) throw Error('CLI no longer loads ' + name + '; update tools/cli-bundle.cts.');
  const tools = Object.keys(result.metafile.inputs).filter(input => BUILD_DEPENDENCIES.test(input));
  if (tools.length) throw Error('Bundled CLI would include build-only dependencies: ' + tools.join(', '));
  const output = result.outputFiles[0];
  if (!output || result.outputFiles.length !== 1) throw Error('Expected exactly one bundled CLI output.');
  const bytes = Buffer.from(output.contents);
  if (!bytes.subarray(0, 20).toString('utf8').startsWith('#!/usr/bin/env node\n')) throw Error('Bundled CLI lacks its node shebang.');
  const text = bytes.toString('utf8');
  if (text.includes(PROJECT)) throw Error('Bundled CLI contains an absolute build path.');
  return {bytes, sha256: sha256(bytes), embeddedJson: [...embeddedJson].sort()};
}

/** Every game folder this checkout has (docs/concepts or WILDLANDS_GAMES_DIR), by id. */
function gameFolders(): Map<string, string> {
  const root = (require('./game-folder.cjs') as typeof import('./game-folder.cjs')).gamesRoot();
  return new Map(fs.readdirSync(root, {withFileTypes: true}).filter(entry => entry.isDirectory() && fs.existsSync(path.join(root, entry.name, 'game.json')))
    .map(entry => [entry.name, path.join(root, entry.name)] as const).sort(([a], [b]) => a < b ? -1 : 1));
}
/** Long prose of every scenario pack this checkout's game folders ship: game-content sentinels. */
function contentSentinels(): string[] {
  const packs: string[] = [];
  for (const directory of gameFolders().values()) {
    const content = path.join(directory, 'content');
    if (fs.existsSync(content)) packs.push(...fs.readdirSync(content).filter(name => name.endsWith('.pack.json') || name.endsWith('.process.json')).map(name => path.join(content, name)));
  }
  return packs.map(file => (JSON.parse(fs.readFileSync(file, 'utf8')) as {description?: unknown}).description).filter((text): text is string => typeof text === 'string' && text.length >= 40);
}
/**
 * Run the candidate from an empty directory with no node_modules. Where Node's permission model is
 * available, file reads are confined to that directory, proving no resource comes from the checkout.
 * It copies Littlewild, RTS Frontier, Pocket Pet and Agency Delivery next to it, builds one game of
 * every template and compares each byte for byte with the checkout's compiled CLI, validates
 * Littlewild, creates and compiles a project and runs the compiled Godot runtime, which installs the
 * game its project embeds.
 */
function smoke(built: BundleResult): void {
  const directory = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'wildlands-cli-smoke-'))), cli = path.join(directory, 'wildlands');
  const confine = process.allowedNodeEnvironmentFlags.has('--permission') ? ['--permission', '--allow-fs-read=' + directory, '--allow-fs-write=' + directory] : [];
  const manifest = JSON.parse(fs.readFileSync(path.join(PROJECT, 'package.json'), 'utf8')) as {name: string; version: string};
  const spawn = (entry: string, args: readonly string[], flags: readonly string[], input?: string) => spawnSync(process.execPath, [...flags, entry, ...args],
    {cwd: directory, encoding: 'utf8', timeout: 300000, maxBuffer: 64 * 1024 * 1024, ...input === undefined ? {} : {input}});
  try {
    fs.writeFileSync(cli, built.bytes, {mode: 0o755});
    const run = (args: readonly string[], status = 0, entry = cli, flags: readonly string[] = confine): Record<string, unknown> => {
      const child = spawn(entry, args, flags);
      const parsed = child.error || child.stderr ? undefined : JSON.parse(child.stdout) as Record<string, unknown>;
      if (!parsed || child.status !== status || parsed.ok !== (status === 0) || parsed.protocolVersion !== 1)
        throw Error(`Bundled CLI smoke failed: wildlands ${args.join(' ')} (exit ${child.status}, expected ${status}) ${child.error?.message ?? (child.stderr + child.stdout).slice(0, 2000)}`);
      return parsed;
    };
    const version = run(['--version']);
    if (version.name !== manifest.name || version.version !== manifest.version) throw Error('Bundled CLI reports the wrong version.');
    for (const args of [['--help'], ['discover']]) run(args);
    const missing = run(['create', '--output', 'smoke.json'], 2);
    if (missing.code !== 'game-required' || !String((missing.errors as string[])[0]).includes('--game') || missing.handbook !== 'docs/reference/wildlands-cli.md')
      throw Error('Bundled CLI create without --game lacks its diagnostic.');
    // Games are data the smoke copies next to the CLI; the candidate reads nothing else.
    const games = path.join(directory, 'games'), folders = gameFolders(), copies = new Map<string, string>();
    for (const id of ['littlewild', 'rts-frontier', 'pocket-pet', 'agency-delivery']) {
     const source = folders.get(id);
     if (!source) throw Error(`The ${id} game folder is required for the CLI smoke.`);
     copies.set(id, path.join(games, id)); fs.cpSync(source, copies.get(id)!, {recursive: true});
    }
    const littlewild = copies.get('littlewild')!;
    if ((run(['validate-game', '--game', littlewild]).errors as unknown[]).length) throw Error('Littlewild did not validate.');
    run(['inspect-game', '--game', copies.get('rts-frontier')!]);
    // Byte identity with the checkout's compiled CLI, which computes the same kit with esbuild.
    for (const [name, game] of copies) {
      const output = path.join(directory, name + '.html'), reference = path.join(directory, name + '-checkout.html');
      run(['build-game', '--game', game, '--output', output]);
      run(['build-game', '--game', game, '--output', reference], 0, ENTRY, []);
      if (!fs.readFileSync(output).equals(fs.readFileSync(reference))) throw Error(`build-game output for ${name} differs between bin/wildlands and the compiled CLI.`);
      run(['build-game', '--game', game, '--check', output]);
    }
    run(['process', 'discover']);
    run(['process', 'schema', '--kind', 'recipe']);
    run(['process', 'create', '--id', 'process-smoke', '--output', 'process.json']);
    run(['process', 'inspect', '--input', 'process.json']);
    const processRun = run(['process', 'run', '--input', 'process.json', '--minutes', '100', '--output', 'process-report.json']);
    if (processRun.status !== 'completed') throw Error('Bundled process runtime did not complete its starter.');
    run(['process', 'build', '--input', 'process.json', '--output', 'process.html']);
    const project = path.join(directory, 'smoke.json');
    run(['create', '--game', littlewild, '--output', project]);
    run(['validate', '--project', project]);
    // Both embedded payloads: the default runnable project and the explicit engine-source opt-in.
    for (const withSources of [false, true]) {
      const target = withSources ? 'godot-sources' : 'godot';
      const compiled = run(['compile', '--project', 'smoke.json', '--output', target, ...(withSources ? ['--with-engine-sources'] : [])]);
      if (compiled.engineSources !== withSources) throw Error('Bundled CLI compile does not honor the engine-source opt-in.');
    }
    const root = path.join(directory, 'godot'), requests = [{id: 1, method: 'inspect', params: {}}, {id: 2, method: 'shutdown', params: {}}].map(value => JSON.stringify(value)).join('\n') + '\n';
    const bridge = spawn(path.join(root, 'runtime/tools/wildlands-runtime.cjs'), ['--project', path.join(root, 'wildlands.project.json'), '--stdio'], confine, requests);
    const replies = bridge.status === 0 && !bridge.stderr ? bridge.stdout.trim().split('\n').map(line => JSON.parse(line) as {ok: boolean}) : [];
    if (replies.length !== 2 || replies.some(reply => !reply.ok)) throw Error('Compiled Godot runtime did not run its embedded game: ' + (bridge.stderr || bridge.stdout).slice(0, 2000));
  } finally { fs.rmSync(directory, {recursive: true, force: true}); }
}

/** No scenario pack prose of any game may appear in the bundle or its decoded payloads. */
function assertNoGameContent(bytes: Buffer): void {
  const text = bytes.toString('utf8'), decoded = [text];
  for (const match of text.matchAll(/^[ \t]*(?:const|var|let) (?:RUNTIME|ENGINE|KIT) = (\{.*\});$/gm)) {
    const item = JSON.parse(match[1]!) as {bytes: number; data: string};
    decoded.push(inflateRawSync(Buffer.from(item.data, 'base64'), {maxOutputLength: item.bytes}).toString('utf8'));
  }
  if (decoded.length !== 4) throw Error('Expected three embedded payloads in the bundled CLI.');
  const sentinels = contentSentinels();
  if (!sentinels.length) throw Error('No game content sentinels found; the no-game-content check would be vacuous.');
  const found = sentinels.filter(sentinel => decoded.some(entry => entry.includes(sentinel) || entry.includes(JSON.stringify(sentinel).slice(1, -1))));
  if (found.length) throw Error('Bundled CLI carries game content: ' + found.map(entry => JSON.stringify(entry.slice(0, 60))).join(', '));
}

function writeExecutable(file: string, bytes: Buffer): void {
  fs.mkdirSync(path.dirname(file), {recursive: true});
  const temporary = file + '.' + process.pid + '.tmp';
  try { fs.writeFileSync(temporary, bytes, {flag: 'wx', mode: 0o755}); fs.chmodSync(temporary, 0o755); fs.renameSync(temporary, file); }
  finally { fs.rmSync(temporary, {force: true}); }
}

/** Build and fully check a candidate; `build:demos` reuses it to build every demo. */
export async function candidate(): Promise<BundleResult> {
  const built = await bundleCli();
  assertNoGameContent(built.bytes);
  smoke(built);
  return built;
}

async function main(argv: readonly string[]): Promise<void> {
  const usage = 'Usage: node --import tsx source/tools/cli-bundle.cts (--output FILE | --check FILE); run npm run build first';
  if (argv.length === 1 && ['--help', '-h'].includes(argv[0]!)) { process.stdout.write(usage + '\n'); return; }
  const [mode, target] = argv;
  if (argv.length !== 2 || !target || (mode !== '--output' && mode !== '--check')) throw Error(usage);
  const file = path.resolve(target), built = await candidate();
  if (mode === '--output') {
    writeExecutable(file, built.bytes);
    process.stdout.write(`Built ${file} (${built.bytes.length.toLocaleString('en-US')} bytes, sha256 ${built.sha256})\n`);
    return;
  }
  const current = fs.existsSync(file) ? fs.readFileSync(file) : undefined;
  const executable = current === undefined || process.platform === 'win32' || (fs.statSync(file).mode & 0o111) === 0o111;
  if (!current || !current.equals(built.bytes) || !executable) {
    throw Error(`${file} is stale (checked-in ${current ? current.length + ' bytes, sha256 ' + sha256(current) : 'missing'}${executable ? '' : ', not executable'}; ` +
      `rebuilt ${built.bytes.length} bytes, sha256 ${built.sha256}). Run npm run build:cli and commit bin/wildlands.`);
  }
  process.stdout.write(`${file} is current (${built.bytes.length.toLocaleString('en-US')} bytes, sha256 ${built.sha256})\n`);
}

if (require.main === module) {
  main(process.argv.slice(2)).catch(error => {
    process.stderr.write('CLI bundle failed: ' + (error instanceof Error ? error.message : String(error)) + '\n');
    process.exitCode = 1;
  });
}
