/**
 * Build-only: publish (`npm run build:demos`) or check (`npm run check:demos`) the repository's
 * playable demos, one self-contained HTML file per game folder.
 *
 * Both modes build the bundled CLI candidate exactly as `npm run build:cli` does (including its
 * smoke checks), then run that candidate's `build-game` once per `docs/concepts/<id>/game.json`
 * (one process per game: a realm runs one game), so every demo is byte-identical to what a user's
 * `bin/wildlands build-game` produces. The demos directory holds exactly `<id>.html` for every game,
 * `manifest.json` (per demo: game digest, engine identity, output bytes and SHA-256, budget) and a
 * README generated from the manifests. Check mode builds in a temporary directory and fails on any
 * byte difference, orphan or missing file; publish mode replaces the directory contents atomically
 * per file and removes orphans. A play artifact over its `targets.html.budgetBytes` fails both.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {candidate} from './cli-bundle.cjs';
import {gamesRoot} from './game-folder.cjs';
import {gameFolders} from './game-build.cjs';

interface Demo {
 readonly id: string; readonly name: string; readonly version: string; readonly template: string;
 readonly title: string; readonly description: string | null; readonly output: string;
 readonly bytes: number; readonly sha256: string; readonly budgetBytes: number; readonly gameDigest: string; readonly engine: string;
}
interface Manifest {readonly format: 'wildlands-demos'; readonly schemaVersion: 1; readonly engine: string; readonly demos: readonly Demo[];}
interface GameJson {id: string; name: string; version: string; template: string; presentation: {title: string; description?: string}; targets: {html: {output: string; budgetBytes: number}};}

const STATIC = new Set(['manifest.json', 'README.md']);
const mib = (bytes: number): string => (bytes / 1024 / 1024).toFixed(2) + ' MiB';

/** Every folder with a game.json under the games root, in id order. */
const folders = (): string[] => gameFolders(gamesRoot());

function readme(manifest: Manifest): string {
 const rows = manifest.demos.map(demo => `| [${demo.title}](${path.posix.basename(demo.output)}) | ${demo.template} | ${demo.version} | ${mib(demo.bytes)} | ${mib(demo.budgetBytes)} | \`${demo.gameDigest.slice(0, 12)}\` |`);
 const notes = manifest.demos.map(demo => `- **${demo.title}** (\`${demo.id}\`, [game folder](../docs/concepts/${demo.id}/README.md)): ${demo.description ?? demo.name}`);
 return ['# Playable demos', '',
  'Each file here is one game built from its folder under [`docs/concepts/`](../docs/concepts/README.md) by the Wildlands',
  'engine CLI. Open a file in a current desktop browser; it runs offline from `file://` with no network access, install or build step.', '',
  '| Demo | Template | Version | Size | Budget | Game digest |', '|---|---|---|---|---|---|', ...rows, '', ...notes, '',
  '## Generated files: never edit by hand', '',
  'This directory is generated by `cd source/wildlands && npm run build:demos`, which builds the `bin/wildlands` candidate and runs',
  '`build-game --game docs/concepts/<id> --output demos/<id>.html` for every game folder. [`manifest.json`](manifest.json) records each',
  "demo's game digest, engine identity, size and SHA-256; this README is generated from it. `npm run check:demos` rebuilds everything",
  'in a temporary directory and fails on any byte difference, missing or orphaned file, or a demo over its `targets.html.budgetBytes`.', '',
  `Engine identity: \`${manifest.engine}\`.`, '',
  'Handbook: [Wildlands CLI](../docs/reference/wildlands-cli.md). Editors and export tools are not published here; build a studio',
  'on demand with `bin/wildlands build-game --game docs/concepts/<id> --output studio.html --profile studio`.', ''].join('\n');
}

/** Build every demo with the candidate CLI into `directory`; returns the manifest. */
function buildAll(cli: string, directory: string): Manifest {
 const demos: Demo[] = [];
 for (const folder of folders()) {
  const game = JSON.parse(fs.readFileSync(path.join(folder, 'game.json'), 'utf8')) as GameJson;
  const file = path.posix.basename(game.targets.html.output), output = path.join(directory, file);
  const child = spawnSync(process.execPath, [cli, 'build-game', '--game', folder, '--output', output], {encoding: 'utf8', timeout: 600000, maxBuffer: 16 * 1024 * 1024});
  const result = child.stdout ? JSON.parse(child.stdout) as Record<string, unknown> : {};
  if (child.error || child.status !== 0 || result.ok !== true) throw Error(`build-game failed for ${game.id}: ${child.error?.message ?? ''}${child.stderr}${child.stdout}`.slice(0, 4000));
  demos.push({id: game.id, name: game.name, version: game.version, template: game.template, title: game.presentation.title, description: game.presentation.description ?? null,
   output: game.targets.html.output, bytes: result.bytes as number, sha256: result.sha256 as string, budgetBytes: result.budgetBytes as number, gameDigest: result.digest as string, engine: result.engine as string});
 }
 const engines = [...new Set(demos.map(demo => demo.engine))];
 if (engines.length > 1) throw Error('Demos were built by different engines: ' + engines.join(', '));
 const manifest: Manifest = {format: 'wildlands-demos', schemaVersion: 1, engine: engines[0] ?? '', demos};
 fs.writeFileSync(path.join(directory, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
 fs.writeFileSync(path.join(directory, 'README.md'), readme(manifest));
 return manifest;
}

async function main(argv: readonly string[]): Promise<void> {
 const usage = 'Usage: node --import tsx source/tools/demos.cts (--output DIR | --check DIR); run npm run build first';
 if (argv.length === 1 && ['--help', '-h'].includes(argv[0]!)) { process.stdout.write(usage + '\n'); return; }
 const [mode, target] = argv;
 if (argv.length !== 2 || !target || (mode !== '--output' && mode !== '--check')) throw Error(usage);
 const destination = path.resolve(target), built = await candidate();
 const work = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'wildlands-demos-'))), cli = path.join(work, 'wildlands'), staged = path.join(work, 'demos');
 try {
  fs.writeFileSync(cli, built.bytes, {mode: 0o755});
  fs.mkdirSync(staged);
  const manifest = buildAll(cli, staged), expected = fs.readdirSync(staged).sort();
  const current = fs.existsSync(destination) ? fs.readdirSync(destination).sort() : [];
  if (mode === '--check') {
   const problems = [...expected.filter(name => !current.includes(name)).map(name => 'missing ' + name),
    ...current.filter(name => !expected.includes(name)).map(name => 'orphan ' + name),
    ...expected.filter(name => current.includes(name) && !fs.readFileSync(path.join(staged, name)).equals(fs.readFileSync(path.join(destination, name)))).map(name => 'stale ' + name)];
   if (problems.length) throw Error(`${destination} is not current (${problems.join(', ')}). Run npm run build:demos and commit demos/.`);
   process.stdout.write(`${destination} is current (${manifest.demos.map(demo => `${demo.id} ${demo.bytes.toLocaleString('en-US')} bytes`).join(', ')}; engine ${manifest.engine})\n`);
   return;
  }
  fs.mkdirSync(destination, {recursive: true});
  for (const name of current.filter(name => !expected.includes(name))) {
   if (!name.endsWith('.html') && !STATIC.has(name)) throw Error(`Refusing to remove unexpected ${path.join(destination, name)}; demos/ holds only generated files.`);
   fs.rmSync(path.join(destination, name));
  }
  for (const name of expected) {
   const temporary = path.join(destination, '.' + name + '.' + process.pid + '.tmp');
   try { fs.copyFileSync(path.join(staged, name), temporary); fs.renameSync(temporary, path.join(destination, name)); }
   finally { fs.rmSync(temporary, {force: true}); }
  }
  process.stdout.write(`Built ${destination} (${manifest.demos.map(demo => `${demo.id} ${demo.bytes.toLocaleString('en-US')} bytes`).join(', ')}; engine ${manifest.engine})\n`);
 } finally { fs.rmSync(work, {recursive: true, force: true}); }
}

if (require.main === module) {
 main(process.argv.slice(2)).catch(error => {
  process.stderr.write('Demos failed: ' + (error instanceof Error ? error.message : String(error)) + '\n');
  process.exitCode = 1;
 });
}
