// Builds the checked-in repository executable bin/model-forge.
//
//   node scripts/standalone.mjs            write ../../bin/model-forge
//   node scripts/standalone.mjs --out F    write another file
//   node scripts/standalone.mjs --check    rebuild into a temporary file and fail when the
//                                          checked-in executable differs or is not executable
//
// The output is one CommonJS file (no package.json is needed beside it) with every
// JavaScript dependency except Playwright, plus the render-only preview page script and the
// example models embedded as strings. It contains no timestamps, absolute paths or source
// maps, so identical sources and a locked esbuild produce identical bytes.
import { build } from 'esbuild';
import { createHash } from 'node:crypto';
import { chmod, mkdir, mkdtemp, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const checkedIn = path.resolve(root, '../../bin/model-forge');
const fromRoot = (...parts) => path.join(root, ...parts);

/** The render-only browser page (src/preview/page.ts), identical to dist/preview.js. */
export async function buildPreview() {
  const threeLicense = await readFile(fromRoot('node_modules/three/LICENSE'), 'utf8');
  const result = await build({
    absWorkingDir: root,
    entryPoints: ['src/preview/page.ts'],
    bundle: true,
    platform: 'browser',
    format: 'iife',
    target: 'es2022',
    minify: true,
    legalComments: 'inline',
    banner: { js: '/*! Bundled Three.js license:\n' + threeLicense + '\n*/' },
    write: false,
    outfile: 'dist/preview.js',
    logLevel: 'warning',
  });
  return result.outputFiles[0].text;
}

/** Asset names match src/infra/assets.ts. Example JSON is stored compactly. */
async function packagedAssets(preview) {
  const assets = { 'preview.js': preview };
  const examples = fromRoot('examples');
  for (const name of (await readdir(examples)).filter((file) => file.endsWith('.json')).sort())
    assets[`examples/${name}`] = JSON.stringify(
      JSON.parse(await readFile(path.join(examples, name), 'utf8')),
    );
  return Object.fromEntries(Object.entries(assets).sort(([a], [b]) => (a < b ? -1 : 1)));
}

const embedAssets = (assets) => ({
  name: 'embed-assets',
  setup(context) {
    context.onLoad({ filter: /[\\/]src[\\/]infra[\\/]embedded-assets\.ts$/ }, () => ({
      contents: `export const embeddedAssets = ${JSON.stringify(assets)};\n`,
      loader: 'js',
    }));
  },
});

/** Package name for a bundled input path such as node_modules/@scope/name/file.js. */
function packageOf(input) {
  const parts = input.split('node_modules/').at(-1).split('/');
  return parts[0].startsWith('@') ? `${parts[0]}/${parts[1]}` : parts[0];
}

/** Full license (and NOTICE) texts of every bundled npm package, in a stable order. */
async function licenseHeader(inputs, version) {
  const packages = [...new Set(inputs.filter((i) => i.includes('node_modules/')).map(packageOf))];
  const sections = [];
  for (const name of packages.sort()) {
    const directory = fromRoot('node_modules', name);
    const metadata = JSON.parse(await readFile(path.join(directory, 'package.json'), 'utf8'));
    const files = (await readdir(directory))
      .filter((file) => /^(licen[cs]e|notices?)(\.|$)/i.test(file))
      .sort();
    if (!files.some((file) => /^licen[cs]e/i.test(file)))
      throw new Error(`Bundled package ${name} has no license file.`);
    const texts = await Promise.all(
      files.map(async (file) => (await readFile(path.join(directory, file), 'utf8')).trim()),
    );
    sections.push(`${name}@${metadata.version} (${metadata.license})\n\n${texts.join('\n\n')}`);
  }
  const body = [
    `model-forge ${version}: standalone Model Forge CLI generated by`,
    'source/model-forge/scripts/standalone.mjs. Do not edit; run npm run build:cli.',
    'Handbook: source/model-forge/README.md. Playwright is loaded at runtime, not bundled.',
    '',
    'Bundled third-party packages and their licenses:',
    '',
    sections.join('\n\n' + '-'.repeat(72) + '\n\n'),
  ].join('\n');
  return `/*!\n${body.replaceAll('*/', '* /')}\n*/\n`;
}

/** Build the executable's bytes. `preview` may reuse an already built page script. */
export async function buildStandalone(preview) {
  const assets = await packagedAssets(preview ?? (await buildPreview()));
  const { version } = JSON.parse(await readFile(fromRoot('package.json'), 'utf8'));
  const result = await build({
    absWorkingDir: root,
    entryPoints: ['src/standalone.ts'],
    bundle: true,
    platform: 'node',
    format: 'cjs',
    target: 'node22',
    external: ['playwright', 'playwright-core'],
    define: { 'import.meta.url': 'undefined' },
    minify: true,
    legalComments: 'eof',
    metafile: true,
    write: false,
    outfile: 'bin/model-forge.js',
    logLevel: 'warning',
    plugins: [embedAssets(assets)],
  });
  const header = await licenseHeader(Object.keys(result.metafile.inputs), version);
  return Buffer.from('#!/usr/bin/env node\n' + header + result.outputFiles[0].text);
}

export async function writeStandalone(file = checkedIn, preview) {
  const bytes = await buildStandalone(preview);
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, bytes);
  await chmod(file, 0o755);
  return bytes;
}

const digest = (bytes) => createHash('sha256').update(bytes).digest('hex');

async function check() {
  const temp = await mkdtemp(path.join(os.tmpdir(), 'model-forge-check-'));
  try {
    const fresh = await writeStandalone(path.join(temp, 'model-forge'));
    let current;
    try {
      current = await readFile(checkedIn);
    } catch {
      current = undefined;
    }
    const executable = current ? ((await stat(checkedIn)).mode & 0o111) !== 0 : false;
    if (!current || !fresh.equals(current) || (process.platform !== 'win32' && !executable)) {
      console.error(
        [
          'bin/model-forge is missing, stale or not executable.',
          `  checked-in: ${current ? `${current.length} bytes sha256 ${digest(current)}` : 'missing'}`,
          `  rebuilt:    ${fresh.length} bytes sha256 ${digest(fresh)}`,
          'Run: cd source/model-forge && npm ci && npm run build:cli, then commit bin/model-forge.',
        ].join('\n'),
      );
      process.exitCode = 1;
      return;
    }
    console.log(`bin/model-forge is current (${fresh.length} bytes, sha256 ${digest(fresh)}).`);
  } finally {
    await rm(temp, { recursive: true, force: true });
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  const args = process.argv.slice(2);
  if (args[0] === '--check') await check();
  else {
    const out = args[0] === '--out' && args[1] ? path.resolve(args[1]) : checkedIn;
    const bytes = await writeStandalone(out);
    console.log(`Built ${path.relative(process.cwd(), out) || out} (${bytes.length} bytes).`);
  }
}
