extends SceneTree
var checks = 0
var failures: Array[String] = []
func _initialize(): call_deferred("run")
func check(value: bool, message: String):
	checks += 1
	if not value: failures.append(message); push_error(message)
func copy(data): return JSON.parse_string(JSON.stringify(data,"",false,true))
func redigest(data):
	data.erase("digest"); data.digest=RaceRecord.fingerprint(data); return data
func run():
	var sim = PracticeRaceSim.new(TrackGeometry.new(Storage.read_catalog().data[7]), {"intensity":"calm"})
	var record=RaceRecord.new(); var before=sim.snapshot(); record.attach(sim)
	check(RaceRecord.equivalent(before,sim.snapshot()),"Attaching a recorder is observational")
	check(sim.command("practice_start"),"Practice approval accepted")
	var plan={"objective":"tyre_life","set_id":"3-M1","laps":1,"baseline":"current"}
	# Discover the real objective ID from the domain, not display text.
	plan.objective=PracticeEvidence.OBJECTIVES.keys()[0]
	var preview=sim.run_preview(3,plan)
	check(sim.command("practice_run",{"id":3,"plan":plan,"revision":preview.revision,"key":preview.key,"time":preview.time}),"Physical practice input accepted")
	for i in range(40): sim.step()
	check(record.steps==40,"Only real fixed steps are counted")
	check(sim.command("pause"),"Explicit pause is recorded")
	for i in range(10):sim.step()
	check(record.steps==40,"Paused no-op loops are not recorded as work")
	check(record.bookmark("Before recall").is_empty(),"Decision checkpoint captured")
	var n=record.inputs.size()
	check(not sim.command("practice_run",{"id":0}) and record.inputs.size()==n,"Rejected input is absent from exact trace")
	check(sim.command("practice_recall",{"id":3}),"Recall is an exact outer input")
	check(sim.command("pause"),"Unpause recorded on same step")
	for i in range(80):sim.step()
	var sealed=record.seal(); var original=sim.snapshot()
	check(RaceRecord.validate(sealed).is_empty(),"Sealed archive validates: "+RaceRecord.validate(sealed))
	check(RaceRecord.validate(copy(sealed)).is_empty(),"JSON archive roundtrip preserves integrity")
	var replay=RaceReplay.new()
	check(replay.load_record(copy(sealed)).is_empty(),"Independent replay loads")
	for i in range(10):replay.tick(32)
	check(replay.verified,"Original exact command replay reaches equivalent endpoint: "+replay.error)
	check(RaceRecord.equivalent(original,sim.snapshot()),"Playback does not mutate live state, including RNG and time")
	check(replay.seek(0),"Selected decision checkpoint restores")
	for i in range(10):replay.tick(32)
	check(replay.verified,"Same-step checkpoint cursor replays only later inputs: "+replay.error)
	var branch=replay.branch();var branch_record=RaceRecord.new();branch_record.attach(branch,"sandbox",replay.lineage())
	check(branch!=sim and branch.paused,"Sandbox is a separately paused copy")
	check(not ResultReceipts.accept(branch_record).ok,"Sandbox cannot accept an original result")
	check(branch.command("pause"),"Experiment can explicitly resume")
	for i in range(5):branch.step()
	check(RaceRecord.equivalent(original,sim.snapshot()),"Changed branch exposure leaves original unchanged")
	var bad=copy(sealed);bad.inputs[0].action="unknown"
	check(not RaceRecord.validate(bad).is_empty(),"Modified archive digest rejected")
	bad=redigest(bad); var damaged=RaceReplay.new()
	check(damaged.load_record(bad).is_empty(),"Structurally valid unknown input can be inspected")
	damaged.tick()
	check(not damaged.error.is_empty() and damaged.step_index==0,"Unknown command stops playback without invented execution")
	for key in ["initial","endpoint"]:
		bad=copy(sealed);bad[key].cars[3].fuel=-4;redigest(bad)
		check(not RaceRecord.validate(bad).is_empty(),"Malformed "+key+" fails validation")
	bad=copy(sealed);bad.marks[0].cursor=0;redigest(bad)
	check(not RaceRecord.validate(bad).is_empty(),"Checkpoint command chronology is validated")
	bad=copy(sealed);bad.steps+=2;redigest(bad)
	check(not RaceRecord.validate(bad).is_empty(),"Inconsistent simulated time rejected")
	check(ReplayStorage.save_session("user://replay-test-session.json",record).is_empty(),"Original session writes atomically")
	var loaded=ReplayStorage.restore_session(Storage.read_json("user://replay-test-session.json").data)
	check(loaded.ok and loaded.record.event_id==record.event_id,"Session continuation retains event identity")
	check(not ReplayStorage.restore_session({"kind":ReplayStorage.SESSION_KIND,"version":1,"record":branch_record.seal()}).ok,"Sandbox cannot load into original slot")
	check(RaceRecord.equivalent(original,loaded.sim.snapshot()),"All authoritative session state restores")
	for i in range(3):check(record.bookmark("Checkpoint "+str(i)).is_empty(),"Manual checkpoint bound accepts available slot")
	check(not record.bookmark("Overflow").is_empty() and record.marks.size()==4,"Checkpoint limit never silently evicts evidence")

	bad=copy(sealed);bad.model="another-model";redigest(bad)
	var incompatible=RaceReplay.new()
	check(incompatible.load_record(bad).is_empty(),"Different model snapshots remain inspectable")
	incompatible.tick()
	check(not incompatible.error.is_empty() and incompatible.step_index==0,"Different model cannot claim original replay")
	check(incompatible.branch()!=null,"Different model can create a disclosed independent experiment")
	bad=copy(sealed);bad.inputs[0].integers=[["not-present"]];redigest(bad)
	check(not RaceRecord.validate(bad).is_empty(),"Invalid numeric-type path is rejected before replay")
	bad=copy(sealed);bad.manifest.seed=1;redigest(bad)
	check(not RaceRecord.validate(bad).is_empty(),"Scenario authoring metadata must match its frozen initial state")
	var burst=PracticeRaceSim.new(sim.track);var burst_record=RaceRecord.new();burst_record.attach(burst)
	for i in range(40):burst.command("speed",{"value":2 if i%2==0 else 1})
	var burst_replay=RaceReplay.new()
	check(burst_replay.load_record(copy(burst_record.seal())).is_empty(),"Same-step input burst validates")
	burst_replay.tick()
	check(burst_replay.cursor==32 and burst_replay.step_index==0,"A playback batch bounds commands without inventing a simulation step")
	burst_replay.tick()
	check(burst_replay.verified,"Remaining same-step inputs reproduce the endpoint in order")
	var limit=RaceRecord.new();limit.attach(burst)
	limit.inputs.resize(RaceRecord.MAX_INPUTS)
	burst.command("speed",{"value":4})
	check(not limit.incomplete.is_empty() and burst.speed==4,"Input limit marks continuity unavailable without suppressing live commands")
	check(not ResultReceipts.valid({"kind":ResultReceipts.KIND,"version":1,"results":{"bad":{}}}),"Malformed receipt ledger is rejected")
	bad=copy(sealed);bad.engine="different-engine";redigest(bad)
	check(not ReplayStorage.restore_session({"kind":ReplayStorage.SESSION_KIND,"version":1,"record":bad}).ok,"Different-engine session cannot silently adopt current provenance")
	bad=copy(sealed);bad.model="different-model";redigest(bad)
	check(not ReplayStorage.restore_session({"kind":ReplayStorage.SESSION_KIND,"version":1,"record":bad}).ok,"Different-model original continuation is rejected atomically")
	bad=copy(sealed);bad.marks[0].snapshot.seed_value+=1;redigest(bad)
	check(not RaceRecord.validate(bad).is_empty(),"Checkpoint cannot change the recording seed")
	check(RaceRecord.equivalent(original,sim.snapshot()),"Malformed and incompatible imports do not consume source streams")
	var report={"passed":failures.is_empty(),"checks":checks,"failures":failures,"engine":Engine.get_version_info().string}
	Storage.write_json("res://reports/replay-tests.json",report);print("REPLAY_TESTS ",JSON.stringify(report));quit(0 if failures.is_empty() else 1)
