import { build } from 'esbuild';
import { readFile, writeFile, chmod, mkdir, stat } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const output = resolve(root, '../../bin/character-studio');
const browser = await build({
  absWorkingDir: root, entryPoints: ['src/ui/main.ts'], bundle: true,
  format: 'iife', platform: 'browser', target: 'es2022', minify: true,
  legalComments: 'inline', write: false,
});
const embedded = {
  html: await readFile(resolve(root, 'src/ui/shell.html'), 'utf8'),
  css: await readFile(resolve(root, 'src/ui/styles.css'), 'utf8'),
  javascript: browser.outputFiles[0].text,
};
const license = await readFile(resolve(root, 'node_modules/three/LICENSE'), 'utf8');
const candidate = await build({
  absWorkingDir: root, entryPoints: ['src/cli.ts'], bundle: true, platform: 'node',
  format: 'cjs', target: 'node22', minify: false, write: false, external: ['playwright'],
  banner: { js: '#!/usr/bin/env node\n/* Generated by source/character-studio/scripts/build.mjs. Do not hand-edit.\nBundled Three.js license:\n' + license.replaceAll('*/', '* /') + '\n*/' },
  plugins: [{ name: 'embedded-ui', setup(context) {
    context.onLoad({ filter: /[\\/]infra[\\/]embedded\.ts$/ }, () => ({ contents: `export const embedded = ${JSON.stringify(embedded)};`, loader: 'js' }));
  } }],
});
const bytes = candidate.outputFiles[0].contents;
if (process.argv.includes('--check')) {
  const existing = await readFile(output);
  if (!existing.equals(Buffer.from(bytes)) || !((await stat(output)).mode & 0o111)) throw Error('bin/character-studio is stale or not executable. Run npm run build:cli.');
  console.log('character-studio bundle matches source.');
} else {
  await mkdir(dirname(output), { recursive: true });
  await writeFile(output, bytes, { mode: 0o755 });
  await chmod(output, 0o755);
  console.log(`Built bin/character-studio (${bytes.length} bytes).`);
}
