"""Actual browser interactions for compact world panels and scene-pack exchange."""
from pathlib import Path
import json, time, traceback
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parent
OUTPUT=ROOT/'verification/v15';OUTPUT.mkdir(parents=True,exist_ok=True)
SHOTS=ROOT/'screenshots/v15-final';SHOTS.mkdir(parents=True,exist_ok=True)
results=[];errors=[];requests=[]
def check(name,fn):
    try:
        value=fn()
        assert value is not False, 'Check returned false'
        results.append({'name':name,'passed':True})
    except Exception as ex:
        results.append({'name':name,'passed':False,'error':str(ex)})
        print('FAIL',name,str(ex)[:240],flush=True)
    (OUTPUT/'browser-progress.json').write_text(json.dumps(results,indent=2))
def equal(a,b):
    assert a==b,f'{a!r} != {b!r}'
def expect(value):
    assert value
with sync_playwright() as play:
    browser=play.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--enable-unsafe-swiftshader','--use-angle=swiftshader'])
    context=browser.new_context(viewport={'width':1440,'height':900},accept_downloads=True)
    p=context.new_page();p.set_default_timeout(5000)
    p.on('pageerror',lambda x:errors.append(str(x)))
    p.on('request',lambda x: requests.append(x.url) if x.url.startswith(('http:','https:')) else None)
    p.set_content((ROOT/'littlewild.html').read_text(),wait_until='load')
    p.wait_for_function('!!window.Littlewild');p.wait_for_timeout(250)
    check('Application identifies the new implementation',lambda:equal(p.evaluate('Littlewild.version'),'15.0.0'))
    p.locator('[data-act=begin]').click();p.wait_for_timeout(250)
    check('Fresh start launches an authored scene',lambda:equal(p.evaluate('Littlewild.engine.scenarioContext.sceneId'),'first-morning'))
    check('Fresh onboarding is non-modal',lambda:expect(p.locator('#guide-panel').is_visible() and p.evaluate('Littlewild.ui.modal===null&&!document.getElementById("app").inert')))
    before=p.evaluate('JSON.stringify(Littlewild.engine.export())')
    p.locator('[data-guide=next]').click()
    check('Tutorial next advances only the saved guide index',lambda:equal(p.evaluate('Littlewild.engine.s.progression.tutorial.step'),1))
    p.locator('[data-guide=minimize]').click()
    check('Guide collapses without losing its step',lambda:expect(p.locator('#guide-panel').evaluate('(el)=>el.classList.contains("minimized")')))
    p.locator('[data-guide=expand]').click();p.locator('#guide-step').select_option('3')
    p.locator('[data-guide=show]').click();p.wait_for_timeout(250)
    check('Show me opens real construction without a task',lambda:expect(p.locator('#build-panel').is_visible()))
    check('Fresh build catalog hides unresearched blueprints',lambda:expect(p.locator('.build-row').count()<23))
    check('World is not inert while planning',lambda:equal(p.evaluate('document.getElementById("app").inert'),False))
    p.evaluate("Littlewild.open('scenarios')")
    p.locator('[data-scenario=review][data-id=charted-home]').click()
    check('Scene review is a safety pause',lambda:equal(p.evaluate('Littlewild.pauseStatus().kind'),'safety'))
    p.locator('[data-scenario=launch]').click();p.wait_for_timeout(400)
    check('Established scene has three companions',lambda:equal(p.evaluate('Littlewild.engine.creatures.length'),3))
    p.evaluate("Littlewild.open('construction')");p.wait_for_timeout(100)
    check('Build panel is a complementary region not a modal',lambda:equal(p.locator('#build-panel').evaluate('(el)=>el.tagName+":"+el.getAttribute("aria-modal")'),'ASIDE:null'))
    check('Automatic pause setting covers the build panel',lambda:equal(p.evaluate('Littlewild.pauseStatus().running'),False))
    check('Build panel leaves over 70% of desktop world uncovered',lambda:expect(p.locator('#build-panel').evaluate('(el)=>{let r=el.getBoundingClientRect();return r.width*r.height<innerWidth*innerHeight*.3;}')))
    check('Build panel has a visible close label',lambda:equal(p.locator('#build-panel [data-build=close]').get_attribute('aria-label'),'Close build panel'))
    p.locator('#build-search').fill('map')
    check('Build search narrows the catalog',lambda:equal(p.locator('.build-row').count(),1))
    p.locator('#build-search').fill('zzzzzz')
    check('Empty search has recovery guidance',lambda:expect('No matching' in p.locator('#build-results').inner_text()))
    p.locator('#build-search').fill('')
    p.locator('#build-category').select_option(index=1)
    check('Category filter reduces displayed blueprints',lambda:expect(p.locator('.build-row').count()<23))
    p.locator('#build-category').select_option('all')
    p.locator('#build-search').focus();p.keyboard.press('F6')
    check('F6 returns focus to the world',lambda:equal(p.evaluate('document.activeElement.id'),'world'))
    p.keyboard.press('F6')
    check('F6 returns focus to the panel',lambda:expect(p.evaluate('document.getElementById("build-panel").contains(document.activeElement)')))
    camera=p.evaluate('JSON.stringify(Littlewild.world.camera)')
    p.mouse.move(660,540);p.mouse.down();p.mouse.move(710,560,steps=5);p.mouse.up();p.wait_for_timeout(100)
    check('Dragging the exposed world moves the camera',lambda:expect(camera!=p.evaluate('JSON.stringify(Littlewild.world.camera)')))
    check('Panning does not dismiss the construction catalog',lambda:expect(p.locator('#build-panel').is_visible()))
    p.evaluate('Littlewild.preferences.set(false);Littlewild.refresh()')
    start=p.evaluate('Littlewild.engine.s.simTime');p.wait_for_timeout(550)
    check('World runs behind a panel with automatic pause disabled',lambda:expect(p.evaluate('Littlewild.engine.s.simTime')>start))
    p.evaluate('Littlewild.engine.s.paused=true;Littlewild.refresh()')
    start=p.evaluate('Littlewild.engine.s.simTime');p.wait_for_timeout(300)
    check('Manual pause still wins behind live panels',lambda:equal(p.evaluate('Littlewild.engine.s.simTime'),start))
    p.evaluate('Littlewild.engine.s.paused=false;Littlewild.preferences.set(true);Littlewild.refresh()')
    p.locator('[data-build=select][data-id=shelter]').click()
    check('Blueprint detail explains physical supplies',lambda:expect('not used remotely' in p.locator('#build-panel').inner_text()))
    p.locator('#build-actor').select_option('c1');prior_policy=p.evaluate('Littlewild.engine.s.buildPolicy.approach');p.locator('#build-approach').select_option('careful')
    check('Explicit construction approach stays in the draft',lambda:equal(p.evaluate('Littlewild.buildPanel.state.approach'),'careful'))
    check('Changing the approach does not mutate the creature policy',lambda:equal(p.evaluate('Littlewild.engine.s.buildPolicy.approach'),prior_policy))
    p.locator('[data-build=place]').click()
    check('Choosing a location dismisses the panel and starts placement',lambda:expect(not p.locator('#build-panel').is_visible() and p.evaluate('Littlewild.world.placement==="shelter"')))
    check('Placement retains the requested actor',lambda:equal(p.evaluate('Littlewild.engine.selected.id'),'c1'))
    p.keyboard.press('Escape')
    check('Escape cancels placement without creating a plan',lambda:equal(p.evaluate('Littlewild.world.placement'),None))
    p.evaluate("Littlewild.open('construction')");p.locator('[data-build=select][data-id=map_table]').click()
    check('Map table remains discoverable in researched build detail',lambda:expect('Map table' in p.locator('#build-panel').inner_text()))
    p.locator('[data-build=list]').click();p.locator('#build-search').fill('work')
    p.locator('[data-build=close]').click();p.evaluate("Littlewild.open('construction')")
    check('Catalog draft survives dismissal',lambda:equal(p.locator('#build-search').input_value(),'work'))
    p.locator('#build-search').fill('')
    p.screenshot(path=str(SHOTS/'01-build.png'))
    p.locator('[data-build=select][data-id=shelter]').click();p.screenshot(path=str(SHOTS/'02-blueprint.png'))
    p.evaluate("Littlewild.open('v10-guide')");p.locator('#guide-step').select_option('2')
    p.screenshot(path=str(SHOTS/'03-tutorial.png'))
    check('Guide preserves access to the canvas',lambda:equal(p.evaluate('document.getElementById("app").inert'),False))
    p.locator('[data-guide=show]').click()
    check('Tutorial links to actual learning workspace',lambda:equal(p.evaluate('Littlewild.ui.modal'),'training'))
    check('Guide is minimized behind its linked workspace',lambda:expect(p.evaluate('Littlewild.guidePanel.state.minimized')))
    p.locator('#modal [data-act=close-modal]').first.click();p.evaluate("Littlewild.open('scenarios')")
    p.screenshot(path=str(SHOTS/'04-scenarios.png'))
    current=p.evaluate('Littlewild.engine.scenarioContext.packId')
    p.locator('[data-scenario=select][data-id="1"]').click()
    p.locator('[data-scenario=review]').last.click();p.locator('[data-scenario=cancel]').click()
    check('Canceling a scene review preserves active experience',lambda:equal(p.evaluate('Littlewild.engine.scenarioContext.packId'),current))
    with p.expect_download() as dl:p.locator('[data-scenario=export]').click()
    download=dl.value;exported=json.loads(Path(download.path()).read_text())
    check('Actual pack download contains scenes and four libraries',lambda:expect(exported['format']=='living-worlds-pack' and len(exported['libraries'])==4))
    malformed=json.dumps({'format':'living-worlds-pack','schemaVersion':99})
    p.locator('#scenario-import-file').set_input_files({'name':'invalid.json','mimeType':'application/json','buffer':malformed.encode()})
    p.wait_for_timeout(150)
    check('Rejected imports leave the world intact and explain errors',lambda:expect('not applied' in p.locator('.validation-issue').inner_text() and p.evaluate('Littlewild.engine.scenarioContext.packId')==current))
    custom=json.loads((ROOT/'source/content/emberworks.pack.json').read_text());custom['name']='Tidewatch';custom['id']='tidewatch';custom['presentation']['title']='Tidewatch'
    p.locator('#scenario-import-file').set_input_files({'name':'tidewatch.json','mimeType':'application/json','buffer':json.dumps(custom).encode()});p.wait_for_timeout(200)
    check('Valid imported pack enters catalog without replacing world',lambda:expect('Tidewatch' in p.locator('.scenario-packs').inner_text() and p.evaluate('Littlewild.engine.scenarioContext.packId')==current))
    p.locator('[data-scenario=review]').last.click();p.locator('[data-scenario=launch]').click();p.wait_for_timeout(300)
    check('Confirmed pack launch uses imported presentation',lambda:expect(p.title().startswith('Tidewatch') and p.locator('.brand-word').inner_text()=='Tidewatch'))
    check('Confirmed pack launch uses imported companion setup',lambda:equal(p.evaluate('Littlewild.engine.creatures[0].name'),'Rivet'))
    check('Confirmed pack changes real definition names',lambda:equal(p.evaluate('LW.BUILDINGS.bench.name'),'Assembly bench'))
    check('World terrain reads the selected authored profile',lambda:equal(p.evaluate('LWGeography.islandTerrain(14,1)'),'water'))
    check('Scenario save envelope includes the exact world template and simulation selection',lambda:equal(p.evaluate('Littlewild.snapshot().version'),10))
    p.screenshot(path=str(SHOTS/'05-emberworks.png'))
    p.evaluate("Littlewild.open('scenarios')")
    with p.expect_download() as dl:p.locator('[data-scenario=capture]').click()
    saved=Path(dl.value.path()).read_text()
    check('Captured current scene downloads as a valid pack',lambda:expect(p.evaluate('(text)=>LWScenarios.validate(text).ok',saved)))
    p.evaluate("() => {window._originalText=File.prototype.text; File.prototype.text=function(){return new Promise(resolve=>setTimeout(()=>_originalText.call(this).then(resolve),400))};}")
    p.locator('#scenario-import-file').set_input_files({'name':'later.json','mimeType':'application/json','buffer':json.dumps(custom).encode()})
    p.locator('#modal [data-act=close-modal]').first.click();p.wait_for_timeout(550)
    check('Delayed import cannot reopen a dismissed library',lambda:equal(p.evaluate('Littlewild.ui.modal'),None))
    p.evaluate('() => {File.prototype.text=window._originalText;}')
    # Same build and guide flows on small screens; measure actual rectangles.
    for width,height in [(1440,900),(1024,768),(768,1024),(390,844),(320,568),(844,390)]:
        p.set_viewport_size({'width':width,'height':height});p.evaluate("Littlewild.open('construction')");p.wait_for_timeout(100)
        tag=f'{width}x{height}'
        check(tag+': build panel fits viewport',lambda:expect(p.locator('#build-panel').evaluate('(el)=>{let r=el.getBoundingClientRect();return r.x>=0&&r.y>=0&&r.right<=innerWidth&&r.bottom<=innerHeight;}')))
        check(tag+': world remains visible beside/above Build',lambda:expect(p.locator('#build-panel').evaluate('(el)=>{let r=el.getBoundingClientRect();return r.width*r.height<innerWidth*innerHeight*.65;}')))
        check(tag+': build footer remains reachable',lambda:expect(p.locator('#build-panel .panel-footer').evaluate('(el)=>el.getBoundingClientRect().bottom<=innerHeight')))
        check(tag+': no horizontal page overflow',lambda:expect(p.evaluate('document.documentElement.scrollWidth<=innerWidth')))
        p.screenshot(path=str(SHOTS/('build-'+tag+'.png')))
        p.locator('.build-row').first.click();p.locator('#build-actor').select_option('c1')
        p.locator('[data-build=place]').scroll_into_view_if_needed()
        check(tag+': primary placement action scrolls into view',lambda:expect(p.locator('[data-build=place]').is_visible()))
        p.evaluate("Littlewild.open('v10-guide')");p.wait_for_timeout(80)
        check(tag+': guide fits without covering entire world',lambda:expect(p.locator('#guide-panel').evaluate('(el)=>{let r=el.getBoundingClientRect();return r.x>=0&&r.y>=0&&r.bottom<=innerHeight&&r.width*r.height<innerWidth*innerHeight*.58;}')))
        check(tag+': guide footer remains reachable',lambda:expect(p.locator('#guide-panel .panel-footer').evaluate('(el)=>el.getBoundingClientRect().bottom<=innerHeight')))
        p.screenshot(path=str(SHOTS/('guide-'+tag+'.png')))
        p.locator('[data-guide=close]').click()
    check('No uncaught browser errors in tested flows',lambda:equal(errors,[]))
    check('Game makes no HTTP/HTTPS requests',lambda:equal(requests,[]))
    browser.close()
report={'passed':sum(x['passed'] for x in results),'total':len(results),'results':results,'errors':errors,'externalRequests':requests}
(OUTPUT/'browser-results.json').write_text(json.dumps(report,indent=2));print(f"{report['passed']}/{report['total']}")
if report['passed']!=report['total']:raise SystemExit(1)
