/// <reference path="./creature-editor-ui-contracts.d.ts" />
/* UI reads detached packages. Apply delegates to the existing Cancel-focused story review. */
(function(inputRoot:unknown){
 'use strict';
 type Data=LWCreatureEditor.Data;
 interface Root {LWSceneGraph:LWSceneGraph.Api;LWCreatureEditor:LWCreatureEditor.Api;LWCreaturePreview:LWCreaturePreview.Api;LWCreatureEditorView:{render(input:{session:LWCreatureEditor.Session;personality:string;pose:string;nodeId:string;notice:string;errors:string[];esc(value:unknown):string}):string;nodes(asset:LWCreatureEditor.Appearance,model:string):Data[]};LWFiles:{downloadJSON(value:unknown,name:string):void};LWCreatureEditorUI?:LWCreatureEditorSurface.Api;}
 const root=inputRoot as Root,record=(value:unknown):Data=>value!==null&&typeof value==='object'&&!Array.isArray(value)?value as Data:{};
 function create(ctx:LWCreatureEditorSurface.Host):LWCreatureEditorSurface.Editor {
  let session:LWCreatureEditor.Session|null=null,preview:LWCreaturePreview.Preview|null=null,canvas:HTMLCanvasElement|null=null,personality='',pose='neutral',nodeId='',notice='',errors:string[]=[],readId=0,previewRevision=-1,previewPersonality='',previewPose='';
  const lifecycle=new AbortController(),input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.hidden=true;input.id='creature-editor-import';document.body.append(input);
  function disposePreview():void {preview?.dispose();preview=null;canvas=null;previewRevision=-1;}
  function redraw(message=''):void {disposePreview();notice=message;ctx.redraw();}
  function fail(error:unknown):void {errors=[error instanceof Error?error.message:String(error)];redraw();}
  function open(pack?:LWContentPorts.ScenarioPack,sceneId?:string,instanceId?:string):void {
   readId++;disposePreview();if(!session){const captured=pack?{pack,sceneId:sceneId||pack.scenes[0]!.id,...(instanceId?{instanceId}:{})}:ctx.capture();const scene=root.LWSceneGraph.owner(captured.pack,captured.sceneId);const creatures=record(scene.initialState.colony).creatures;const selected=Array.isArray(creatures)?creatures.map(record).find(row=>row.id===captured.instanceId)||creatures.map(record)[0]:undefined;const definitions=captured.pack.resources?.creatures.definitions??[];const archetypeId=String(selected?.archetype||record(definitions[0]).id||'sproutling');session=root.LWCreatureEditor.create(captured.pack,{sceneId:captured.sceneId,archetypeId,...(selected?{instanceId:String(selected.id)}:{})});personality=String(selected?.personality||session.snapshot().gameplayDefinition.defaultPersonality);}
   errors=[];ctx.open('creature-editor');
  }
  function render(type='creature-editor'):string|null {if(type!=='creature-editor')return null;if(!session)return ctx.head('Open the creature editor from a captured scene.')+ctx.footer();const value=session.snapshot();if(!value.gameplayDefinition.personalities.includes(personality))personality=value.gameplayDefinition.personalities[0]||'';return ctx.head('Littlewild 3D Creature Editor','Edit an archetype and the selected companion in a detached draft.','')+root.LWCreatureEditorView.render({session,personality,pose,nodeId,notice,errors,esc:ctx.esc})+ctx.footer();}
  function draw():void {if(ctx.modal()!=='creature-editor'||!session){disposePreview();return;}const next=document.querySelector<HTMLCanvasElement>('#creature-editor-preview');if(!next)return;try{if(canvas!==next){disposePreview();canvas=next;preview=root.LWCreaturePreview.create(next);}if(previewRevision!==session.revision||previewPersonality!==personality||previewPose!==pose){preview!.update(session.snapshot(),personality,pose);previewRevision=session.revision;previewPersonality=personality;previewPose=pose;}preview!.draw();next.dataset.nodeCount=String(preview!.nodeCount);}catch(error){disposePreview();if(!errors.length)fail(error);}}
  const text=(form:HTMLFormElement,name:string):string=>(form.elements.namedItem(name) as HTMLInputElement|null)?.value||'';
  function submit(event:Event):void {const form=(event.target as Element).closest<HTMLFormElement>('[data-creature-form]');if(!form||ctx.modal()!=='creature-editor'||!session)return;event.preventDefault();try{const kind=form.dataset.creatureForm;if(kind==='field'){const field=session.fields().find(row=>row.id===form.dataset.fieldId)!;const raw=text(form,field.id);session.setField(field.id,field.type==='json'?JSON.parse(raw):field.type==='number'?Number(raw):field.type==='boolean'?raw==='true':raw);}
   if(kind==='duplicate'){session.duplicateArchetype(text(form,'new-id'),text(form,'new-name'));nodeId='';}
   if(kind==='advanced'){const patch=JSON.parse(text(form,'json')) as Data;if(form.dataset.target==='definition')session.updateDefinition(patch);if(form.dataset.target==='appearance')session.updateAppearance(patch);if(form.dataset.target==='instance')session.updateInstance(patch);}
   if(kind==='palette'){const value=session.snapshot(),appearances=record(value.appearanceManifest.behaviors.appearances),chosen=record(appearances[personality]),materials=record(chosen.materials);for(const role of Object.keys(materials)){const color=text(form,'color-'+role);materials[role]=typeof materials[role]==='string'?color:{...record(materials[role]),color};}chosen.model=text(form,'model');session.updateAppearance({behaviors:value.appearanceManifest.behaviors});nodeId='';}
   if(kind==='node'){const value=session.snapshot(),chosen=record(record(value.appearanceManifest.behaviors.appearances)[personality]),node=root.LWCreatureEditorView.nodes(value.appearanceManifest,String(chosen.model)).find(row=>row.id===form.dataset.nodeId);if(!node)throw Error('Choose a body part.');for(const property of ['position','scale','rotation'])node[property]=[0,1,2].map(index=>Number(text(form,property+'-'+index)));session.updateAppearance({models:value.appearanceManifest.models});}
   errors=[];redraw('Saved in the draft. Review the complete scenario to apply it.');
  }catch(error){fail(error);}}
  function click(event:Event):void {const button=(event.target as Element).closest<HTMLButtonElement>('[data-creature-editor]');if(!button||button.disabled||ctx.modal()!=='creature-editor'||!session)return;event.preventDefault();try{const action=button.dataset.creatureEditor;if(action==='undo'||action==='redo'){session[action]();errors=[];redraw();}if(action==='import')input.click();if(action==='export'){root.LWFiles.downloadJSON(session.exportPackage(),session.snapshot().gameplayDefinition.id+'.creature.json');redraw('Creature package exported.');}if(action==='export-pack'){root.LWFiles.downloadJSON(session.exportScenario(),'creature-edited.pack.json');redraw('Complete scenario exported.');}if(action==='review'){const pack=session.exportScenario();disposePreview();ctx.review(pack,session.selection.sceneId);}}catch(error){fail(error);}}
  function change(event:Event):void {const control=(event.target as Element).closest<HTMLSelectElement>('[data-creature-option]');if(!control||ctx.modal()!=='creature-editor')return;if(control.dataset.creatureOption==='instance'&&session){const pack=session.exportScenario(),scene=root.LWSceneGraph.owner(pack,session!.selection.sceneId),actors=record(scene.initialState.colony).creatures,selected=Array.isArray(actors)?actors.map(record).find(row=>row.id===control.value):undefined;session.select({sceneId:session.selection.sceneId,archetypeId:selected?String(selected.archetype):session.selection.archetypeId,...(selected?{instanceId:String(selected.id)}:{})});personality=String(selected?.personality||session.snapshot().gameplayDefinition.defaultPersonality);nodeId='';}if(control.dataset.creatureOption==='archetype'&&session){session.select({sceneId:session.selection.sceneId,archetypeId:control.value});personality=String(session.snapshot().gameplayDefinition.defaultPersonality);nodeId='';}if(control.dataset.creatureOption==='personality'){personality=control.value;nodeId='';}if(control.dataset.creatureOption==='pose')pose=control.value;if(control.dataset.creatureOption==='node')nodeId=control.value;redraw();}
  document.addEventListener('submit',submit,{signal:lifecycle.signal});document.addEventListener('click',click,{signal:lifecycle.signal});document.addEventListener('change',change,{signal:lifecycle.signal});
  input.addEventListener('change',async()=>{const file=input.files?.[0];if(!file||!session)return;const token=++readId,owner=session,revision=owner.revision;
   const current=():boolean=>token===readId&&session===owner&&owner.revision===revision&&ctx.modal()==='creature-editor';
   try{if(file.size>root.LWCreatureEditor.MAX_PACKAGE_BYTES)throw Error('Creature packages must be at most 8 MiB.');const value=await file.text();if(!current())return;owner.importPackage(value);errors=[];nodeId='';redraw('Imported a validated creature package. The active story is unchanged.');}catch(error){if(current())fail(error);}finally{if(token===readId)input.value='';}
  },{signal:lifecycle.signal});
  return {get session(){return session;},open,render,draw,cancelRead(){readId++;disposePreview();},reset(){readId++;disposePreview();session=null;errors=[];notice='';},dispose(){readId++;disposePreview();lifecycle.abort();input.remove();session=null;}};
 }
 root.LWCreatureEditorUI={create};
})(globalThis);
