/// <reference path="./creature-editor-ui-contracts.d.ts" />
/* Forms derive from a closed authored field catalog and the validated package's values. */
(function(inputRoot:unknown){
 'use strict';
 type Data=LWCreatureEditor.Data;
 interface Input {session:LWCreatureEditor.Session;personality:string;pose:string;nodeId:string;notice:string;errors:string[];esc(value:unknown):string;}
 const root=inputRoot as {LWSceneGraph:LWSceneGraph.Api;LWCreatureEditorView?:{render(input:Input):string;nodes(value:LWCreatureEditor.Appearance,model:string):Data[]}};
 const record=(value:unknown):Data=>value!==null&&typeof value==='object'&&!Array.isArray(value)?value as Data:{};
 function nodes(asset:LWCreatureEditor.Appearance,model:string):Data[]{const out:Data[]=[];function visit(list:Data[]):void{for(const node of list){if(node.id)out.push(node);if(Array.isArray(node.children))visit(node.children as Data[]);}}visit(asset.models[model]?.nodes??[]);return out;}
 function render(input:Input):string {
  const {session,personality,pose,nodeId,notice,errors,esc:e}=input,value=session.snapshot(),appearance=record(record(value.appearanceManifest.behaviors.appearances)[personality]);
  const button=(label:string,action:string,disabled=false)=>`<button type="button" class="btn" data-creature-editor="${action}" ${disabled?'disabled':''}>${label}</button>`;
  function control(field:LWCreatureEditor.Field):string {let current:unknown=field.target==='definition'?value.gameplayDefinition:value.selectedInstance;for(const key of field.path)current=record(current)[key];const name=e(field.id),label=e(field.label);if(field.id==='definition:visualAsset')return `<label>${label}<select name="${name}">${(session.exportScenario().resources?.assets??[]).filter(row=>record(row).category==='actor').map(row=>`<option value="${e(record(row).id)}" ${record(row).id===current?'selected':''}>${e(record(row).name)} · ${e(record(row).id)}</option>`).join('')}</select></label>`;if(field.type==='json')return `<label class="creature-field-json">${label}<textarea name="${name}" rows="3">${e(JSON.stringify(current,null,2))}</textarea></label>`;if(field.type==='boolean')return `<label>${label}<select name="${name}"><option value="true" ${current===true?'selected':''}>Yes</option><option value="false" ${current===false?'selected':''}>No</option></select></label>`;return `<label>${label}<input name="${name}" type="${field.type==='number'?'number':'text'}" value="${e(current)}" ${field.type==='number'?`step="${field.step??'any'}" ${field.min!==undefined?`min="${field.min}"`:''} ${field.max!==undefined?`max="${field.max}"`:''}`:'maxlength="300"'}></label>`;}
  const pack=session.exportScenario(),scene=root.LWSceneGraph.owner(pack,session.selection.sceneId),companions=record(scene.initialState.colony).creatures,actors=Array.isArray(companions)?companions.map(record):[],definitions=(pack.resources?.creatures.definitions??[]).map(record);
  const fields=session.fields(),groups=[...new Set(fields.map(field=>field.group))];
  const palette=record(appearance.materials),modelNodes=nodes(value.appearanceManifest,String(appearance.model)),selected=modelNodes.find(node=>node.id===nodeId)||modelNodes[0];
  return `<div class="modal-body creature-editor"><div class="creature-toolbar">${button('Undo','undo',!session.canUndo)}${button('Redo','redo',!session.canRedo)}${button('Import creature JSON','import')}${button('Export creature JSON','export')}${button('Export full scenario','export-pack')}<button class="btn primary" data-creature-editor="review">Review & apply</button><span>Draft revision ${session.revision}</span></div>
   ${errors.length?`<div class="validation-issue" role="alert"><strong>The edit was not applied.</strong>${errors.map(error=>`<p>${e(error)}</p>`).join('')}</div>`:''}${notice?`<p role="status" class="creature-notice">${e(notice)}</p>`:''}
   <div class="creature-control-pair creature-selection"><label>Archetype defaults<select data-creature-option="archetype">${definitions.map(def=>`<option value="${e(def.id)}" ${def.id===value.gameplayDefinition.id?'selected':''}>${e(def.name)}</option>`).join('')}</select></label><label>Current companion<select data-creature-option="instance"><option value="">Archetype defaults only</option>${actors.map(actor=>`<option value="${e(actor.id)}" ${actor.id===value.selectedInstance?.id?'selected':''}>${e(actor.name)} · ${e(actor.archetype)}</option>`).join('')}</select></label></div><div class="creature-workspace"><section class="creature-preview-column"><h3>${e(value.gameplayDefinition.name)}</h3><p>${value.selectedInstance?`Editing ${e(value.selectedInstance.name)} (${e(value.selectedInstance.id)}) and archetype defaults.`:'Editing archetype defaults for future companions.'}</p><canvas id="creature-editor-preview" tabindex="0" role="img" aria-label="Interactive 3D creature preview. Arrow keys orbit, plus and minus zoom, Home resets."></canvas><p class="panel-hint">Drag to orbit · scroll to zoom. Keyboard: arrows, +, −, Home.</p><div class="creature-control-pair"><label>Appearance<select data-creature-option="personality">${value.gameplayDefinition.personalities.map(id=>`<option value="${e(id)}" ${id===personality?'selected':''}>${e(id)}</option>`).join('')}</select></label><label>Preview pose<select data-creature-option="pose">${['neutral','curious','wave','rest'].map(id=>`<option ${id===pose?'selected':''}>${id}</option>`).join('')}</select></label></div><p class="panel-hint">Poses change this preview only. Supported primitive models and the declared rig are rendered directly.</p><details><summary>Create an archetype</summary><form data-creature-form="duplicate"><label>Stable ID<input name="new-id" required pattern="[a-z](?:[a-z0-9]|_|-){0,60}" placeholder="brookling"></label><label>Name<input name="new-name" required maxlength="100"></label><button class="btn" type="submit">Create from this archetype</button><p class="panel-hint">Copies gameplay and visuals without changing existing companions. Recruit it after applying the reviewed scenario.</p></form></details></section>
   <section class="creature-properties"><h3>Gameplay values</h3><p class="panel-hint">State defaults affect new companions. Movement and physiology tune every companion of this archetype. Current values belong only to the selected companion; existing work and deterministic state are retained.</p>${groups.map((group,index)=>`<details ${index<2?'open':''}><summary>${e(group)}</summary><div class="creature-fields">${fields.filter(field=>field.group===group).map(field=>`<form data-creature-form="field" data-field-id="${e(field.id)}">${control(field)}<button class="btn small" type="submit">Save ${e(field.label)}</button></form>`).join('')}</div></details>`).join('')}</section>
   <section class="creature-appearance"><h3>Appearance & body</h3><form data-creature-form="palette"><label>Model<select name="model">${Object.keys(value.appearanceManifest.models).map(model=>`<option value="${e(model)}" ${model===appearance.model?'selected':''}>${e(model)}</option>`).join('')}</select></label><div class="creature-fields">${Object.entries(palette).map(([role,color])=>`<label>${e(role)}<input type="color" name="color-${e(role)}" value="${e(typeof color==='string'?color:record(color).color)}"></label>`).join('')}</div><button class="btn" type="submit">Save appearance palette</button></form><label>Body part<select data-creature-option="node">${modelNodes.map(node=>`<option value="${e(node.id)}" ${node.id===selected?.id?'selected':''}>${e(node.id)} · ${e(node.primitive)}</option>`).join('')}</select></label>${selected?`<form data-creature-form="node" data-node-id="${e(selected.id)}"><div class="creature-fields">${['position','scale','rotation'].map(property=>`<fieldset><legend>${property}</legend>${['X','Y','Z'].map((axis,index)=>`<label>${axis}<input type="number" step="0.01" name="${property}-${index}" value="${e(Array.isArray(selected[property])?selected[property][index]:property==='scale'?1:0)}"></label>`).join('')}</fieldset>`).join('')}</div><button class="btn" type="submit">Save body part</button></form>`:''}<details><summary>Advanced validated JSON</summary><p class="panel-hint">The same native validators check defaults, components, rig and primitive nodes. Executable content and unsupported formats are rejected.</p>${(['definition','appearance',...(value.selectedInstance?['instance']:[])] as string[]).map(target=>`<form data-creature-form="advanced" data-target="${target}"><label>${target}<textarea name="json" rows="10">${e(JSON.stringify(target==='definition'?value.gameplayDefinition:target==='appearance'?value.appearanceManifest:value.selectedInstance,null,2))}</textarea></label><button class="btn" type="submit">Save ${target} JSON</button></form>`).join('')}</details></section></div></div>`;
 }
 root.LWCreatureEditorView={render,nodes};
})(globalThis);
