'use strict';
// Tests run the composite showcase game: install its content profile before any engine module loads.
require('./test-support/install-games.cjs');
const fs=require('node:fs'),assert=require('node:assert/strict'),crypto=require('node:crypto'),cp=require('node:child_process'),path=require('node:path');
const {executableFiles,assertAuthoredTypescript}=require('./verification/release-integrity.js');
const L=require('./simulation.cjs'),S=require('./story-codec.js'),G=require('./growth-content.js'),root=path.resolve(__dirname,'..'),sourceRoot=path.join(root,'source');const results=[];
function test(name,fn){try{fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:e.stack});console.error('FAIL',name,e.message);}}
const html=fs.readFileSync(root+'/.generated/artifacts/showcase.html','utf8');
test('Title and entry point are v15, with no unresolved build markers',()=>{assert(html.includes('Worlds of Possibility · v15'));assert(!html.includes('<!-- INLINE_'));assert(html.includes("version: '15.0.0'"));});
test('No external executable or visual dependencies',()=>{assert(!/<script[^>]+src=/i.test(html));assert(!/<(?:link|img|iframe)[^>]+(?:href|src)=["']https?:/i.test(html));assert(html.includes("connect-src 'none'"));});
test('Vendor license is retained in the actual HTML',()=>assert(html.includes('Copyright © 2010-2026 three.js authors')));
test('Compiled output parses and authored executable source is TypeScript',()=>{for(const file of executableFiles(__dirname).filter(file=>/\.(?:js|cjs|mjs)$/i.test(file)))cp.execFileSync(process.execPath,['--check',file],{stdio:'pipe',timeout:10000});assertAuthoredTypescript(sourceRoot);});
test('Native story import rejects obsolete versions',()=>{const doc=S.encode(L.createWorldDemo());for(const version of [1,2,3,4,5,6,7])assert.throws(()=>S.inspect({...doc,version}),/current Littlewild story format/);});
test('Mechanical Growth change cannot replace committed work',()=>{const e=L.createWorldDemo(),candidate=G.clone(G.content);candidate.rules.landCoinsBase++;assert(S.committed(e));const before=JSON.stringify(e.export()),hash=G.hash;assert.throws(()=>S.applyGrowth(candidate,e));assert.equal(JSON.stringify(e.export()),before);assert.equal(G.hash,hash);});
test('Presentation-only Growth change is safe during committed work',()=>{const e=L.createWorldDemo(),candidate=G.clone(G.content),before=JSON.stringify(e.export()),original=G.clone(G.content);candidate.interactions[0].label='A test label';try{const loaded=S.applyGrowth(candidate,e);assert.equal(G.content.interactions[0].label,'A test label');assert.equal(JSON.stringify(loaded.export()),before);}finally{G.replace(original);}});
test('Growth fingerprints include rules, requirements, events and presentation metadata',()=>{const original=G.clone(G.content);for(const mutate of [p=>p.rules.landCoinsBase++,p=>p.requirements.items.wood.playerLevel++,p=>p.events[0].seconds++,p=>p.interactions[0].label+='!',p=>p.extensions={externalTool:'round-trip'}]){const candidate=G.clone(original);mutate(candidate);assert.notEqual(G.hashOf(candidate),G.hashOf(original));}});
test('Growth hash is key-order invariant but mechanical hash ignores only presentation',()=>{const p=G.clone(G.content),reversed=Object.fromEntries(Object.entries(p).reverse());assert.equal(G.hashOf(p),G.hashOf(reversed));const copy=G.clone(p);copy.interactions[0].label+='!';assert.equal(G.mechanicalHash(copy),G.mechanicalHash(p));copy.rules.slotPrestigeBase++;assert.notEqual(G.mechanicalHash(copy),G.mechanicalHash(p));});
test('Tampered Growth snapshot cannot be loaded under an old fingerprint',()=>{const e=L.createWorldDemo(),doc=S.encode(e);doc.growth.library.rules.landCoinsBase++;assert.throws(()=>S.inspect(doc),/fingerprint|match|hash|changed/i);});
test('Native care rejects extra configurable costs instead of silently ignoring them',()=>{const doc=G.clone(G.content);doc.interactions.find(i=>i.handler==='care').cost={berries:1};assert.equal(G.validate(doc).ok,false);});
test('Raw item requirements guard requests, autonomous sourcing and planner choices',()=>{const doc=G.clone(G.content);doc.requirements.items.wood.playerLevel=3;G.withLibrary(doc,()=>{const e=new L.Engine();e.s.started=true;e.selectCreature('c1');const before=JSON.stringify(e.export());assert(!e.request('gather','wood',1).ok);assert.equal(e.resourceTask('wood'),null);assert(!global.LWPlanner.taskOptions(e,'gather',e.actor).some(d=>d.id==='wood'));assert.equal(JSON.stringify(e.export()),before);e.s.player.level=3;assert(e.unlocked('items','wood'));});});
test('Recipe output also respects its item-level requirement',()=>{const doc=G.clone(G.content);doc.requirements.items.planks.playerLevel=3;G.withLibrary(doc,()=>{const e=new L.Engine();e.s.started=true;e.selectCreature('c1');assert(e.s.progression.research['recipe-planks']);assert(!e.unlocked('recipes','planks'));const before=JSON.stringify(e.export());assert(!e.request('craft','planks',1).ok);assert.equal(JSON.stringify(e.export()),before);});});
test('Item feature-rank requirements remain separate from player level',()=>{const doc=G.clone(G.content);doc.requirements.items.wood.features={making:1};G.withLibrary(doc,()=>{const e=new L.Engine();e.s.player.level=20;assert(!e.unlocked('items','wood'));e.s.progression.features.making=1;assert(e.unlocked('items','wood'));});});
test('Prestige offers cannot bypass item-level requirements',()=>{const doc=G.clone(G.content);doc.requirements.items.walking_boots.playerLevel=10;G.withLibrary(doc,()=>{const e=L.createWorldDemo();e.s.player.level=5;e.s.progression.prestige=100;const before=JSON.stringify(e.export());assert(!e.buyPrestigeItem('boots').ok);assert.equal(JSON.stringify(e.export()),before);});});
test('Example event library validates with carried-item costs',()=>{const example=JSON.parse(fs.readFileSync(root+'/examples/new-island-interaction.json'));assert(G.validate(example).ok);G.withLibrary(example,()=>{const e=L.createWorldDemo();e.grantInteractionEvent('island-purchased','c1');const action=e.interactions(e.actor).find(i=>i.id==='shore-picnic');assert(action);e.selectCreature('c1');e.actor.inventory.berries=1;assert(e.interact('c1',action.instance).ok);assert.equal(e.actor.inventory.berries,0);assert(!e.interact('c1',action.instance).ok);});});
for(const command of ['export','schema','validate','diff'])test('Growth CLI '+command+' emits valid JSON and never writes inputs',()=>{const file=root+'/examples/new-island-interaction.json',args=[__dirname+'/tools/growth-cli.cjs',command];if(['validate','diff'].includes(command))args.push(file);const before=fs.readFileSync(file,'utf8'),out=JSON.parse(cp.execFileSync(process.execPath,args,{encoding:'utf8'}));assert(out);if(out.ok!==undefined)assert(out.ok);assert.equal(fs.readFileSync(file,'utf8'),before);});
test('Authoring CLI rejects invalid usage with structured error',()=>{const r=cp.spawnSync(process.execPath,[__dirname+'/tools/growth-cli.cjs','bad'],{encoding:'utf8'});assert.equal(r.status,2);assert.equal(JSON.parse(r.stdout).ok,false);});
test('All four shipped content libraries validate through runtime CLIs',()=>{for(const[tool,file]of [['content','default-library.json'],['adventure','adventure-library.json'],['world','world-library.json'],['growth','growth-library.json']]){const r=cp.spawnSync(process.execPath,[__dirname+'/tools/'+tool+'-cli.cjs','validate',__dirname+'/content/'+file],{encoding:'utf8'});assert.equal(r.status,0,r.stdout+r.stderr);assert(JSON.parse(r.stdout).ok);}});
test('Shipped simulation profile validates through its data-only CLI',()=>{const file=__dirname+'/content/simulation-profile.json',before=fs.readFileSync(file);const r=cp.spawnSync(process.execPath,[__dirname+'/tools/simulation-profile-cli.cjs','validate',file],{encoding:'utf8'});assert.equal(r.status,0,r.stdout+r.stderr);const out=JSON.parse(r.stdout);assert(out.ok);assert.equal(out.profile,'classic-v1');assert.equal(out.archetype,'living-world-v1');assert.equal(fs.readFileSync(file).compare(before),0);});
test('Simulation profile CLI exposes the committed standalone schema',()=>{const r=cp.spawnSync(process.execPath,[__dirname+'/tools/simulation-profile-cli.cjs','schema'],{encoding:'utf8'});assert.equal(r.status,0,r.stdout+r.stderr);assert.deepEqual(JSON.parse(r.stdout),JSON.parse(fs.readFileSync(__dirname+'/content/simulation.schema.json')));});
test('Built-in scenario packs publish schema 2 and a validated profile',()=>{for(const [name,profile] of [['littlewild','classic-v1'],['emberworks','classic-v1'],['office','office-v1']]){const file=__dirname+'/content/'+name+'.pack.json',before=fs.readFileSync(file);const r=cp.spawnSync(process.execPath,[__dirname+'/tools/scenario-cli.cjs','validate',file],{encoding:'utf8'});assert.equal(r.status,0,r.stdout+r.stderr);const out=JSON.parse(r.stdout);assert(out.ok);assert.equal(out.simulationProfile,profile);assert.equal(out.compositionArchetype,'living-world-v1');assert.equal(fs.readFileSync(file).compare(before),0);}});
test('Standalone bundle contains the versioned profile and envelope-10 boundary',()=>{for(const marker of ['LWSimulationProfile','living-world-v1','simulationFingerprint','version = 10'])assert(html.includes(marker),marker);});


test('Every bundled script parses as JavaScript',()=>{const vm=require('node:vm');for(const m of html.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);});
test('Scenario code is bundled without runtime network dependencies',()=>{for(const marker of ['LWScenarios','LWGuidePanel','LWBuildPanel','living-worlds-pack','emberworks','office-v1','scenarioWorkflow','scenarioResources'])assert(html.includes(marker),marker);});

const passed=results.filter(r=>r.passed).length,hash=crypto.createHash('sha256').update(html).digest('hex');fs.writeFileSync(__dirname+'/release-results.json',JSON.stringify({passed,total:results.length,htmlSha256:hash,bytes:Buffer.byteLength(html),results},null,2));console.log(passed+'/'+results.length+' release checks passed');if(passed!==results.length)process.exitCode=1;
