'use strict';
// Tests run the composite showcase game: install its content profile before any engine module loads.
require('./test-support/install-games.cjs');
const fs=require('node:fs'),assert=require('node:assert/strict'),L=require('./simulation.cjs'),S=require('./story-codec.js'),C=global.LWGrowth,G=global.LWGeography,P=global.LWPlanner;
const results=[],test=(name,fn)=>{let now=performance.now();try{fn();results.push({name,passed:true,ms:performance.now()-now});}catch(e){console.error('FAIL',name,e.message);results.push({name,passed:false,error:e.stack});}};
function openAll(e){for(const research of C.content.research){e.s.progression.research[research.id]=true;if(research.grants)e.s.progression.features[research.grants.feature]=Math.max(e.s.progression.features[research.grants.feature]||0,research.grants.rank);}}
function scenario(seed){const e=L.createWorldDemo();e.s.started=true;e.s.paused=false;e.s.player.coins=100000;e.s.player.level=20;e.s.progression.prestige=e.s.progression.earnedPrestige=100000;e.s.progression.slots=6;openAll(e);e.s.colony.rng=seed;for(const b of e.s.buildings)if(C.content.homes[b.kind])b.level=3;for(const p of ['maker','sunny','steadfast']){const r=e.purchaseCreature(p);assert(r.ok,r.reason);}e.selectCreature('c1');for(const[x,y]of[[1,0],[0,-1]])assert(e.buyIsland(x,y).ok);for(const c of e.creatures){c.orders=[];c.task=null;c.training=null;c.learning.queue=[];c.equipQueue=[];c.rpg.rng=seed*341+Number(c.id.slice(1));}return e;}
for(const seed of [13,47])test('Six creatures / three islands / 30 simulated minutes / seed '+seed,()=>{let e=scenario(seed),restores=0;const seen=new Set();for(let i=0;i<18000;i++){if(i%2400===0){const carrier=e.creatures[i/2400%6|0];P.add(e,{type:'gather',id:i%4800?'stone':'wood',quantity:5,actorId:carrier.id});if(e.s.colony.warehouse.inventory.wood>=3)e.sellItem('wood',3,carrier.id);}if(i===2000)P.add(e,{type:'build',id:'shelter',quantity:1,actorId:'c2'});e.step(.1);for(const c of e.creatures){assert(Number.isFinite(c.creature.x)&&Number.isFinite(c.creature.y));assert(Object.values(c.inventory).every(n=>Number.isInteger(n)&&n>=0));if(c.task)seen.add(c.task.kind);}if(i%1800===1799){const next=S.commit(S.inspect(S.encode(e)));assert.deepEqual(next.export(),e.export());e=next;restores++;}}
 const b=S.commit(S.inspect(S.encode(e)));for(let n=0;n<300;n++){e.step(.1);b.step(.1);}assert.deepEqual(b.export(),e.export());assert(seen.has('market-pickup')&&seen.has('market-deliver')&&seen.has('market-sell'));assert.equal(restores,10);assert.equal(e.creatures.length,6);assert.equal(G.bridges(e.s).length,2);console.log('seed',seed,'actions', [...seen].join(','),'market receipts',e.s.market.history.length);});
test('25-island purchase cap, unique resources and reachable bridges',()=>{const e=scenario(3);e.s.player.coins=1e12;e.s.progression.prestige=e.s.progression.earnedPrestige=1e12;while(e.s.estate.islands.length<25){const f=G.frontier(e.s).sort((a,b)=>Math.abs(a.ix)+Math.abs(a.iy)-Math.abs(b.ix)-Math.abs(b.iy))[0];const r=e.buyIsland(f.ix,f.iy);assert(r.ok,r.reason);}const before=JSON.stringify(e.export()),f=G.frontier(e.s)[0];assert(!e.buyIsland(f.ix,f.iy).ok);assert.equal(JSON.stringify(e.export()),before);assert.equal(new Set(e.s.nodes.map(n=>n.id)).size,e.s.nodes.length);const grid=G.grid(e.s);assert.equal(grid.flood({x:9,y:9}).size,grid.cells.size);assert.doesNotThrow(()=>S.inspect(S.encode(e)));});
const passed=results.filter(r=>r.passed).length;fs.writeFileSync(__dirname+'/growth-stress-results.json',JSON.stringify({passed,total:results.length,results},null,2));console.log(passed+'/'+results.length+' stress scenarios passed');if(passed!==results.length)process.exitCode=1;
