/// <reference path="./engine-export-contracts.d.ts" />
/// <reference path="./renderer-contracts.d.ts" />
/// <reference path="./animation-contracts.d.ts" />
// Tests run the composite showcase game: install its content profile before any engine module loads.
import './test-support/install-games.cjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {gunzipSync} from 'node:zlib';
const X=require('./scenario-runtime.js') as LWContentPorts.ScenarioApi,E=require('./engine-export.js') as LWEngineExport.Api,D=require('./engine-export-data.js') as LWEngineExport.Decoder;
const results:{name:string;passed:boolean;error?:string}[]=[];
async function test(name:string,fn:()=>Promise<void>|void):Promise<void>{try{await fn();results.push({name,passed:true});}catch(error){results.push({name,passed:false,error:String(error)});console.error(name,String(error));}}
async function main():Promise<void>{
 const pack=X.builtins().find(value=>value.id==='office')!,before=JSON.stringify(pack),exchanged=await E.export(pack,pack.scenes[0]!.id),source=exchanged.sources;
 await test('Ignored generated suite evidence cannot change the source bundle or its metadata',()=>{
  const builder=require('./tools/engine-export-bundle.cjs') as {createSourceBundle(project:string):LWEngineExport.SourceBundle};
  const project=path.resolve(__dirname,'..'),evidence=path.join(project,'source/engine-export-audit-results.json');
  assert.equal(fs.existsSync(evidence),false);const original=builder.createSourceBundle(project);
  try{fs.writeFileSync(evidence,JSON.stringify({passed:1,total:1,results:[{name:'Prior run',passed:true}]}));const rebuilt=builder.createSourceBundle(project);assert.deepEqual(rebuilt,original);assert.equal(rebuilt.files.some(file=>file.path==='source/engine-export-audit-results.json'),false);}
  finally{fs.rmSync(evidence,{force:true});}
 });
 await test('Complete versioned inert input preserves native pack/checkpoints and has cryptographic inventory',async()=>{
  assert.equal(exchanged.format,'littlewild-engine-export');assert.deepEqual(exchanged.pack,pack);assert.equal(JSON.stringify(pack),before);assert(source.files.length>300);assert.equal(source.identity,exchanged.sourceIdentity);assert.equal(new Set(source.files.map(file=>file.path)).size,source.files.length);assert.deepEqual(source.inventory.included,source.files.map(file=>file.path));assert((await E.validate(exchanged)).ok);
  for(const required of ['source/engine.ts','source/physical-ecs-contracts.d.ts','source/storytelling-player.ts','source/content/balancing.json','source/content/balancing-inventory.json','source/assets/creatures/sproutling/definition.json','package-lock.json','vendor/p5-source-2.3.4.tar.gz','toolchain/typescript/lib/typescript.js','toolchain/@types/node/index.d.ts'])assert(source.files.some(file=>file.path===required),required);
  for(const required of ['source/wildlands-godot/main.gd','source/wildlands-godot/bridge.gd','source/wildlands-godot/assets.gd','source/tools/wildlands-bundle.cts'])assert(source.files.some(file=>file.path===required),required);
  assert(!source.files.some(file=>file.path==='source/wildlands-godot/test-native.gd'),'Native verification code must not become playable export source');
 });
 await test('Real system/command/schedule capabilities and Godot transforms remain explicit',()=>{
  const runtime=exchanged.runtime,commands=(runtime.commands as {manifest:{id:string}[]}).manifest,systems=runtime.systems as {id:string;source:string;components:string[]}[];assert(commands.some(command=>command.id==='apply-terraform'));assert(commands.some(command=>command.id==='request-interaction'));assert(systems.some(system=>system.id==='production-settlement'));assert(systems.some(system=>system.id==='task-movement'));assert.equal((runtime.schedule as {compiled:unknown[]}).compiled.length,6);assert(systems.every(system=>system.components.length&&source.files.some(file=>file.path===system.source)));
  const coordinates=exchanged.godot.coordinateSystem as {islandCells:number;islandStride:number;mapping:{z:string}};assert.equal(coordinates.islandCells,19);assert.equal(coordinates.islandStride,23);assert.equal(coordinates.mapping.z,'native.y');assert((exchanged.godot.requiredWork as string[]).some(value=>value.includes('gameplay parity')));
 });
 await test('Dimension-aware Godot scenes retain actual floor geometry, embeds and native elevation',async()=>{
  const p=D.parse(pack) as LWContentPorts.ScenarioPack,scene=p.scenes[0]!,state=scene.initialState,buildings=state.buildings as {id:string;kind:string}[],building=buildings.find(value=>value.kind==='bench')!,interiors=(globalThis as unknown as {LWInteriors:LWInterior.CatalogApi}).LWInteriors,floor=interiors.forBuilding(state as unknown as LWInterior.CatalogWorld,building).floors[0]!,point=floor.cells?.[0]??{x:1,y:1};
  scene.graph={kind:'level',rendering:{dimension:'3d',rendererId:'basic',embeds:[{id:'room-panel',sceneId:'room-export',role:'panel'}]}};p.scenes.push({id:'room-export',name:'Room',description:'Bound canonical floor',worldId:scene.worldId,initialState:{},graph:{kind:'interior',parentId:scene.id,binding:{type:'interior',sourceSceneId:scene.id,buildingId:building.id,floorId:floor.id},rendering:{dimension:'2d',rendererId:'pixi-2d'},props:[{id:'floor-prop',name:'Wood',category:'item',assetId:'wood',model:'world',x:point.x,y:point.y}]}});
  const actor=(state.colony as {creatures:{creature:{x:number;y:number}}[]}).creatures[0]!.creature;state.terraform={version:1,revision:0,sequence:1,tiles:{[Math.round(actor.x)+','+Math.round(actor.y)]:{ground:'grass',height:1}},plants:{}};
  const result=await E.export(p,'room-export'),scenes=result.godot.scenes as {id:string;node:string;floor:LWInterior.Floor;bounds:{width:number;height:number};rendering:{dimension:string};embeds:unknown[];entities:{category:string;node:string;position:number[]}[]}[],room=scenes.find(value=>value.id==='room-export')!,rootScene=scenes.find(value=>value.id===scene.id)!;
  assert.equal(room.node,'Node2D');assert.equal(room.rendering.dimension,'2d');assert.deepEqual(room.floor,floor);assert.equal(room.bounds.width,floor.width);assert.equal(room.bounds.height,floor.height);assert.equal(room.entities[0]!.node,'Node2D');assert.deepEqual(room.entities[0]!.position,[point.x,point.y]);assert.equal(rootScene.embeds.length,1);assert.equal(rootScene.entities.find(value=>value.category==='creatures')!.position[1],1);assert((await E.validate(result)).ok);
 });
 await test('Every manifest source reference resolves the trusted source inventory and all RNG streams are declared',()=>{
  function visit(value:unknown):void{if(typeof value==='string'&&value.startsWith('source/'))assert(source.files.some(file=>file.path===value),'Unresolved '+value);else if(Array.isArray(value))value.forEach(visit);else if(value&&typeof value==='object')Object.values(value).forEach(visit);}
  visit(exchanged.runtime);visit(exchanged.godot);assert((exchanged.runtime.determinism as {rng:{streams:string}}).rng.streams.includes('creatureInteractions.rng'));assert(source.files.some(file=>file.path==='toolchain/undici-types/index.d.ts'));
 });
 await test('Registered custom main and embedded renderers export metadata and explicit missing-module/manual-port requirements',async()=>{
  const registry=require('./renderer-registry.js') as LittlewildRenderer.Registry;let calls=0;
  const withdraw3d=registry.register({id:'export-custom-3d',name:'Export3D',description:'Trusted compiled extension',capabilities:['camera'],dimensions:['3d']},()=>{calls++;throw Error('Export must never invoke renderer factories.');});
  const withdraw2d=registry.register({id:'export-custom-2d',name:'Export2D',description:'Trusted embedded extension',capabilities:['camera','hit-test'],dimensions:['2d']},()=>{calls++;throw Error('Export must never invoke renderer factories.');});
  try{
   const p=D.parse(pack) as LWContentPorts.ScenarioPack,scene=p.scenes[0]!;scene.graph={kind:'level',rendering:{dimension:'3d',rendererId:'export-custom-3d',embeds:[{id:'custom-map',sceneId:'custom-embedded',role:'minimap'}]}};
   const building=(scene.initialState.buildings as {id:string;kind:string}[]).find(value=>value.kind==='bench')!,interiors=(globalThis as unknown as {LWInteriors:LWInterior.CatalogApi}).LWInteriors,floor=interiors.forBuilding(scene.initialState as unknown as LWInterior.CatalogWorld,building).floors[0]!;
   for(const [id,name,rendererId] of [['custom-embedded','Custom embedded view','export-custom-2d'],['portable-unavailable','Unavailable renderer','constructor']] as const)p.scenes.push({id,name,description:'Native bound floor projection',worldId:scene.worldId,initialState:{},graph:{kind:'interior',parentId:scene.id,binding:{type:'interior',sourceSceneId:scene.id,buildingId:building.id,floorId:floor.id},rendering:{dimension:'2d',rendererId}}});
   const result=await E.export(p,scene.id),entries=result.godot.renderers as {id:string;metadata:LittlewildRenderer.Metadata|null;registered:boolean;source:string|null;sourceIncluded:boolean;requiresModule:boolean;uses:{sceneId:string;dimension:string;embeddedBy:string[]}[];requiredWork:string}[];
   for(const id of ['export-custom-3d','export-custom-2d','constructor']){const entry=entries.find(value=>value.id===id)!;assert(entry);assert.equal(entry.source,null);assert.equal(entry.sourceIncluded,false);assert.equal(entry.requiresModule,true);assert(entry.requiredWork.includes('compiled renderer extension module'));assert(result.limitations.some(value=>value.includes(id)&&value.includes('manual semantic port')));assert(!Object.hasOwn(entry,'factory'));}
   const embedded=entries.find(value=>value.id==='export-custom-2d')!;assert.deepEqual(embedded.metadata?.dimensions,['2d']);assert(embedded.uses.some(use=>use.sceneId==='custom-embedded'&&use.embeddedBy.includes(scene.id)));assert.equal(entries.find(value=>value.id==='export-custom-3d')!.registered,true);assert.equal(entries.find(value=>value.id==='constructor')!.metadata,null);assert.equal(entries.find(value=>value.id==='constructor')!.registered,false);withdraw3d();withdraw2d();assert((await E.validate(result)).ok);assert.equal(calls,0);
   for(const mutate of [(doc:LWEngineExport.Document)=>{doc.extensions.renderers[0]!.metadata={...doc.extensions.renderers[0]!.metadata!,dimensions:['2d']};},(doc:LWEngineExport.Document)=>{doc.extensions.renderers[0]!.id='wrong-id';},(doc:LWEngineExport.Document)=>{Object.assign(doc.extensions.renderers[0]!.metadata!,{factory:'unsafe'});},(doc:LWEngineExport.Document)=>{doc.extensions.renderers.pop();}]){const invalid=D.parse(result) as LWEngineExport.Document;mutate(invalid);assert.equal((await E.validate(invalid)).ok,false);}
  }finally{withdraw3d();withdraw2d();}
 });
 await test('Custom animation snapshots survive immediate withdrawal and cold validation without installing callbacks',async()=>{
  require('./developer-data.js');require('./renderer-animations.js');const animations=(globalThis as unknown as {LWAnimations:LWAnimations.Api}).LWAnimations;let calls=0;
  const withdraw=animations.register({id:'export-custom-preset',name:'Custom export preset',description:'Compiled draw extension',source:'source/renderer-example.ts'},()=>{calls++;throw Error('Never draw during inert export.');});
  const p=D.parse(pack) as LWContentPorts.ScenarioPack,scene=p.scenes[0]!;p.storytelling={version:1,cutscenes:[{id:'export-clip',name:'Export',sceneId:scene.id,duration:2,skipPolicy:'finish',tracks:[],animations:['sparkles','orbit','ripple','export-custom-preset'].map((presetId,index)=>({id:'animation-'+index,presetId,start:0,duration:1,x:1,y:1,radius:4,color:'#ffffff',count:3}))}],storyboards:[]};
  try{const pending=E.export(p,scene.id);withdraw();const result=await pending;assert.deepEqual(result.pack,p);assert.equal(result.extensions.animations[0]!.metadata.source,'source/renderer-example.ts');assert((await E.validate(result)).ok);assert.equal(calls,0);assert.equal(X.validate(p).ok,false);
   for(const mutate of [(doc:LWEngineExport.Document)=>{doc.extensions.animations[0]!.metadata={...doc.extensions.animations[0]!.metadata,source:'../escape.ts'};},(doc:LWEngineExport.Document)=>{doc.extensions.animations[0]!.metadata={...doc.extensions.animations[0]!.metadata,id:'wrong-id'};},(doc:LWEngineExport.Document)=>{Object.assign(doc.extensions.animations[0]!.metadata,{parameters:'unknown'});},(doc:LWEngineExport.Document)=>{doc.pack.storytelling!.cutscenes[0]!.animations![0]!.count=Infinity;}]){const invalid=D.parse(result) as LWEngineExport.Document;mutate(invalid);assert.equal((await E.validate(invalid)).ok,false);}
  }finally{withdraw();}
 });
 await test('Exact source hashes include binary vendor source archive without UTF8 corruption',()=>{
  for(const file of source.files){const raw=Buffer.from(file.text,file.encoding==='base64'?'base64':'utf8');assert.equal(raw.byteLength,file.bytes);assert.equal(createHash('sha256').update(raw).digest('hex'),file.sha256);}
  const archive=source.files.find(file=>file.path==='vendor/p5-source-2.3.4.tar.gz')!;assert.equal(archive.encoding,'base64');assert(gunzipSync(Buffer.from(archive.text,'base64')).byteLength>archive.bytes);
 });
 await test('Browser compressed loader expands into byte-identical Node bundle',()=>{
  const loader=JSON.parse(fs.readFileSync(path.join(__dirname,'engine-source-loader.json'),'utf8')) as LWEngineExport.SourceLoader;const bytes=Buffer.from(loader.data,'base64'),decoded=gunzipSync(bytes);assert.equal(bytes.byteLength,loader.compressedBytes);assert.equal(decoded.byteLength,loader.decodedBytes);assert.deepEqual(decoded,fs.readFileSync(path.join(__dirname,'engine-source-bundle.json')));assert.deepEqual(JSON.parse(decoded.toString()),source);assert.equal(loader.identity,source.identity);
 });
 await test('Incomplete inventory, path traversal, hash tampering and derived manifest edits reject',async()=>{
  for(const mutate of [(value:LWEngineExport.Document)=>{value.sources.files.pop();},(value:LWEngineExport.Document)=>{value.sources.files[0]!.path='../engine.ts';},(value:LWEngineExport.Document)=>{value.sources.files[0]!.text+='\n//changed';},(value:LWEngineExport.Document)=>{value.sources.inventory.included.pop();},(value:LWEngineExport.Document)=>{value.godot.selectedSceneId='missing';}]){const changed=D.parse(exchanged) as LWEngineExport.Document;mutate(changed);assert.equal((await E.validate(changed)).ok,false);}assert.equal(JSON.stringify(pack),before);
 });
 await test('Long inert source text is data and object accessors/functions/prototypes never run',()=>{
  let calls=0;const accessor={};Object.defineProperty(accessor,'text',{enumerable:true,get(){calls++;return 'executed';}});assert.throws(()=>D.parse(accessor));assert.equal(calls,0);assert.throws(()=>D.parse({run:()=>calls++}));assert.throws(()=>D.parse(Object.create({source:'unsafe'}) as unknown));assert.throws(()=>D.parse(JSON.parse('{"__proto__":{}}')));assert.throws(()=>D.parse('{"key":1,"key":2}'));assert.throws(()=>D.parse(new Array(1)));assert.throws(()=>D.parse(new Array(250001)));assert.deepEqual(D.parse({source:'globalThis.shouldNeverExecute=true;'}),{source:'globalThis.shouldNeverExecute=true;'});assert.equal((globalThis as unknown as {shouldNeverExecute?:boolean}).shouldNeverExecute,undefined);assert.throws(()=>D.parse({value:Infinity}));assert.throws(()=>D.parse({text:'x'.repeat(16*1024*1024+1)}));
 });
 await test('Engine input is rejected by playable scenario admission; canonical JSON object order is immaterial',async()=>{
  assert.equal(X.validate({format:exchanged.format,schemaVersion:1}).ok,false);const ordered={...exchanged,sources:{...source,files:source.files.map(file=>({text:file.text,dependencies:file.dependencies,sha256:file.sha256,bytes:file.bytes,role:file.role,encoding:file.encoding,path:file.path}))}};assert((await E.validate(ordered)).ok);
 });
 await test('Paid native work/actor fractional coordinates survive export without losing continuation state',async()=>{
  const engine=X.commitScene(X.prepareScene(pack,pack.scenes[0]!.id)) as LWContentPorts.ScenarioEngine&{advance(seconds:number):void};let paid=false;for(let i=0;i<1000;i++){engine.advance(.1);const buildings=engine.export().state.buildings as {storage?:{job?:{progress:number}}}[];if(buildings.some(building=>(building.storage?.job?.progress??0)>0)){paid=true;break;}}assert(paid);const captured=X.capture(engine),snapshot=engine.export(),value=await E.export(captured,captured.scenes[0]!.id);assert.deepEqual(value.pack,captured);assert.deepEqual(engine.export(),snapshot);assert.deepEqual(value.checkpoint.owners.find(owner=>owner.id===captured.scenes[0]!.id)!.state,captured.scenes[0]!.initialState);assert((await E.validate(value)).ok);const restored=X.commitScene(X.prepareScene(value.pack,value.sceneId)) as LWContentPorts.ScenarioEngine&{advance(seconds:number):void};engine.advance(1);restored.advance(1);assert.deepEqual(restored.export(),engine.export());
 });
}
main().catch(error=>{results.push({name:'Setup',passed:false,error:String(error)});}).finally(()=>{const report={suite:'engine-export',passed:results.filter(result=>result.passed).length,total:results.length,results};fs.writeFileSync(path.join(__dirname,'engine-export-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(results.some(result=>!result.passed))process.exitCode=1;});
