/// <reference path="./creature-editor-contracts.d.ts" />
/// <reference path="./creature-editor-preview-contracts.d.ts" />
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
const {toolbox}=require('./developer-sdk.cjs') as {toolbox:LittlewildDeveloper.Toolbox};
const X=require('./scenario-runtime.js') as LWContentPorts.ScenarioApi,E=require('./creature-editor.js') as LWCreatureEditor.Api;
type Data=LWCreatureEditor.Data;
interface Engine extends LWContentPorts.ScenarioEngine {advance(seconds:number):void;export():{state:Data};}
const root=globalThis as unknown as {LWContent:LWContentPorts.ContentApi;LWAssets:{all():unknown[];revision:number};LWCreatures:{all():unknown[];revision:number};LWWorldProfile:{current:unknown};THREE:unknown;LWAssetRenderer:{createFromDefinition(kit:LWCreaturePreview.Kit,parent:LWCreaturePreview.Object3D,input:unknown,model:string,options:Data):LWCreaturePreview.Instance};};
const copy=root.LWContent.copy,record=(value:unknown):Data=>value!==null&&typeof value==='object'&&!Array.isArray(value)?value as Data:{};
const results:{name:string;passed:boolean;error?:string}[]=[];
function test(name:string,work:()=>void):void{try{work();results.push({name,passed:true});}catch(error){results.push({name,passed:false,error:String(error)});}}
const base=():LWContentPorts.ScenarioPack=>copy(X.builtins().find(pack=>pack.id==='office')!);
const selection={sceneId:'operations-shift',archetypeId:'sproutling',instanceId:'c1'};
const catalog=():string=>JSON.stringify([root.LWAssets.all(),root.LWAssets.revision,root.LWCreatures.all(),root.LWCreatures.revision,root.LWWorldProfile.current]);
function actor(pack:LWContentPorts.ScenarioPack,id='c1'):Data {const list=record(pack.scenes[0]!.initialState.colony).creatures as Data[];return list.find(row=>row.id===id)!;}
function sameAfterReject(editor:LWCreatureEditor.Session,work:()=>void):void{const before=editor.exportPackage(),pack=editor.exportScenario(),revision=editor.revision,context=catalog();assert.throws(work);assert.deepEqual(editor.exportPackage(),before);assert.deepEqual(editor.exportScenario(),pack);assert.equal(editor.revision,revision);assert.equal(catalog(),context);}
test('Standalone package includes complete co-located gameplay and visuals, exact JSON roundtrip',()=>{
 const editor=E.create(base(),selection),original=editor.exportPackage(),context=catalog();assert.equal(original.gameplayDefinition.visualAsset,original.appearanceManifest.id);assert(original.appearanceManifest.rig);assert(original.selectedInstance);editor.importPackage(JSON.stringify(original));assert.deepEqual(editor.exportPackage(),original);assert.equal(catalog(),context);assert.equal(E.validatePackage(original).ok,false);assert(E.validatePackage(original,{pack:base(),selection}).ok);
});
test('Public SDK editor façade exposes detached intent and the same package authority',()=>{const editor=toolbox.createCreatureEditor(base(),selection);editor.setField('instance:rpg.attributes.IQ',12);assert.equal(record(record(editor.snapshot().selectedInstance!.rpg).attributes).IQ,12);assert(!('engine' in editor));assert(toolbox.validateCreaturePackage(editor.exportPackage(),{pack:base(),selection}).ok);});
test('Snapshots, fields and exported scenario values are detached from the owned draft',()=>{
 const editor=E.create(base(),selection),value=editor.snapshot();value.gameplayDefinition.name='Mutated';value.appearanceManifest.materials.fur='#000000';value.selectedInstance!.name='Mutated';assert.notEqual(editor.snapshot().selectedInstance!.name,'Mutated');assert.notEqual(editor.snapshot().gameplayDefinition.name,'Mutated');const pack=editor.exportScenario();actor(pack).name='Mutated';assert.notEqual(actor(editor.exportScenario()).name,'Mutated');
});
test('Defaults and current attributes, inventory and needs have distinct data-driven field intent',()=>{
 const editor=E.create(base(),selection),before=editor.snapshot();editor.setField('definition:physiology.food',.6);editor.setField('instance:rpg.attributes.ST',12);editor.setField('instance:inventory.berries',7);editor.setField('instance:needs.food',73);const saved=editor.snapshot();assert.equal(record(saved.gameplayDefinition.physiology).food,.6);assert.equal(record(record(saved.selectedInstance!.rpg).attributes).ST,12);assert.equal(record(saved.selectedInstance!.inventory).berries,7);assert.deepEqual(saved.gameplayDefinition.state.defaults,before.gameplayDefinition.state.defaults);assert.equal(record(actor(editor.exportScenario()).needs).food,73);editor.undo();assert.notEqual(record(editor.snapshot().selectedInstance!.needs).food,73);editor.redo();assert.equal(record(editor.snapshot().selectedInstance!.needs).food,73);
});
test('Archetype creation uses compiled catalogs, supports future recruitment and preserves current actors',()=>{
 const editor=E.create(base(),selection),before=copy(actor(editor.exportScenario()));editor.duplicateArchetype('brookling','Brookling');const pack=editor.exportScenario();assert(pack.resources!.creatures.definitions.some(row=>record(row).id==='brookling'));assert(pack.resources!.assets.some(row=>record(row).id==='brookling'&&record(row).category==='actor'));assert.deepEqual(actor(pack),before);assert.equal(editor.selection.archetypeId,'brookling');assert.equal(editor.snapshot().selectedInstance,undefined);assert(X.validate(pack).ok);editor.undo();assert.equal(editor.selection.instanceId,'c1');editor.redo();assert.equal(editor.snapshot().gameplayDefinition.id,'brookling');
});
test('Visual swapping and existing companion archetype edits use declared assets without resetting work',()=>{const editor=E.create(base(),selection),before=editor.snapshot().selectedInstance!;editor.duplicateArchetype('brookling','Brookling');editor.select(selection);editor.setField('definition:visualAsset','brookling');assert.equal(editor.snapshot().appearanceManifest.id,'brookling');editor.setField('instance:archetype','brookling');assert.equal(editor.selection.archetypeId,'brookling');const current=editor.snapshot().selectedInstance!;assert.equal(current.archetype,'brookling');for(const key of ['task','orders','inventory','rpg','creature'])assert.deepEqual(current[key],before[key]);});
test('Companion selection keeps accepted prior edits in the same complete scenario',()=>{
 const editor=E.create(base(),selection);editor.setField('instance:name','Angela edited');editor.select({...selection,instanceId:'c2'});assert.notEqual(editor.snapshot().selectedInstance!.name,'Angela edited');assert.equal(actor(editor.exportScenario()).name,'Angela edited');editor.undo();assert.equal(editor.snapshot().selectedInstance!.name,'Angela edited');
});
test('Visual palette and actual primitive node changes are retained in the portable resource catalog',()=>{
 const editor=E.create(base(),selection),value=editor.snapshot();const appearances=record(value.appearanceManifest.behaviors.appearances),chosen=record(appearances.curious);record(chosen.materials).fur='#cc8844';const model=String(chosen.model),node=value.appearanceManifest.models[model]!.nodes[1]!;node.position=[0,.1,0];editor.updateAppearance({behaviors:value.appearanceManifest.behaviors,models:value.appearanceManifest.models});assert.deepEqual(editor.exportPackage().appearanceManifest.models[model]!.nodes[1]!.position,[0,.1,0]);const assets=editor.exportScenario().resources!.assets;assert.equal(record(record(record(assets.find(row=>record(row).id==='sproutling')).behaviors).appearances).curious instanceof Object,true);
});
test('Malformed executable, unknown primitive, missing rig and incompatible native fields reject atomically',()=>{
 const editor=E.create(base(),selection);
 for(const mutate of [
  (value:LWCreatureEditor.Package)=>{value.gameplayDefinition.script='run';},
  (value:LWCreatureEditor.Package)=>{value.appearanceManifest.models.world!.nodes[0]!.primitive='external-mesh';},
  (value:LWCreatureEditor.Package)=>{value.appearanceManifest.rig.head='absent-node';},
  (value:LWCreatureEditor.Package)=>{value.selectedInstance!.inventory={wood:-2};},
  (value:LWCreatureEditor.Package)=>{value.selectedInstance!.id='c99';},
  (value:LWCreatureEditor.Package)=>{value.selectedInstance!.unsupportedFunction={script:'run'};}
 ]){const bad=editor.snapshot();mutate(bad);sameAfterReject(editor,()=>editor.importPackage(bad));}
 sameAfterReject(editor,()=>editor.setField('definition:physiology.food',5));sameAfterReject(editor,()=>editor.setField('not-an-authored-field',1));sameAfterReject(editor,()=>editor.importPackage('{'));
});
test('Rejected creation cannot replace an existing archetype or silently retune its actors',()=>{
 const editor=E.create(base(),selection);sameAfterReject(editor,()=>editor.duplicateArchetype('sproutling','Collision'));sameAfterReject(editor,()=>editor.duplicateArchetype('bad ID','Invalid'));sameAfterReject(editor,()=>editor.updateDefinition({id:'other'}));
});
test('Imported another archetype changes draft selection consistently and invalid scenes reject',()=>{const editor=E.create(base(),selection),other=E.create(base(),selection);other.duplicateArchetype('brookling','Brookling');editor.importPackage(other.exportPackage());assert.equal(editor.selection.archetypeId,'brookling');assert.equal(editor.snapshot().gameplayDefinition.id,'brookling');assert.equal(editor.selection.instanceId,undefined);assert.throws(()=>E.create(base(),{sceneId:'absent',archetypeId:'sproutling'}));sameAfterReject(editor,()=>editor.select({sceneId:'absent',archetypeId:'brookling'}));});
test('Authoring a gated scene validates native state without executing entry requirements or events',()=>{const pack=base();pack.scenes[0]!.graph={kind:'level',requirements:[{type:'player-level',minimum:999}],events:[{type:'message',text:'Entry message'}]};assert(X.validate(pack).ok);const editor=E.create(pack,selection);editor.updateInstance({name:'Angela revised'});assert.equal(editor.snapshot().selectedInstance!.name,'Angela revised');assert.equal(editor.revision,1);});
test('Bound Office floor edits target the owner companion and retain the selected review scene',()=>{const pack=base(),source=pack.scenes[0]!;pack.scenes.push({id:'office-floor',name:'Office floor',description:'Bound packing room',worldId:source.worldId,initialState:{},graph:{kind:'interior',parentId:source.id,binding:{type:'interior',sourceSceneId:source.id,buildingId:'bench',floorId:'ground'}}});const building=(source.initialState.buildings as Data[]).find(row=>row.kind==='bench')!;(pack.scenes[1]!.graph!.binding as {buildingId:string}).buildingId=String(building.id);assert(X.validate(pack).ok);const editor=E.create(pack,{...selection,sceneId:'office-floor'});editor.setField('instance:name','Floor companion');assert.equal(actor(editor.exportScenario()).name,'Floor companion');assert.equal(editor.selection.sceneId,'office-floor');assert.deepEqual(editor.exportScenario().scenes[1]!.initialState,{});});
test('Bounded history retains only twenty accepted edits and redo branches are discarded',()=>{
 const editor=E.create(base(),selection);for(let index=0;index<22;index++)editor.setField('instance:name','Companion '+index);let count=0;while(editor.canUndo){editor.undo();count++;}assert.equal(count,20);editor.redo();editor.setField('instance:name','New branch');assert.equal(editor.canRedo,false);
});
test('Captured running paid work, inventory, deterministic state and native continuation survive reviewed name edit',()=>{
 const engine=X.commitScene(X.prepareScene(base(),selection.sceneId)) as Engine;engine.advance(36);const pack=X.capture(engine),before=copy(engine.export().state),context=catalog(),editor=E.create(pack,selection);editor.setField('instance:name','Angela edited');assert.deepEqual(engine.export().state,before);assert.equal(catalog(),context);const exported=editor.exportScenario(),native=X.commitScene(X.prepareScene(exported,selection.sceneId)) as Engine;
 const actual=copy(native.export().state),expected=copy(before);actor({scenes:[{initialState:actual}]} as unknown as LWContentPorts.ScenarioPack).name='Angela';delete actual.scenarioResources;delete expected.scenarioResources;assert.deepEqual(actual,expected);
 const reference=X.commitScene(X.prepareScene(pack,selection.sceneId)) as Engine;native.advance(24);reference.advance(24);const a=copy(native.export().state),b=copy(reference.export().state);actor({scenes:[{initialState:a}]} as unknown as LWContentPorts.ScenarioPack).name='Angela';delete a.scenarioResources;delete b.scenarioResources;assert.deepEqual(JSON.parse(JSON.stringify(a).replaceAll('Angela edited','Angela')),b);
});
test('Field catalog rejects unsupported selectors and executable control types',()=>{
 const fields=require('./creature-editor-fields.js') as {validate(input:unknown):unknown};const definition=JSON.parse(fs.readFileSync(__dirname+'/creature-editor-fields.json','utf8')) as Data;const bad=copy(definition);(bad.groups as Data[])[0]!.selector='#live-engine';assert.throws(()=>fields.validate(bad));const wrong=copy(definition);(wrong.groups as Data[])[0]!.target='engine';assert.throws(()=>fields.validate(wrong));
});
test('Descriptor-shaped imports and field catalogs reject without executing getters',()=>{const editor=E.create(base(),selection);let reads=0;const hostile=Object.defineProperty({},'id',{enumerable:true,get(){reads++;return 'sproutling';}});sameAfterReject(editor,()=>editor.updateDefinition(hostile));const fields=require('./creature-editor-fields.js') as {validate(input:unknown):unknown};assert.throws(()=>fields.validate(hostile));assert.equal(reads,0);});
test('Pure canonical asset interpreter builds real Three.js geometry from an unapplied draft',()=>{
 const vendor=path.resolve(__dirname,'../vendor/three.js');const realm:Data={};realm.window=realm;vm.runInNewContext(fs.readFileSync(vendor,'utf8'),realm);const three=realm.THREE as {Group:new()=>LWCreaturePreview.Object3D;Mesh:new(geometry:unknown,material:unknown)=>LWCreaturePreview.Object3D;SphereGeometry:new(radius:number,width:number,height:number)=>unknown;CylinderGeometry:new(top:number,bottom:number,height:number,segments:number)=>unknown;ConeGeometry:new(radius:number,height:number,segments:number)=>unknown;BoxGeometry:new(x:number,y:number,z:number)=>unknown;IcosahedronGeometry:new(radius:number,detail:number)=>unknown;TorusGeometry:new(radius:number,tube:number,radial:number,tubular:number)=>unknown;MeshStandardMaterial:new(options:Data)=>unknown;};root.THREE=three;require('./asset-renderer.js');const scene=new three.Group(),kit:LWCreaturePreview.Kit={group(parent){const group=new three.Group();parent.add(group);return group;},piece(parent,kind,x,y,z,sx,sy,sz,color){const geometry=kind==='soft'?new three.SphereGeometry(1,10,7):kind==='tiny'?new three.SphereGeometry(1,6,4):kind==='cylinder'?new three.CylinderGeometry(1,1,1,8):kind==='cone'?new three.ConeGeometry(1,1,7):kind==='box'?new three.BoxGeometry(1,1,1):kind==='ball'?new three.IcosahedronGeometry(1,0):new three.TorusGeometry(1,.07,4,16);const node=new three.Mesh(geometry,new three.MeshStandardMaterial({color}));node.position.set(x,y,z);node.scale.set(sx,sy,sz);parent.add(node);return node;}};const editor=E.create(base(),selection),draft=editor.snapshot();draft.appearanceManifest.id='unapplied-preview';const context=catalog();const profile=record(record(draft.appearanceManifest.behaviors.appearances).curious),instance=root.LWAssetRenderer.createFromDefinition(kit,scene,draft.appearanceManifest,String(profile.model),{materials:profile.materials,scale:profile.scale});assert(instance.handles.has(String(draft.appearanceManifest.rig.head)));let actual=0;instance.root.traverse(node=>{if(node.geometry)actual++;});assert(actual>20);assert.equal(catalog(),context);
});
const report={suite:'creature-editor',passed:results.filter(row=>row.passed).length,total:results.length,results};fs.writeFileSync(__dirname+'/creature-editor-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(results.some(row=>!row.passed))process.exitCode=1;
