/// <reference path="../creature-editor-ui-contracts.d.ts" />
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {ARTIFACT_FIXTURE_URL,launchBrowser} from './browser-harness';
import {artifactPath,monitorArtifacts,openColony,renderingFrames} from './browser-pages';
import type {Page} from 'playwright';
const ROOT=path.resolve(__dirname,'../..'),ARTIFACT=artifactPath(ROOT,'studio'),OUT=process.env.LITTLEWILD_CREATURE_EDITOR_OUT||path.join(ROOT,'verification/v15'),SHOTS=process.env.LITTLEWILD_SCREENSHOT_DIR||OUT;
const results:{name:string;passed:boolean;error?:string}[]=[],rawConsole:{type:string;text:string}[]=[],failedRequests:string[]=[];let diagnostics:unknown=null;
async function check(name:string,work:()=>Promise<void>):Promise<void>{try{await work();results.push({name,passed:true});console.log('PASS '+name);}catch(error){results.push({name,passed:false,error:String(error)});console.error(name,error);}}
async function value<T=unknown>(page:Page,expression:string):Promise<T>{return page.evaluate(expression) as Promise<T>;}
const state=(page:Page):Promise<string>=>value(page,'JSON.stringify(Littlewild.engine.export())');
const packageValue=(page:Page):Promise<LWCreatureEditor.Package>=>value(page,'Littlewild.scenarioUI.creatureEditor.session.exportPackage()');
async function pixels(page:Page):Promise<{colors:number;figurePixels:number}>{return value(page,'(()=>{const source=document.querySelector("#creature-editor-preview"),copy=document.createElement("canvas");copy.width=source.width;copy.height=source.height;const c=copy.getContext("2d");c.drawImage(source,0,0);const d=c.getImageData(0,0,copy.width,copy.height).data,counts=new Map();for(let i=0;i<d.length;i+=4){const key=(d[i]>>3)+","+(d[i+1]>>3)+","+(d[i+2]>>3);counts.set(key,(counts.get(key)||0)+1);}return{colors:counts.size,figurePixels:copy.width*copy.height-Math.max(...counts.values())}})()');}
async function image(page:Page):Promise<string>{return crypto.createHash('sha256').update(await page.locator('#creature-editor-preview').screenshot()).digest('hex');}
async function main():Promise<void>{
 const browser=await launchBrowser(),context=await browser.newContext({acceptDownloads:true}),observed=monitorArtifacts(context);context.on('page',p=>{p.on('console',message=>rawConsole.push({type:message.type(),text:message.text()}));p.on('requestfailed',request=>failedRequests.push(request.url()+': '+request.failure()?.errorText));});
 try{for(const viewport of [{width:1440,height:1000},{width:390,height:844}]){
  const page=await context.newPage();page.setDefaultTimeout(15000);await page.setViewportSize(viewport);await openColony(page,ARTIFACT);await page.locator('[data-act="begin"]').click();
  await page.evaluate('(()=>{const pack=LWScenarios.builtins().find(p=>p.id==="office");Littlewild.setEngine(LWScenarios.commitScene(LWScenarios.prepareScene(pack,"operations-shift")));Littlewild.engine.s.paused=true;Littlewild.engine.advance(36);Littlewild.refresh();Littlewild.open("scenarios");window.creaturePreviewStats={created:0,disposed:0};const original=LWCreaturePreview;window.LWCreaturePreview={create(canvas){creaturePreviewStats.created++;const view=original.create(canvas);return {...view,get nodeCount(){return view.nodeCount},dispose(){creaturePreviewStats.disposed++;view.dispose()}}}};})()');await page.locator('[data-scenario="creature-editor"]').click();
  const suffix=' at '+viewport.width+'px',original=await state(page);
  await check('Visible actual 3D preview and detached current Office companion'+suffix,async()=>{await page.waitForFunction(()=>Number(document.querySelector<HTMLCanvasElement>('#creature-editor-preview')?.dataset.nodeCount)>20);assert(await page.getByRole('heading',{name:'Littlewild 3D Creature Editor',exact:true}).isVisible());const projection=await pixels(page);assert(projection.colors>20,JSON.stringify(projection));assert(projection.figurePixels>1500,JSON.stringify(projection));assert.equal(await state(page),original);assert(await value(page,'document.documentElement.scrollWidth<=innerWidth'));});
  await check('Keyboard orbit, zoom and preview pose change real projected pixels'+suffix,async()=>{const before=await image(page);await page.locator('#creature-editor-preview').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('+');await renderingFrames(page);assert.notEqual(await image(page),before);const after=await image(page);await page.locator('[data-creature-option="pose"]').selectOption('wave');await renderingFrames(page);assert.notEqual(await image(page),after);assert.equal(await state(page),original);});
  await check('Appearance model palette and body transforms edit actual canonical assets'+suffix,async()=>{const before=await image(page),form=page.locator('[data-creature-form="palette"]');await form.locator('[name="color-fur"]').fill('#426a54');await form.getByRole('button',{name:'Save appearance palette'}).click();await renderingFrames(page);assert.notEqual(await image(page),before);const current=await packageValue(page);assert.equal(((current.appearanceManifest.behaviors.appearances as Record<string,{materials:Record<string,string>}>).curious!).materials.fur,'#426a54');await page.locator('[data-creature-option="node"]').selectOption('head');const node=page.locator('[data-creature-form="node"]');await node.locator('[name="scale-0"]').fill('1.25');await node.getByRole('button',{name:'Save body part'}).click();assert.equal(await state(page),original);await page.locator('[data-creature-editor="undo"]').click();await page.locator('[data-creature-editor="redo"]').click();});
  await check('Actual current inventory and RPG values remain separate from archetype defaults'+suffix,async()=>{await page.getByText('Current inventory',{exact:true}).click();let form=page.locator('[data-creature-form="field"][data-field-id="instance:inventory.berries"]');await form.locator('input').fill('9');await form.getByRole('button').click();await page.getByText('Current attributes',{exact:true}).click();form=page.locator('[data-creature-form="field"][data-field-id="instance:rpg.attributes.ST"]');await form.locator('input').fill('12');await form.getByRole('button').click();const current=await packageValue(page);assert.equal((current.selectedInstance!.inventory as Record<string,number>).berries,9);assert.equal(((current.selectedInstance!.rpg as {attributes:Record<string,number>}).attributes.ST),12);assert.equal(await state(page),original);});
  await check('Package download and import retain the exact accepted package'+suffix,async()=>{const exported=await packageValue(page),downloadPromise=page.waitForEvent('download');await page.locator('[data-creature-editor="export"]').click();const download=await downloadPromise,file=await download.path();assert(file);assert.deepEqual(JSON.parse(fs.readFileSync(file,'utf8')),exported);await page.locator('#creature-editor-import').setInputFiles({name:'roundtrip.creature.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});await page.getByRole('status').filter({hasText:'Imported a validated'}).waitFor();assert.deepEqual(await packageValue(page),exported);assert.equal(await state(page),original);});
  await check('Malformed package import preserves draft, history, globals and live work'+suffix,async()=>{const before=await packageValue(page),revision=await value(page,'Littlewild.scenarioUI.creatureEditor.session.revision');const bad=structuredClone(before);bad.appearanceManifest.models.world!.nodes[0]!.primitive='scripted-mesh';await page.locator('#creature-editor-import').setInputFiles({name:'bad.creature.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});await page.getByRole('alert').filter({hasText:'The edit was not applied'}).waitFor();assert.deepEqual(await packageValue(page),before);assert.equal(await value(page,'Littlewild.scenarioUI.creatureEditor.session.revision'),revision);assert.equal(await state(page),original);});
  await check('Delayed real package import preserves a newer current companion edit'+suffix,async()=>{
   const before=await packageValue(page);await page.evaluate('window.__creatureOriginalText=File.prototype.text;File.prototype.text=function(){const selected=this;return new Promise((resolve,reject)=>{window.__releaseCreatureImport=()=>window.__creatureOriginalText.call(selected).then(resolve,reject);});};');
   try{
    await page.locator('#creature-editor-import').setInputFiles({name:'delayed.creature.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(before))});await page.waitForFunction('typeof window.__releaseCreatureImport==="function"');
    await page.getByText('Current identity',{exact:true}).click();const form=page.locator('[data-creature-form="field"][data-field-id="instance:name"]');await form.locator('input').fill('Later companion edit');await form.getByRole('button').click();
    const newer=await packageValue(page),revision=await value(page,'Littlewild.scenarioUI.creatureEditor.session.revision');assert.equal(newer.selectedInstance!.name,'Later companion edit');await page.evaluate('window.__releaseCreatureImport()');assert.deepEqual(await packageValue(page),newer);assert.equal(await value(page,'Littlewild.scenarioUI.creatureEditor.session.revision'),revision);assert.equal(await state(page),original);
    await page.locator('[data-creature-editor="undo"]').click();assert.deepEqual(await packageValue(page),before);
   }finally{await page.evaluate('File.prototype.text=window.__creatureOriginalText;delete window.__creatureOriginalText;delete window.__releaseCreatureImport;');}
  });
  await check('Close and reopen retain same-story draft and dispose preview canvas'+suffix,async()=>{const before=await packageValue(page);await page.locator('[data-act="close-modal"]').first().click();assert.equal(await value(page,'Littlewild.ui.modal'),null);assert(await value(page,'creaturePreviewStats.created===creaturePreviewStats.disposed'));await page.evaluate('Littlewild.open("scenarios")');await page.locator('[data-scenario="creature-editor"]').click();assert.deepEqual(await packageValue(page),before);await page.waitForFunction(()=>Number(document.querySelector<HTMLCanvasElement>('#creature-editor-preview')?.dataset.nodeCount)>20);});
  await page.locator('.creature-editor').evaluate(element=>{element.scrollTop=0;});if(viewport.width===390){if(process.env.LITTLEWILD_CAPTURE_SCREENSHOTS==='1')await page.screenshot({path:path.join(SHOTS,'creature-editor-390-overview.png'),fullPage:true});await page.locator('#creature-editor-preview').scrollIntoViewIfNeeded();}if(process.env.LITTLEWILD_CAPTURE_SCREENSHOTS==='1')await page.screenshot({path:path.join(SHOTS,`creature-editor-${viewport.width}.png`),fullPage:true});
  await check('Review cancellation preserves draft and current paid Office state'+suffix,async()=>{const before=await packageValue(page),revision=await value(page,'Littlewild.scenarioUI.creatureEditor.session.revision');await page.locator('[data-creature-editor="review"]').click();assert.equal(await state(page),original);const cancelFocused=await page.locator('[data-scenario="cancel"]').evaluate(element=>element===document.activeElement);await page.locator('[data-scenario="cancel"]').click();assert(cancelFocused);assert.deepEqual(await packageValue(page),before);assert.equal(await value(page,'Littlewild.scenarioUI.creatureEditor.session.revision'),revision);assert.equal(await state(page),original);});
  if(viewport.width===1440){await check('Reviewed apply preserves native paid work and portable deterministic continuation',async()=>{await page.evaluate('window.creatureExpected=Littlewild.scenarioUI.creatureEditor.session.exportScenario().scenes[0].initialState');await page.locator('[data-creature-editor="review"]').click();await page.locator('[data-scenario="launch"]').click();await page.evaluate('Littlewild.engine.s.paused=true;Littlewild.refresh()');assert(await value(page,'LWContent.stable(Littlewild.engine.export().state)===LWContent.stable(creatureExpected)'));assert.equal(await value(page,'Littlewild.scenarioUI.creatureEditor.session'),null);assert(await value(page,'(()=>{const expected=LW.Engine.import(Littlewild.engine.export()),native=LW.Engine.import(Littlewild.engine.export()),portable=LWStory.commit(LWStory.inspect(Littlewild.snapshot()));expected.advance(12);native.advance(12);portable.advance(12);return LWContent.stable(expected.export())===LWContent.stable(native.export())&&LWContent.stable(native.export())===LWContent.stable(portable.export())})()'));});}
  await page.close();
 }}finally{diagnostics=observed;await context.close();await browser.close();}
 await check('Raw browser diagnostics contain no console warnings, page errors or external network requests',async()=>{assert.deepEqual(observed.errors,[]);assert.deepEqual(observed.consoleProblems,[]);assert.deepEqual(observed.requests,[]);assert.deepEqual(observed.fixtureRequests,[ARTIFACT_FIXTURE_URL,ARTIFACT_FIXTURE_URL]);assert.deepEqual(failedRequests,[]);});
}
fs.mkdirSync(OUT,{recursive:true});fs.mkdirSync(SHOTS,{recursive:true});main().catch(error=>{results.push({name:'Creature editor browser setup',passed:false,error:String(error)});}).finally(()=>{const passed=results.filter(row=>row.passed).length;fs.writeFileSync(path.join(OUT,'creature-editor-browser-results.json'),JSON.stringify({passed,total:results.length,results,diagnostics,rawConsole,failedRequests,artifact:{bytes:fs.statSync(ARTIFACT).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(ARTIFACT)).digest('hex')}},null,2));console.log(`Creature editor browser: ${passed}/${results.length} passed.`);if(passed!==results.length)process.exitCode=1;});
