/// <reference path="../engine-export-contracts.d.ts" />
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import type {Page} from 'playwright';
import {launchBrowser,monitorContext,READY_TIMEOUT_MS,waitForReady} from './browser-harness';
const ROOT=path.resolve(__dirname,'../..'),ARTIFACT=process.env.LITTLEWILD_BROWSER_ARTIFACT||path.join(ROOT,'littlewild.html'),OUT=process.env.LITTLEWILD_ENGINE_EXPORT_OUT||path.join(ROOT,'verification/v15');
const FIXTURE='https://localhost/littlewild-engine-export-proof';
const results:{name:string;passed:boolean;error?:string}[]=[];let diagnostics:unknown;
async function test(name:string,fn:()=>Promise<void>):Promise<void>{try{await fn();results.push({name,passed:true});console.log('PASS '+name);}catch(error){results.push({name,passed:false,error:String(error)});console.error(name,String(error));}}
const value=<T=unknown>(page:Page,text:string):Promise<T>=>page.evaluate(text) as Promise<T>;
async function main():Promise<void>{
 fs.mkdirSync(OUT,{recursive:true});const native=require('../engine-export.js') as LWEngineExport.Api,bundle=require('../engine-source-bundle.json') as LWEngineExport.SourceBundle,browser=await launchBrowser(),context=await browser.newContext({acceptDownloads:true}),observations=monitorContext(context);
 // Managed Chromium blocks file://; this exact document route serves the offline artifact without network.
 await context.route(FIXTURE,route=>route.fulfill({status:200,contentType:'text/html',body:fs.readFileSync(ARTIFACT,'utf8')}));
 try{for(const width of [1440,390]){
  const page=await context.newPage();page.setDefaultTimeout(60000);await page.setViewportSize({width,height:width===390?844:1000});
  await page.addInitScript('localStorage.clear();window.__sourceInflations=0;window.__originalDecompressionStream=DecompressionStream;window.DecompressionStream=class extends window.__originalDecompressionStream{constructor(format){super(format);window.__sourceInflations++;}}');
  const started=Date.now();await page.goto(FIXTURE,{waitUntil:'load',timeout:60000});await waitForReady(page,{timeout:READY_TIMEOUT_MS});const startup=Date.now()-started;
  await page.locator('[data-act="begin"]').click();await page.evaluate('Littlewild.engine.s.paused=true;Littlewild.open("scenarios")');await page.locator('[data-scenario="editor"]').click();const original=await value<string>(page,'JSON.stringify(Littlewild.engine.export())'),draft=await value<string>(page,'JSON.stringify(Littlewild.scenarioUI.editor.session.snapshot())');
  await test(width+'px engine source stays compressed during offline startup and editor opening',async()=>{assert(await value<boolean>(page,'window.isSecureContext&&!!crypto.subtle'));assert.equal(await value<number>(page,'window.__sourceInflations'),0);assert(startup<20000,'startup '+startup+'ms');assert.equal(await page.locator('[data-engine-export-panel]').getAttribute('open'),null);if(process.env.LITTLEWILD_CAPTURE_SCREENSHOTS==='1')await page.screenshot({path:path.join(OUT,'engine-export-collapsed-'+width+'.png'),fullPage:true});});
  if(width===1440)await test('Declared source inflation bounds stop oversized streaming data before admission',async()=>{const error=await value<string>(page,'(async()=>{const old=LWEngineSourceLoader.decodedBytes;LWEngineSourceLoader.decodedBytes=32;try{await LWDeveloper.engineExport.export(Littlewild.scenarioUI.editor.session.export(),Littlewild.scenarioUI.editor.state.selection.id);return "accepted";}catch(error){return error.message;}finally{LWEngineSourceLoader.decodedBytes=old;}})()');assert(error.includes('bounds'));assert.equal(await value<string>(page,'JSON.stringify(Littlewild.engine.export())'),original);});
  if(width===390)await test('Mobile engine export retains a reachable 44px touch target',async()=>{await page.locator('[data-engine-export-panel] summary').click();try{const target=await page.locator('[data-engine-export-download]').boundingBox();assert(target&&target.width>=44&&target.height>=44,JSON.stringify(target));}finally{await page.locator('[data-engine-export-panel] summary').click();}});
  await test(width+'px actual engine JSON download matches Node full source inventory and native draft',async()=>{
   await page.locator('[data-engine-export-panel] summary').click();const download=page.waitForEvent('download',{timeout:60000});await page.locator('[data-engine-export-download]').click();const file=await download,saved=path.join(OUT,'engine-'+width+'.json');assert(file.suggestedFilename().endsWith('.engine.json'));await file.saveAs(saved);const exchanged=JSON.parse(fs.readFileSync(saved,'utf8')) as LWEngineExport.Document;assert.equal(exchanged.sourceIdentity,bundle.identity);assert.deepEqual(exchanged.sources,bundle);assert.deepEqual(exchanged.pack,JSON.parse(draft));const checked=await native.validate(exchanged);assert(checked.ok,checked.ok?'':checked.errors.join('\n'));assert.equal(await value<string>(page,'JSON.stringify(Littlewild.engine.export())'),original);assert.equal(await value<string>(page,'JSON.stringify(Littlewild.scenarioUI.editor.session.snapshot())'),draft);assert.equal(await value<number>(page,'Littlewild.scenarioUI.editor.session.revision'),0);if(process.env.LITTLEWILD_CAPTURE_SCREENSHOTS==='1')await page.screenshot({path:path.join(OUT,'engine-export-complete-'+width+'.png'),fullPage:true});
  });
  if(width===1440){
   await test('Browser built-in and custom renderer/p5 exports validate in a cold Node CLI after extension withdrawal',async()=>{
    const download=page.waitForEvent('download',{timeout:120000}).catch(()=>null);
    await page.evaluate(`(async()=>{
     window.__exportExtensionCalls=0;
     const remove3d=LWRenderers.register({id:'browser-export-3d',name:'Browser3D',description:'Compiled browser extension',capabilities:['camera'],dimensions:['3d']},()=>{window.__exportExtensionCalls++;throw Error('Factory cannot run during export');});
     const remove2d=LWRenderers.register({id:'browser-export-2d',name:'Browser2D',description:'Compiled embedded extension',capabilities:['camera'],dimensions:['2d']},()=>{window.__exportExtensionCalls++;throw Error('Factory cannot run during export');});
     const removePreset=LWAnimations.register({id:'browser-export-preset',name:'Browser preset',description:'Compiled p5 extension',source:'source/renderer-example.ts'},()=>{window.__exportExtensionCalls++;throw Error('Draw cannot run during export');});
     try{
      const p=LWContent.copy(LWScenarios.builtins().find(row=>row.id==='office')),scene=p.scenes[0],building=scene.initialState.buildings.find(row=>row.kind==='bench'),floor=LWInteriors.forBuilding(scene.initialState,building).floors[0];
      scene.graph={kind:'level',rendering:{dimension:'3d',rendererId:'browser-export-3d',embeds:[]}};
      for(const [index,rendererId] of ['pixi-2d','excalibur-2d','browser-export-2d'].entries()){
       const id='browser-export-room-'+index;p.scenes.push({id,name:'Export room '+index,description:'Canonical floor projection',worldId:scene.worldId,initialState:{},graph:{kind:'interior',parentId:scene.id,binding:{type:'interior',sourceSceneId:scene.id,buildingId:building.id,floorId:floor.id},rendering:{dimension:'2d',rendererId}}});scene.graph.rendering.embeds.push({id:'export-panel-'+index,sceneId:id,role:'panel'});
      }
      p.storytelling={version:1,cutscenes:[{id:'browser-export-clip',name:'Export',sceneId:scene.id,duration:2,skipPolicy:'finish',tracks:[],animations:['sparkles','orbit','ripple','browser-export-preset'].map((presetId,index)=>({id:'browser-animation-'+index,presetId,start:0,duration:1,x:1,y:1,radius:4,color:'#ffffff',count:3}))}],storyboards:[]};
      const pending=LWDeveloper.engineExport.export(p,scene.id);remove3d();remove2d();removePreset();const d=await pending;
      const checked=await LWDeveloper.engineExport.validate(d);if(!checked.ok)throw Error('Cold browser metadata validation failed: '+checked.errors.join('; '));LWFiles.downloadJSON(d,'extensions.engine.json');
     }finally{remove3d();remove2d();removePreset();}
    })()`);
    const file=await download,saved=path.join(OUT,'browser-extensions.engine.json');assert(file,'Expected actual extension engine JSON download');await file.saveAs(saved);
    const checked=spawnSync(process.execPath,[path.join(ROOT,'.generated/tools/scenario-cli.cjs'),'engine-export-validate',saved],{encoding:'utf8',timeout:120000,maxBuffer:2*1024*1024});assert.equal(checked.stderr,'');assert.equal(checked.status,0,checked.stdout);assert.equal(JSON.parse(checked.stdout).ok,true);
    const d=JSON.parse(fs.readFileSync(saved,'utf8')) as LWEngineExport.Document;assert.deepEqual(d.extensions.renderers.map(row=>row.id),['browser-export-3d','browser-export-2d']);assert.equal(d.extensions.animations[0]!.id,'browser-export-preset');assert.equal(await value<number>(page,'window.__exportExtensionCalls'),0);assert.equal(await value<string>(page,'JSON.stringify(Littlewild.engine.export())'),original);assert.equal(await value<string>(page,'JSON.stringify(Littlewild.scenarioUI.editor.session.snapshot())'),draft);
   });
   await test('Browser validates cryptographic source integrity and rejects tampered inert text',async()=>{const error=await value<string>(page,'(async()=>{const d=await LWDeveloper.engineExport.export(Littlewild.scenarioUI.editor.session.export(),Littlewild.scenarioUI.editor.state.selection.id);d.sources.files[0].text+="changed";return (await LWDeveloper.engineExport.validate(d)).errors.join("; ");})()');assert(error.includes('Source integrity failure'),error);assert.equal(await value<string>(page,'JSON.stringify(Littlewild.engine.export())'),original);});
   await test('Async programmatic export captures caller data before the await boundary',async()=>{assert(await value<boolean>(page,'(async()=>{const p=Littlewild.scenarioUI.editor.session.export(),before=JSON.stringify(p),pending=LWDeveloper.engineExport.export(p,Littlewild.scenarioUI.editor.state.selection.id);p.name="Changed after export began";const d=await pending;return JSON.stringify(d.pack)===before;})()'));});
   await test('Changed authoring revision cancels a pending export download',async()=>{let downloads=0;page.on('download',()=>downloads++);await page.evaluate('window.__savedEngineExport=LWEngineExport.export;LWEngineExport.export=(...args)=>new Promise(resolve=>window.__savedEngineExport(...args).then(result=>{window.__releaseEngineExport=()=>resolve(result);}));');await page.locator('[data-engine-export-download]').click();await page.waitForFunction('typeof window.__releaseEngineExport==="function"');await page.evaluate('const session=Littlewild.scenarioUI.editor.session,id=Littlewild.scenarioUI.editor.state.selection.id;session.updateScene(id,{name:"Revised during export"});window.__releaseEngineExport();LWEngineExport.export=window.__savedEngineExport;');await page.waitForFunction('!document.querySelector("[data-engine-export-download]").disabled');assert.equal(downloads,0);assert.equal(await value<string>(page,'JSON.stringify(Littlewild.engine.export())'),original);});
  }
  await page.close();
 }}finally{diagnostics=observations;await context.close();await browser.close();}
 await test('Engine export browser performs no external requests, script errors or console warnings',async()=>{assert.deepEqual(observations.errors,[]);assert.deepEqual(observations.consoleProblems,[]);assert.equal(observations.requests.filter(url=>url===FIXTURE).length,2);assert.deepEqual(observations.requests.filter(url=>url!==FIXTURE),[]);});
}
main().catch(error=>{results.push({name:'Browser setup',passed:false,error:String(error)});}).finally(()=>{fs.mkdirSync(OUT,{recursive:true});const report={suite:'engine-export-browser',passed:results.filter(result=>result.passed).length,total:results.length,results,diagnostics};fs.writeFileSync(path.join(OUT,'engine-export-browser-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(results.some(result=>!result.passed))process.exitCode=1;});
