/// <reference path="../external-editor-contracts.d.ts" />
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import type {Page} from 'playwright';
import {launchBrowser,monitorContext,READY_TIMEOUT_MS,waitForReady} from './browser-harness';
const ROOT=path.resolve(__dirname,'../..'),ARTIFACT=process.env.LITTLEWILD_BROWSER_ARTIFACT||path.join(ROOT,'littlewild.html'),OUT=process.env.LITTLEWILD_EXTERNAL_EDITOR_OUT||path.join(ROOT,'verification/v15');
const results:{name:string;passed:boolean;error?:string}[]=[];let diagnostics:unknown;
async function test(name:string,fn:()=>Promise<void>):Promise<void>{try{await fn();results.push({name,passed:true});console.log('PASS '+name);}catch(error){results.push({name,passed:false,error:String(error)});console.error(name,String(error));}}
async function value<T=unknown>(page:Page,text:string):Promise<T>{return page.evaluate(text) as Promise<T>;}
async function story(page:Page):Promise<string>{return value<string>(page,'JSON.stringify(Littlewild.engine.export())');}
async function main():Promise<void>{
 const browser=await launchBrowser(),context=await browser.newContext({acceptDownloads:true}),observations=monitorContext(context);
 try{for(const width of [1440,390]){
  const page=await context.newPage();page.setDefaultTimeout(15000);await page.setViewportSize({width,height:width===390?844:1000});await page.setContent(fs.readFileSync(ARTIFACT,'utf8'),{waitUntil:'load',timeout:30000});await waitForReady(page,{timeout:READY_TIMEOUT_MS});await page.locator('[data-act="begin"]').click();await page.evaluate('Littlewild.engine.s.paused=true;Littlewild.open("scenarios")');await page.locator('[data-scenario="editor"]').click();const original=await story(page);
  if(process.env.LITTLEWILD_CAPTURE_SCREENSHOTS==='1'){fs.mkdirSync(OUT,{recursive:true});await page.screenshot({path:path.join(OUT,'external-editor-collapsed-'+width+'.png'),animations:'disabled'});}
  await page.locator('[data-external-editor-panel] summary').first().click();
  for(const format of ['tiled','ldtk','gltf'])await test(format+' actual file download, detached review cancellation and explicit draft apply at '+width+'px',async()=>{
   const revision=await value<number>(page,'Littlewild.scenarioUI.editor.session.revision');await page.locator('[data-external-editor-format]').selectOption(format);const event=page.waitForEvent('download');await page.locator('[data-external-editor="export"]').click();const download=await event;const location=await download.path();assert(location);assert(download.suggestedFilename().endsWith(format==='tiled'?'.tmj':format==='ldtk'?'.ldtk':'.gltf'));const bytes=fs.readFileSync(location);const before=await value<string>(page,'JSON.stringify(Littlewild.scenarioUI.editor.session.snapshot())');
   await page.locator('#scene-editor-external-import').setInputFiles({name:download.suggestedFilename(),mimeType:'application/json',buffer:bytes});await page.locator('[data-external-editor="apply"]').waitFor();assert.equal(await page.evaluate(()=>(document.activeElement as HTMLElement).dataset.externalEditor),'cancel');if(format==='tiled'&&process.env.LITTLEWILD_CAPTURE_SCREENSHOTS==='1'){await page.locator('[data-external-editor=cancel]').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(OUT,'external-editor-review-'+width+'.png'),animations:'disabled'});}assert.equal(await value<string>(page,'JSON.stringify(Littlewild.scenarioUI.editor.session.snapshot())'),before);assert.equal(await story(page),original);await page.locator('[data-external-editor="cancel"]').click();assert.equal(await value<number>(page,'Littlewild.scenarioUI.editor.session.revision'),revision);assert.equal(await page.evaluate(()=>(document.activeElement as HTMLElement).dataset.externalEditor),'import');
   await page.locator('#scene-editor-external-import').setInputFiles({name:download.suggestedFilename(),mimeType:'application/json',buffer:bytes});await page.locator('[data-external-editor="apply"]').click();assert.equal(await value<number>(page,'Littlewild.scenarioUI.editor.session.revision'),revision+1);assert.equal(await value<string>(page,'JSON.stringify(Littlewild.scenarioUI.editor.session.snapshot())'),before);assert.equal(await story(page),original);
  });
  await test('Malformed external file and stale conversion retain complete draft and story at '+width+'px',async()=>{
   const before=await value<string>(page,'JSON.stringify(Littlewild.scenarioUI.editor.session.snapshot())'),revision=await value<number>(page,'Littlewild.scenarioUI.editor.session.revision');await page.locator('#scene-editor-external-import').setInputFiles({name:'bad.tmj',mimeType:'application/json',buffer:Buffer.from('{invalid')});await page.locator('.scene-editor-exchange .is-error').waitFor();assert.equal(await value<string>(page,'JSON.stringify(Littlewild.scenarioUI.editor.session.snapshot())'),before);assert.equal(await value<number>(page,'Littlewild.scenarioUI.editor.session.revision'),revision);assert.equal(await story(page),original);
   const external=await value(page,'(()=>{const editor=Littlewild.scenarioUI.editor;return LWExternalEditors.export(editor.session.export(),editor.state.selection.id,"tiled").document})()');await page.locator('#scene-editor-external-import').setInputFiles({name:'review.tmj',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(external))});await page.locator('[data-external-editor="apply"]').waitFor();await page.evaluate('(()=>{const editor=Littlewild.scenarioUI.editor,s=editor.session.snapshot().scenes[0];editor.session.updateScene(s.id,{name:s.name+" revised"})})()');await page.locator('[data-external-editor="apply"]').click();assert((await page.locator('.scene-editor-exchange .is-error').textContent())?.includes('changed after conversion'));assert.equal(await value<number>(page,'Littlewild.scenarioUI.editor.session.revision'),revision+1);await page.locator('[data-external-editor="cancel"]').click();assert.equal(await story(page),original);
  });
  if(width===1440)await test('Actual binary GLB file import reviews and applies native placement without changing the story',async()=>{
   const doc=await value<Record<string,unknown>>(page,'(()=>{const e=Littlewild.scenarioUI.editor;return LWExternalEditors.export(e.session.export(),e.state.selection.id,"gltf").document})()');
   const buffers=doc.buffers as Record<string,unknown>[],binary=Buffer.from(String(buffers[0]!.uri).split(',')[1]!,'base64');delete buffers[0]!.uri;const nodes=doc.nodes as Record<string,unknown>[];nodes.find(n=>(n.extras as Record<string,unknown>)?.entityId==='c1')!.translation=[9,0,10];
   const json=Buffer.from(JSON.stringify(doc)),jsonSize=Math.ceil(json.length/4)*4,binSize=Math.ceil(binary.length/4)*4,bytes=Buffer.alloc(28+jsonSize+binSize);bytes.writeUInt32LE(0x46546c67,0);bytes.writeUInt32LE(2,4);bytes.writeUInt32LE(bytes.length,8);bytes.writeUInt32LE(jsonSize,12);bytes.writeUInt32LE(0x4e4f534a,16);bytes.fill(32,20,20+jsonSize);json.copy(bytes,20);bytes.writeUInt32LE(binSize,20+jsonSize);bytes.writeUInt32LE(0x004e4942,24+jsonSize);binary.copy(bytes,28+jsonSize);
   await page.locator('#scene-editor-external-import').setInputFiles({name:'edited.glb',mimeType:'model/gltf-binary',buffer:bytes});await page.locator('[data-external-editor="apply"]').waitFor();assert.equal(await story(page),original);assert((await page.locator('.scene-editor-exchange').textContent())?.includes('binary'));await page.locator('[data-external-editor="apply"]').click();assert.equal(await value<number>(page,'Littlewild.scenarioUI.editor.session.snapshot().scenes[0].initialState.colony.creatures.find(c=>c.id==="c1").creature.x'),9);assert.equal(await story(page),original);
  });
  if(width===1440)await test('Generic Tiled mapping review adds multiple canonical companions through native draft authority',async()=>{
   await page.locator('.scene-editor-exchange details summary').click();await page.locator('[data-external-editor-mappings]').fill('[{"externalType":"Worker","category":"creatures","templateId":"c1"}]');const file={type:'map',orientation:'orthogonal',tilewidth:32,tileheight:32,layers:[{type:'objectgroup',objects:[{name:'c4',class:'Worker',type:'',x:288,y:320},{name:'c5',type:'Worker',x:256,y:320}]}]};await page.locator('#scene-editor-external-import').setInputFiles({name:'generic.tmj',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(file))});await page.locator('[data-external-editor="apply"]').click();assert(await value<boolean>(page,'Littlewild.scenarioUI.editor.session.snapshot().scenes[0].initialState.colony.creatures.some(c=>c.id==="c4")'));assert(await value<boolean>(page,'Littlewild.scenarioUI.editor.session.snapshot().scenes[0].initialState.colony.creatures.some(c=>c.id==="c5")'));assert.equal(await story(page),original);
  });
  await page.close();
 }}finally{diagnostics=observations;await context.close();await browser.close();}
 await test('External browser exchange performs no network requests or script/console errors',async()=>{assert.deepEqual(observations.errors,[]);assert.deepEqual(observations.consoleProblems,[]);assert.deepEqual(observations.requests,[]);});
}
main().catch(error=>{results.push({name:'Browser setup',passed:false,error:String(error)});}).finally(()=>{fs.mkdirSync(OUT,{recursive:true});const report={suite:'external-editors-browser',passed:results.filter(r=>r.passed).length,total:results.length,results,diagnostics};fs.writeFileSync(path.join(OUT,'external-editors-browser-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(results.some(r=>!r.passed))process.exitCode=1;});
