/// <reference path="../external-editor-canvas-contracts.d.ts" />
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import type {Page} from 'playwright';
import {ARTIFACT_FIXTURE_URL,launchBrowser} from './browser-harness';
import {artifactPath,monitorArtifacts,openColony} from './browser-pages';
const ROOT=path.resolve(__dirname,'../..'),ARTIFACT=artifactPath(ROOT,'studio'),OUT=process.env.LITTLEWILD_EXTERNAL_CANVAS_OUT||path.join(ROOT,'verification/v15');
type Data=Record<string,unknown>;
const data=(v:unknown):Data=>v as Data,rows=(v:unknown):Data[]=>v as Data[];
const results:{name:string;passed:boolean;error?:string}[]=[];
async function test(name:string,work:()=>Promise<void>):Promise<void>{try{await work();results.push({name,passed:true});console.log('PASS '+name);}catch(error){results.push({name,passed:false,error:String(error)});console.error(name,error);}}
async function value<T=unknown>(page:Page,expression:string):Promise<T>{return page.evaluate(expression) as Promise<T>;}
const sourceNode=(doc:Data,id:string):Data=>rows(doc.nodes).find(n=>n.id===id)!;
async function main():Promise<void>{
 const browser=await launchBrowser(),context=await browser.newContext({acceptDownloads:true}),diagnostics=monitorArtifacts(context);
 try{for(const width of [1440,390]){
  const page=await context.newPage();page.setDefaultTimeout(15000);await page.setViewportSize({width,height:width===390?844:1000});await openColony(page,ARTIFACT);await page.locator('[data-act="begin"]').click();await page.evaluate('Littlewild.engine.s.paused=true;Littlewild.open("scenarios")');await page.locator('[data-scenario="editor"]').click();
  await page.evaluate('(()=>{const e=Littlewild.scenarioUI.editor,p=e.session.snapshot(),first=p.scenes[0];for(const s of p.scenes)delete s.initialState.scenarioResources;first.graph={...first.graph,kind:"level",connections:[{id:"canvas-travel",targetSceneId:"canvas-remote",label:"Travel to remote world"}]};p.worlds.push({...structuredClone(p.worlds[0]),id:"canvas-world",name:"Canvas World"});p.scenes.push({...structuredClone(first),id:"canvas-remote",name:"Canvas Remote",worldId:"canvas-world",graph:{kind:"level"}});e.session.replace(p);Littlewild.open("scene-editor")})()');
  const original=await value<string>(page,'JSON.stringify(Littlewild.engine.export())');await page.locator('[data-external-editor-panel] summary').first().click();
  for(const format of ['canvas','advanced-canvas'] as const)await test(format+' real edited file review, Cancel and explicit graph apply at '+width+'px',async()=>{
   const before=await value<string>(page,'JSON.stringify(Littlewild.scenarioUI.editor.session.snapshot())'),revision=await value<number>(page,'Littlewild.scenarioUI.editor.session.revision');
   await page.locator('[data-external-editor-format]').selectOption(format);const event=page.waitForEvent('download');await page.locator('[data-external-editor="export"]').click();const download=await event,location=await download.path();assert(location);assert(download.suggestedFilename().endsWith('.canvas'));
   const doc=data(JSON.parse(fs.readFileSync(location,'utf8'))),world=sourceNode(doc,'world:canvas-world'),scene=sourceNode(doc,'scene:canvas-remote');world.label='Edited Canvas World '+format;scene.label='Edited Canvas Remote '+format;
   if(format==='advanced-canvas'){scene.styleAttributes={shape:'diamond',border:'dotted'};rows(doc.edges)[0]!.styleAttributes={path:'long-dashed',arrow:'diamond'};}
   const fixture={name:'edited-'+format+'.canvas',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(doc))};
   await page.locator('#scene-editor-external-import').setInputFiles(fixture);await page.locator('[data-external-editor="apply"]').waitFor();assert.equal(await page.evaluate(()=>(document.activeElement as HTMLElement).dataset.externalEditor),'cancel');assert((await page.locator('[aria-label="External conversion review"]').textContent())?.includes('graph layout pixels'));assert.equal(await value<string>(page,'JSON.stringify(Littlewild.scenarioUI.editor.session.snapshot())'),before);assert.equal(await value<string>(page,'JSON.stringify(Littlewild.engine.export())'),original);
   if(width===1440&&process.env.LITTLEWILD_CAPTURE_SCREENSHOTS==='1'){fs.mkdirSync(OUT,{recursive:true});await page.locator('[data-external-editor="cancel"]').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(OUT,'external-'+format+'-review.png'),animations:'disabled'});}
   await page.locator('[data-external-editor="cancel"]').click();assert.equal(await value<number>(page,'Littlewild.scenarioUI.editor.session.revision'),revision);assert.equal(await value<string>(page,'JSON.stringify(Littlewild.scenarioUI.editor.session.snapshot())'),before);assert.equal(await page.evaluate(()=>(document.activeElement as HTMLElement).dataset.externalEditor),'import');
   await page.locator('#scene-editor-external-import').setInputFiles(fixture);await page.locator('[data-external-editor="apply"]').click();assert.equal(await value<number>(page,'Littlewild.scenarioUI.editor.session.revision'),revision+1);
   const updated=await value<LWContentPorts.ScenarioPack>(page,'Littlewild.scenarioUI.editor.session.snapshot()');assert.equal(updated.scenes.find(s=>s.id==='canvas-remote')!.name,scene.label);assert.equal(updated.worlds.find(w=>w.id==='canvas-world')!.name,world.label);assert(updated.scenes.some(s=>s.graph?.connections?.some(c=>c.targetSceneId==='canvas-remote')));assert.equal(await value<string>(page,'JSON.stringify(Littlewild.engine.export())'),original);
   if(format==='advanced-canvas')assert.deepEqual(updated.canvasAuthoring!.nodes['scene:canvas-remote']!.styleAttributes,{shape:'diamond',border:'dotted'});
   await page.locator('[data-external-editor-format]').selectOption(format);const roundtripEvent=page.waitForEvent('download');await page.locator('[data-external-editor="export"]').click();const nextLocation=await (await roundtripEvent).path();assert(nextLocation);const reexport=data(JSON.parse(fs.readFileSync(nextLocation,'utf8')));assert.equal(sourceNode(reexport,'scene:canvas-remote').label,scene.label);if(format==='advanced-canvas')assert.deepEqual(sourceNode(reexport,'scene:canvas-remote').styleAttributes,scene.styleAttributes);
  });
  await test('Malformed Canvas graph references and code/URL config retain draft revision and active story at '+width+'px',async()=>{
   const before=await value<string>(page,'JSON.stringify(Littlewild.scenarioUI.editor.session.snapshot())'),revision=await value<number>(page,'Littlewild.scenarioUI.editor.session.revision');
   const fixture=await value<Data>(page,'(()=>{const e=Littlewild.scenarioUI.editor;return LWExternalEditors.export(e.session.export(),e.state.selection.id,"canvas").document})()');rows(fixture.edges)[0]!.toNode='missing';
   await page.locator('#scene-editor-external-import').setInputFiles({name:'broken.canvas',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture))});await page.locator('.scene-editor-exchange .is-error').waitFor();assert((await page.locator('.scene-editor-exchange .is-error').textContent())?.includes('Dangling'));assert.equal(await value<string>(page,'JSON.stringify(Littlewild.scenarioUI.editor.session.snapshot())'),before);assert.equal(await value<number>(page,'Littlewild.scenarioUI.editor.session.revision'),revision);assert.equal(await value<string>(page,'JSON.stringify(Littlewild.engine.export())'),original);
   const unsafe=await value<Data>(page,'(()=>{const e=Littlewild.scenarioUI.editor;return LWExternalEditors.export(e.session.export(),e.state.selection.id,"canvas").document})()');rows(unsafe.nodes).push({id:'remote-script',type:'link',url:'https://example.invalid/script.js',x:0,y:0,width:100,height:100});await page.locator('#scene-editor-external-import').setInputFiles({name:'unsafe.canvas',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(unsafe))});await page.waitForFunction(()=>document.querySelector('.scene-editor-exchange .is-error')?.textContent?.includes('no external content'));assert.equal(await value<number>(page,'Littlewild.scenarioUI.editor.session.revision'),revision);assert.equal(await value<string>(page,'JSON.stringify(Littlewild.engine.export())'),original);
  });
  await page.close();
 }}finally{await context.close();await browser.close();}
 await test('Canvas browser exchange has no page errors, console warnings or external network requests',async()=>{assert.deepEqual(diagnostics.errors,[]);assert.deepEqual(diagnostics.consoleProblems,[]);assert.deepEqual(diagnostics.requests,[]);assert.deepEqual(diagnostics.fixtureRequests,[ARTIFACT_FIXTURE_URL,ARTIFACT_FIXTURE_URL]);});
 fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(path.join(OUT,'external-canvas-browser-results.json'),JSON.stringify({suite:'external-canvas-browser',passed:results.filter(r=>r.passed).length,total:results.length,results,diagnostics},null,2)+'\n');
}
main().catch(error=>{results.push({name:'Canvas browser setup',passed:false,error:String(error)});console.error(error);}).finally(()=>{console.log(`External Canvas browser: ${results.filter(r=>r.passed).length}/${results.length} passed.`);if(results.some(r=>!r.passed))process.exitCode=1;});
