/// <reference path="../renderer-contracts.d.ts" />
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {toolbox} from '../developer-sdk.cjs';
import {launchBrowser,monitorContext,READY_TIMEOUT_MS,waitForReady} from './browser-harness';
interface Result {name:string;passed:boolean;error?:string;}
const SHOTS=process.env.LITTLEWILD_SCREENSHOT_DIR||'/tmp/littlewild-renderers';
const ROOT=path.resolve(__dirname,'../..'),OUT=path.join(ROOT,'verification','v15'),results:Result[]=[];
fs.mkdirSync(OUT,{recursive:true});
async function check(name:string,work:()=>unknown|Promise<unknown>):Promise<void>{try{await work();results.push({name,passed:true});}catch(error){results.push({name,passed:false,error:String(error)});console.error(name,error);}}
async function main():Promise<void>{
 const browser=await launchBrowser(),context=await browser.newContext({viewport:{width:1440,height:900}}),diagnostics=monitorContext(context);
 try {
  const p=await context.newPage();p.setDefaultTimeout(5000);
  await p.setContent(fs.readFileSync(process.env.LITTLEWILD_BROWSER_ARTIFACT??path.join(ROOT,'.generated/artifacts/showcase.html'),'utf8'),{waitUntil:'load',timeout:30000});
  await waitForReady(p,{timeout:READY_TIMEOUT_MS});await p.locator('[data-act=begin]').click();
  await p.evaluate("Littlewild.engine.s.paused=true;LWRendererExample.register()");
  await p.keyboard.press('Escape');
  await check('Default adapter retains the shipped graphics renderer',async()=>{assert.equal(await p.evaluate('Littlewild.world.rendererId'),'basic');assert.match(await p.evaluate('Littlewild.world.mode') as string,/WebGL|Software/);});
  await check('Real custom map installs without mutating simulation or save state',async()=>{
   const value=await p.evaluate(`(()=>{const before=JSON.stringify(Littlewild.engine.export());const switched=Littlewild.world.selectRenderer('field-map');Littlewild.world.draw(0,.02);return{switched,id:Littlewild.world.rendererId,unchanged:before===JSON.stringify(Littlewild.engine.export()),canvases:document.querySelectorAll('canvas#world').length,hidden:document.getElementById('world-basic').hidden};})()`);
   assert.deepEqual(value,{switched:{ok:true},id:'field-map',unchanged:true,canvases:1,hidden:true});
   assert(await p.locator('#world').isVisible());
  });
  await check('Custom map hit-testing opens the existing creature UI and camera controls',async()=>{
   await p.evaluate(`(()=>{const actor=Littlewild.engine.creatures[0],w=Littlewild.world;w.focus(actor.creature.x,actor.creature.y);w.draw(0,.02);})()`);
   const position=await p.evaluate('Littlewild.world.toScreen(Littlewild.engine.creatures[0].creature.x,Littlewild.engine.creatures[0].creature.y)') as {x:number;y:number};
   await p.locator('#world').click({position});assert(await p.locator('#creature-context').isVisible());
   await p.locator('[data-act=w7-close]').first().click();const before=await p.evaluate('JSON.stringify(Littlewild.engine.export())');
   await p.locator('#world').focus();await p.keyboard.press('ArrowRight');assert.equal(await p.evaluate('JSON.stringify(Littlewild.engine.export())'),before);
  });
  await check('Lifecycle failures roll back and dispose all candidate resources',async()=>{
   const value=await p.evaluate(`(()=>{const counts={cleanup:0,dispose:0},before=JSON.stringify(Littlewild.engine.export());LWRenderers.register({id:'failure',name:'Failure',description:'Test lifecycle rollback.',capabilities:[]},context=>{context.onDispose(()=>counts.cleanup++);return{mount(){throw Error('Expected mount failure');},draw(){},resize(){},dispose(){counts.dispose++;}};});const failure=Littlewild.world.selectRenderer('failure');return{failed:!failure.ok,id:Littlewild.world.rendererId,...counts,unchanged:before===JSON.stringify(Littlewild.engine.export()),canvases:document.querySelectorAll('.world-canvas').length};})()`);
   assert.deepEqual(value,{failed:true,id:'field-map',cleanup:1,dispose:1,unchanged:true,canvases:2});
  });
  await check('Custom frames expose detached geometry and reject draw-time command mutation',async()=>{
   const value=await p.evaluate(`(()=>{const status={noAuthority:false,frozen:false,blocked:false,blockedCode:null,assets:false,disposed:0,cleanup:0,events:0,commands:[]};window.rendererStatus=status;window.rendererContext=null;LWRenderers.register({id:'probe',name:'Probe',description:'Observe renderer capabilities.',capabilities:[]},context=>{window.rendererContext=context;context.onDispose(()=>status.cleanup++);context.canvas.addEventListener('renderer-intent',()=>{status.events++;status.commands.push(context.commands.submit({id:'select-creature',args:['c1']}).ok);},{signal:context.signal});return{mount(){},resize(){},draw(frame){status.noAuthority=!('engine'in context)&&!('step'in context)&&!('storage'in context)&&!('engine'in frame);status.frozen=Object.isFrozen(frame)&&Object.isFrozen(frame.actors[0])&&Object.isFrozen(frame.construction)&&Object.isFrozen(frame.interiors)&&Object.isFrozen(frame.terrain);const actor=frame.actors[0],definition=context.query.creatureDefinition(actor.archetype),asset=context.query.asset('actor',actor.visualAsset);status.assets=!!asset&&definition.visualAsset===actor.visualAsset&&Object.isFrozen(asset)&&Object.isFrozen(definition);const blocked=context.commands.submit({id:'set-stock-target',actorId:'c1',args:['berries',24]});status.blocked=!blocked.ok;status.blockedCode=blocked.code;},dispose(){status.disposed++;}};});const before=JSON.stringify(Littlewild.engine.export()),switched=Littlewild.world.selectRenderer('probe');Littlewild.world.draw(0,.02);return{switched,...status,unchanged:before===JSON.stringify(Littlewild.engine.export())};})()`);
   assert.deepEqual(value,{switched:{ok:true},noAuthority:true,frozen:true,blocked:true,blockedCode:'busy',assets:true,disposed:0,cleanup:0,events:0,commands:[],unchanged:true});
  });
  await check('User intents share command validation and disposed renderer callbacks lose authority',async()=>{
   const session=toolbox.create({scenarioId:'littlewild'});let sdkFailure:LittlewildDeveloper.CommandResult;try{sdkFailure=session.command({id:'configure-building',args:['missing','enabled',false]});}finally{session.dispose();}
   const value=await p.evaluate(`(()=>{const context=window.rendererContext,canvas=context.canvas,before=JSON.stringify(Littlewild.engine.export());const invalid=context.commands.submit({id:'set-stock-target',actorId:'c1',args:['berries',Infinity]});const rejected=context.commands.submit({id:'configure-building',args:['missing','enabled',false]});const unchanged=before===JSON.stringify(Littlewild.engine.export());canvas.dispatchEvent(new Event('renderer-intent'));const status={...window.rendererStatus};Littlewild.world.selectRenderer('basic');canvas.dispatchEvent(new Event('renderer-intent'));const expired=context.commands.submit({id:'select-creature',args:['c2']});return{invalid:!invalid.ok,invalidCode:invalid.code,rejected:{ok:rejected.ok,code:rejected.code,reason:rejected.reason},unchanged,accepted:status.commands[0],expired:!expired.ok,expiredCode:expired.code,events:window.rendererStatus.events,disposed:window.rendererStatus.disposed,cleanup:window.rendererStatus.cleanup,canvases:document.querySelectorAll('.world-canvas').length};})()`);
   assert.deepEqual(value,{invalid:true,invalidCode:'invalid-command',rejected:{ok:sdkFailure.ok,code:sdkFailure.code,reason:sdkFailure.reason},unchanged:true,accepted:true,expired:true,expiredCode:'unavailable-command',events:1,disposed:1,cleanup:1,canvases:1});
  });
  await check('Active draw failures restore basic while preserving state',async()=>{
   const value=await p.evaluate(`(()=>{let calls=0,disposed=0;LWRenderers.register({id:'draw-failure',name:'Draw failure',description:'Runtime rollback.',capabilities:[]},()=>({mount(){},resize(){},draw(){if(++calls>1)throw Error('Expected draw failure');},dispose(){disposed++;}}));const before=JSON.stringify(Littlewild.engine.export());Littlewild.world.selectRenderer('draw-failure');Littlewild.world.draw(0,.02);return{id:Littlewild.world.rendererId,disposed,unchanged:before===JSON.stringify(Littlewild.engine.export())};})()`);
   assert.deepEqual(value,{id:'basic',disposed:1,unchanged:true});
  });
  await check('Custom renderer follows replacement engines without retaining old geometry',async()=>{
   await p.evaluate(`(()=>{Littlewild.world.selectRenderer('field-map');window.rendererOldEngine=Littlewild.engine;const restored=LWStory.commit(LWStory.inspect(Littlewild.snapshot()));Littlewild.setEngine(restored);rendererOldEngine.creatures[0].name='Retired renderer source';})()`);
   await p.waitForFunction(()=>(window as unknown as {Littlewild:{world:LittlewildRenderer.Host}}).Littlewild.world.rendererId==='basic');
   const value=await p.evaluate(`(()=>{const restored=Littlewild.engine,before=JSON.stringify(restored.export()),declared=Littlewild.world.rendererId,selected=Littlewild.world.selectRenderer('field-map');Littlewild.world.draw(0,.02);const frame=Littlewild.world.snapshot(),actors=restored.creatures.map(actor=>[actor.id,actor.name,actor.creature.x,actor.creature.y]),nodes=restored.s.nodes.map(node=>[node.id,node.x,node.y]);return{declared,selected,id:Littlewild.world.rendererId,replaced:rendererOldEngine!==restored,fresh:frame.actors[0].name!==rendererOldEngine.creatures[0].name&&JSON.stringify(frame.actors.map(actor=>[actor.id,actor.name,actor.x,actor.y]))===JSON.stringify(actors)&&JSON.stringify(frame.nodes.map(node=>[node.id,node.x,node.y]))===JSON.stringify(nodes),frozen:Object.isFrozen(frame)&&Object.isFrozen(frame.actors[0]),unchanged:before===JSON.stringify(restored.export())};})()`);
   assert.deepEqual(value,{declared:'basic',selected:{ok:true},id:'field-map',replaced:true,fresh:true,frozen:true,unchanged:true});
  });
  await check('Custom renderer draws the visited upper floor and real worker progress without changing active work or save',async()=>{
   await p.evaluate("Littlewild.open('scenarios')");await p.locator('[data-scenario=select]').filter({hasText:'Littlewild'}).click();await p.locator('[data-scenario=review][data-id=charted-home]').click();await p.locator('[data-scenario=launch]').click();await p.waitForFunction(()=>(window as unknown as {Littlewild:{world:LittlewildRenderer.Host}}).Littlewild.world.rendererId==='basic');await p.evaluate("Littlewild.engine.s.paused=true;Littlewild.land.show('building','b2')");await p.locator('[data-act=land-visit]').click();await p.locator('[data-interior=floor][data-floor=upper]').click();
   await p.locator('#interior-production [name=recipe]').selectOption('planks');await p.locator('#interior-production [name=batches]').fill('2');await p.locator('#interior-production button[type=submit]').click();
   const result=await p.evaluate(`(()=>{Littlewild.engine.s.paused=false;for(let i=0;i<1200;i++){Littlewild.engine.step(.1);if(Littlewild.engine.buildingInterior('b2').actors.some(actor=>actor.floorId==='upper'&&actor.progress>0))break;}Littlewild.engine.s.paused=true;Littlewild.refresh();const engine=Littlewild.engine,before=JSON.stringify(engine.export()),work=engine.buildingInterior('b2').actors.filter(actor=>actor.floorId==='upper'&&actor.progress>0),declared=Littlewild.world.rendererId,selected=Littlewild.world.selectRenderer('field-map');Littlewild.refresh();Littlewild.world.draw(0,.02);return{declared,selected,id:Littlewild.world.rendererId,sameEngine:engine===Littlewild.engine,workers:work.length,floor:Littlewild.world.canvas.dataset.interiorFloor,actors:Number(Littlewild.world.canvas.dataset.interiorActors),unchanged:before===JSON.stringify(engine.export()),custom:document.getElementById('building-interior').classList.contains('custom-interior-renderer')};})()` ) as {declared:string;selected:LittlewildRenderer.SwitchResult;id:string;sameEngine:boolean;workers:number;floor:string;actors:number;unchanged:boolean;custom:boolean};
   assert.equal(result.declared,'basic');assert.deepEqual(result.selected,{ok:true});assert.equal(result.id,'field-map');assert(result.sameEngine);assert(result.workers>0);assert.equal(result.floor,'upper');assert.equal(await p.evaluate('Littlewild.world.canvas.dataset.scene'),'interior');assert(result.actors>0);assert(result.unchanged);assert(result.custom);assert.equal(await p.locator('.building-interior-stage canvas').isVisible(),false);
   if(process.env.LITTLEWILD_CAPTURE_SCREENSHOTS==='1'){fs.mkdirSync(SHOTS,{recursive:true});await p.screenshot({path:path.join(SHOTS,'field-map-upper-work-1440.png'),animations:'disabled'});}
   await p.keyboard.press('Escape');
  });
  for(const width of [1440,390]){await p.setViewportSize({width,height:width===390?844:900});await p.waitForTimeout(150);await check('Custom renderer resizes with the browser at '+width+'px',async()=>{assert(await p.locator('#world').isVisible());assert.equal(await p.evaluate('Littlewild.world.rendererId'),'field-map');assert.equal(await p.evaluate('document.documentElement.scrollWidth<=innerWidth'),true);});if(process.env.LITTLEWILD_CAPTURE_SCREENSHOTS==='1'){fs.mkdirSync(SHOTS,{recursive:true});await p.screenshot({path:path.join(SHOTS,'field-map-'+width+'.png'),animations:'disabled'});}}
  await check('Repeated switches leave one input owner and no duplicate canvases',async()=>{
   const value=await p.evaluate(`(()=>{for(let i=0;i<4;i++){Littlewild.world.selectRenderer('basic');Littlewild.world.selectRenderer('field-map');}Littlewild.world.selectRenderer('basic');return{canvases:document.querySelectorAll('.world-canvas').length,labels:document.querySelectorAll('.v10-labels').length,suspended:!!Littlewild.world.suspended};})()`);assert.deepEqual(value,{canvases:1,labels:1,suspended:false});
  });
  await check('Custom Office frames keep a real onsite customer-call quest actor visible and selectable',async()=>{
   await p.setViewportSize({width:1440,height:900});await p.evaluate("Littlewild.open('scenarios')");await p.locator('[data-scenario=select]').filter({hasText:'Office'}).click();await p.locator('[data-scenario=review][data-id=operations-shift]').click();await p.evaluate("document.querySelector('[data-scenario=launch]').click();Littlewild.engine.s.paused=true;Littlewild.refresh()");
   const value=await p.evaluate(`(()=>{const e=Littlewild.engine;e.s.paused=false;for(let i=0;i<100;i++){e.step(.1);const actor=e.creatures.find(actor=>actor.name==='Phil');if(actor.activeQuest&&LWSceneEnvironment.onsite(e.s,actor))break;}e.s.paused=true;Littlewild.refresh();const actor=e.creatures.find(actor=>actor.name==='Phil'),before=JSON.stringify(e.export());let captured=null;LWRenderers.register({id:'office-observer',name:'Office observer',description:'Observe authored onsite work.',capabilities:[]},()=>({mount(){},resize(){},dispose(){},draw(frame){captured=frame;}}));const switched=Littlewild.world.selectRenderer('office-observer');Littlewild.world.draw(0,.02);const observed=captured.actors.find(view=>view.id===actor.id);Littlewild.world.selectRenderer('field-map');Littlewild.world.draw(0,.02);const point=Littlewild.world.toScreen(actor.creature.x,actor.creature.y),hit=Littlewild.world.hitTest(point.x,point.y);return{switched,quest:actor.activeQuest?.name||'',onsite:LWSceneEnvironment.onsite(e.s,actor),away:observed.away,hitActor:hit.actorId,actorId:actor.id,unchanged:before===JSON.stringify(e.export()),frozen:Object.isFrozen(observed)};})()` ) as {switched:{ok:boolean};quest:string;onsite:boolean;away:boolean;hitActor:string;actorId:string;unchanged:boolean;frozen:boolean};
   assert(value.switched.ok);assert.match(value.quest,/Customer discovery call/);assert(value.onsite);assert.equal(value.away,false);assert.equal(value.hitActor,value.actorId);assert(value.unchanged);assert(value.frozen);
   if(process.env.LITTLEWILD_CAPTURE_SCREENSHOTS==='1'){fs.mkdirSync(SHOTS,{recursive:true});await p.screenshot({path:path.join(SHOTS,'field-map-office-onsite-1440.png'),animations:'disabled'});}
  });
  await check('Renderer extension flows remain offline and produce no browser errors',()=>{assert.deepEqual(diagnostics.errors,[]);assert.deepEqual(diagnostics.consoleProblems,[]);assert.deepEqual(diagnostics.requests,[]);});
 }finally{await browser.close();}
 const report={passed:results.filter(result=>result.passed).length,total:results.length,results,...diagnostics};fs.writeFileSync(path.join(OUT,'renderers-browser-results.json'),JSON.stringify(report,null,2)+'\n');console.log(report.passed+'/'+report.total+' browser renderer checks passed');if(report.passed!==report.total)process.exitCode=1;
}
main().catch(error=>{console.error(error);process.exitCode=1;});
