/// <reference path="./content-contracts.d.ts" />
/** Captured numeric gameplay profiles; domain code never reads a mutable tuning registry. */
declare namespace LWBalanceRules {
 interface Task {
  breakthroughAnger:number;
  setbackAnger:number;
  criticalSetbackAnger:number;
  defaultDifficulty:number;
  socialFailureAnger:number;
  socialFailureJoy:number;
  breakthroughJoy:number;
  setbackJoy:number;
  setbackActorXp:number;
  practiceDifficulty:number;
  buildDifficulty:number;
  trainDifficulty:number;
  gatherDifficulty:number;
  socialSuccessAnger:number;
  socialSuccessJoy:number;
  quietJoy:number;
  quietAnger:number;
  affinityGate:number;
  affinitySuccess:number;
  affinityFailure:number;
  trustSuccess:number;
  trustFailure:number;
  sourceSocial:number;
  targetSocial:number;
  targetJoy:number;
  buildRetryFraction:number;
  trainingRetryFraction:number;
  restAnger:number;
  gearActorXp:number;
  gearPlayerXp:number;
 }
 interface Quest {
  recallJoy:number;
  recallAnger:number;

  travelCap:number;
  loadTimeFactor:number;
  requiredFraction:number;
  energyReserve:number;
  foodRate:number;
  waterRate:number;
  abortedActorXp:number;
  partialActorXp:number;
  playerXp:number;
  actorXp:number;
  guaranteedAfterMisses:number;
 }
 interface Autonomy {
  socialFood:number;
  socialWater:number;
  socialEnergy:number;
  socialCooldown:number;
  socialDuration:number;
  urgentEnergy:number;
  urgentNeed:number;
  coolAnger:number;
  coolDuration:number;
  comfortEnergy:number;
  comfortComfort:number;
  comfortNeed:number;
  cozyBonus:number;
 }
 interface Production {
  gathererBonus:number;
  cropInitialStock:number;
  cropGatherAmount:number;
  transferSeconds:number;

  collectFraction:number;
  retryFraction:number;
  merchantBonus:number;
  marketPerLevel:number;
  cropLevelRate:number;
  greenhouseBonus:number;
  cropSeconds:number;
  cropStockCap:number;
  orchardYield:number;
  cropYield:number;
 }
 interface Policy {
  urgentNeed:number;
  angerAttention:number;
  sellFraction:number;
 }
 interface Completion {
  shopActorXp:number;
  saleActorXp:number;
  salePlayerXp:number;
  cropPlayerXp:number;
  cropActorXp:number;
  practicePlayerXp:number;
  practiceActorXp:number;
  buildResearch:number;
  gatherActorXp:number;
  gatherPlayerXp:number;
  gatherResearchEvery:number;
  craftActorXp:number;
  craftPlayerXp:number;
  buildActorXp:number;
  buildPlayerXp:number;
  buildBond:number;
  buildJoy:number;
  trainActorXp:number;
  trainPlayerXp:number;
  trainBond:number;
  trainJoy:number;
  mealFood:number;
  meatFood:number;
  berryFood:number;
  drinkWater:number;
  cottageEnergy:number;
  shelterEnergy:number;
  outsideEnergy:number;
  shelterComfort:number;
  outsideComfort:number;
  warmComfort:number;
  warmJoy:number;
  playJoy:number;
  playEnergy:number;
  exploreGuideCoins:number;
  explorePocketCoins:number;
  exploreResearch:number;
  exploreActorXp:number;
  explorePlayerXp:number;
  exploreCooldown:number;
  huntEnergy:number;
  huntActorXp:number;
  researchCooldown:number;
  deliverActorXp:number;
  deliverPlayerXp:number;
 }
 interface Work {
  togetherFatigue:number;
  thinkerResearch:number;
  repeatedPracticePoints:number;
  practiceFreshCount:number;
  playfulFatigue:number;
  observatoryResearch:number;
  mentorPracticePoints:number;
  independentFatigue:number;
  idleFatigue:number;
  freshPracticePoints:number;
  firstPracticeResearch:number;
  fatigueResumeGate:number;
  fatigueRecoverGate:number;
  explorerResearch:number;
  stationPerLevel:number;
  qualityDivisor:number;
  storehouseBonus:number;
  waterwheelBonus:number;
  stationCap:number;
  circleBonus:number;
  circlePerLevel:number;
  observatoryLearningBonus:number;
  mentorLearningBonus:number;
  comfortableGate:number;
  comfortLearningBonus:number;
  makerBonus:number;
  efficientBonus:number;
  workshopRadius:number;
  workshopBonus:number;
  practiceCircleBonus:number;
  explorerBonus:number;
  stewardBonus:number;
  maximumRate:number;
  baseRateCap:number;
  globalPerLevel:number;
  supportRadius:number;
  qualityBaseline:number;
 }
 interface Construction {
  wellMadeQuality:number;
  dependableQuality:number;
  beautifulQuality:number;
  woodCellDivisor:number;
  stoneCellDivisor:number;
  wallWood:number;
  windowGlass:number;
  doorPlanks:number;
  stairPlanks:number;
  stationFiberDivisor:number;
  improvementWood:number;
  cellSeconds:number;
  edgeSeconds:number;

  upgradeLevelTwoFraction:number;
  upgradeLevelThreeFraction:number;
  upgradeTimeFraction:number;
  foundationFraction:number;
  structureFraction:number;
  finishFraction:number;
  refundCompletedFraction:number;
  qualityBase:number;
  qualityPerRank:number;
  comfortableQuality:number;
  builderQuality:number;
  finisherQuality:number;
  minimumQuality:number;
 }
 interface Recovery {
  reflectFatigue:number;
  reflectJoy:number;
  breadFood:number;
  breadJoy:number;
  balmComfort:number;
  balmJoy:number;
  homePerLevel:number;
  comfortSpecialist:number;
 }
 interface Modifiers {
  tiredEnergy:number;
  lowEnergy:number;
  needGate:number;
  tiredPenalty:number;
  lowPenalty:number;
  needPenalty:number;
  angerGate:number;
  frustratedGate:number;
  angerPenalty:number;
  frustratedPenalty:number;
 }
 interface Care {
  soothingCooldown:number;
  spaceCooling:number;
  spaceJoy:number;
  spaceAnger:number;
  sootheJoy:number;
  sootheAnger:number;
  sootheBond:number;
  careJoy:number;
  careAnger:number;
  fullGate:number;
  waterFullGate:number;
  bondFoodGate:number;
  bondWaterGate:number;
  bondEnergyGate:number;
  praiseAge:number;
  feedMeal:number;
  feedBerry:number;
  feedJoy:number;
  feedBond:number;
  feedCooldown:number;
  waterAmount:number;
  waterBond:number;
  waterCooldown:number;
  bondJoy:number;
  freshBondCount:number;
  bondCooldown:number;
  praiseJoy:number;
  praiseBond:number;
  praiseCooldown:number;
 }
 interface Legacy {
  foodWork:number;
  foodIdle:number;
  waterWork:number;
  waterIdle:number;
  energyWork:number;
  energyIdle:number;
  cottageComfortRate:number;
  shelterComfortRate:number;
  outsideComfortRate:number;
  joyRate:number;
  urgentEnergy:number;
  urgentNeed:number;
  speed:number;
  bondGate:number;
  bondSpeedBonus:number;
 }
 interface Mood {
  needGate:number;
  joyLow:number;
  comfortLow:number;
  lovedBond:number;
  lovedJoy:number;
  contentFood:number;
  contentWater:number;
  contentEnergy:number;
  friendOne:number;
  friendTwo:number;
  friendThree:number;
  friendFour:number;
  socialLow:number;
  delightedJoy:number;
  delightedBond:number;
  contentJoy:number;
  sadJoy:number;
 }
 interface Clock {
  hourRate:number;
 }
 interface Rules {
  legacy:Readonly<Legacy>;
  mood:Readonly<Mood>;
  clock:Readonly<Clock>;

  task:Readonly<Task>;
  quest:Readonly<Quest>;
  autonomy:Readonly<Autonomy>;
  production:Readonly<Production>;
  policy:Readonly<Policy>;
  completion:Readonly<Completion>;
  work:Readonly<Work>;
  construction:Readonly<Construction>;
  recovery:Readonly<Recovery>;
  modifiers:Readonly<Modifiers>;
  care:Readonly<Care>;
 }
 interface Owner {simulationProfile?:{rules?:{gameplay?:Rules|undefined}|undefined}|null|undefined;}
 interface Api {readonly defaults:Rules;supported():readonly {path:string;minimum:number;maximum:number;integer:boolean}[];validate(input:unknown):Rules;forEngine(engine:Owner):Rules;}
}
