/// <reference path="./building-interior-contracts.d.ts" />
/* Player visits are presentation state. Creature visits and orders emit compiled domain commands. */
(function(inputRoot:unknown){
 'use strict';
 interface World {camera:{x:number;y:number;z:number};manual:boolean;canvas:HTMLCanvasElement;invalidate():void;setInteriorView?(id:string|null,floorId?:string,surface?:{x:number;y:number;width:number;height:number}):void;rendererId?:string;capabilities?:string[];}
 interface Host {engine():LWInterior.Engine;world():World;esc(value:unknown):string;save():void;refresh():void;closeContexts():void;}
 const root=inputRoot as {LWBuildingInteriorProjector:{snapshot(e:LWInterior.Engine,id:string):LWInterior.Snapshot|null};LWBuildingInteriorRenderer:{create(canvas:HTMLCanvasElement):LWInterior.Renderer};LWBuildingInteriorUI?:unknown;LWConstructionEditor?:{open(id:string):boolean}};
 function create(h:Host){
  const panel=document.createElement('section');panel.className='building-interior';panel.id='building-interior';panel.hidden=true;panel.setAttribute('aria-label','Building interior');
  panel.innerHTML='<header class="building-interior-header"><div class="building-interior-title"><small>INSIDE THE BUILDING</small><h1 id="building-interior-title" tabindex="-1"></h1></div><button type="button" data-interior="back">← Back to world map</button><button type="button" data-interior="redesign">Improve building layout</button><nav class="building-interior-floors" aria-label="Building floors"></nav></header><main class="building-interior-main"><div class="building-interior-stage"><canvas aria-label="Live building interior"></canvas></div><aside class="building-interior-details" aria-label="Building activity"></aside></main><footer class="building-interior-footer"><span class="building-interior-status" role="status"></span><button type="button" data-interior="back">Leave building <kbd>Esc</kbd></button></footer>';
  document.getElementById('app')!.append(panel);
  const canvas=panel.querySelector('canvas')!,renderer=root.LWBuildingInteriorRenderer.create(canvas),title=panel.querySelector<HTMLHeadingElement>('h1')!,floors=panel.querySelector<HTMLElement>('nav')!,details=panel.querySelector<HTMLElement>('aside')!,status=panel.querySelector<HTMLElement>('[role=status]')!;
  const state={buildingId:'',floorId:'',recipe:'',station:'',actor:'',batches:'1',feedback:'',signature:'',mapCanvas:null as HTMLCanvasElement|null,origin:null as HTMLElement|null,source:null as LWInterior.Engine|null,camera:null as {x:number;y:number;z:number;manual:boolean}|null};
  const e=h.esc;
  function close(restore=true):void{
   if(!state.buildingId)return;const origin=state.origin,world=h.world();if(state.camera){Object.assign(world.camera,{x:state.camera.x,y:state.camera.y,z:state.camera.z});world.manual=state.camera.manual;world.invalidate();}
   world.setInteriorView?.(null);state.buildingId='';state.source=null;state.camera=null;panel.hidden=true;document.body.classList.remove('building-interior-open');if(state.mapCanvas){state.mapCanvas.inert=false;state.mapCanvas.removeAttribute('aria-hidden');state.mapCanvas=null;}world.canvas.inert=false;world.canvas.removeAttribute('aria-hidden');if(restore)(origin?.isConnected&&!origin.closest('[hidden]')?origin:world.canvas).focus({preventScroll:true});
  }
  function open(id:string,origin:HTMLElement|null=null):boolean{
   const snapshot=root.LWBuildingInteriorProjector.snapshot(h.engine(),id);if(!snapshot)return false;close(false);const world=h.world();state.camera={...world.camera,manual:world.manual};h.closeContexts();state.buildingId=id;state.floorId=snapshot.floors[0]!.id;state.recipe=snapshot.recipes[0]?.id||'';state.actor=h.engine().creatures.find(a=>!a.activeQuest)?.id||'';state.batches='1';state.station=snapshot.floors[0]!.stations.find(s=>s.production)?.id||'';state.origin=origin;state.source=h.engine();world.setInteriorView?.(id,state.floorId);state.feedback='';state.signature='';panel.hidden=false;document.body.classList.add('building-interior-open');state.mapCanvas=world.canvas;world.canvas.inert=true;world.canvas.setAttribute('aria-hidden','true');update();details.scrollTop=0;renderer.resize();paint();title.focus({preventScroll:true});h.refresh();return true;
  }
  function update():void{
   if(!state.buildingId)return;if(state.source!==h.engine()){close(false);return;}const snapshot=root.LWBuildingInteriorProjector.snapshot(h.engine(),state.buildingId);if(!snapshot){close();return;}
   const custom=h.world().rendererId!=='basic'&&!!h.world().capabilities?.includes('interiors');panel.classList.toggle('custom-interior-renderer',custom);h.world().canvas.inert=true;
   const roomBounds=panel.querySelector<HTMLElement>('.building-interior-stage')!.getBoundingClientRect(),mapBounds=h.world().canvas.getBoundingClientRect(),scaleX=h.world().canvas.width/mapBounds.width,scaleY=h.world().canvas.height/mapBounds.height;if(mapBounds.width&&mapBounds.height)h.world().setInteriorView?.(state.buildingId,state.floorId,{x:(roomBounds.x-mapBounds.x)*scaleX,y:(roomBounds.y-mapBounds.y)*scaleY,width:roomBounds.width*scaleX,height:roomBounds.height*scaleY});
   title.textContent=snapshot.buildingName;const floor=snapshot.floors.find(f=>f.id===state.floorId)||snapshot.floors[0]!;state.floorId=floor.id;
   const focusedFloor=(document.activeElement as HTMLElement)?.dataset.floor;const floorMarkup=snapshot.floors.map(f=>`<button type="button" data-interior="floor" data-floor="${e(f.id)}" aria-pressed="${f.id===state.floorId}">${e(f.label)} <span>${snapshot.actors.filter(a=>a.floorId===f.id).length} inside</span></button>`).join('');if(floors.innerHTML!==floorMarkup){floors.innerHTML=floorMarkup;if(focusedFloor)floors.querySelector<HTMLButtonElement>('[data-floor="'+focusedFloor+'"]')?.focus({preventScroll:true});}
   const actors=snapshot.actors.filter(a=>a.floorId===floor.id),stations=floor.stations.filter(s=>s.production),selected=stations.find(s=>s.id===state.station)||stations[0];state.station=selected?.id||'';
   const recipe=snapshot.recipes.find(r=>r.id===state.recipe)||snapshot.recipes[0];state.recipe=recipe?.id||'';
   const supplies=(stock:Record<string,number>):string=>Object.entries(stock).filter(([,n])=>n>0).map(([id,n])=>`${n} ${e(id.replaceAll('_',' '))}`).join(', ')||'Empty';
   const body=`<section><h2>Live activity · ${e(floor.label)}</h2>${actors.length?actors.map(a=>`<article><strong>${e(a.name)}</strong><p>${e(a.action)}</p>${a.progress!==null?`<meter min="0" max="1" value="${a.progress}" aria-label="${e(a.name)} task progress"></meter><small>${Math.round(a.progress*100)}%${a.remainingSeconds!==null?' · '+Math.ceil(a.remainingSeconds)+'s remaining':''}</small>`:''}${a.cargo?`<small>Satchel: ${e(a.cargo)}</small>`:''}</article>`).join(''):'<p>No companion is on this floor. Creatures arrive through the doorway when their real task brings them here.</p>'}</section><section><h2>Production orders</h2><p>${e(snapshot.status.label)} · ${e(snapshot.status.detail)}</p>${recipe&&selected?`<form id="interior-production"><label>Workstation<select name="station">${stations.map(s=>`<option value="${e(s.id)}" ${s.id===state.station?'selected':''}>${e(s.label)}</option>`).join('')}</select></label><label>Item or equipment<select name="recipe">${snapshot.recipes.map(r=>`<option value="${e(r.id)}" ${r.id===state.recipe?'selected':''}>${e(r.name)} · ${r.amount} per batch</option>`).join('')}</select></label><label>Batches<input name="batches" type="number" min="1" max="12" step="1" value="${e(state.batches)}" required></label><small>${recipe.time}s base work per batch · ${recipe.queued} queued. Ingredients must be carried to this building.</small><button type="submit">Place production order</button></form>`:'<p>This floor has no manufacturing workstation.</p>'}</section><section><h2>Visit this floor</h2><form id="interior-visit"><label>Companion<select name="actor">${h.engine().creatures.map(a=>`<option value="${e(a.id)}" ${a.activeQuest?'disabled':''} ${a.id===state.actor?'selected':''}>${e(a.name)}${a.activeQuest?' · away':''}</option>`).join('')}</select></label><button type="submit">Suggest a floor visit</button></form><small>Companions finish their current task, walk here and use the stairs. Their needs continue.</small></section><section><h2>Physical supplies</h2><p><b>Inputs:</b> ${supplies(snapshot.input)}</p><p><b>Finished goods:</b> ${supplies(snapshot.output)}</p>${snapshot.transfers.slice(0,3).map(t=>`<small>${e(t.name)} ${t.direction==='in'?'delivered':'collected'} ${t.amount} ${e(t.resource.replaceAll('_',' '))}</small>`).join('')}</section>`;
   const signature=body;if(signature!==state.signature){const active=details.contains(document.activeElement)?document.activeElement as HTMLInputElement:null,form=active?.form?.id,name=active?.name,value=active?.value,batches=details.querySelector<HTMLInputElement>('[name=batches]')?.value;details.innerHTML=body;state.signature=signature;if(batches){const input=details.querySelector<HTMLInputElement>('[name=batches]');if(input)input.value=batches;}if(name&&form){const replacement=details.querySelector<HTMLInputElement|HTMLSelectElement>('#'+form+' [name="'+name+'"]');if(replacement){if(value!==undefined)replacement.value=value;replacement.focus({preventScroll:true});}}}
   status.textContent=state.feedback||(h.engine().s.paused?'Time is paused. Use the shared time controls to continue.':'The world keeps running. Use the shared time controls to pause.');
  }
  function paint():void{if(!state.buildingId||panel.classList.contains('custom-interior-renderer'))return;const snapshot=root.LWBuildingInteriorProjector.snapshot(h.engine(),state.buildingId);if(snapshot)renderer.draw(snapshot,state.floorId,h.engine().s.simTime);}
  panel.addEventListener('click',event=>{const target=(event.target as Element).closest<HTMLButtonElement>('[data-interior]');if(!target)return;event.stopPropagation();if(target.dataset.interior==='back'){close();h.refresh();}else if(target.dataset.interior==='redesign'){const id=state.buildingId;close(false);root.LWConstructionEditor?.open(id);}else{state.floorId=target.dataset.floor!;h.world().setInteriorView?.(state.buildingId,state.floorId);state.station='';state.signature='';update();details.scrollTop=0;paint();floors.querySelector<HTMLButtonElement>('[data-floor="'+state.floorId+'"]')?.focus();}});
  panel.addEventListener('change',event=>{const input=event.target as HTMLInputElement;if(input.name==='recipe')state.recipe=input.value;if(input.name==='station')state.station=input.value;if(input.name==='actor')state.actor=input.value;});
  panel.addEventListener('input',event=>{const input=event.target as HTMLInputElement;if(input.name==='batches')state.batches=input.value;});
  panel.addEventListener('submit',event=>{
   event.preventDefault();event.stopPropagation();if(state.source!==h.engine())return;const form=event.target as HTMLFormElement,data=new FormData(form);
   const result=h.engine().dispatchCommand(form.id==='interior-production'?{id:'order-building-production',args:[state.buildingId,state.floorId,String(data.get('station')),String(data.get('recipe')),Number(data.get('batches'))]}:{id:'visit-building-floor',args:[String(data.get('actor')),state.buildingId,state.floorId]});
   state.feedback=result.ok?(form.id==='interior-production'?'Production order placed at this floor workstation.':'Floor visit suggested. The companion will walk here after current work.'):(result.reason||'The request is unavailable.');if(result.ok)h.save();update();h.refresh();
  });
  document.addEventListener('keydown',event=>{if(state.buildingId&&event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();close();h.refresh();}},true);
  return {open,close,update,paint,reset:()=>close(false),get state(){return{buildingId:state.buildingId,floorId:state.floorId};}};
 }
 root.LWBuildingInteriorUI=Object.freeze({create});
})(globalThis);
