/// <reference path="./engine-export-contracts.d.ts" />
/// <reference path="./scene-graph-contracts.d.ts" />
/// <reference path="./building-interior-data-contracts.d.ts" />
/// <reference path="./renderer-data-contracts.d.ts" />
/* Code-generator binding guidance is explicit about systems requiring a semantic port. */
(function(inputRoot:unknown){
 'use strict';
 const root=inputRoot as {LWEngineExportManifest?:LWEngineExport.ManifestApi;LWSceneGraph:LWSceneGraph.Api;LWInteriors:LWInterior.CatalogApi;LWRendererCatalog:LittlewildRenderer.Catalog;LWCommandRouter?:{manifest:readonly unknown[]};LWSimulationPipeline?:{schedule:readonly unknown[]};LWEngineExportData:LWEngineExport.Decoder;LWAnimationCatalog?:{list():readonly {id:string;name:string;description:string;source?:string}[]}};
 const node=typeof module!=='undefined'&&module.exports;if(node)require('./animation-catalog.js');
 const G=(node?require('./scene-graph.js'):root.LWSceneGraph) as LWSceneGraph.Api;
 const R=(node?require('./renderer-catalog.js'):root.LWRendererCatalog) as LittlewildRenderer.Catalog;
 const I=(node?require('./building-interior-catalog.js'):root.LWInteriors) as LWInterior.CatalogApi;
 const record=(value:unknown):Record<string,unknown>=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};
 const rows=(value:unknown):Record<string,unknown>[]=>Array.isArray(value)?value.map(record):[];
 const D=(node?require('./engine-export-data.js'):root.LWEngineExportData) as LWEngineExport.Decoder;
 const rendererIds=['basic','pixi-2d','excalibur-2d'],animationIds=['sparkles','orbit','ripple'],capabilities:LittlewildRenderer.Capability[]=['camera','hit-test','terrain-preview','construction-preview','resource-lens','interiors'];
 const builtinRenderers:LittlewildRenderer.Metadata[]=[{id:'basic',name:'Basic',description:'Built-in world renderer with graphics compatibility fallback.',capabilities,dimensions:['2d','3d']},...['pixi-2d','excalibur-2d'].map(id=>({id,name:id==='pixi-2d'?'PixiJS 2D':'ExcaliburJS 2D',description:'Built-in library graphics adapter.',capabilities:['camera','hit-test','interiors','terrain-preview','construction-preview'] as LittlewildRenderer.Capability[],dimensions:['2d'] as LittlewildRenderer.Dimension[]}))];
 function stableId(input:unknown):string{if(typeof input!=='string'||!/^[a-z][a-z0-9-]{0,63}$/.test(input))throw Error('Invalid authored extension ID.');return input;}
 function metadata(input:unknown,id:string,renderer:boolean):LittlewildRenderer.Metadata|LWAnimations.Metadata{
  const value=D.record(input),allowed=renderer?['id','name','description','capabilities','dimensions']:['id','name','description','source'];
  if(value.id!==id||Object.keys(value).some(key=>!allowed.includes(key))||typeof value.name!=='string'||!value.name.trim()||[...value.name].length>80||typeof value.description!=='string'||[...value.description].length>400)throw Error('Invalid captured extension metadata: '+id);
  if(renderer){const caps=value.capabilities,dims=value.dimensions;if(!Array.isArray(caps)||caps.length>6||new Set(caps).size!==caps.length||caps.some(cap=>!capabilities.includes(cap as LittlewildRenderer.Capability))||dims!==undefined&&(!Array.isArray(dims)||dims.length<1||dims.length>2||new Set(dims).size!==dims.length||dims.some(dim=>dim!=='2d'&&dim!=='3d')))throw Error('Invalid captured renderer dimensions/capabilities: '+id);}
  else if(value.source!==undefined&&(typeof value.source!=='string'||value.source.length>200||D.path(value.source)!==value.source))throw Error('Invalid captured animation source: '+id);
  return value as unknown as LittlewildRenderer.Metadata|LWAnimations.Metadata;
 }
 function extensions(pack:LWContentPorts.ScenarioPack,input?:unknown):LWEngineExport.Extensions{
  const renderers=[...new Set(pack.scenes.map(scene=>stableId(scene.graph?.rendering?.rendererId??'basic')))].filter(id=>!rendererIds.includes(id)),animations=[...new Set((pack.storytelling?.cutscenes??[]).flatMap(clip=>(clip.animations??[]).map(animation=>stableId(animation.presetId))))].filter(id=>!animationIds.includes(id));
  const captured=input===undefined?{version:1,renderers:renderers.map(id=>({id,metadata:R.list().find(row=>row.id===id)??null})),animations:animations.map(id=>{const preset=root.LWAnimationCatalog?.list().find(row=>row.id===id);return {id,metadata:preset?{id:preset.id,name:preset.name,description:preset.description,...(preset.source?{source:preset.source}:{})}:null};})}:input,value=D.record(D.parse(captured));
  if(value.version!==1||Object.keys(value).length!==3||!Array.isArray(value.renderers)||!Array.isArray(value.animations)||value.renderers.length>2048||value.animations.length>2048)throw Error('Invalid captured extension snapshot.');
  function check(values:unknown[],ids:string[],renderer:boolean):void{if(values.length!==ids.length)throw Error('Incomplete captured extension coverage.');for(const [index,raw] of values.entries()){const entry=D.record(raw),id=ids[index]!;if(Object.keys(entry).length!==2||entry.id!==id||!Object.hasOwn(entry,'metadata'))throw Error('Invalid captured extension identity or order.');if(entry.metadata!==null||!renderer)metadata(entry.metadata,id,renderer);}}
  check(value.renderers,renderers,true);check(value.animations,animations,false);
  const snapshot=value as unknown as LWEngineExport.Extensions;
  for(const scene of pack.scenes){const rendering=scene.graph?.rendering;if(!rendering)continue;const descriptor=builtinRenderers.find(row=>row.id===rendering.rendererId)??snapshot.renderers.find(row=>row.id===rendering.rendererId)?.metadata;if(descriptor?.dimensions&&!descriptor.dimensions.includes(rendering.dimension))throw Error('Captured renderer '+rendering.rendererId+' does not support authored dimension '+rendering.dimension+'.');}
  return snapshot;
 }
 function create(pack:LWContentPorts.ScenarioPack,sceneId:string,bundle:LWEngineExport.SourceBundle,snapshot:LWEngineExport.Extensions):ReturnType<LWEngineExport.ManifestApi['create']>{
  const catalogs:Record<string,unknown>={},sources=new Map(bundle.files.map(file=>[file.path,file]));
  // Pocket Pet meshes belong to a separate demo application; they stay exported as source text, not colony catalogs.
  for(const file of bundle.files)if(file.path.endsWith('.json')&&/^source\/(assets|content|schemas)\//.test(file.path)&&!/^source\/(assets\/pets\/|content\/pet-demo\.json$)/.test(file.path))catalogs[file.path]=JSON.parse(file.text) as unknown;
  const commandText=sources.get('source/command-router.ts')?.text??'',scheduleText=sources.get('source/simulation-pipeline.ts')?.text??'';
  const commands=[...commandText.matchAll(/\{id:'([^']+)',method:'([^']+)',scope:'([^']+)',maxArgs:(\d+),away:(true|false)\}/g)].map(match=>({id:match[1],method:match[2],scope:match[3],maxArgs:Number(match[4]),away:match[5]==='true'}));
  const schedule=[...scheduleText.matchAll(/\{id:'([^']+)',scope:'([^']+)',order:(\d+),owner:'([^']+)'\}/g)].map(match=>({id:match[1],scope:match[2],order:Number(match[3]),owner:match[4]}));
  const systems:Record<string,unknown>[]=[];
  for(const path of ['source/actor-ecs.ts','source/world-ecs.ts','source/economy-ecs.ts']){
   const text=sources.get(path)?.text??'';
   for(const match of text.matchAll(/register(?:<[^>]+>)?\(\{id:'([^']+)',phase:'([^']+)',order:(\d+),query:\[([^\]]*)\]/g))systems.push({id:match[1],phase:match[2],order:Number(match[3]),components:[...match[4]!.matchAll(/'([^']+)'/g)].map(value=>value[1]),source:path,port:'manual-semantic-port'});
  }
  const owners=new Map<string,Record<string,unknown>>();for(const scene of pack.scenes){const owner=G.owner(pack,scene.id);owners.set(owner.id,owner.initialState);}
  const checkpoints=[...owners].map(([id,state])=>({id,state}));
  const scenes=pack.scenes.map(scene=>{
   const state=G.owner(pack,scene.id).initialState,rendering=scene.graph?.rendering??{dimension:'3d' as const,rendererId:'basic' as const},dimension=rendering.dimension,binding=scene.graph?.binding;
   let floor:LWInterior.Floor|null=null;
   if(binding?.type==='interior'){const building=rows(state.buildings).find(value=>value.id===binding.buildingId)!;floor=I.floor(I.forBuilding(state as unknown as LWInterior.CatalogWorld,building as unknown as LWInterior.CatalogBuilding),binding.floorId);}
   const height=(x:number,y:number):number=>binding?.type==='interior'?0:Number(record(record(record(state.terraform).tiles)[Math.round(x)+','+Math.round(y)]).height??0);
   return {id:scene.id,worldId:scene.worldId,parentId:scene.graph?.parentId??null,ownerSceneId:G.owner(pack,scene.id).id,resource:'scenes/'+scene.id+'.tscn',dimension,node:dimension==='2d'?'Node2D':'Node3D',rendering,embeds:(rendering.embeds??[]).map(embed=>({...embed,target:'SubViewportContainer',overlay:'CanvasLayer'})),bounds:G.bounds(pack,scene.id)??null,binding:binding??null,floor,coordinateSpace:binding?.type==='interior'?'local-native-floor':'global-native-grid',entities:G.entities(pack,scene.id).map(entity=>({id:entity.id,category:entity.category,kind:entity.kind,node:entity.category==='creatures'?(dimension==='2d'?'CharacterBody2D':'CharacterBody3D'):(dimension==='2d'?'Node2D':'Node3D'),position:dimension==='2d'?[entity.x,entity.y]:[entity.x,height(entity.x,entity.y),entity.y],elevation:height(entity.x,entity.y),canonical:entity.data}))};
  });
  const rendererSources=new Map<string,string>([['basic','source/renderer-basic-adapter.ts'],['pixi-2d','source/renderer-pixi.ts'],['excalibur-2d','source/renderer-excalibur.ts']]);
  const renderers=[...new Set(scenes.map(scene=>scene.rendering.rendererId))].map(id=>{
   const metadata=builtinRenderers.find(value=>value.id===id)??snapshot.renderers.find(value=>value.id===id)?.metadata??null,source=rendererSources.get(id)??null;
   const uses=scenes.filter(scene=>scene.rendering.rendererId===id).map(scene=>({sceneId:scene.id,dimension:scene.dimension,embeddedBy:scenes.filter(parent=>parent.embeds.some(embed=>embed.sceneId===scene.id)).map(parent=>parent.id)}));
   return {id,metadata,registered:metadata!==null,source,sourceIncluded:source!==null&&sources.has(source),requiresModule:source===null,uses,requiredWork:source===null?'Supply or identify the compiled renderer extension module and manually port its factory/platform behavior; catalog metadata does not declare source provenance, and JSON never contains executable factories.':'Port the included compiled platform adapter with its declared dimensions and capabilities.'};
  });
  const assets=bundle.files.filter(file=>/^source\/assets\/.+\/asset\.json$/.test(file.path)).map(file=>{const data=D.record(catalogs[file.path]);return {id:String(data.category)+':'+String(data.id),source:file.path,sha256:file.sha256,target:'MeshInstance3D',status:'translate-canonical-primitive-tree-and-rig',canonical:data};});
  for(const [index,value] of (pack.resources?.assets??[]).entries()){const data=D.record(value),id=String(data.category)+':'+String(data.id),existing=assets.findIndex(asset=>asset.id===id),record={id,source:'pack.resources.assets['+index+']',sha256:'pack-canonical-data',target:'MeshInstance3D',status:'translate-canonical-primitive-tree-and-rig',canonical:data};if(existing<0)assets.push(record);else assets[existing]=record;}
  const authoredAnimations=new Set((pack.storytelling?.cutscenes??[]).flatMap(cutscene=>(cutscene.animations??[]).map(animation=>animation.presetId)));
  const animations=[...authoredAnimations].map(id=>{const preset=animationIds.includes(id)?{id,name:id[0]!.toUpperCase()+id.slice(1),description:'Deterministic p5 presentation preset.',source:'source/renderer-animations.ts'}:snapshot.animations.find(value=>value.id===id)?.metadata;return {id,metadata:preset??null,sourceIncluded:!!preset?.source&&sources.has(preset.source),requiredWork:!animationIds.includes(id)?'Compiled custom preset: supply the extension module and manually port its draw capability; JSON never supplies executable callbacks.':'Port compiled deterministic presentation preset.'};});
  const runtime:Record<string,unknown>={
   components:{contracts:bundle.files.filter(file=>file.role==='contract'&&/(ecs|physical|creature|content|engine|runtime)/.test(file.path)).map(file=>({source:file.path,sha256:file.sha256})),catalogBindings:'Creature definitions ecs.components are authoritative archetype-specific bindings.'},
   systems,ecsOrder:{phases:['pre','simulate','post'],systems:'phase, then numeric order, then lexical system ID',entities:'Lexical entity ID query order',source:'source/ecs.ts'},
   commands:{manifest:commands,failureCodes:['rule-rejected','invalid-command','unknown-command','unavailable-command','invalid-target','invalid-data','busy','insufficient-resources','settlement-rejected'],contracts:['source/runtime-contracts.d.ts','source/runtime-results.ts'],source:'source/command-router.ts',ownership:'UI emits validated intents; command router owns scope, argument limits and dispatch; statuses/errors and receipts remain data contracts.'},
   schedule:{compiled:schedule,source:'source/simulation-pipeline.ts',actorOrder:'Actor-major, stable native creature order; each actor dynamics then activity; world/economy transactions settle through their ordered ECS systems.'},
   persistence:{native:{app:'littlewild',version:8,source:'source/engine.ts'},story:{version:10,source:'source/scenario-story.ts'},journey:{source:'source/scene-navigation.ts',checkpoints:'Canonical owner state per root scene; shared child scenes retain their owner identity.'},pack:{format:'living-worlds-pack',schemaVersion:2}},
   determinism:{fixedStepSeconds:0.1,maxPendingSteps:32,maxFrameSeconds:0.1,maxSpeed:16,clockSource:'source/simulation-clock.ts',rng:{algorithm:'Mulberry32',state:'unsigned32-bit seed',increment:1831565813,divisor:4294967296,source:'source/rpg.ts',streams:'Separate actor.rpg.rng, world colony.rng and creatureInteractions.rng (decision stream seeded from colony.rng XOR0x9e3779b9); preserve every seed and draw order.',streamSources:['source/colony.ts','source/interaction-triggers.ts']},transactions:'Paid reservations, jobs, transfer/settlement receipts and outboxes are canonical state. Port validate/reserve/update/settle ordering and idempotency before promising continuation parity.',transactionSources:['source/world-ecs.ts','source/economy-ecs.ts','source/physical-ecs-contracts.d.ts']},
   balancing:{document:'source/content/balancing.json',assembly:'source/tools/bundled-content.cts',definitions:bundle.files.filter(file=>/^source\/assets\/(items|buildings|creatures)\/[^/]+\/definition\.json$/.test(file.path)).map(file=>file.path),inventory:'source/content/balancing-inventory.json',policy:'Assemble canonical defaults from the authoring document and discovered definition facets; catalog selectors are build-only and portable documents contain complete values. Explicit pack overrides remain authoritative; mathematical, serialization and grid invariants are classified separately.'},
   sourceDependencies:bundle.files.filter(file=>file.dependencies.length).map(file=>({source:file.path,dependencies:file.dependencies})),architecture:bundle.architecture
  };
  const godot:Record<string,unknown>={
   version:'Godot4',coordinateSystem:{native:'x/y grid, elevation separate',godot:'right-handed x/z ground plane, y elevation',mapping:{x:'native.x',y:'native elevation',z:'native.y'},gridUnitMeters:1,islandCells:19,islandStride:23,warning:'Never scale island topology or interior floor bounds; values expressed in grid units convert at one meter per grid unit.'},
   transforms:{source:'source/asset-renderer.ts',rotation:'Three Euler intrinsic XYZ rotations are radians. Convert to Basis/Quaternion preserving XYZ order; do not assign Godot Euler triples without order conversion.',hierarchy:'Primitive nodes, rig bones and sockets use hierarchical local transforms. Preserve parent, pivot, local position, rotation, scale and socket bindings.',materials:'Map canonical color/roughness/metalness/opacity roles to StandardMaterial3D; preserve semantic material IDs and per-model variant assignments.'},
   scenes,assets,animations,renderers,
   bindings:[{native:'canonical primitive tree',godot:'Node3D / MeshInstance3D + ArrayMesh primitive geometry',source:'source/asset-renderer.ts'},{native:'rig / socket / gait',godot:'Node3D hierarchy + AnimationPlayer, optionally Skeleton3D after reviewed rig conversion',source:'source/world-fidelity.ts'},{native:'2D/3D renderer embeds',godot:'SubViewport / SubViewportContainer + CanvasLayer for overlay UI',source:'source/renderer-compositor.ts'},{native:'story timeline tracks / camera / actor pose',godot:'AnimationPlayer tracks + explicit validated story action dispatcher',source:'source/storytelling-player.ts'},{native:'ECS simulation / behavior / economy / progression',godot:'Deterministic fixed-step systems with Resource component schemas; manual semantic translation',sources:['source/actor-ecs.ts','source/world-ecs.ts','source/economy-ecs.ts','source/behavior-tree.ts']},{native:'browser UI / p5 / Pixi / Excalibur',godot:'Control/CanvasLayer/SubViewport adapters; manual platform port',source:'source/index.html'}],
   stableIds:'Use canonical world/scene/entity/asset/component/command IDs as Resource metadata and node identity; names are presentation only.',selectedSceneId:sceneId,requiredWork:['Translate TypeScript systems to GDScript or C# preserving numeric and RNG semantics.','Generate meshes/materials/resources/scenes from canonical assets and catalogs.','Implement validated commands, transaction receipts, checkpoint migration, offline UI and renderer adapters.','Run exported contract/conformance checks and native save-continuation comparisons before claiming gameplay parity.']
  };
  return D.parse({checkpoint:{format:'canonical-owner-states',owners:checkpoints},catalogs,runtime,godot,limitations:[...renderers.filter(renderer=>renderer.requiresModule).map(renderer=>'Compiled renderer '+renderer.id+': '+(renderer.registered?'registered metadata has no declared extension module provenance;':'unregistered portable identity is unavailable to the current host;')+' supply or identify its compiled extension source and perform a manual semantic port. Executable factories cannot be reconstructed from JSON.'),...animations.filter(animation=>!['sparkles','orbit','ripple'].includes(animation.id)).map(animation=>'Compiled custom animation '+animation.id+': '+(animation.sourceIncluded?'extension source included; manual semantic port required.':'extension module absent from the trusted source inventory; supply its source before generating that capability.')),'This is complete inert source and data input for a code generator; it does not automatically translate TypeScript or establish Godot gameplay parity.','Godot bindings are a reviewed mapping manifest; platform UI, shaders, renderer vendors and systems require semantic ports.','World geometry, assets, rigs, paid jobs, inventories, configuration and all canonical owner checkpoints remain native authoritative data.']}) as ReturnType<LWEngineExport.ManifestApi['create']>;
 }
 const api:LWEngineExport.ManifestApi={extensions,create};root.LWEngineExportManifest=api;if(node)module.exports=api;
})(globalThis);
