/// <reference path="./external-editor-contracts.d.ts" />
/* Offline interchange facade; the caller owns review and draft replacement. */
(function(inputRoot:unknown){
 'use strict';
 const root=inputRoot as {LWExternalEditorCore:LWExternalEditors.Core;LWExternalTiled:LWExternalEditors.Codec;LWExternalLdtk:LWExternalEditors.Codec;LWExternalGltf:LWExternalEditors.Codec;LWExternalCanvas?:LWExternalEditors.Codec;LWExternalAdvancedCanvas?:LWExternalEditors.Codec;LWExternalEditors?:LWExternalEditors.Api};
 const node=typeof module!=='undefined'&&module.exports,C=(node?require('./external-editor-core.js'):root.LWExternalEditorCore) as LWExternalEditors.Core;
 const codecs:Partial<Record<LWExternalEditors.Format,LWExternalEditors.Codec>>={tiled:(node?require('./external-editor-tiled.js'):root.LWExternalTiled) as LWExternalEditors.Codec,ldtk:(node?require('./external-editor-ldtk.js'):root.LWExternalLdtk) as LWExternalEditors.Codec,gltf:(node?require('./external-editor-gltf.js'):root.LWExternalGltf) as LWExternalEditors.Codec};
 function optionalCanvas():void{if(node){try{const canvas=require('./external-editor-canvas.js') as {canvas:LWExternalEditors.Codec;advancedCanvas:LWExternalEditors.Codec};codecs.canvas=canvas.canvas;codecs['advanced-canvas']=canvas.advancedCanvas;}catch(error){if(!(error instanceof Error)||!('code' in error)||(error as Error&{code:unknown}).code!=='MODULE_NOT_FOUND')throw error;}}else{if(root.LWExternalCanvas)codecs.canvas=root.LWExternalCanvas;if(root.LWExternalAdvancedCanvas)codecs['advanced-canvas']=root.LWExternalAdvancedCanvas;}}
 const formats=()=>[{id:'tiled' as const,label:'Tiled JSON map',extension:'tmj'},{id:'ldtk' as const,label:'LDtk project',extension:'ldtk'},{id:'gltf' as const,label:'Blender / Godot glTF 2',extension:'gltf'},{id:'canvas' as const,label:'Obsidian Canvas',extension:'canvas'},{id:'advanced-canvas' as const,label:'Obsidian Advanced Canvas',extension:'canvas'}];
 function detectDocument(doc:Record<string,unknown>):LWExternalEditors.Format{if(Array.isArray(doc.nodes)&&Array.isArray(doc.edges))return C.record(doc.metadata).version==='1.0-1.0'?'advanced-canvas':'canvas';if(doc.type==='map')return 'tiled';if(doc.jsonVersion!==undefined&&doc.levels!==undefined)return 'ldtk';if(C.record(doc.asset).version==='2.0')return 'gltf';throw Error('Choose a Tiled .tmj, LDtk .ldtk glTF 2 .gltf/.glb, or Obsidian .canvas document.');}
 const api:LWExternalEditors.Api={formats,detect:input=>detectDocument(C.parse(input)),export(pack,sceneId,format){optionalCanvas();const codec=codecs[format];if(!codec)throw Error('Unsupported external editor format.');const exchange=C.prepare(pack,sceneId),exchanged=codec.write(exchange);C.parse(exchanged);const warnings=codec.read(exchanged).warnings;return {ok:true,format,document:exchanged,filename:sceneId+'.'+formats().find(f=>f.id===format)!.extension,warnings};},import(input,options){let warnings:string[]=[];try{if(options)C.parse(options);optionalCanvas();const exchanged=C.parse(input),format=detectDocument(exchanged),codec=codecs[format];if(!codec)throw Error('This external codec is unavailable in the current build.');const exchange=codec.read(exchanged,options);warnings=exchange.warnings;const applied=C.apply(exchange,options);return {ok:true,format,...applied,warnings};}catch(error){return {ok:false,errors:[error instanceof Error?error.message:String(error)],warnings};}}};
 root.LWExternalEditors=api;if(node)module.exports=api;
})(globalThis);
