/* Unified planner adapters. Rows are derived from authoritative orders, not a second task queue.
 * Adding a row delegates to a registered feature command. Lifecycles keep paid work physical. */
(function(root){'use strict';const L=root.LW,Composition=L.EngineComposition,C=root.LWGrowth,fail=reason=>({ok:false,reason}),ok=(extra={})=>({ok:true,...extra});
 const key=(type,actor,id='')=>[type,actor,id].filter(Boolean).join(':'),terminal=q=>['done','cancelled'].includes(q.status);
 function control(e,k){return e.s.planning.controls[k]||{};}
 function paused(e,k){return !!control(e,k).paused;}
 function reason(value){return typeof value==='string'?value:value?.text||value?.reason||'';}
 function rows(e){const out=[];for(const c of e.creatures){
  const common={actorId:c.id,assignee:c.name,away:!!c.activeQuest};
  for(const o of c.orders){const k=key('order',c.id,o.id),current=c.task?.orderId===o.id,issue=e.withActor(c,()=>reason(e.orderIssue(o)));out.push({...common,key:k,type:'order',id:o.id,system:['build','upgrade'].includes(o.type)?'Construction':o.type==='practice'?'Learning':'Production',name:e.withActor(c,()=>e.orderName(o)),priority:o.priority||0,paused:!!o.paused,stopped:!!control(e,k).stopped,state:c.activeQuest?'Waiting for return':o.paused?'Paused':current?'In progress':issue?'Blocked':'Queued',detail:issue||c.task?.reason||'Urgent needs come first.',progress:['build','upgrade'].includes(o.type)?((o.stage||0)+(o.progress||0)/(e.withActor(c,()=>e.constructionPhases(o)[o.stage||0].time)||1))/3:(o.done||0)/(o.amount||1),canAssign:true});}
  for(const t of [...(c.training?[c.training]:[]),...c.learning.queue]){const k=key('lesson',c.id,t.id),p=paused(e,k)||c.learning.paused;out.push({...common,key:k,type:'lesson',id:t.id,system:'Learning',name:'Learn '+L.SKILLS[t.id].short,priority:control(e,k).priority||0,paused:p,stopped:!!control(e,k).stopped,state:c.activeQuest?'Waiting for return':p?'Paused':c.training===t?'Learning':'Queued',detail:'Tuition paid. Understand → try → reflect.',progress:t.progress/L.SKILLS[t.id].time,canAssign:!t.progress});}
  for(const id of c.equipQueue){const k=key('outfit',c.id,id),p=paused(e,k),status=root.LWPolicies.equipmentStatus(e,c,id);out.push({...common,key:k,type:'outfit',id,system:'Equipment',name:'Prepare '+L.colony.item(id).name,priority:control(e,k).priority||0,paused:p,stopped:!!control(e,k).stopped,state:p?'Paused':status.blockers.length?'Blocked':'Preparing',detail:status.text,progress:0,canAssign:true});}
  if(c.questPlan||c.activeQuest){const q=c.activeQuest||c.questPlan,id=q.questId,k=key('quest',c.id,id);out.push({...common,key:k,type:'quest',id,system:'Adventure',name:root.LWAdventure.content.quests.find(d=>d.id===id)?.name||'Quest',priority:control(e,k).priority||0,paused:!!q.paused,stopped:!!control(e,k).stopped,state:c.activeQuest?(q.status==='returning'?'Returning':'Away'):q.paused?'Paused':'Preparing',detail:(q.islandName?q.islandName+' · ':'')+(c.activeQuest?'While away, only recall is available.':e.questPlanIssue?.(q,c)||'Provisions, equipment, energy, then departure.'),progress:c.activeQuest?q.elapsed/q.duration:0,canAssign:!c.activeQuest});}
  if(c.socialIntent){const k=key('social',c.id,c.socialIntent),p=paused(e,k);out.push({...common,key:k,type:'social',id:c.socialIntent,system:'Friendship',name:'Spend time with '+(e.creatures.find(x=>x.id===c.socialIntent)?.name||'a friend'),priority:control(e,k).priority||0,paused:p,state:p?'Paused':'Waiting to meet',detail:'Both creatures must be home and available.',progress:0});}
  if(c.unpackIntent){const k=key('unpack',c.id);out.push({...common,key:k,type:'unpack',id:'',system:'Inventory',name:'Open a woodland chest',priority:control(e,k).priority||0,paused:paused(e,k),state:paused(e,k)?'Paused':'Queued',detail:'Collect a chest, then open it at the warehouse.',progress:0});}
  if(c.needsDeposit){const k=key('unload',c.id);out.push({...common,key:k,type:'unload',id:'',system:'Logistics',name:'Deposit carried findings',priority:1,paused:false,state:'Bringing items home',detail:'Physical warehouse delivery. Essential hauling is protected.',progress:0,protected:true});}
  const t=c.task;if(t&&!t.orderId&&!['train','equip','unpack'].includes(t.kind)&&!t.saleId&&!t.buffered&&!(c.equipQueue.length&&['withdraw','gearcraft'].includes(t.kind))&&!['social','socialwait'].includes(t.kind)&&!(t.kind==='deposit'&&c.needsDeposit))out.push({...common,key:key('activity',c.id,t.kind),type:'activity',id:t.kind,system:t.need?'Self-care':['stockbuilding','collectbuilding','emptybuilding','deposit','withdraw'].includes(t.kind)?'Logistics':'Autonomous',name:t.label||t.kind,state:t.phase==='walk'?'Walking':'In progress',detail:t.reason||'Creature-led activity. Tasks may recur if still needed.',priority:0,paused:false,progress:t.elapsed/t.duration,protected:!!t.need||['rest','eat','drink','eatbread','calmdown'].includes(t.kind)});
 }
 for(const b of e.s.buildings){const st=b.storage;if(!st)continue;const requested=Object.values(st.requests).some(n=>n>0),target=Object.entries(st.targets).some(([id,n])=>n>e.demandStock(id));if(!st.job&&!requested&&!target&&!st.emptyInputs&&!st.flushOutput)continue;const status=e.buildingStatus(b),actorId=b.planAssignee||st.job?.workerId||null;out.push({key:'workplace:'+b.id,type:'workplace',id:b.id,actorId,assignee:actorId?e.creatures.find(c=>c.id===actorId)?.name||'Unknown':'Any qualified creature',system:'Workplace',name:L.BUILDINGS[b.kind].name+' production',state:status.label,detail:status.detail,priority:st.priority,paused:!st.enabled,progress:st.job?st.job.progress/st.job.duration:0,canAssign:true,away:false});}
 for(const q of e.s.market.orders.filter(q=>!terminal(q))){const actorId=q.assignedId||Object.keys(q.transit).find(id=>q.transit[id]>0)||null;out.push({key:'sale:'+q.id,type:'sale',id:q.id,actorId,assignee:actorId?e.creatures.find(c=>c.id===actorId)?.name||'Unknown':'Any available creature',system:'Market',name:'Sell '+q.amount+' '+L.colony.item(q.item).name,state:q.paused?'Paused':q.status==='cancelling'?'Returning unsold goods':q.status,detail:q.sold+'/'+q.amount+' sold · '+q.remaining+' awaiting pickup · coins only at stall',priority:q.priority,paused:q.paused,progress:q.sold/q.amount,canAssign:true});}
 return out.sort((a,b)=>Number(a.paused)-Number(b.paused)||b.priority-a.priority||(a.key<b.key?-1:a.key>b.key?1:0));}
 function archive(e,row,label){e.s.planning.history.unshift({time:e.s.simTime,key:row.key,name:row.name,actorId:row.actorId,action:label});e.s.planning.history=e.s.planning.history.slice(0,60);}
 function act(e,k,command,value){const row=rows(e).find(r=>r.key===k);if(!row)return fail('That task has finished or changed.');if(row.away){if(row.type==='quest'&&command==='cancel')return e.commandActor(row.actorId,()=>e.abortQuest(),{away:true});return fail('This creature is away. Only quest recall is available.');}if(row.protected)return fail('Essential care and returning carried goods cannot be stopped.');
  if(!['pause','resume','stop','cancel','priority','assign'].includes(command))return fail('Unknown planner operation.');if(row.type==='activity'&&!['stop','cancel'].includes(command))return fail('This is an autonomous activity. Stop it once; the creature may choose it again when needed.');if(command==='priority'&&![0,1,2].includes(value))return fail('Choose a valid priority.');
  if(row.type==='sale'){const r=e.controlSale(row.id,command,value);if(r.ok)archive(e,row,command);return r;}
  if(row.type==='workplace'){const b=e.s.buildings.find(b=>b.id===row.id);if(command==='assign'){if(value&&!e.creatures.some(c=>c.id===value&&!c.activeQuest))return fail('Choose an available creature.');for(const c of e.creatures)if(c.task?.buildingId===b.id)e.interruptActor(c);b.planAssignee=value||null;archive(e,row,command);return ok();}let r;if(command==='cancel'){e.configureBuilding(b.id,'clear');r=e.configureBuilding(b.id,'enabled',false);}else r=e.configureBuilding(b.id,command==='priority'?'priority':'enabled',command==='priority'?value:command==='resume');if(r.ok)archive(e,row,command);return r;}
  const c=e.creatures.find(c=>c.id===row.actorId);if(command==='assign'){const target=e.creatures.find(c=>c.id===value&&!c.activeQuest);if(!row.canAssign||!target)return fail('This task cannot be reassigned now.');if(c===target)return ok();if(row.type==='order'){if(target.orders.length>=12)return fail('The receiving creature already has twelve plans.');const o=c.orders.find(o=>o.id===row.id);e.interruptActor(c);c.orders=c.orders.filter(v=>v!==o);target.orders.push(o);for(const b of e.s.buildings)if(b.storage?.job?.orderId===o.id)b.storage.job.originId=target.id;}
   else if(row.type==='lesson'){const lesson=c.training?.id===row.id?c.training:c.learning.queue.find(t=>t.id===row.id);if(lesson.progress||target.skills[row.id]||target.learning.queue.length>=4||target.training?.id===row.id||target.learning.queue.some(t=>t.id===row.id))return fail('Only an unstarted lesson can move to a creature who has not queued or learned it.');e.interruptActor(c);if(c.training===lesson)c.training=null;else c.learning.queue=c.learning.queue.filter(t=>t!==lesson);target.learning.queue.push(lesson);target.researched[row.id]=true;}
   else if(row.type==='outfit'){if(target.equipQueue.length>=4||target.equipQueue.includes(row.id))return fail('The outfit queue is full or already has that item.');e.interruptActor(c);c.equipQueue=c.equipQueue.filter(id=>id!==row.id);target.equipQueue.push(row.id);}
   else if(row.type==='quest'){if(target.questPlan||target.activeQuest)return fail('The receiving creature already has a quest.');const issue=e.questPlanIssue?.(c.questPlan,target);if(issue)return fail(issue);e.interruptActor(c);target.questPlan=c.questPlan;c.questPlan=null;}
   else return fail('This task cannot be reassigned.');const newKey=key(row.type,target.id,row.id);if(e.s.planning.controls[k]){e.s.planning.controls[newKey]={...e.s.planning.controls[k]};delete e.s.planning.controls[k];}archive(e,row,'assigned to '+target.name);return ok();}
  const meta=e.s.planning.controls[k]||{};let r=ok();
  if(command==='priority'){meta.priority=value;if(row.type==='order'){c.orders.find(o=>o.id===row.id).priority=value;}if(row.type==='lesson'&&c.training?.id!==row.id){const i=c.learning.queue.findIndex(t=>t.id===row.id);if(i>=0&&value===2)c.learning.queue.unshift(...c.learning.queue.splice(i,1));}}
  else if(command==='cancel'){
   r=e.commandActor(c.id,()=>{if(row.type==='order')return e.cancel(row.id);if(row.type==='lesson')return e.cancelLesson(row.id);if(row.type==='outfit')return e.cancelEquipment(row.id);if(row.type==='quest')return e.cancelQuestPlan();if(row.type==='social'){e.interruptActor(c);c.socialIntent=null;}if(row.type==='unpack'){e.interruptActor(c);c.unpackIntent=false;}if(row.type==='activity')e.interruptActor(c);return ok();});delete e.s.planning.controls[k];
  }else{const hold=command!=='resume';meta.paused=hold;meta.stopped=command==='stop';if(row.type==='order')r=e.commandActor(c.id,()=>e.pauseOrder(row.id,hold));else if(row.type==='quest')c.questPlan.paused=hold;else if(row.type==='activity'){if(hold)e.interruptActor(c);meta.paused=false;}if(hold&&row.type!=='order')e.interruptActor(c);if(row.type==='lesson'&&!hold)c.learning.paused=false;}
  if(command!=='cancel')e.s.planning.controls[k]=meta;if(r?.ok!==false)archive(e,row,command);return r||ok();}
 function taskOptions(e,type,c){if(type==='gather')return root.LWWorldContent.content.nodes.filter(n=>n.direct&&L.RES[n.resource]&&e.unlocked('items',n.resource)).map(n=>({id:n.resource,name:L.RES[n.resource].name})).filter((d,i,a)=>a.findIndex(x=>x.id===d.id)===i);if(type==='craft')return Object.keys(L.RECIPES).filter(id=>e.unlocked('recipes',id)).map(id=>({id,name:L.RES[id].name}));if(type==='build')return Object.entries(L.BUILDINGS).filter(([id])=>e.unlocked('buildings',id)).map(([id,b])=>({id,name:b.name}));if(type==='lesson'||type==='practice')return Object.entries(L.SKILLS).filter(([id,k])=>k.tier<=e.s.player.level&&(type==='lesson'?!c?.skills[id]:c?.skills[id])).map(([id,k])=>({id,name:k.short+(type==='lesson'?' · '+k.coins+' coins':'')}));if(type==='outfit')return root.LWAdventure.content.equipment.filter(d=>e.unlocked('items',d.id)).map(d=>({id:d.id,name:d.name}));if(type==='quest')return e.unlocked('features','quests')?e.s.colony.board.offers.filter(o=>!e.questOfferIssue?.(o.id,c)).map(o=>({id:o.id,name:root.LWAdventure.content.quests.find(q=>q.id===o.questId).name+' · '+(o.islandName||'Mossmeadow')})):[];if(type==='social')return e.creatures.filter(x=>x.id!==c?.id&&!x.activeQuest).map(x=>({id:x.id,name:x.name}));if(type==='workplace')return e.s.buildings.filter(b=>b.storage).map(b=>({id:b.id,name:L.BUILDINGS[b.kind].name+' · '+b.x+', '+b.y}));return[{id:'',name:type==='unpack'?'Open carried or stored chest':type==='unload'?'Deposit excess carried goods':'Neighbor delivery'}];}
 const types=[['gather','Gather resources','Production'],['craft','Craft items','Production'],['build','Build a place','Construction'],['lesson','Learn a skill','Learning'],['practice','Practice a skill','Learning'],['outfit','Prepare equipment','Equipment'],['quest','Prepare a quest','Adventure'],['social','Meet a companion','Friendship'],['delivery','Neighbor delivery','Market'],['unpack','Open a chest','Inventory'],['unload','Bring findings home','Logistics'],['workplace','Workplace production','Workplace']].map(([id,name,system])=>({id,name,system}));
 function availableTypes(e){return types.filter(t=>t.id!=='quest'||e.unlocked('features','quests')).filter(t=>t.id!=='delivery'||e.unlocked('features','trade'));}
 function add(e,input){const {actorId,type,id,quantity=1,recipe}=input;const c=e.creatures.find(c=>c.id===actorId);if(!c||c.activeQuest)return fail('Assign an available creature.');if(!availableTypes(e).some(t=>t.id===type)||!Number.isInteger(quantity)||quantity<1||quantity>24)return fail('Choose a supported task and whole-number quantity.');if(type==='build'){if(!e.unlocked('buildings',id))return fail(e.gateIssue('buildings',id));return ok({placement:id,actorId});}
  return e.commandActor(actorId,()=>{if(type==='gather'||type==='craft')return e.request(type,id,quantity);if(type==='lesson'){if(!c.researched[id])return fail('Research this lesson in Learn before purchasing the training.');return e.teach(id);}if(type==='practice')return e.practice(id,Math.min(3,quantity));if(type==='outfit')return e.requestEquipment(id);if(type==='quest')return e.acceptQuest(id);if(type==='social')return e.suggestSocial(id);if(type==='delivery')return e.request('deliver');if(type==='unpack')return e.requestUnpack();if(type==='unload'){c.needsDeposit=true;return ok();}if(type==='workplace'){const b=e.s.buildings.find(b=>b.id===id);if(!b?.storage)return fail('Choose a production building.');const r=e.configureBuilding(id,'batch',{recipe,amount:Math.min(12,quantity)});if(r.ok)b.planAssignee=actorId;return r;}return fail('Unsupported task.');});}
 function attach(engine){const original=engine.handlers();engine._plannerHandlers=original;const start=t=>t&&engine.startTask(t)?'running':'failure';
  const h={...original};h.learning=()=>{const c=engine.actor,t=c.training||c.learning.queue[0];return t&&paused(engine,key('lesson',c.id,t.id))?'failure':original.learning();};
  h.outfit=()=>{const c=engine.actor;return c.equipQueue[0]&&paused(engine,key('outfit',c.id,c.equipQueue[0]))?'failure':original.outfit();};
  h.companionship=()=>{const c=engine.actor;return c.socialIntent&&paused(engine,key('social',c.id,c.socialIntent))?'failure':original.companionship();};
  // A priority boost spans feature queues, but never displaces survival, recovery or homecoming.
  h.prioritized=()=>{const c=engine.actor;const candidates=[];for(const o of c.orders)if(!o.paused&&o.priority===2)candidates.push({key:key('order',c.id,o.id),run:()=>start(engine.orderTask(o))});for(const t of [...(c.training?[c.training]:[]),...c.learning.queue]){const k=key('lesson',c.id,t.id);if(control(engine,k).priority===2&&!paused(engine,k))candidates.push({key:k,run:h.learning});}for(const id of c.equipQueue){const k=key('outfit',c.id,id);if(control(engine,k).priority===2&&!paused(engine,k))candidates.push({key:k,run:h.outfit});}if(c.questPlan){const k=key('quest',c.id,c.questPlan.questId);if(control(engine,k).priority===2&&!c.questPlan.paused)candidates.push({key:k,run:h.quest});}for(const q of engine.s.market.orders)if(q.priority===2&&!q.paused&&(!q.assignedId||q.assignedId===c.id)&&!terminal(q))candidates.push({key:'sale:'+q.id,run:()=>start(engine.marketTask())});for(const r of candidates.sort((a,b)=>(a.key<b.key?-1:a.key>b.key?1:0))){const result=r.run();if(result!=='failure')return result;}return 'failure';};
  engine.behaviorTree=new root.LWBehaviorTree(h);
  engine._plannerTree=C.clone(root.LWAdventure.content.behaviorTree);const children=engine._plannerTree.children;if(children){const at=children.findIndex(n=>n.type==='action'&&['outfit','quest','learning','plans'].includes(n.action));children.splice(at<0?Math.min(5,children.length):at,0,{id:'planner-priority',name:'Prioritized player plans',type:'action',action:'prioritized'});}
  engine.behaviorTree.validate(engine._plannerTree);
 }
 function initializePlanner(self){attach(self);}
 function defineLayer(Base){return class PlannerLayer extends Base{decide(){if(this.actor.activeQuest)return;const result=this.behaviorTree.tick(this._plannerTree,{time:this.s.simTime,behaviorMemory:this.actor.behavior.memory});this.actor.behavior.trace=result.trace;this.actor.behavior.lastAction=this.actor.task?.label||'Considering the next step';}};}
 function installFactories(){const scenarioNames=['createWorldDemo','createColonyDemo','createWorkshopDemo'],rawFactories=Object.fromEntries(scenarioNames.map(k=>[k,L[k]])),wrappedFactories={};
  // Existing authored fixtures compose the original factories. Canonicalize once after
  // their setup, so recruitment gates do not interfere with fixture construction.
  for(const name of scenarioNames)wrappedFactories[name]=()=>{let demo;try{Object.assign(L,rawFactories);demo=rawFactories[name]();}finally{Object.assign(L,wrappedFactories);}return Composition.constructThrough('planner',demo.export().state);};Object.assign(L,wrappedFactories);}
 Composition.register({id:'planner',order:50,define:defineLayer,initialize:initializePlanner,installFactories});
 root.LWPlanner={rows,act,add,types,taskOptions,availableTypes,control,paused,attach};if(typeof module!=='undefined'&&module.exports)module.exports=L;
})(typeof globalThis!=='undefined'?globalThis:this);
