/* Feature presentation: learning studio, construction atlas and production book.
 * All mutations call the simulation API. Rendering reads state, never moves Pip.
 */
(function(root){
'use strict';
root.LWProgressionUI={create(ctx){
 const {SKILLS,BUILDINGS,RES,RECIPES,DISCIPLINES,STYLES,APPROACHES,DRILLS,SPECIALIZATIONS,STUDIES,PATHS,CATEGORY_NAMES,CROP_RES}=LW;
 const {icon:ic,esc:e,head,footer,open,redraw,save,close,result}=ctx;
 const view={learn:'lessons',discipline:'all',status:'all',search:'',build:'blueprints',category:'all',buildSearch:'',qty:3,practiceCount:1,selectedSkill:null,lessonDetailOpen:false,buildStatus:'all',recipeSearch:'',recipeStatus:'all'};
 const eng=()=>ctx.engine(),st=()=>eng().s;
 const btn=(label,act,id='',cls='',disabled=false)=>`<button class="btn ${cls}" data-act="${act}" data-id="${id}" ${disabled?'disabled':''}>${label}</button>`;
 const tabs=(items,current,act)=>`<nav class="studio-tabs" aria-label="Panel sections">${items.map(([id,label])=>`<button data-act="${act}" data-id="${id}" class="${current===id?'active':''}" aria-pressed="${current===id}">${label}</button>`).join('')}</nav>`;
 const meter=(value,cls='')=>`<div class="meter ${cls}"><i style="width:${Math.max(0,Math.min(100,value))}%"></i></div>`;
 const costs=(cost,check=true)=>`<div class="material-pills">${Object.entries(cost).map(([r,n])=>`<span class="material-pill ${check&&st().inventory[r]<n?'shortfall':''}" title="${st().inventory[r]} in the shared pantry">${ic(RES[r].icon)}<b>${n}</b> ${e(RES[r].name)}</span>`).join('')||'<span class="muted micro">No extra materials for this step.</span>'}</div>`;
 const sketch=(kind,large=false)=>`<canvas class="building-sketch ${large?'large':''}" data-building-art="${kind}" width="240" height="170" aria-label="Pixel-art ${e(BUILDINGS[kind].name)}"></canvas>`;
 const stats=items=>`<div class="studio-stats">${items.map(([n,label,icon])=>`<div>${ic(icon)}<strong>${n}</strong><span>${label}</span></div>`).join('')}</div>`;
 const empty=(title,desc)=>`<div class="studio-empty">${ic('sprout')}<h3>${title}</h3><p>${desc}</p></div>`;
 const wrap=(title,desc,eyebrow,body,extra='')=>head(title,desc,eyebrow)+`<div class="modal-body studio-body">${body}</div>`+footer(extra);
 function issueAction(issue){if(!issue)return '';if(issue.practice)return btn('Practice '+e(SKILLS[issue.practice].short),'v3-practice-focus',issue.practice,'small');if(issue.skill)return btn('Explore '+e(SKILLS[issue.skill].short),'v3-skill',issue.skill,'small');if(issue.building)return btn('See '+e(BUILDINGS[issue.building].name),'v3-blueprint',issue.building,'small');return '';}
 function queue(){
  const s=st(),l=s.learning,all=[...(s.training?[s.training]:[]),...l.queue];
  return `<section class="learning-plan"><div class="section-heading"><div><span class="eyebrow">OUR LEARNING PLAN</span><h3>${all.length?all.length+' of 4 lessons · no rush':'A little room to learn'}</h3></div>${all.length?btn(ic(l.paused?'play':'pause')+(l.paused?'Resume lessons':'Pause lessons'),'v3-learning-pause','','small'):''}</div><div class="learning-queue">${all.map((t,j)=>{const p=t.progress/SKILLS[t.id].time;return `<article class="queue-lesson ${j===0?'current':''}"><span class="queue-number">${j+1}</span><div><strong>${e(SKILLS[t.id].short)}</strong><small>${j===0?(l.paused?'On hold':l.recovering?'Taking a mental break':eng().learningPhase(t).label):'Waiting · tuition paid'} · ${e(STYLES[t.style].name)}</small>${meter(p*100)}</div><button class="icon-btn" data-act="v3-cancel-lesson" data-id="${t.id}" aria-label="Review cancellation of ${e(SKILLS[t.id].short)}">${ic('close')}</button></article>`;}).join('')||'<p class="muted">Research a lesson, then buy its training. Pip chooses when to learn. Lesson supplies are included in the tuition.</p>'}</div><div class="learning-energy"><span>${ic('leaf')} Mental effort <b>${Math.round(l.fatigue)} / 100</b></span><span>${l.recovering?'Letting new ideas settle.':'Breaks are part of learning, not a penalty.'}</span></div>${meter(l.fatigue,'effort-meter')}</section>`;
 }

 function learning(){
  const s=st();
  return wrap('Learning studio','Choose a lesson. Make space for practice. Pip takes it from there.','LEARN & GROW',
   stats([[Object.keys(s.skills).length+'/'+Object.keys(SKILLS).length,'skills learned','book'],[Object.values(s.practice).reduce((a,b)=>a+b,0),'practice earned','star'],[s.rp,'research available','research'],[s.player.coins,'guide coins','coin']])+
   tabs([['lessons','Lessons'],['practice','Practice'],['trees','Skill trees'],['talents','Talents'],['studies','Field studies'],['paths','Learning paths']],view.learn,'v3-learn-tab')+
   (view.learn==='lessons'?lessonLibrary():view.learn==='practice'?practicePanel():view.learn==='trees'?globalThis.LWSkillTreeUI.render(eng().skillTreeState(eng().actor.id),eng().actor.name):view.learn==='talents'?talentsPanel():view.learn==='studies'?studiesPanel():pathsPanel()));
 }
 function filteredLessons(){
  const s=st();
  return Object.entries(SKILLS).filter(([id,k])=>
   (view.discipline==='all'||k.discipline===view.discipline)&&
   (view.status==='all'||view.status==='learned'&&s.skills[id]||view.status==='ready'&&!s.skills[id]&&!eng().lessonIssue(id)||view.status==='unlearned'&&!s.skills[id])&&
   `${k.name} ${k.short} ${k.desc} ${k.unlocks}`.toLowerCase().includes(view.search.trim().toLowerCase()));
 }
 function selectVisibleLesson(){
  const list=filteredLessons();
  if(!list.some(([id])=>id===view.selectedSkill))view.selectedSkill=list.find(([id])=>!st().skills[id]&&!eng().lessonIssue(id))?.[0]||list[0]?.[0]||null;
  return list;
 }

 function lessonLibrary(){
  selectVisibleLesson();
  return `<div class="lesson-workspace ${view.lessonDetailOpen?'show-detail':''}">
   <aside class="lesson-catalog" aria-label="Lesson catalog">
    <label class="studio-search">${ic('search')}<input id="studio-lesson-search" type="search" value="${e(view.search)}" placeholder="Search lessons or unlocks…" aria-label="Search lessons"></label>
    <div class="catalog-filters"><label>Discipline<select id="studio-lesson-discipline"><option value="all">All disciplines</option>${Object.entries(DISCIPLINES).map(([id,d])=>`<option value="${id}" ${view.discipline===id?'selected':''}>${e(d.name)}</option>`).join('')}</select></label><label>Availability<select id="studio-lesson-status">${[['all','All lessons'],['ready','Ready to learn'],['unlearned','Not learned'],['learned','Learned']].map(([id,n])=>`<option value="${id}" ${view.status===id?'selected':''}>${n}</option>`).join('')}</select></label></div>
    <div id="studio-lesson-list" class="lesson-results" data-scroll-key="lesson-results">${lessonList()}</div>
   </aside>
   <section class="lesson-inspector" id="lesson-inspector" data-scroll-key="lesson-detail" aria-label="Selected lesson">${lessonInspector()}</section>
  </div>`;
 }

 function lessonList(){
  const s=st(),list=selectVisibleLesson();
  if(!list.length)return empty('No matching lessons','Try another filter or clear the search.')+btn('Clear filters','v4-reset-lessons','','small');
  return `<p class="result-count" role="status">${list.length} of ${Object.keys(SKILLS).length} lessons</p>`+[1,2,3,4].map(tier=>{
   const group=list.filter(([,k])=>k.tier===tier);
   if(!group.length)return '';
   return `<div class="catalog-tier"><span>Tier ${tier}</span><span>Guide level ${tier}${s.player.level>=tier?' · open':''}</span></div>`+group.map(([id,k])=>{
    const queued=s.training?.id===id||s.learning.queue.some(t=>t.id===id);
    const learned=!!s.skills[id],issue=eng().lessonIssue(id);
    const label=learned?'Learned':queued?'Queued':issue?'Locked':s.researched[id]?'Researched':'Ready';
    return `<button class="lesson-row ${view.selectedSkill===id?'selected':''}" id="lesson-row-${id}" data-act="v4-select-lesson" data-id="${id}" aria-pressed="${view.selectedSkill===id}"><span class="catalog-icon">${ic(k.icon)}</span><span class="lesson-row-copy"><strong>${e(k.short)}</strong><small>${e(DISCIPLINES[k.discipline].name)}</small></span><span class="catalog-status ${learned?'learned':queued?'queued':issue?'locked':'ready'}">${label}</span></button>`;
   }).join('');
  }).join('');
 }
 function lessonInspector(){
  const id=view.selectedSkill,s=st();
  if(!id)return `<div class="detail-empty">${ic('book')}<h3>A little possibility will fit here.</h3><p>Choose a lesson from the catalog.</p></div>`;
  return `<button class="text-btn mobile-detail-back" data-act="v4-lesson-back">← All matching lessons</button>${lessonCard(id,SKILLS[id])}
   <details class="teaching-preferences" ${s.training||s.learning.queue.length?'':'open'}><summary>Teaching approach <span>${e(STYLES[s.learning.style].name)}</span></summary><div class="teaching-style"><label for="studio-learning-style">For the next purchased lesson</label><select id="studio-learning-style">${Object.entries(STYLES).map(([id,x])=>`<option value="${id}" ${s.learning.style===id?'selected':''}>${e(x.name)}</option>`).join('')}</select><small>${e(STYLES[s.learning.style].desc)}</small></div></details>${queue()}`;
 }

 function lessonCard(id,k){
  const s=st(),learned=!!s.skills[id],queued=s.training?.id===id||s.learning.queue.some(t=>t.id===id),researched=s.researched[id],m=eng().mastery(id),issue=eng().lessonIssue(id);let action;
  if(learned)action=`<div class="mastery-panel"><div><strong>${ic('star')}${m.label}</strong><span>+${m.bonus}% work speed</span></div>${meter(m.next?m.points/m.next*100:100)}<small>${m.points} practice${m.next?' · '+m.next+' for next rank':' · fully fluent'}</small></div>`+btn('Explore practice','v3-practice-focus',id,'primary');
  else if(queued)action='<div class="notice-box">'+ic('book')+' <strong>Purchased and in the learning plan.</strong><br>Pip studies when their needs are met. Return to the glade to let time pass.</div>';
  else if(issue)action=`<div class="lesson-blocker">${ic('book')}<span>${e(issue.text)}</span></div>${issueAction(issue)}`;
  else if(!researched)action=btn(ic('research')+'Research · '+k.rp+' points','v3-research',id,'primary',s.rp<k.rp)+(s.rp<k.rp?`<p class="action-reason">Need ${k.rp-s.rp} more shared research. Curiosity and useful work earn research.</p>`:'<p class="action-reason">Research unlocks the lesson. Tuition is a separate purchase.</p>');
  else {const full=s.learning.queue.length+(s.training?1:0)>=4;action=btn(ic('coin')+'Buy training · '+k.coins+' coins','v3-teach',id,'primary',s.player.coins<k.coins||full)+`<p class="action-reason">${full?'Your learning plan is full. Finish or cancel a lesson first.':s.player.coins<k.coins?'Need '+(k.coins-s.player.coins)+' more guide coins.':'Adds the lesson to your plan. Training supplies are included.'}</p>`;}
  return `<article class="studio-lesson lesson-detail ${learned?'learned':''}" id="skill-${id}"><div class="lesson-meta"><span>${ic(DISCIPLINES[k.discipline].icon)}${e(DISCIPLINES[k.discipline].name)}</span><span>Tier ${k.tier} · ${learned?'Learned':queued?'In progress':researched?'Researched':'Not learned'}</span></div><h3 tabindex="-1">${e(k.name)}</h3><p class="detail-description">${e(k.desc)}</p><div class="lesson-unlocks">${ic('sprout')}<div><span class="eyebrow">WHAT THIS MAKES POSSIBLE</span><p>${e(k.unlocks)}</p></div></div><div class="lesson-steps" aria-label="Learning stages"><span class="${researched||learned?'done':''}">${researched||learned?'✓':'1'} Research <b>${k.rp} RP</b></span><span class="${queued||learned?'done':''}">${queued||learned?'✓':'2'} Tuition <b>${k.coins} coins</b></span><span class="${learned?'done':''}">${learned?'✓':'3'} Pip learns <b>${k.time}s base</b></span></div>${k.requires.length?`<div class="prerequisite-links"><span>Builds on</span>${k.requires.map(r=>`<button data-act="v3-skill" data-id="${r}" class="${s.skills[r]?'done':''}">${s.skills[r]?'✓ ':''}${e(SKILLS[r].short)}</button>`).join('')}</div>`:''}<div class="lesson-action">${action}</div></article>`;
 }
 function practicePanel(focus=null){
  const s=st(),learned=Object.keys(SKILLS).filter(id=>s.skills[id]);
  return `<details class="inline-help"><summary>How practice works</summary><p><strong>Useful practice, not a progress button.</strong> Pip visits a suitable place, works for 12 base seconds, and uses real supplies. The first two drills per skill each day earn 4 practice; later repeats earn 2. A learning circle and a mentor talent add more. The first drill per skill per day also earns 1 shared research.</p></details><div class="section-heading"><h3>A little deliberate practice</h3><label class="micro">Sessions <select id="studio-practice-count" aria-label="Practice sessions">${[1,2,3].map(n=>`<option value="${n}" ${view.practiceCount===n?'selected':''}>${n}</option>`).join('')}</select></label></div><div class="practice-grid">${learned.map(id=>{const k=SKILLS[id],d=DRILLS[id],m=eng().mastery(id),pending=s.orders.some(o=>o.type==='practice'&&o.skillId===id);return `<article class="practice-card ${focus===id?'focused':''}" id="practice-${id}"><div class="section-heading"><h4>${ic(k.icon)}${e(k.short)}</h4><span class="tiny-tag">${m.label}</span></div>${meter(m.next?m.points/m.next*100:100)}<p>${m.points} practice · ${m.next?m.next+' for next rank':'Fluent'} · +${m.bonus}% work speed</p>${costs(d.cost)}<small>${d.station?'At the '+e(BUILDINGS[d.station].name.toLowerCase())+(eng().has(d.station)?'':' · not built yet'):'In the clearing, or at our learning circle'}</small>${btn(pending?'Practice already planned':'Suggest '+view.practiceCount+' '+(view.practiceCount===1?'session':'sessions'),'v3-practice',id,'small',pending)}</article>`;}).join('')||empty('The first lesson comes first.','Research and teach a skill to discover its practice exercise.')}</div>`;
 }
 function talentsPanel(){const s=st();return `<div class="studio-section-title"><span class="eyebrow">A PERSONAL WAY TO GROW</span><h3>Talents, not just bigger numbers.</h3><p>Learn two skills in a discipline and earn 12 total practice points to choose one specialty. A first choice costs 4 research + 18 coins. Changing it costs 2 research; only one talent per discipline is active.</p></div><div class="talent-grid">${Object.entries(DISCIPLINES).map(([id,d])=>{const p=eng().disciplineProgress(id),selected=s.specializations[id],eligible=p.learned>=2&&p.practice>=12;return `<article class="talent-card"><h4>${ic(d.icon)}${e(d.name)}</h4><p>${p.learned}/2 learned · ${p.practice}/12 practice ${eligible?'· ready':'· keep growing'}</p><div class="talent-options">${SPECIALIZATIONS[id].map(t=>`<button class="talent-option ${selected===t.id?'selected':''}" data-act="v3-talent" data-id="${t.id}" data-discipline="${id}" ${!eligible||selected===t.id?'disabled':''}><strong>${selected===t.id?'✓ ':''}${e(t.name)}</strong><span>${e(t.desc)}</span><small>${selected===t.id?'Active specialty':selected?'Change · 2 research':'Choose · 4 research + 18 coins'}</small></button>`).join('')}</div></article>`;}).join('')}</div>`;
 }
 function studiesPanel(){
  const s=st(),f=s.fieldStudies;return `<div class="notice-box">${ic('research')}<strong>Questions answered by actually living.</strong> Choose one study, then collect evidence through normal play. New gathering, making and practice count while active. Existing structures also satisfy construction milestones. Pausing keeps its evidence. Each study pays its research and coin reward once.</div><div class="study-grid">${Object.entries(STUDIES).map(([id,d])=>{const done=f.completed.includes(id),active=f.active===id,pr=f.progress[id]||{},locked=d.requires&&!s.skills[d.requires];return `<article class="study-card ${active?'active':''} ${done?'done':''}"><div class="lesson-meta"><span>${ic(DISCIPLINES[d.discipline].icon)}${e(DISCIPLINES[d.discipline].name)}</span><span>${done?'DISCOVERED':active?'OBSERVING':'FIELD STUDY'}</span></div><h3>${e(d.name)}</h3><p>${e(d.desc)}</p><div class="evidence-list">${d.goals.map(g=>{const n=Math.min(g.amount,pr[g.event]||0);return `<div><span class="evidence-check ${n>=g.amount?'done':''}">${n>=g.amount?'✓':'·'}</span><span>${g.label}</span><strong>${n}/${g.amount}</strong></div>`;}).join('')}</div><div class="study-reward">${ic('research')} ${d.reward.rp} shared research ${ic('coin')} ${d.reward.coins} guide coins</div>${done?'<span class="lesson-tag">A discovery to keep.</span>':active?btn('Put this question aside','v3-study-pause','','small'):locked?btn('First learn '+SKILLS[d.requires].short,'v3-skill',d.requires,'small'):btn(f.active?'Another study is active':'Start observing','v3-study',id,'primary',!!f.active)}</article>`;}).join('')}</div>`;
 }
 function pathsPanel(){
  const s=st();return `<div class="notice-box">A learning path is a direction to grow, not an automatic shopping list. Each lesson shows its real prerequisites. No coins are spent and no plans are placed until you choose them.</div><div class="path-grid">${Object.entries(PATHS).map(([id,p])=>`<article class="path-card ${s.learning.path===id?'pinned':''}"><div class="section-heading"><h3>${e(p.name)}</h3>${btn(s.learning.path===id?'Following':'Follow this path','v3-path',id,'small',s.learning.path===id)}</div><p>${e(p.desc)}</p><div class="path-steps">${p.skills.map(sk=>`<button data-act="v3-skill" data-id="${sk}" class="${s.skills[sk]?'complete':''}"><span>${s.skills[sk]?'✓':SKILLS[sk].tier}</span><div><strong>${e(SKILLS[sk].short)}</strong><small>${s.skills[sk]?'Learned':eng().lessonIssue(sk)?.text||'Ready to explore'}</small></div>${ic('arrow')}</button>`).join('')}</div><div class="path-places">${p.buildings.map(b=>`<button data-act="v3-blueprint" data-id="${b}">${ic(BUILDINGS[b].icon)}${e(BUILDINGS[b].name)}${eng().has(b)?' ✓':''}</button>`).join('')}</div></article>`).join('')}</div>`;
 }

 function construction(){
  const s=st();return wrap('Construction atlas','Find a place, inspect its supply chain, then leave the building to Pip.','PLAN & BUILD',
   stats([[s.buildings.length+'/'+Object.keys(BUILDINGS).length,'places made','home'],[s.orders.filter(o=>['build','upgrade'].includes(o.type)).length,'building projects','plan'],[s.metrics.upgrades,'improvements','star'],[Object.keys(RECIPES).length,'recipes','bench']])+
   tabs([['blueprints','Blueprints'],['settlement','Our settlement'],['recipes','Production book'],['projects','Project board']],view.build,'v3-build-tab')+
   (view.build==='blueprints'?blueprintLibrary():view.build==='settlement'?settlement():view.build==='recipes'?recipes():projectBoard()));
 }
 function approaches(){return `<div class="approach-picker" role="group" aria-label="Construction approach">${Object.entries(APPROACHES).map(([id,a])=>`<button data-act="v3-approach" data-id="${id}" class="${st().buildPolicy.approach===id?'selected':''}" aria-pressed="${st().buildPolicy.approach===id}"><strong>${ic(id==='careful'?'heart':id==='quick'?'energy':'paw')}${e(a.name)}</strong><span>${e(a.desc)}</span></button>`).join('')}</div><p class="micro muted">Applies to the next blueprint or upgrade you plan. Existing projects keep their original approach.</p>`;}

 function blueprintLibrary(){
  return `<div class="atlas-toolbar"><label class="studio-search">${ic('search')}<input id="studio-build-search" type="search" placeholder="Search places or benefits…" value="${e(view.buildSearch)}" aria-label="Search blueprints"></label><label class="compact-filter">Show<select id="studio-build-status">${[['all','All blueprints'],['ready','Ready to plan'],['not-built','Not built'],['planned','Planned'],['built','Built']].map(([id,n])=>`<option value="${id}" ${view.buildStatus===id?'selected':''}>${n}</option>`).join('')}</select></label></div><div class="atlas-categories">${Object.entries(CATEGORY_NAMES).map(([id,name])=>`<button class="chip ${view.category===id?'active':''}" data-act="v3-category" data-id="${id}" aria-pressed="${view.category===id}">${name}</button>`).join('')}</div><div id="studio-blueprint-list">${blueprintList()}</div>`;
 }
 function landEffect(id,fallback){const p=window.LWWorldContent?.building(id);return p?.production?'Creatures supply and tend this place. Finished '+RES[p.production.output].name.toLowerCase()+' wait here for collection.':p?.requiresNode?'Requires '+window.LWWorldContent.node(p.requiresNode).name.toLowerCase()+' on its exact tile.':fallback;}
 function blueprintList(){const s=st(),list=Object.entries(BUILDINGS).filter(([id])=>eng().unlocked('buildings',id)).filter(([id,b])=>{const built=s.buildings.some(x=>x.kind===id),planned=s.orders.some(o=>o.type==='build'&&o.kind===id);return (view.buildStatus==='all'||view.buildStatus==='ready'&&!built&&!planned&&s.skills[b.skill]||view.buildStatus==='not-built'&&!built||view.buildStatus==='built'&&built||view.buildStatus==='planned'&&planned)&&(view.category==='all'||b.category===view.category)&&(`${b.name} ${b.effect} ${b.desc}`.toLowerCase().includes(view.buildSearch.toLowerCase()));});return `<p class="result-count" role="status">${list.length} of ${Object.keys(BUILDINGS).length} blueprints · approach and materials in each detail</p><div class="blueprint-grid">${list.map(([id,b])=>{const built=s.buildings.find(x=>x.kind===id),planned=s.orders.find(o=>o.type==='build'&&o.kind===id),known=s.skills[b.skill];return `<article class="atlas-blueprint ${built?'built':''}"><button class="blueprint-art" data-act="v3-blueprint" data-id="${id}" aria-label="Inspect ${e(b.name)}">${sketch(id)}<span class="art-category">${CATEGORY_NAMES[b.category]}</span><span class="art-status ${built?'built':known?'ready':''}">${built?'LEVEL '+built.level:planned?'PLANNED':known?'READY TO PLAN':'NEEDS TRAINING'}</span></button><div class="atlas-blueprint-body"><h3>${e(b.name)}</h3><p>${e(landEffect(id,b.effect))}</p>${costs(b.cost,false)}<div class="blueprint-next"><span>${built?eng().qualityName(built.quality):known?'Three little stages':'Needs '+e(SKILLS[b.skill].short)}</span>${btn(built?'Inspect':planned?'See plan':'Explore','v3-blueprint',id,'small')}</div></div></article>`;}).join('')}</div>${list.length?'':empty('No places match.','Try a different category or search.')}`;}
 function blueprintDetail(id){
  const b=BUILDINGS[id];if(!b)return wrap('Unknown blueprint.','','BLUEPRINT','');const s=st(),built=s.buildings.find(x=>x.kind===id),planned=s.orders.find(o=>o.type==='build'&&o.kind===id);
  const o={type:'build',kind:id,stage:0,progress:0,paid:false,approach:s.buildPolicy.approach},f=eng().materialForecast(o);
  return wrap(e(b.name),b.desc,'BLUEPRINT · '+CATEGORY_NAMES[b.category],`<div class="blueprint-detail-hero"><div class="large-sketch">${sketch(id,true)}</div><div><span class="eyebrow">WHAT THIS PLACE BRINGS</span><h3>${e(landEffect(id,b.effect))}</h3><p>${window.LWWorldContent?.building(id)?.requiresNode?'Site requirement: '+e(window.LWWorldContent.node(window.LWWorldContent.building(id).requiresNode).name.toLowerCase())+' on this exact tile. Suitable sites are highlighted while placing.':'Choose clear ground. Leave an open approach for creatures and their deliveries.'}</p><div class="blueprint-facts"><span>${ic('book')}${e(SKILLS[b.skill].short)}</span><span>${ic('clock')}${Math.round(eng().constructionPhases(o).reduce((a,p)=>a+p.time,0))}s base work</span><span>${ic('star')}Expected quality ${eng().buildQuality(o)}</span></div>${built?btn('Inspect our level '+built.level+' '+b.name.toLowerCase(),'v3-building',built.id,'primary'):planned?btn('See our construction plan','order',planned.id,'primary'):btn(ic('plus')+'Place this blueprint','blueprint',id,'primary')}<small class="micro">${built?'Our place remains usable while being upgraded.':planned?'Already on the plan board.':'Placing is free. Learning and materials may come later.'}</small></div></div>${!built&&!planned?approaches():''}<div class="section-heading"><h3>Three stages, one shared idea.</h3><span class="tiny-tag">${e(APPROACHES[o.approach].name)}</span></div>${phases(o)}${forecast(f)}<div class="modal-actions">${btn('Back to the atlas','v3-construction')}${btn('Explore '+SKILLS[b.skill].short,'v3-skill',b.skill)}</div>`);
 }
 function phases(o){const ps=eng().constructionPhases(o);return `<div class="construction-phases">${ps.map((p,i)=>{const done=i<o.stage,current=i===o.stage;return `<article class="construction-phase ${done?'complete':current?'current':''}"><span class="phase-index">${done?'✓':i+1}</span><h4>${e(p.name)}</h4><small>${done?'Installed':current&&o.paid?'Supplies reserved':Math.round(p.time)+' base work seconds'}</small>${costs(p.cost,!done&&!(current&&o.paid))}${current&&o.progress?meter(o.progress/p.time*100):''}</article>`;}).join('')}</div>`;}
 function forecast(f){return `<section class="studio-forecast"><div class="section-heading"><div><span class="eyebrow">FROM THE WORLD TO OUR PAWS</span><h3>Materials & the making chain</h3></div>${ic('planks')}</div><p class="muted micro">Forecast includes intermediate ingredients, uses shared stock once, and rounds crafting up to whole batches. Food, water and other plans may also use these supplies.</p>${f.rows.length?`<div class="forecast-table"><div class="forecast-table-head"><span>Material</span><span>Needed</span><span>From pantry</span><span>Still to find</span></div>${f.rows.map(r=>`<div><button data-act="${RECIPES[r.resource]?'v3-recipe':'pantry'}" data-id="${r.resource}">${ic(RES[r.resource].icon)}${e(RES[r.resource].name)}</button><span>${r.needed}</span><span>${r.used}</span><strong class="${r.missing?'shortfall':''}">${r.missing||'—'}</strong></div>`).join('')}</div>`:'<p>All paid stages have their materials reserved.</p>'}${f.steps.length?`<div class="chain-strip">${f.steps.slice(0,16).map(x=>`<span>${ic(x.kind==='craft'?'bench':'leaf')}${x.kind==='craft'?'Make':'Find'} ${x.amount} ${e(RES[x.resource].name.toLowerCase())}${x.station?' · '+BUILDINGS[x.station].name:''}</span>`).join('<i>→</i>')}</div>`:''}${f.issues.length?`<div class="forecast-blockers">${f.issues.map(x=>`<div><span>${ic('book')}${e(x.text)}</span>${issueAction(x)}</div>`).join('')}</div>`:'<p class="forecast-ready">'+ic('check')+' Pip knows the skills and has the places this plan needs.</p>'}</section>`;}
 function settlement(){const s=st();return `<div class="notice-box"><strong>Improve what we already made.</strong> Each place supports three levels. Level 2 asks for 8 practice in its original skill; level 3 also needs an advanced skill. Buildings stay usable during upgrades. Workstations benefit from quality, level and nearby support.</div><div class="settlement-grid">${s.buildings.map(b=>`<article class="settlement-card"><div class="settlement-art">${sketch(b.kind)}</div><div><span class="eyebrow">LEVEL ${b.level} OF 3 · ${eng().qualityName(b.quality).toUpperCase()}</span><h3>${e(BUILDINGS[b.kind].name)}</h3><p>${e(landEffect(b.kind,BUILDINGS[b.kind].effect))}</p><div class="service-tags"><span>${ic('star')}${b.quality} quality</span>${Object.values(RECIPES).some(r=>r.station===b.kind)?'<span>'+ic('energy')+'+'+Math.round(eng().stationBonus(b.kind)*100)+'% station speed</span>':''}</div>${btn('Inspect & improve','v3-building',b.id,'small')}</div></article>`).join('')||empty('The clearing is full of possibilities.','Explore the blueprints to imagine a first place.')}</div>`;}
 function buildingDetail(id){const s=st(),b=s.buildings.find(b=>b.id===id);if(!b)return wrap('That place is not here.','','OUR SETTLEMENT','');const def=BUILDINGS[b.kind],upgrade=s.orders.find(o=>o.type==='upgrade'&&o.kind===b.kind),next={type:'upgrade',kind:b.kind,targetLevel:b.level+1,stage:0,progress:0,paid:false,approach:s.buildPolicy.approach};const recipes=Object.entries(RECIPES).filter(([id])=>eng().unlocked('recipes',id)).filter(([r,x])=>x.station===b.kind);const issue=b.level<3?eng().orderIssue(next):null;
 return wrap(def.name,def.desc,'OUR SETTLEMENT · LEVEL '+b.level,`<div class="blueprint-detail-hero"><div class="large-sketch">${sketch(b.kind,true)}</div><div><span class="eyebrow">${eng().qualityName(b.quality).toUpperCase()} · ${b.quality} QUALITY</span><h3>${e(landEffect(b.kind,def.effect))}</h3><p>${b.level>1?eng().upgradeEffect(b,b.level):'A first version, made by our own paws. There is room to grow.'}</p>${recipes.length?`<span class="service-pill">${ic('energy')}+${Math.round(eng().stationBonus(b.kind)*100)}% station speed from level, quality and proximity</span>`:''}${b.storage?`<p>Building inventory: ${Object.values(b.storage.input).reduce((a,n)=>a+n,0)} input · ${Object.values(b.storage.output).reduce((a,n)=>a+n,0)} output. No automatic regeneration.</p><button class="btn" data-act="land-show-building" data-id="${b.id}">Inspect inputs & production ↗</button>`:''}</div></div><div class="building-levels">${[1,2,3].map(l=>`<div class="${b.level>=l?'complete':''}"><strong>${b.level>=l?'✓':'○'} Level ${l}</strong><span>${l===1?'A place of our own':eng().upgradeEffect(b,l)}</span></div>`).join('')}</div>${upgrade?`<div class="notice-box">An improvement is already planned. The building remains usable.</div>${btn('View improvement project','order',upgrade.id,'primary')}`:b.level<3?`<div class="upgrade-preview"><div class="section-heading"><h3>The next little improvement</h3><span class="tiny-tag">LEVEL ${b.level+1}</span></div><p>${eng().upgradeEffect(b)}</p>${approaches()}${costs(eng().totalCost(next))}<p class="micro">Needs ${e(SKILLS[eng().constructionSkill(next)].short)} and 8 practice in ${e(SKILLS[def.skill].short)}. Three construction stages; no upkeep timer.</p>${issue?`<div class="notice-box">${e(issue.text)} ${issueAction(issue)}</div>`:''}${btn(ic('plus')+'Plan this improvement','v3-upgrade',id,'primary')}</div>`:'<div class="notice-box">'+ic('star')+' Fully improved. A little place we can be proud of.</div>'}${recipes.length?`<div class="section-heading" style="margin-top:22px"><h3>What we can make here</h3></div><div class="station-recipes">${recipes.map(([r,x])=>btn(ic(RES[r].icon)+RES[r].name,'v3-recipe',r)).join('')}</div>`:''}<div class="modal-actions">${btn('Our settlement','v3-settlement')}${b.kind==='market'?btn('Visit the market','market','','primary'):''}</div>`);
 }

 function recipes(){return `<div class="atlas-toolbar"><label class="studio-search">${ic('search')}<input id="studio-recipe-search" type="search" value="${e(view.recipeSearch)}" placeholder="Find an item, ingredient or station…" aria-label="Search recipes"></label><label class="compact-filter">Show<select id="studio-recipe-status"><option value="all" ${view.recipeStatus==='all'?'selected':''}>All recipes</option><option value="ready" ${view.recipeStatus==='ready'?'selected':''}>Ready to make</option></select></label></div><p class="catalog-note">Suggestions create work, not instant items. Pip gathers ingredients and uses the required station.</p><div id="studio-recipe-list">${recipeList()}</div>`;}
 function recipeList(){
  const list=Object.entries(RECIPES).filter(([id])=>eng().unlocked('recipes',id)).filter(([id,r])=>(view.recipeStatus==='all'||!eng().orderIssue({type:'craft',resource:id,amount:r.amount,done:0}))&&[RES[id].name,BUILDINGS[r.station].name,...Object.keys(r.cost).map(x=>RES[x].name)].join(' ').toLowerCase().includes(view.recipeSearch.trim().toLowerCase()));
  return `<p class="result-count" role="status">${list.length} of ${Object.keys(RECIPES).length} recipes</p><div class="recipe-grid">${list.map(([id,r])=>{const issue=eng().orderIssue({type:'craft',resource:id,amount:r.amount,done:0}),ready=!issue;return `<article class="recipe-card"><span class="recipe-icon">${ic(RES[id].icon)}</span><div class="recipe-heading"><h3>${e(RES[id].name)}</h3><span>${r.amount} per batch · ${r.time}s base work</span></div>${costs(r.cost)}<div class="recipe-station">${ic('bench')}${e(BUILDINGS[r.station].name)}<span class="${ready?'ready-note':'locked-note'}">${ready?'Ready to make':e(issue.text)}</span></div>${btn('Inspect recipe','v3-recipe',id,'small')}</article>`;}).join('')}</div>${list.length?'':empty('No matching recipes','Try another search or show all recipes.')}`;
 }
 function recipeDetail(id){const r=RECIPES[id];if(!r)return wrap('Unknown recipe.','','PRODUCTION BOOK','');const f=eng().recipeForecast(id,view.qty),s=st(),pending=s.orders.some(o=>o.type==='craft'&&o.resource===id);return wrap(e(RES[id].name),'A useful little transformation, one batch at a time.','PRODUCTION BOOK',`<div class="recipe-equation">${costs(r.cost,false)}<span class="equation-arrow">→</span><span class="recipe-output">${ic(RES[id].icon)}<b>${r.amount}</b> ${e(RES[id].name)}</span></div><div class="recipe-detail-facts"><span>${ic('book')}${e(SKILLS[r.skill].short)}</span><span>${ic('bench')}${e(BUILDINGS[r.station].name)}</span><span>${ic('clock')}${r.time}s base work</span></div><div class="quantity-toolbar"><label for="studio-recipe-qty">At least this many</label><select id="studio-recipe-qty">${[1,3,6,12,24].map(n=>`<option value="${n}" ${view.qty===n?'selected':''}>${n}</option>`).join('')}</select><small>Plans ${Math.ceil(view.qty/r.amount)*r.amount} units in ${Math.ceil(view.qty/r.amount)} whole batches. Talents can add a little extra.</small></div><div class="modal-actions">${btn(pending?'Already on the plan board':ic('plus')+'Suggest making '+Math.ceil(view.qty/r.amount)*r.amount,'v3-craft',id,'primary',pending)}${btn('Keep '+view.qty+' in reserve','v3-reserve',id)}${btn('Inspect the station','v3-blueprint',r.station)}</div>${forecast(f)}<p class="micro muted">Deliberate drills use supplies but do not output products. Crafting a recipe outputs items and awards normal skill practice.</p>`);}
 function projectBoard(){const s=st();return `<div class="project-board-grid">${s.orders.map(o=>{const status=eng().planStatus(o),construction=['build','upgrade'].includes(o.type),p=eng().projectProgress(o);return `<article class="project-card"><div class="section-heading"><span class="status-tag ${status.kind}">${status.label}</span>${o.priority?'<span class="tiny-tag">Priority</span>':''}</div><h3>${e(eng().orderName(o))}</h3><p>${e(status.detail)}</p>${construction?`<div class="mini-stages">${eng().constructionPhases(o).map((x,i)=>`<span class="${i<o.stage?'complete':i===o.stage?'current':''}">${i<o.stage?'✓':i+1}</span>`).join('')}</div>`:''}${meter(p*100)}<div class="project-card-bottom"><span>${Math.round(p*100)}% ${construction?'overall':o.done+'/'+o.amount}</span>${btn('Next steps','order',o.id,'small')}</div></article>`;}).join('')||empty('Room for a little idea.','Place a blueprint, improve a building, or suggest a practice session.')}</div><div class="modal-actions">${btn('Explore blueprints','v3-construction','','primary')}${btn('Suggest a recipe','v3-recipes')}${btn('Explore lessons','v3-learn')}${btn('Other ideas','suggest')}</div>${s.orders.length?forecast(eng().materialForecast()):''}`;}
 function projectDetail(id){const o=st().orders.find(o=>o.id===id);if(!o)return wrap('That idea is already complete.','','OUR PLAN','');const issue=eng().orderIssue(o),construction=['build','upgrade'].includes(o.type);return wrap(e(eng().orderName(o)),'A shared intention, with room for Pip to be Pip.','OUR PLAN · '+(construction?'CONSTRUCTION':'PRACTICE'),`<div class="project-summary"><div><span class="eyebrow">${construction?APPROACHES[o.approach||'balanced'].name:'A USEFUL EXERCISE'}</span><h3>${Math.round(eng().projectProgress(o)*100)}% ${construction?'of our place made':o.done+' of '+o.amount+' sessions'}</h3></div><span class="status-tag ${eng().planStatus(o).kind}">${eng().planStatus(o).label}</span></div>${meter(eng().projectProgress(o)*100)}${construction?phases(o):`<p>Uses these supplies per completed drill. Interrupted work keeps its progress.</p>${costs(DRILLS[o.skillId].cost)}`}<div class="notice-box">${issue?e(issue.text):'Ready when Pip is. Care comes first; materials and walking add time beyond the base work estimate.'} ${issueAction(issue)}</div>${forecast(eng().materialForecast(o))}<div class="modal-actions">${btn(o.priority?'Prioritized':'Make this our next idea','prioritize',id,'small')}${btn(o.paused?'Resume':'Put on hold','hold',id,'small')}${btn('Set aside','cancel-order',id,'small danger')}${btn('Project board','v3-projects','','small')}</div>${construction?'<p class="micro muted">Cancelling returns 100% of reserved current-stage supplies and 50% of installed earlier-stage supplies, rounded down per material. A building being upgraded stays at its previous level.</p>':''}`);}
 function render(type,id){
  if(type==='training'){document.getElementById('modal').classList.add('studio-modal');if(view.learn==='lessons')document.getElementById('modal').classList.add('lesson-layout-modal');return learning();}
  if(type==='construction'||type==='production-catalog'){document.getElementById('modal').classList.add('studio-modal');return construction();}
  if(type==='blueprint-detail')return blueprintDetail(id);
  if(type==='building')return buildingDetail(id);
  if(type==='recipe')return recipeDetail(id);
  if(type==='plans')return wrap('Big ideas. Little steps.','Pip finds the next useful step, even when one plan is waiting for a new skill.','OUR PROJECT BOARD',projectBoard());
  if(type==='order'&&['build','upgrade','practice'].includes(st().orders.find(o=>o.id===id)?.type))return projectDetail(id);
  if(type==='lesson-cancel'){const t=st().training?.id===id?st().training:st().learning.queue.find(t=>t.id===id);return wrap('Set this lesson aside?','There is no need to rush a new skill.','OUR LEARNING PLAN',t?`<h3>${e(SKILLS[t.id].short)}</h3><p>${t.progress===0?'Teaching has not begun. All '+t.tuition+' guide coins will be refunded.':'Teaching has already begun. Tuition is not refunded; lesson progress will be set aside.'}</p><div class="modal-actions">${btn('Cancel lesson','v3-confirm-lesson-cancel',id,'danger')}${btn('Keep our learning plan','v3-learn')}</div>`:'<p>This lesson is no longer queued.</p>');}
  return null;
 }

 function focusSkill(id){if(!SKILLS[id])return;view.learn='lessons';view.search='';view.discipline='all';view.status='all';view.selectedSkill=id;view.lessonDetailOpen=true;open('training',id);}
 function action(act,id,element){
  const engine=eng(),s=st();let r;let handled=true;
  if(act==='v4-select-lesson'){view.lessonListScroll=document.querySelector('#modal .modal-body')?.scrollTop||0;view.selectedSkill=id;view.lessonDetailOpen=true;redraw();requestAnimationFrame(()=>{const inspector=document.getElementById('lesson-inspector');if(inspector)inspector.scrollTop=0;if(innerWidth<=720)document.querySelector('#modal .modal-body').scrollTop=0;document.getElementById('skill-'+id)?.querySelector('h3')?.focus({preventScroll:true});});}
  else if(act==='v4-lesson-back'){view.lessonDetailOpen=false;redraw();document.querySelector('#modal .modal-body').scrollTop=view.lessonListScroll||0;document.getElementById('lesson-row-'+view.selectedSkill)?.focus({preventScroll:true});}
  else if(act==='v4-reset-lessons'){view.search='';view.status='all';view.discipline='all';redraw();}
  else if(act==='v3-learn'){view.learn='lessons';open('training');}
  else if(act==='v3-paths'){view.learn='paths';open('training');}
  else if(act==='v3-studies'){view.learn='studies';open('training');}
  else if(act==='v3-learn-tab'){view.learn=id;redraw();}
  else if(act==='v3-discipline'){view.discipline=id;redraw();}
  else if(act==='v3-research'){r=engine.research(id);result(r);redraw();}
  else if(act==='v3-teach'){r=engine.teach(id);result(r,r.ok?'Lesson purchased. Return to the glade for Pip to learn.':null);redraw();}
  else if(act==='v3-skill')focusSkill(id);
  else if(act==='v3-learning-pause'){result(engine.pauseLearning());redraw();}
  else if(act==='v3-cancel-lesson')open('lesson-cancel',id);
  else if(act==='v3-confirm-lesson-cancel'){result(engine.cancelLesson(id));open('training');}
  else if(act==='v3-practice-focus'){view.learn='practice';open('training');requestAnimationFrame(()=>{const el=document.getElementById('practice-'+id);el?.classList.add('focused');el?.scrollIntoView({block:'center'});});}
  else if(act==='v3-practice'){r=engine.practice(id,view.practiceCount);result(r,r.ok?'Practice added to the plan board. Supplies are used when each session finishes.':null);redraw();}
  else if(act==='skill-tree-unlock'){const treeId=element.dataset.tree;r=engine.dispatchCommand({id:'unlock-skill-tree-node',args:[engine.actor.id,treeId,id]});result(r,r.ok?'A new skill-tree rank is active.':null);redraw();requestAnimationFrame(()=>[...document.querySelectorAll<HTMLElement>('.skill-tree-node')].find(node=>node.dataset.skillTree===treeId&&node.dataset.skillNode===id)?.focus());}
  else if(act==='v3-talent'){r=engine.chooseSpecialization(element.dataset.discipline,id);result(r,r.ok?'A new way to grow. The selected bonus is active.':null);redraw();}
  else if(act==='v3-study'){result(engine.startStudy(id),'A question to explore. New actions count now; existing structures satisfy construction milestones.');redraw();}
  else if(act==='v3-study-pause'){result(engine.pauseStudy());redraw();}
  else if(act==='v3-path'){s.learning.path=id;save();redraw();}
  else if(act==='v3-construction'){view.build='blueprints';open('construction');}
  else if(act==='v3-recipes'){view.build='recipes';open('production-catalog');}
  else if(act==='v3-settlement'){view.build='settlement';open('production-catalog');}
  else if(act==='v3-projects'){view.build='projects';open('production-catalog');}
  else if(act==='v3-build-tab'){view.build=id;if(id==='blueprints')open('construction');else redraw();}
  else if(act==='v3-category'){view.category=id;redraw();}
  else if(act==='v3-approach'){if(APPROACHES[id])s.buildPolicy.approach=id;save();redraw();}
  else if(act==='v3-blueprint')open('blueprint-detail',id);
  else if(act==='v3-building')open('building',id);
  else if(act==='v3-recipe')open('recipe',id);
  else if(act==='v3-craft'){r=engine.request('craft',id,view.qty);result(r,'A making idea is on the board. Pip will find what it needs.');if(r.ok)close();}
  else if(act==='v3-reserve'){result(engine.setStockTarget(id,view.qty),'Pantry reserve set. Pip stocks it after more important work.');redraw();}
  else if(act==='v3-upgrade'){r=engine.upgrade(id);result(r);if(r.ok)open('order',r.order.id);}
  else handled=false;
  return handled;
 }
 function change(el){
  if(el.id==='studio-learning-style'){result(eng().setLearningStyle(el.value));redraw();return true;}
  if(el.id==='studio-lesson-discipline'){view.discipline=el.value;view.lessonDetailOpen=false;redraw();return true;}
  if(el.id==='studio-build-status'){view.buildStatus=el.value;redraw();return true;}
  if(el.id==='studio-recipe-status'){view.recipeStatus=el.value;redraw();return true;}
  if(el.id==='studio-lesson-status'){view.status=el.value;redraw();return true;}
  if(el.id==='studio-practice-count'){view.practiceCount=Number(el.value);redraw();return true;}
  if(el.id==='studio-recipe-qty'){view.qty=Number(el.value);redraw();return true;}
  return false;
 }

 function input(el){
  if(el.id==='studio-lesson-search'){view.search=el.value;view.lessonDetailOpen=false;document.querySelector('.lesson-workspace')?.classList.remove('show-detail');document.getElementById('studio-lesson-list').innerHTML=lessonList();document.getElementById('lesson-inspector').innerHTML=lessonInspector();return true;}
  if(el.id==='studio-build-search'){view.buildSearch=el.value;document.getElementById('studio-blueprint-list').innerHTML=blueprintList();afterRender();return true;}
  if(el.id==='studio-recipe-search'){view.recipeSearch=el.value;document.getElementById('studio-recipe-list').innerHTML=recipeList();return true;}
  return false;
 }
 function afterRender(){document.querySelectorAll('[data-building-art]').forEach(c=>{const g=c.getContext('2d');g.imageSmoothingEnabled=false;g.clearRect(0,0,c.width,c.height);g.save();g.translate(c.width/2,c.height*.72);g.scale(1.7,1.7);LWArt.diamond(g,0,4,90,43,'#cbd5b4');LWArt.diamond(g,0,1,90,43,'#dce3c7');LWArt.building(g,0,0,c.dataset.buildingArt,0);g.restore();});}
 return {render,action,change,input,afterRender,view,focusSkill};
}};
})(window);
