/// <reference path="./rts-mission-editor-ui-contracts.d.ts" />
/** HTML for detached authoring forms; escaping is shared by every imported text field. */
(function(input:unknown){
 'use strict';
 const root=input as {LWRTSMissionEditorForms?:LWRTSMissionEditorUI.FormsApi};
 const escape=(value:unknown):string=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
 const options=(rows:readonly {id:string;name:string}[],selected=''):string=>rows.map(row=>`<option value="${escape(row.id)}" ${row.id===selected?'selected':''}>${escape(row.name)}</option>`).join('');
 const number=(name:string,label:string,value:number,min=0):string=>`<label>${label}<input name="${name}" type="number" value="${value}" min="${min}" step="1" required></label>`;
 function metadata({catalog,mission}:LWRTSMissionEditor.Snapshot):string {
  return `<form data-editor-form="metadata"><h2>Mission settings</h2><label>Name<input name="name" required value="${escape(mission.name)}"></label><label>Description<textarea name="description" rows="3">${escape(mission.description)}</textarea></label><div class="rts-editor-pair">${number('width','Map width',mission.width,8)}${number('height','Map height',mission.height,8)}</div><label>Player faction<select name="playerFaction">${options(catalog.factions,mission.playerFaction)}</select></label><label>Default terrain<select name="defaultTerrain">${options(catalog.terrain,mission.defaultTerrain)}</select></label>${number('seed','Seed',mission.seed)}<label class="rts-editor-check"><input name="fog" type="checkbox" ${mission.fog?'checked':''}> Fog of war</label><button type="submit">Apply mission settings</button><p>Resizing or changing terrain must keep every placement valid.</p></form>`;
 }
 function brush({catalog,mission}:LWRTSMissionEditor.Snapshot):string {
  return `<form data-editor-form="brush"><h2>Map tools</h2><label>Tool<select name="tool" data-editor-tool><option value="terrain">Paint terrain</option><option value="spawns">Place unit / building / creature</option><option value="deposits">Place resource deposit</option><option value="items">Place item</option><option value="remove">Remove placement</option><option value="inspect">Inspect tile</option></select></label><div data-editor-fields="terrain"><label>Terrain<select name="terrain">${options(catalog.terrain,mission.defaultTerrain)}</select></label><div class="rts-editor-pair">${number('width','Brush width',1,1)}${number('height','Brush height',1,1)}</div></div><div data-editor-fields="spawns" hidden><label>Faction<select name="faction" data-editor-faction>${options(catalog.factions,mission.playerFaction)}</select></label><label>Archetype<select name="archetype" data-editor-archetype>${options([...catalog.units,...catalog.buildings])}</select></label>${number('count','Count',1,1)}</div><div data-editor-fields="deposits" hidden><label>Resource<select name="resource">${options(catalog.resources)}</select></label>${number('amount','Deposit amount',1000,1)}</div><div data-editor-fields="items" hidden><label>Item<select name="item">${options(catalog.items)}</select></label></div><div class="rts-editor-pair">${number('x','Tile X',0).replace('step="1"','step="any"')}${number('y','Tile Y',0).replace('step="1"','step="any"')}</div><button type="submit" data-editor-apply>Apply map tool</button><p>Click or tap the map, or enter coordinates and apply. Terrain paints a rectangle; drag to set its size. Inspect first to reposition an existing record.</p></form>`;
 }
 function objectives({catalog,mission}:LWRTSMissionEditor.Snapshot):string {
  return `<details><summary>Objectives · ${mission.objectives.length}</summary><div class="rts-editor-records">${mission.objectives.map((row,index)=>`<div><span>${escape(row.name)}<small>${escape(row.type)} · ${escape(row.target)} · ${row.amount}</small></span><button type="button" data-editor="edit-objective" data-index="${index}">Edit</button><button type="button" data-editor="remove-record" data-collection="objectives" data-index="${index}">Remove</button></div>`).join('')||'<p>No objectives. Add one to define victory.</p>'}</div><form data-editor-form="objective"><input name="index" type="hidden" value=""><label>Objective ID<input name="id" required value="new-objective"></label><label>Name<input name="name" required value="New objective"></label><label>Description<textarea name="description" rows="2"></textarea></label><label>Type<select name="type" data-editor-objective-type><option value="eliminate">Eliminate faction</option><option value="stockpile">Stockpile resource</option><option value="survive">Survive seconds</option></select></label><label>Target<select name="target" data-editor-objective-target>${options(catalog.factions)}</select></label>${number('amount','Required amount / seconds',1)}<button type="submit">Save objective</button><button type="button" data-editor="new-objective">New objective</button></form></details>`;
 }
 function records({mission}:LWRTSMissionEditor.Snapshot):string {
  const rows: {collection:string;index:number;label:string}[]=[];
  mission.spawns.forEach((row,index)=>rows.push({collection:'spawns',index,label:`${row.archetype} × ${row.count} · ${row.faction} · ${row.x}, ${row.y}`}));
  mission.deposits.forEach((row,index)=>rows.push({collection:'deposits',index,label:`${row.resource} · ${row.amount} · ${row.x}, ${row.y}`}));
  mission.items.forEach((row,index)=>rows.push({collection:'items',index,label:`${row.item} · ${row.x}, ${row.y}`}));
  return `<details><summary>Placements · ${rows.length}</summary><div class="rts-editor-records">${rows.map(row=>`<div><button type="button" data-editor="edit-record" data-collection="${row.collection}" data-index="${row.index}">${escape(row.label)}</button><button type="button" data-editor="remove-record" data-collection="${row.collection}" data-index="${row.index}">Remove</button></div>`).join('')||'<p>No placements yet.</p>'}</div></details>`;
 }
 root.LWRTSMissionEditorForms={escape,metadata,brush,objectives,records};
})(globalThis);
