// Historical regression adapted explicitly for v10 research, beds, physical stalls and door routing.
const V10=require('./test-v10-fixtures.cjs');
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const L=require('./simulation.cjs'),A=require('./adventure-content.js'),S=require('./story-codec.js'),C=require('./content-runtime.js');
const P=require('./colony-policies.js'),Clock=require('./simulation-clock.js'),BT=require('./behavior-tree.js');
const results=[],test=(name,fn)=>{try{fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:e.stack});console.error('FAIL',name,e.message);}};
const clone=A.copy,snap=e=>JSON.stringify(e.export()),demo=()=>{const e=L.createColonyDemo();e.selectCreature('c1');e.s.paused=false;return e;};
const run=(e,n)=>{for(let i=0;i<n*10;i++)e.step(.1);};
const clean=e=>{for(const c of e.creatures){c.task=null;c.orders=[];c.training=null;c.learning.queue=[];c.equipQueue=[];c.stockTargets={};Object.assign(c.needs,{food:90,water:90,energy:90,comfort:90,joy:80});c.feelings.anger=0;}return e;};
const plan=e=>{clean(e);e.actor.inventory.berries=6;e.actor.inventory.water=6;const offer=e.s.colony.board.offers.find(o=>o.questId==='meadow');assert(e.acceptQuest(offer.id).ok);return A.content.quests.find(q=>q.id==='meadow');};
function socialPair(e){clean(e);e.actor.creature.x=7;e.actor.creature.y=7;const b=e.creatures[1];b.creature.x=8;b.creature.y=7;e.actor.feelings.lastSocial=b.feelings.lastSocial=-100;e.actor.socialIntent=b.id;assert(e.startTask(e.socialTask()));assert.equal(b.task.kind,'socialwait');return b;}

test('Requested but blocked equipment prevents departure without consuming provisions',()=>{const e=demo();plan(e);e.actor.equipQueue=['stargazer_hat'];const before=snap(e);assert.equal(e.depart(),false);assert.equal(snap(e),before);});
test('Canceling blocked outfit allows an otherwise-ready departure',()=>{const e=demo();plan(e);e.actor.equipQueue=['stargazer_hat'];assert(e.cancelEquipment('stargazer_hat').ok);assert(e.depart());});
test('Quest readiness names outstanding equipment rather than implying ready',()=>{const e=demo(),q=plan(e);e.actor.equipQueue=['stargazer_hat'];const r=P.questReadiness(e,e.actor,q);assert(!r.ready);assert(!r.outfitReady);assert.equal(r.equipment.length,1);});
test('Canceling an active equip task never equips the canceled item later',()=>{const e=demo();clean(e);e.actor.inventory.trail_cap=1;e.actor.equipment.head=null;assert(e.requestEquipment('trail_cap').ok);assert(e.startTask({kind:'equip',itemId:'trail_cap',target:e.actor.creature,duration:2,label:'test'}));assert(e.cancelEquipment('trail_cap').ok);assert.equal(e.actor.task,null);assert.equal(e.actor.equipment.head,null);assert.equal(e.actor.inventory.trail_cap,1);});
test('Canceling unknown equipment is a rejected no-op',()=>{const e=demo(),before=snap(e);assert(!e.cancelEquipment('not-queued').ok);assert.equal(snap(e),before);});
test('Canceling crafting preserves unused material ownership',()=>{const e=demo();clean(e);e.actor.equipQueue=['rain_cape'];e.actor.task={kind:'gearcraft',resource:'rain_cape',elapsed:1,duration:8};const before=clone(e.actor.inventory);assert(e.cancelEquipment('rain_cape').ok);assert.equal(e.actor.task,null);assert.deepEqual(e.actor.inventory,before);});
test('Space for the initiator releases the waiting companion',()=>{const e=demo(),b=socialPair(e);assert(e.care('space').ok);assert.equal(e.actor.task,null);assert.equal(b.task,null);});
test('Space for the recipient releases the approaching companion',()=>{const e=demo(),b=socialPair(e),a=e.actor;e.selectCreature(b.id);assert(e.care('space').ok);assert.equal(b.task,null);assert.equal(a.task,null);});
test('Interrupted social activity cannot award phantom relationships',()=>{const e=demo(),b=socialPair(e),task=clone(e.actor.task);b.task=null;const before=clone(e.relationship(e.actor.id,b.id));e.finishTask(task);assert.deepEqual(e.relationship(e.actor.id,b.id),before);});
test('Social timeout clears the corresponding invitation on both sides',()=>{const e=demo(),b=socialPair(e),a=e.actor;e.withActor(b,()=>e.finishTask(b.task));assert.equal(a.task,null);assert.equal(b.task,null);});
test('Unrelated social tasks are not accidentally canceled',()=>{const e=demo();clean(e);const b=e.creatures[1];b.task={kind:'socialwait',partner:'c3'};e.releaseSocial({kind:'social',otherId:'c2'});assert(b.task);});
test('Urgent needs interrupt friendship and free the other companion',()=>{const e=demo(),b=socialPair(e);e.actor.needs.food=2;run(e,.1);assert.notEqual(b.task?.kind,'socialwait');});
test('A returned quest is settled exactly once',()=>{const e=demo();plan(e);assert(e.depart());for(let i=0;i<3000&&e.actor.activeQuest;i++)e.step(.1);assert.equal(e.actor.activeQuest,null);assert(e.actor.questHistory.length>0);const before=snap(e);assert.equal(e.returnQuest(),false);assert.equal(snap(e),before);});
test('Outfit inspection is a pure read across all companions and pieces',()=>{const e=demo(),before=snap(e);for(const c of e.creatures)for(const g of A.content.equipment)P.equipmentStatus(e,c,g.id);assert.equal(snap(e),before);});
test('Quest readiness and ownership forecasts consume no RNG',()=>{const e=demo(),before=snap(e);for(const c of e.creatures){for(const q of A.content.quests)P.questReadiness(e,c,q);P.attention(e,c);P.protectedInventory(e,c);}for(const id of Object.keys(L.RES))P.inventoryRow(e,id);assert.equal(snap(e),before);});
test('Stored outfit readiness does not grant it to a creature',()=>{const e=demo(),c=e.creatures[1];c.inventory.walking_boots=0;e.s.colony.warehouse.inventory.walking_boots=1;assert.equal(P.equipmentStatus(e,c,'walking_boots').state,'stored');assert.equal(c.inventory.walking_boots,0);});
test('Absent station gives actionable equipment preparation reason',()=>{const e=demo();clean(e);const g=A.content.equipment.find(g=>g.recipe.station==='loom')||A.content.equipment[0];e.s.buildings=e.s.buildings.filter(b=>b.kind!==g.recipe.station);e.actor.skills[g.recipe.skill]=true;e.actor.equipment[g.slot]=null;e.actor.inventory[g.id]=0;e.s.colony.warehouse.inventory[g.id]=0;assert(P.equipmentStatus(e,e.actor,g.id).blockers.some(x=>x.startsWith('Build ')));});
test('Missing skill gives actionable equipment preparation reason',()=>{const e=demo(),g=A.content.equipment[0];delete e.actor.skills[g.recipe.skill];e.actor.equipment[g.slot]=null;e.actor.inventory[g.id]=0;e.s.colony.warehouse.inventory[g.id]=0;assert(P.equipmentStatus(e,e.actor,g.id).blockers.some(x=>x.startsWith('Learn ')));});
test('Warehouse inspection lists ownership and correct sale value',()=>{const e=demo();e.actor.inventory.wood=7;e.creatures[1].inventory.wood=3;e.creatures[2].inventory.wood=0;e.s.colony.warehouse.inventory.wood=2;const r=P.inventoryRow(e,'wood');assert.equal(r.carried,10);assert.equal(r.stored,2);assert.equal(r.price,Math.max(1,Math.floor(L.RES.wood.price*.65)));assert.deepEqual(r.carriers.map(c=>c.id),['c1','c2']);});
test('Attention makes an urgent need visible ahead of mood',()=>{const e=demo();e.actor.feelings.anger=70;e.actor.needs.water=2;assert.equal(P.attention(e,e.actor).label,'Thirsty');});
test('Attention distinguishes returning from being in the glade',()=>{const e=demo();plan(e);e.depart();e.abortQuest();assert.equal(P.attention(e,e.actor).label,'Returning home');});
test('Planned gear keeps its ingredients out of surplus',()=>{const e=demo();clean(e);const g=A.content.equipment.find(g=>g.id==='rain_cape');e.actor.equipment.body=null;e.actor.inventory.rain_cape=0;e.actor.equipQueue=[g.id];for(const [id,n]of Object.entries(g.recipe.cost))e.actor.inventory[id]=n;const keep=P.protectedInventory(e,e.actor);for(const[id,n]of Object.entries(g.recipe.cost))assert(keep[id]>=n);});
test('Worn equipment survives unloading without double-counted ownership',()=>{const e=demo();clean(e);e.actor.needsDeposit=true;const keep=P.protectedInventory(e,e.actor);for(const id of Object.values(e.actor.equipment))assert.equal(keep[id],1);});
test('Quest provisions and a basic care spare remain carried',()=>{const e=demo(),q=plan(e),keep=P.protectedInventory(e,e.actor);assert.equal(keep.berries,q.cost.berries+1);assert.equal(keep.water,q.cost.water+1);});
test('Build-stage ingredients are preserved before assembly',()=>{const e=new L.Engine();e.s.started=true;e.s.skills.shelter=true;const spot=[];for(let x=1;x<18&&!spot.length;x++)for(let y=1;y<18;y++)if(e.canBuild(x,y)){spot.push(x,y);break;}const r=e.place('shelter',...spot);assert(r.ok);const cost=e.constructionCost(r.order),keep=P.protectedInventory(e,e.actor);for(const[id,n]of Object.entries(cost))assert(keep[id]>=n);});

for(const hz of [20,30,60,120])test('Fixed-step clock: 10 seconds at '+hz+' display frames/s gives 100 steps',()=>{const c=new Clock(.1),steps=[];for(let i=0;i<hz*10;i++)c.advance(1/hz,1,dt=>steps.push(dt));assert.equal(steps.length,100);assert(steps.every(x=>x===.1));});
for(const speed of [1,2,4,16])test('Clock speed '+speed+' scales game steps only',()=>{const c=new Clock(),steps=[];for(let i=0;i<600;i++)c.advance(1/60,speed,dt=>steps.push(dt));assert.equal(steps.length,100*speed);});
test('Clock validates invalid inputs before simulation callback',()=>{const c=new Clock();let calls=0;for(const value of [-1,NaN,Infinity])assert.throws(()=>c.advance(value,1,()=>calls++));assert.equal(calls,0);});
test('Clock pause resets only fractional presentation time',()=>{const c=new Clock();let calls=0;c.advance(.05,1,()=>calls++);c.reset();c.advance(.05,1,()=>calls++);assert.equal(calls,0);});
test('Suspension cannot trigger unbounded offline catch-up',()=>{const c=new Clock();let calls=0;c.advance(3600,1,()=>calls++);assert.equal(calls,1);});
test('Identical commands and fixed ticks match at 30 and 60 display frames/s',()=>{const a=demo(),b=S.commit(S.inspect(S.encode(a)));for(const [e,hz]of [[a,30],[b,60]]){const c=new Clock();for(let i=0;i<hz*20;i++)c.advance(1/hz,1,dt=>e.step(dt));}assert.equal(snap(a),snap(b));});
test('Unknown inherited behavior function is rejected',()=>{const b=new BT({});assert.throws(()=>b.validate({id:'bad',name:'Bad',type:'action',action:'toString'}));});
test('Behavior cooldown persists when caller did not provide a memory object',()=>{let calls=0;const b=new BT({hi:()=>{calls++;return 'success';}}),tree={id:'wait',name:'Wait',type:'cooldown',seconds:10,children:[{id:'hi',name:'Hi',type:'action',action:'hi'}]},context={time:2};b.tick(tree,context);b.tick(tree,context);assert.equal(calls,1);assert.equal(context.behaviorMemory.wait,12);});
test('A missing chest is rejected consistently with the schema',()=>{const p=clone(A.content);delete p.chest;assert(!A.validate(p).ok);});
test('Adventure diff uses stable definition IDs and exact field values',()=>{const p=clone(A.content);p.equipment[0].name='Changed hat';const d=A.diff(A.content,p);assert.equal(d.total,1);assert.equal(d.changes[0].path,'/equipment/'+p.equipment[0].id+'/name');assert.equal(d.changes[0].after,'Changed hat');});
test('Unchanged content produces no changes',()=>assert.equal(A.diff(A.content,clone(A.content)).total,0));
test('External metadata round trips without executable interpretation',()=>{const p=clone(A.content);p.extensions={editor:{note:'<script>not executed</script>',selected:'trail_cap'}};const v=A.validate(p);assert(v.ok);assert.deepEqual(v.content.extensions,p.extensions);});
test('Content diff limits rendered entries while keeping exact count',()=>{const d=A.diff({a:1,b:2,c:3},{a:2,b:3,c:4},2);assert.equal(d.total,3);assert.equal(d.changes.length,2);assert(d.truncated);});
test('Imported malformed world node is rejected without committing content',()=>{const e=demo(),doc=S.encode(e);doc.state.nodes[0].kind='not-a-resource';const ah=A.hash,ch=C.registry.hash;assert.throws(()=>S.inspect(doc));assert.equal(A.hash,ah);assert.equal(C.registry.hash,ch);});
test('In-progress canceled social scene still saves and restores',()=>{const e=demo();socialPair(e);e.care('space');const r=S.commit(S.inspect(S.encode(e)));assert.equal(snap(r),snap(e));});
test('Prepared quest with blocked gear survives save and reload without spending',()=>{const e=demo();plan(e);e.actor.equipQueue=['trail_cap'];const r=S.commit(S.inspect(S.encode(e)));assert.equal(snap(r),snap(e));assert(!r.depart());});


test('Behavior branch reordering remains a material diff',()=>{const p=clone(A.content),kids=p.behaviorTree.children;[kids[2],kids[3]]=[kids[3],kids[2]];assert(A.validate(p).ok);const d=A.diff(A.content,p);assert(d.total>0);assert(d.changes.some(c=>c.path==='/behaviorTree/children'&&c.kind==='order'));});
test('Pure equipment collection reorder is visible without inventing value changes',()=>{const p=clone(A.content);p.equipment.reverse();const d=A.diff(A.content,p);assert.equal(d.total,1);assert.equal(d.changes[0].kind,'order');});

// Several seeds and six inhabitants exercise sustainability, histories and load bounds.
const soak=[];
for(const seed of [13,29,47])test('Six-creature 30-minute regression soak, seed '+seed,()=>{
 const e=V10.beds(demo());e.s.player.coins=100000;for(const p of ['maker','sunny','steadfast'])assert(e.purchaseCreature(p).ok);e.selectCreature('c1');
 for(const [i,c]of e.creatures.entries())c.rpg.rng=seed+i*313;
 const start=performance.now();run(e,1800);
 for(const c of e.creatures){assert(Object.values(c.needs).every(n=>Number.isFinite(n)&&n>=0&&n<=100));assert(Object.values(c.inventory).every(n=>Number.isInteger(n)&&n>=0));assert(!e.load(c).overloaded);assert.equal(c.activeQuest,null);}
 const restored=S.commit(S.inspect(S.encode(e)));assert.equal(snap(restored),snap(e));run(e,10);run(restored,10);assert.equal(snap(restored),snap(e));
 soak.push({seed,creatures:e.creatures.length,seconds:1810,wallMs:Math.round(performance.now()-start),needs:e.creatures.map(c=>({name:c.name,...c.needs})),transfers:e.s.colony.warehouse.transfers.length});
});
const report={suite:'Littlewild v6 product-review regressions',passed:results.filter(r=>r.passed).length,failed:results.filter(r=>!r.passed).length,results,soak};fs.writeFileSync(__dirname+'/v10-regression-v6-test-results.json',JSON.stringify(report,null,2));console.log(report.passed+'/'+results.length+' checks passed');process.exitCode=report.failed?1:0;
