// Historical regression adapted explicitly for v10 research, beds, physical stalls and door routing.
const V10=require('./test-v10-fixtures.cjs');
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const L=require('./simulation.cjs'),W=require('./world-content.js'),S=require('./story-codec.js'),A=require('./adventure-content.js');
const results=[];function test(name,fn){try{fn();results.push({name,passed:true});}catch(error){results.push({name,passed:false,error:error.stack});console.error('FAIL',name,error.message);}}
const clone=W.clone,snap=e=>JSON.stringify(e.export()),run=(e,secs)=>{for(let i=0;i<Math.round(secs*10);i++)e.step(.1);};
function clean(e=L.createWorldDemo()){
 e.s.started=true;e.s.paused=false;e.selectCreature('c1');
 for(const c of e.creatures){c.task=null;c.orders=[];c.training=null;c.learning.queue=[];c.equipQueue=[];c.questPlan=null;c.activeQuest=null;c.stockTargets={};c.worldPickup=null;c.worldSupply=null;c.needsDeposit=false;c.feelings.anger=0;c.feelings.coolingUntil=0;c.feelings.social=90;for(const n of Object.keys(c.needs))c.needs[n]=95;}
 for(const b of e.s.buildings)if(b.storage){b.storage.input={};b.storage.output={};b.storage.job=null;b.storage.requests={};b.storage.targets={};b.storage.enabled=true;}
 return e;
}
function bench(e){return e.s.buildings.find(b=>b.kind==='bench');}
function arrive(e,t){assert(e.startTask(t),'task starts');const p=e.s.task.path.at(-1)||e.s.creature;e.s.creature.x=p.x;e.s.creature.y=p.y;e.s.task.path=[];e.s.task.phase='work';return e.s.task;}
const inventoryTotal=(e,id)=>(e.s.colony.warehouse.inventory[id]||0)+e.creatures.reduce((n,c)=>n+(c.inventory[id]||0),0)+e.s.buildings.reduce((n,b)=>n+(b.storage?.input[id]||0)+(b.storage?.output[id]||0)+(b.storage?.job?.cost[id]||0),0);
function recipeFixture(id='planks'){const e=clean(),b=bench(e);e.actor.skills.woodwork=true;e.actor.skills.fiberwork=true;const r=e.recipe(b,id);b.storage.input=clone(r.cost);return {e,b,r};}
function validationBad(name,mutate){test(name,()=>{const d=clone(W.defaults);mutate(d);const r=W.validate(d);assert.equal(r.ok,false);assert(r.errors.length);});}

test('Default world library validates',()=>assert(W.validate(W.defaults).ok));
test('World library validation is pure',()=>{const before=W.hash;W.validate(W.defaults);assert.equal(before,W.hash);});
validationBad('An authored site on water is rejected before application',d=>{d.sites[0].x=14;d.sites[0].y=5;});
validationBad('An authored site cannot overwrite a built-in resource',d=>{d.sites[0].x=2;d.sites[0].y=3;});
validationBad('Authored IDs cannot duplicate built-in resource IDs',d=>{d.sites[0].id='n0';});
test('Fresh world contains every configured site exactly once',()=>{const e=new L.Engine();for(const n of W.content.sites)assert.equal(e.s.nodes.filter(x=>x.id===n.id&&x.kind===n.kind&&x.x===n.x&&x.y===n.y).length,1);});
test('All thirteen node kinds exist in a fresh world',()=>{const e=new L.Engine();for(const d of W.content.nodes)assert(e.s.nodes.some(n=>n.kind===d.id));});
test('Infinite nodes do not change their stored stock over time',()=>{const e=new L.Engine();const n=e.s.nodes.find(n=>n.kind==='wood');n.stock=1;e.stepWorld(999);assert.equal(n.stock,1);assert.equal(e.remaining(n),Infinity);});
test('Finite depleted nodes never regenerate',()=>{const e=new L.Engine();const n=e.s.nodes.find(n=>n.kind==='stone');n.stock=0;for(let i=0;i<100;i++)e.stepWorld(100);assert.equal(n.stock,0);assert(!e.nodeAvailable(n));});
test('Infinite nodes remain available even when legacy stock is zero',()=>{const e=new L.Engine(),n=e.s.nodes.find(n=>n.kind==='berries');n.stock=0;assert(e.nodeAvailable(n));});
test('Finite gathering is limited by the node and conserves resources',()=>{const e=clean(),n=e.s.nodes.find(n=>n.kind==='stone');n.stock=1;e.actor.inventory.stone=0;e.actor.skills.stonework=true;e.check=()=>({success:true});const t=arrive(e,{kind:'gather',worldGather:true,nodeId:n.id,resource:'stone',target:n,duration:2});const before=inventoryTotal(e,'stone');e.finishTask(t);assert.equal(n.stock,0);assert.equal(inventoryTotal(e,'stone')-before,1);});
test('A failed harvest consumes no finite resource',()=>{const e=clean(),n=e.s.nodes.find(n=>n.kind==='ore');e.actor.skills.metalwork=true;e.check=()=>({success:false});const old=n.stock,t=arrive(e,{kind:'gather',worldGather:true,nodeId:n.id,resource:'ore',target:n,duration:2});e.finishTask(t);assert.equal(n.stock,old);});
test('Successful gathering cannot remotely harvest a node',()=>{const e=clean(),n=e.s.nodes.find(n=>n.kind==='stone');e.actor.creature.x=8;e.actor.creature.y=8;assert(!e.at(n));const old=n.stock;e.finishTask({kind:'gather',worldGather:true,nodeId:n.id,resource:'stone',target:n});assert.equal(n.stock,old);});
test('Required resource on an adjacent tile is insufficient',()=>{const e=V10.knowledge(new L.Engine()),n=e.s.nodes.find(n=>n.kind==='soil');assert.match(e.placementIssue('garden',n.x+1,n.y)||'',/exact tile|approach|exhausted/);});
test('Wrong node kind rejects a special blueprint',()=>{const e=new L.Engine(),n=e.s.nodes.find(n=>n.kind==='stone'),before=snap(e);assert(!e.place('garden',n.x,n.y).ok);assert.equal(snap(e),before);});
test('A depleted finite substrate rejects new construction',()=>{const d=clone(W.defaults);d.nodes.find(n=>n.id==='soil').mode='finite';W.withLibrary(d,()=>{const e=V10.knowledge(new L.Engine()),n=e.s.nodes.find(n=>n.kind==='soil');n.stock=0;assert.match(e.placementIssue('garden',n.x,n.y),/exhausted/);});});
test('Matching site accepts construction without spending or spawning a building',()=>{const e=V10.knowledge(new L.Engine());e.s.started=true;const n=e.s.nodes.find(n=>n.kind==='soil'&&!e.placementIssue('garden',n.x,n.y));assert(n);const before=e.s.buildings.length,inv=clone(e.actor.inventory);assert(e.place('garden',n.x,n.y).ok);assert.equal(e.s.buildings.length,before);assert.deepEqual(inv,e.actor.inventory);assert(e.nodeAt(n.x,n.y));});
test('General buildings cannot cover a resource node',()=>{const e=V10.knowledge(new L.Engine()),n=e.s.nodes.find(n=>n.kind==='soil');assert(!e.place('shelter',n.x,n.y).ok);});
test('Placement checks never mutate node order or RNG',()=>{const e=new L.Engine(),before=snap(e);for(const n of e.s.nodes)for(const b of ['well','garden','waterwheel','shelter']){e.canBuild(n.x,n.y,b);e.placementIssue(b,n.x,n.y);}assert.equal(snap(e),before);});
test('The same site cannot host two plans',()=>{const e=V10.knowledge(new L.Engine());const n=e.s.nodes.find(n=>n.kind==='soil'&&!e.placementIssue('garden',n.x,n.y));assert(e.place('garden',n.x,n.y).ok);assert(!e.place('grainplot',n.x,n.y).ok);});
test('New productive buildings have empty physical trays',()=>{const e=clean(),b=bench(e);assert.equal(L.WorldSystem.sum(b.storage.input),0);assert.equal(L.WorldSystem.sum(b.storage.output),0);});
test('Recipe job cannot start using remote warehouse materials',()=>{const e=clean(),b=bench(e);e.s.colony.warehouse.inventory.wood=99;const t=e.workTask(b,e.recipe(b,'planks'),null,null),before=snap(e);assert(!e.startTask(t));assert.equal(snap(e),before);});
test('Planning an input delivery does not move goods',()=>{const e=clean(),b=bench(e);e.actor.inventory.wood=4;const before=inventoryTotal(e,'wood');const t=e.productionTask(b,'planks');assert.equal(t.kind,'stockbuilding');assert.equal(b.storage.input.wood||0,0);assert.equal(e.actor.inventory.wood,4);assert.equal(inventoryTotal(e,'wood'),before);});
test('Input transfer settles only after the carrier arrives',()=>{const e=clean(),b=bench(e);e.actor.inventory.wood=4;e.actor.creature.x=3;e.actor.creature.y=4;const t=e.productionTask(b,'planks');assert(e.startTask(t));assert.equal(b.storage.input.wood||0,0);e.finishTask(t);assert.equal(b.storage.input.wood||0,0);const t2=arrive(e,e.productionTask(b,'planks'));e.finishTask(t2);assert.equal(b.storage.input.wood,2);assert.equal(e.actor.inventory.wood,2);});
test('Concurrent ingredient trips cannot overfill a single recipe',()=>{const e=clean(),b=bench(e);const a=e.actor,c=e.creatures[1];a.inventory.wood=5;c.inventory.wood=5;const t1=e.productionTask(b,'planks');const t2=e.withActor(c,()=>e.productionTask(b,'planks'));e.finishTask(arrive(e,t1));e.withActor(c,()=>e.finishTask(arrive(e,t2)));assert.equal(b.storage.input.wood,2);assert.equal(a.inventory.wood+c.inventory.wood,8);});
test('Paid batch reserves input once',()=>{const {e,b,r}=recipeFixture();const before=inventoryTotal(e,'wood'),t=arrive(e,e.productionTask(b,r.id));assert.equal(b.storage.input.wood,0);assert.equal(b.storage.job.cost.wood,2);assert.equal(inventoryTotal(e,'wood'),before);assert.equal(b.storage.job.id,t.jobId);});
test('Two workers cannot claim the same paid batch',()=>{const {e,b}=recipeFixture();assert(e.startTask(e.productionTask(b,'planks')));const c=e.creatures[1];assert.equal(e.withActor(c,()=>e.productionTask(b,'planks')),null);});
test('Success puts the product in the building, not satchel or warehouse',()=>{const {e,b}=recipeFixture(),before=e.s.colony.warehouse.inventory.planks||0,carry=e.actor.inventory.planks||0;const t=arrive(e,e.productionTask(b,'planks'));e.check=()=>({success:true});e.finishTask(t);assert.equal(b.storage.output.planks,1);assert.equal(e.s.colony.warehouse.inventory.planks||0,before);assert.equal(e.actor.inventory.planks||0,carry);});
test('Failed work retains reserved ingredients for another attempt',()=>{const {e,b}=recipeFixture();const t=arrive(e,e.productionTask(b,'planks'));e.check=()=>({success:false});t.elapsed=t.duration;e.finishTask(t);assert.equal(b.storage.job.cost.wood,2);assert.equal(b.storage.output.planks||0,0);assert.equal(b.storage.job.progress,t.duration*.4);});
test('Failed batch cannot reroll immediately without doing remaining work',()=>{const {e,b}=recipeFixture();const t=arrive(e,e.productionTask(b,'planks'));e.check=()=>({success:false});t.elapsed=t.duration-.001;e.withActor(e.actor,()=>e.stepActor(.1));assert(b.storage.job);assert.equal(b.storage.job.progress,t.duration*.4);});
test('Pausing a workplace releases the worker without refunding or losing materials',()=>{const {e,b}=recipeFixture();arrive(e,e.productionTask(b,'planks'));const before=inventoryTotal(e,'wood');assert(e.configureBuilding(b.id,'enabled',false).ok);assert.equal(e.actor.task,null);assert.equal(b.storage.job.workerId,null);assert.equal(inventoryTotal(e,'wood'),before);assert.equal(e.productionTask(b,'planks'),null);});
test('A resumed paid batch is not charged twice',()=>{const {e,b}=recipeFixture();arrive(e,e.productionTask(b,'planks'));e.configureBuilding(b.id,'enabled',false);const before=inventoryTotal(e,'wood');e.configureBuilding(b.id,'enabled',true);assert(e.startTask(e.productionTask(b,'planks')));assert.equal(inventoryTotal(e,'wood'),before);});
test('Give space safely interrupts a paid batch and saves immediately',()=>{const {e,b}=recipeFixture();arrive(e,e.productionTask(b,'planks'));assert(e.care('space').ok);assert.equal(b.storage.job.workerId,null);assert.doesNotThrow(()=>S.inspect(S.encode(e)));});
test('Removing an equipment request safely releases its buffered job',()=>{const e=clean(),g=A.content.equipment.find(g=>g.recipe.station==='bench'),b=bench(e);e.actor.skills[g.recipe.skill]=true;e.actor.equipQueue=[g.id];b.storage.input=clone(g.recipe.cost);assert(e.startTask(e.productionTask(b,g.id)));assert(e.cancelEquipment(g.id).ok);assert.equal(b.storage.job.workerId,null);assert.doesNotThrow(()=>S.inspect(S.encode(e)));});
test('A second trained creature can resume interrupted paid work',()=>{const {e,b}=recipeFixture();const t=arrive(e,e.productionTask(b,'planks'));t.elapsed=2;b.storage.job.progress=2;e.care('space');const c=e.creatures[1];e.withActor(c,()=>{const next=e.productionTask(b,'planks');assert(next);assert.equal(next.elapsed,2);assert(e.startTask(next));assert.equal(b.storage.job.workerId,c.id);});});
test('Completed outputs are unavailable to a remote sale',()=>{const e=clean(),b=bench(e);b.storage.output.planks=4;e.s.colony.warehouse.inventory.planks=0;const before=snap(e);assert(!e.sellItem('planks',1).ok);assert.equal(snap(e),before);});
test('Collecting output changes only building and satchel ownership',()=>{const e=clean(),b=bench(e);b.storage.output.planks=4;const before=inventoryTotal(e,'planks'),stored=e.s.colony.warehouse.inventory.planks,carry=e.actor.inventory.planks||0;e.finishTask(arrive(e,e.collectTask(b,'planks',3)));assert.equal(b.storage.output.planks,1);assert.equal(e.actor.inventory.planks,carry+3);assert.equal(e.s.colony.warehouse.inventory.planks,stored);assert.equal(inventoryTotal(e,'planks'),before);});
test('Two collectors cannot duplicate the same output',()=>{const e=clean(),b=bench(e);b.storage.output.planks=1;const before=inventoryTotal(e,'planks');const t1=e.collectTask(b,'planks'),c=e.creatures[1],t2=e.withActor(c,()=>e.collectTask(b,'planks'));e.finishTask(arrive(e,t1));e.withActor(c,()=>e.finishTask(arrive(e,t2)));assert.equal(b.storage.output.planks,0);assert.equal(inventoryTotal(e,'planks'),before);});
test('Output capacity blocks a new batch until collection',()=>{const {e,b}=recipeFixture();b.storage.output.planks=e.capacity(b,'output');assert.equal(e.startTask(e.workTask(b,e.recipe(b,'planks'))),false);const t=e.productionTask(b,'planks');assert.equal(t.kind,'collectbuilding');});
test('A full carrier cannot exceed its weight limit with output',()=>{const e=clean(),b=bench(e);b.storage.output.stone=4;e.actor.inventory.stone=500;const before=e.actor.inventory.stone;const t=e.transferTask('collectbuilding',b,'stone',4);e.finishTask(arrive(e,t));assert.equal(e.actor.inventory.stone,before);assert.equal(b.storage.output.stone,4);});
test('Reclaiming input pauses work but still requires a carrier',()=>{const {e,b}=recipeFixture(),old=inventoryTotal(e,'wood');assert(e.configureBuilding(b.id,'reclaim').ok);assert.equal(b.storage.enabled,false);assert.equal(b.storage.input.wood,2);assert.equal(inventoryTotal(e,'wood'),old);assert.equal(e.haulingTask().kind,'emptybuilding');});
test('A returned input remains owned, never deleted',()=>{const {e,b}=recipeFixture();e.configureBuilding(b.id,'reclaim');const old=inventoryTotal(e,'wood');e.finishTask(arrive(e,e.haulingTask()));assert.equal(inventoryTotal(e,'wood'),old);assert.equal(b.storage.input.wood,0);});
test('Stock targets count output at all physical locations',()=>{const e=clean(),b=bench(e);e.s.colony.warehouse.inventory.planks=2;e.actor.inventory.planks=3;e.creatures[1].inventory.planks=4;e.creatures[2].inventory.planks=0;b.storage.output.planks=5;assert.equal(e.totalStock('planks'),14);});
test('Paid output counts against scheduling without pretending to be physical stock',()=>{const {e,b}=recipeFixture();const old=e.totalStock('planks');arrive(e,e.productionTask(b,'planks'));assert.equal(e.totalStock('planks'),old);assert.equal(e.demandStock('planks'),old+1);});
test('Completed work decrements a requested batch once',()=>{const {e,b}=recipeFixture();e.configureBuilding(b.id,'batch',{recipe:'planks',amount:2});const t=arrive(e,e.productionTask(b,'planks'));e.check=()=>({success:true});e.finishTask(t);e.finishTask(t);assert.equal(b.storage.requests.planks,1);assert.equal(b.storage.output.planks,1);});
test('Clearing future work leaves a paid batch and its supplies intact',()=>{const {e,b}=recipeFixture();e.configureBuilding(b.id,'batch',{recipe:'planks',amount:3});arrive(e,e.productionTask(b,'planks'));const job=clone(b.storage.job);e.configureBuilding(b.id,'clear');assert.deepEqual(b.storage.job,job);assert.deepEqual(b.storage.requests,{});});
test('Finite site charge is committed once, not per failed attempt',()=>{const d=clone(W.defaults);d.nodes.find(n=>n.id==='groundwater').mode='finite';W.withLibrary(d,()=>{const e=clean(),b=e.s.buildings.find(b=>b.kind==='well'),n=e.nodeAt(b.x,b.y),old=n.stock;e.actor.skills.masonry=true;const t=arrive(e,e.productionTask(b,'water'));assert.equal(n.stock,old-4);e.check=()=>({success:false});e.finishTask(t);arrive(e,e.productionTask(b,'water'));assert.equal(n.stock,old-4);});});
test('A paid batch can finish after its finite site was exhausted by reservation',()=>{const d=clone(W.defaults);d.nodes.find(n=>n.id==='groundwater').mode='finite';W.withLibrary(d,()=>{const e=clean(),b=e.s.buildings.find(b=>b.kind==='well'),n=e.nodeAt(b.x,b.y);n.stock=4;e.actor.skills.masonry=true;const t=arrive(e,e.productionTask(b,'water'));assert.equal(n.stock,0);e.check=()=>({success:true});e.finishTask(t);assert.equal(b.storage.output.water,4);assert.equal(e.productionTask(b,'water'),null);});});
test('Buffer capacities grow with building upgrades',()=>{const {e,b}=recipeFixture();const initial=e.capacity(b,'input');b.level++;assert.equal(e.capacity(b,'input'),initial+4);});
test('Production plans do not require a selected creature',()=>{const e=clean(),b=bench(e);e.s.colony.selectedId=null;assert(e.configureBuilding(b.id,'batch',{recipe:'rope',amount:1}).ok);});
test('Building inspection and resource forecasts consume no random state',()=>{const e=clean(),before=snap(e);for(const b of e.s.buildings){e.buildingStatus(b);e.buildingRecipes(b);e.capacity(b,'input');}for(const id of Object.keys(L.RES)){e.totalStock(id);e.assessResource(id,2);}assert.equal(snap(e),before);});
for(const [label,command,value]of [['negative target','target',{recipe:'planks',amount:-1}],['non-integer batch','batch',{recipe:'planks',amount:1.5}],['unknown recipe','target',{recipe:'notreal',amount:2}],['too many batches','batch',{recipe:'planks',amount:13}],['unknown command','teleport',10],['invalid priority','priority',99]])test('Reject '+label+' without mutation',()=>{const e=clean(),b=bench(e),old=snap(e);assert(!e.configureBuilding(b.id,command,value).ok);assert.equal(snap(e),old);});
validationBad('Reject unknown world fields',d=>d.secret=true);
validationBad('Reject negative node stock',d=>d.nodes[0].quantity=-1);
validationBad('Reject duplicate node identifiers',d=>d.nodes[1].id=d.nodes[0].id);
validationBad('Reject missing supported node kinds',d=>d.nodes.pop());
validationBad('Reject unknown production ingredients',d=>d.buildings.find(b=>b.production).production.cost.no_such_item=1);
validationBad('Reject recipes that cannot fit the input buffer',d=>d.buildings.find(b=>b.id==='bench').inputCapacity=1);
validationBad('Reject recipes that cannot fit the output buffer',d=>d.buildings.find(b=>b.id==='kiln').outputCapacity=1);
validationBad('Reject circular production dependencies',d=>d.buildings.find(b=>b.id==='well').production.cost.water=1);
validationBad('Reject unknown required-node references',d=>d.buildings[0].requiresNode='no_such_node');
validationBad('Reject duplicate authored tiles',d=>{d.sites[1].x=d.sites[0].x;d.sites[1].y=d.sites[0].y;});
validationBad('Reject out-of-world site coordinates',d=>d.sites[0].x=50);
test('World changes preserve extension metadata through round trip',()=>{const d=clone(W.defaults);d.extensions={editor:{labels:['timber','water']}};assert(W.validate(d).ok);W.withLibrary(d,()=>assert.deepEqual(W.content.extensions,d.extensions));});
test('World diff identifies a stable field path',()=>{const d=clone(W.defaults);d.nodes[0].mode='finite';assert(W.diff(W.defaults,d).some(x=>x.path==='/nodes/wood/mode'));});
test('Identical world library has no changes',()=>assert.deepEqual(W.diff(W.defaults,W.defaults),[]));
test('Reordered sites have an explicit ordering diff',()=>{const d=clone(W.defaults);d.sites.reverse();assert(W.diff(W.defaults,d).some(x=>x.path==='/sites/$order'));});
test('World import rejects mechanics changes during a paid batch',()=>{const {e,b}=recipeFixture();arrive(e,e.productionTask(b,'planks'));const d=clone(W.content);d.nodes[0].mode='finite';const before=snap(e),hash=W.hash;assert.throws(()=>S.applyWorld(d,e));assert.equal(snap(e),before);assert.equal(W.hash,hash);});
test('Label-only world import is permitted during committed work',()=>{const {e,b}=recipeFixture();arrive(e,e.productionTask(b,'planks'));const d=clone(W.content);d.nodes[0].name='Branching woodland';const old=clone(W.content);try{assert.equal(S.applyWorld(d,e),e);assert.equal(W.node('wood').name,'Branching woodland');}finally{W.replace(old);}});
test('Editing site coordinates requires a new story',()=>{const e=clean(),d=clone(W.content);d.sites[0].x=8;d.sites[0].y=12;assert.throws(()=>S.applyWorld(d,e),/Site layout/);});
test('New-story world imports apply initial finite quantities',()=>{const d=clone(W.content);d.nodes.find(n=>n.id==='stone').quantity=17;const old=clone(W.content);try{const e=S.applyWorld(d,clean(),true);assert(e.s.nodes.filter(n=>n.kind==='stone').every(n=>n.stock===17));}finally{W.replace(old);}});
test('A portable story embeds all four exact content libraries',()=>{const e=clean(),save=S.encode(e);assert.equal(save.version,8);assert(save.growth.library);assert.equal(save.world.fingerprint,W.hash);assert(save.adventure.library);assert(save.content.library);});
test('World-fingerprint tampering is rejected',()=>{const d=S.encode(clean());d.world.library.nodes[0].name='Changed';assert.throws(()=>S.inspect(d),/fingerprint/);});
test('Inspecting a story does not change active world definitions',()=>{const e=clean(),before=W.hash;S.inspect(S.encode(e));assert.equal(W.hash,before);});
test('Paid batches and inventory locations survive exact save continuation',()=>{const {e,b}=recipeFixture();arrive(e,e.productionTask(b,'planks'));run(e,1);const restored=S.commit(S.inspect(S.encode(e)));assert.equal(snap(restored),snap(e));run(e,60);run(restored,60);assert.equal(snap(restored),snap(e));});
for(const [label,mutate]of [['overfilled output',s=>s.buildings.find(b=>b.kind==='bench').storage.output.wood=999],['unknown inventory item',s=>s.buildings.find(b=>b.kind==='bench').storage.input.fake=1],['duplicate node tile',s=>{s.nodes[1].x=s.nodes[0].x;s.nodes[1].y=s.nodes[0].y;}],['invalid quantity',s=>s.nodes[0].stock=-1],['missing substrate',s=>{const b=s.buildings.find(b=>b.kind==='well');s.nodes=s.nodes.filter(n=>n.x!==b.x||n.y!==b.y);} ]])test('Save import rejects '+label,()=>{const d=S.encode(clean());mutate(d.state);assert.throws(()=>S.inspect(d));});
const soaks=[];
for(const seed of [13,29,47])test('Six-creature world logistics, 30 simulated minutes, seed '+seed,()=>{
 const e=V10.beds(clean());e.s.player.coins=100000;for(const p of ['maker','sunny','steadfast'])assert(e.purchaseCreature(p).ok);e.selectCreature('c1');
 for(const [i,c]of e.creatures.entries())c.rpg.rng=seed+i*313;const b=bench(e);e.configureBuilding(b.id,'target',{recipe:'planks',amount:12});e.configureBuilding(b.id,'target',{recipe:'rope',amount:8});const k=e.s.buildings.find(b=>b.kind==='kiln');e.configureBuilding(k.id,'batch',{recipe:'bricks',amount:3});
 const start=performance.now();for(let i=0;i<18;i++){run(e,100);L.WorldSystem.validateState(e.export().state);}
 assert(e.s.world.transfers.length>0);assert(b.storage.completed>0);assert(k.storage.completed>0);
 for(const c of e.creatures){assert(Object.values(c.needs).every(n=>Number.isFinite(n)&&n>=0&&n<=100));assert(Object.values(c.inventory).every(n=>Number.isInteger(n)&&n>=0));assert(!e.load(c).overloaded);}
 const restored=S.commit(S.inspect(S.encode(e)));assert.equal(snap(restored),snap(e));run(e,15);run(restored,15);assert.equal(snap(restored),snap(e));soaks.push({seed,creatures:e.creatures.length,simulatedSeconds:1815,wallMs:Math.round(performance.now()-start),batches:e.s.buildings.reduce((n,b)=>n+(b.storage?.completed||0),0),transfers:e.s.world.transfers.length,minimumNeed:Math.min(...e.creatures.flatMap(c=>Object.values(c.needs)))});
});
const report={suite:'Littlewild v8 world, production and logistics',passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length,results,soaks};fs.writeFileSync(__dirname+'/v10-regression-v8-test-results.json',JSON.stringify(report,null,2));console.log(report.passed+'/'+results.length+' checks passed');process.exitCode=report.failed?1:0;
