'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),L=require('./simulation.cjs'),S=require('./story-codec.js');
const C=global.LWGrowth,G=global.LWGeography,P=global.LWPlanner,A=global.LWAdventure,W=global.LWWorldContent,results=[];
const test=(name,fn)=>{const start=performance.now();try{fn();results.push({name,passed:true,ms:performance.now()-start});}catch(e){results.push({name,passed:false,error:e.stack});console.error('FAIL',name,e.message);}};
const copy=v=>JSON.parse(JSON.stringify(v)), snap=e=>JSON.stringify(e.export());
function clean(){const e=L.createWorldDemo();e.s.started=true;e.s.paused=false;e.selectCreature('c1');for(const c of e.creatures){c.task=null;c.orders=[];c.training=null;c.learning.queue=[];c.learning.paused=false;c.equipQueue=[];c.questPlan=null;c.activeQuest=null;c.stockTargets={};c.worldPickup=null;c.worldSupply=null;c.needsDeposit=false;c.socialIntent=null;c.unpackIntent=false;c.feelings.anger=0;c.feelings.coolingUntil=0;c.feelings.social=90;for(const k in c.needs)c.needs[k]=95;}for(const b of e.s.buildings)if(b.storage)Object.assign(b.storage,{input:{},output:{},job:null,requests:{},targets:{},enabled:true});return e;}
function rich(e){e.s.player.level=20;e.s.player.coins=1e7;e.s.progression.prestige=e.s.progression.earnedPrestige=1e7;openAll(e);return e;}
function ticks(e,secs){for(let i=0;i<Math.ceil(secs*10);i++)e.step(.1);}
function arrive(e,t){assert(t,'task exists');assert(e.startTask(t),'task starts');const p=t.path.at(-1)||e.actor.creature;Object.assign(e.actor.creature,{x:p.x,y:p.y});t.path=[];t.phase='work';return t;}
function finish(e,t){arrive(e,t);e.finishTask(t);return t;}
function noChange(e,fn){const before=snap(e);const r=fn();assert.equal(r.ok,false);assert.equal(snap(e),before);return r;}
function openAll(e){for(const r of C.content.research){e.s.progression.research[r.id]=true;if(r.grants)e.s.progression.features[r.grants.feature]=r.grants.rank;}}
function marketFixture(){const e=clean();openAll(e);e.actor.inventory={...Object.fromEntries(Object.keys(L.RES).map(k=>[k,0])),berries:2,water:2};for(const id of Object.values(e.actor.equipment))if(id)e.actor.inventory[id]=1;e.s.colony.warehouse.inventory.wood=20;assert(e.sellItem('wood',4,'c1').ok);return e;}
function marketStep(e){const t=e.marketTask();assert(t);return finish(e,t);}
// Settlement fixture uses a real invitation and an explicitly completed checkpoint record.
function quest(e,success=true){openAll(e);const c=e.actor;c.equipQueue=[];c.inventory={berries:8,water:8};for(const id of Object.values(c.equipment))if(id)c.inventory[id]=1;const offer=e.s.colony.board.offers.find(o=>o.questId==='meadow');assert(offer);assert(e.acceptQuest(offer.id).ok);c.needs.energy=100;assert(e.depart());if(success){const q=c.activeQuest;q.elapsed=q.duration;q.checkIndex=q.checks.length;q.successes=q.checks.length;q.rolls=q.checks.map(st=>({dice:[1,1,1],total:3,target:st.target,margin:st.target-3,success:true,outcome:'Critical success'}));q.status='returning';q.outcome='Success';q.returnRemaining=0;}return c.activeQuest;}


// Sparse expansion, topology, reservation and deterministic island data.
test('Fresh story starts on exactly one owned island and one slot',()=>{const e=new L.Engine();assert.equal(e.s.estate.islands.length,1);assert.equal(e.s.progression.slots,1);assert.equal(e.s.progression.prestige,0);assert.deepEqual(G.frontier(e.s).map(i=>i.id).sort(),['-1,0','0,-1','0,1','1,0']);});
test('Land buying rejects a fresh player without changing balances or state',()=>{const e=new L.Engine();noChange(e,()=>e.buyIsland(1,0));});
for(const[ix,iy]of[[1,0],[-1,0],[0,1],[0,-1]])test('Island purchase supports edge '+ix+','+iy+' and physical bridge',()=>{const e=rich(clean()),q=e.landQuote();assert(e.buyIsland(ix,iy).ok);assert.equal(e.s.player.coins,1e7-q.coins);assert.equal(e.s.progression.prestige,1e7-q.prestige);assert.equal(G.bridges(e.s).length,1);const target={x:ix*23+9,y:iy*23+9};const path=e.findPath(target,false);assert(path&&path.length>20);assert(path.every(p=>G.available(e.s,p.x,p.y)));assert.doesNotThrow(()=>S.inspect(S.encode(e)));});
test('Nonadjacent and duplicate islands are rejected atomically',()=>{const e=rich(clean());noChange(e,()=>e.buyIsland(1,1));assert(e.buyIsland(1,0).ok);noChange(e,()=>e.buyIsland(1,0));noChange(e,()=>e.buyIsland(4,0));});
test('Each purchase increases both costs without changing creature positions',()=>{const e=rich(clean()),before=copy(e.creatures.map(c=>c.creature)),q=e.landQuote();assert(e.buyIsland(1,0).ok);const n=e.landQuote();assert(n.coins>q.coins&&n.prestige>q.prestige);assert.deepEqual(e.creatures.map(c=>c.creature),before);});
test('Completing an island square creates each shared edge exactly once',()=>{const e=rich(clean());for(const p of[[1,0],[0,1],[1,1]])assert(e.buyIsland(...p).ok);assert.equal(G.bridges(e.s).length,4);assert.equal(new Set(G.bridges(e.s).map(x=>x.id)).size,4);assert.doesNotThrow(()=>L.Engine.import(e.export()));});
test('Insufficient coins or prestige cannot create a bridge or resources',()=>{const e=clean();e.s.player.coins=0;noChange(e,()=>e.buyIsland(1,0));e.s.player.coins=900;e.s.progression.prestige=0;noChange(e,()=>e.buyIsland(1,0));});
test('An actual moving creature crosses only owned bridge cells',()=>{const e=rich(clean());assert(e.buyIsland(1,0).ok);const c=e.actor;c.needs.energy=c.needs.water=c.needs.food=100;const t={kind:'idle',target:{x:32,y:9},duration:2,label:'Cross-island observation',reason:'Test movement'};assert(e.startTask(t));let crossed=false,last={...c.creature};for(let i=0;i<900&&c.task===t;i++){e.withActor(c,()=>e.stepActor(.1));assert(Math.hypot(c.creature.x-last.x,c.creature.y-last.y)<.2);const x=Math.round(c.creature.x),y=Math.round(c.creature.y);assert(G.available(e.s,x,y));if(x>=19&&x<23)crossed=true;last={...c.creature};}assert(crossed);assert.equal(Math.round(c.creature.x),32);});
test('New resource nodes have unique stable IDs and reserve bridge corridors',()=>{const e=rich(clean());e.buyIsland(1,0);const nodes=e.s.nodes.filter(n=>n.id.startsWith('island:'));assert(nodes.length>35);assert.equal(new Set(e.s.nodes.map(n=>n.id)).size,e.s.nodes.length);assert(!nodes.some(n=>['wood','stone'].includes(n.kind)&&(G.cell(n.x,n.y).x===9||G.cell(n.x,n.y).y===9)));assert.deepEqual(G.generatedNodes(1,0,W),G.generatedNodes(1,0,W));});
test('Camera-independent land generation does not consume gameplay RNG',()=>{const e=rich(clean()),rng=copy(e.s.colony.rng);G.describe(5,-8);G.generatedNodes(1,0,W);assert.deepEqual(e.s.colony.rng,rng);});
test('Buildings cannot be placed on bridges or unowned islands',()=>{const e=rich(clean());openAll(e);assert(e.placementIssue('shelter',32,9));e.buyIsland(1,0);assert(e.placementIssue('shelter',20,9));});
test('New-island placement is valid away from shore and nodes',()=>{const e=rich(clean());e.buyIsland(1,0);let plot;for(let y=2;y<=16&&!plot;y++)for(let x=25;x<=39&&!plot;x++)if(!e.placementIssue('shelter',x,y))plot={x,y};assert(plot);assert(e.place('shelter',plot.x,plot.y).ok);assert.doesNotThrow(()=>S.inspect(S.encode(e)));});

// Homes, recruitment and separate slot progression.
test('Existing demo companions each have a capacity-safe assigned home',()=>{const e=clean();for(const c of e.creatures)assert(e.home(c));for(const b of e.s.buildings)assert(e.residents(b.id).length<=e.homeCapacity(b));});
test('Home capacity increases with completed home level',()=>{const e=clean(),b=e.s.buildings.find(b=>b.kind==='shelter');b.level=1;assert.equal(e.homeCapacity(b),1);b.level=3;assert.equal(e.homeCapacity(b),3);});
test('Slot progression prices and level requirements escalate',()=>{const e=rich(clean());const q=e.slotQuote();assert(e.unlockSlot().ok);const n=e.slotQuote();assert(n.prestige>q.prestige&&n.level>q.level);assert.equal(e.s.progression.slots,4);});
test('Slot unlock validates guide level and prestige before charging',()=>{const e=clean();e.s.player.level=1;noChange(e,()=>e.unlockSlot());e.s.player.level=20;e.s.progression.prestige=0;noChange(e,()=>e.unlockSlot());});
test('Recruitment requires a spare bed as well as an unlocked slot',()=>{const e=rich(clean());e.s.progression.slots=4;for(const b of e.s.buildings)if(C.content.homes[b.kind])b.level=1;const cottage=e.s.buildings.find(b=>b.kind==='cottage');if(cottage){e.s.buildings=e.s.buildings.filter(b=>!C.content.homes[b.kind]||b===cottage);for(const c of e.creatures)c.homeId=cottage.id;}else e.s.buildings=e.s.buildings.filter(b=>!C.content.homes[b.kind]);assert(!e.freeHome());noChange(e,()=>e.purchaseCreature(A.content.personalities[0].id));});
test('Recruitment spends coins, keeps independent state and assigns a bed',()=>{const e=rich(clean());e.s.progression.slots=4;const b=e.s.buildings.find(b=>b.kind==='cottage')||e.s.buildings.find(b=>b.kind==='shelter');b.level=3;const price=e.purchasePrice(),coins=e.s.player.coins,r=e.purchaseCreature(A.content.personalities[0].id);assert(r.ok,r.reason);assert.equal(e.s.player.coins,coins-price);assert(e.home(r.creature));assert.notEqual(r.creature.inventory,e.creatures[0].inventory);assert.notEqual(r.creature.skills,e.creatures[0].skills);assert.doesNotThrow(()=>L.Engine.import(e.export()));});
test('Home assignment cannot overbook or move an away creature',()=>{const e=clean(),b=e.s.buildings.find(b=>b.kind==='shelter');b.level=1;e.creatures[0].homeId=b.id;e.creatures[1].homeId=null;noChange(e,()=>e.assignHome('c2',b.id));});
test('Rest task travels to the assigned home doorway',()=>{const e=clean(),t=e.createNeedTask('energy');assert(t);assert.equal(t.target.id,e.home().id);const path=e.findPath(t.target,true);assert.deepEqual(path.at(-1),e.doorway(e.home()));});

// Knowledge is not inventory; progression never charges rejected operations.
test('Initial operational blueprints and recipes are narrowly unlocked',()=>{const e=new L.Engine();assert(e.unlocked('buildings','shelter'));assert(e.unlocked('recipes','planks'));assert(!e.unlocked('buildings','cottage'));assert(!e.unlocked('features','land'));assert(!P.taskOptions(e,'build',e.actor).some(o=>o.id==='cottage'));assert(!P.availableTypes(e).some(t=>t.id==='quest'));});
test('Research charges points once, not coins or inventory, and then reveals content',()=>{const e=new L.Engine();e.s.rp=1000;e.s.player.level=20;const r=C.content.research.find(r=>r.grants&&Object.keys(r.requires).length===0);const before=copy(e.actor.inventory),rp=e.s.rp;assert(e.researchFeature(r.id).ok);assert.equal(e.s.rp,rp-r.cost);assert.deepEqual(e.actor.inventory,before);noChange(e,()=>e.researchFeature(r.id));});
test('Research prerequisites reject unsupported ranks without mutation',()=>{const e=new L.Engine();e.s.rp=1000;const r=C.content.research.find(r=>r.grants?.rank===4);noChange(e,()=>e.researchFeature(r.id));});
test('Prestige shop deposits to warehouse, not a selected satchel',()=>{const e=rich(clean()),d=C.content.shop[0],inv=copy(e.actor.inventory),before=copy(e.s.colony.warehouse.inventory),prestige=e.s.progression.prestige;assert(e.buyPrestigeItem(d.id).ok);assert.equal(e.s.progression.prestige,prestige-d.prestige);for(const[k,n]of Object.entries(d.items))assert.equal(e.s.colony.warehouse.inventory[k],(before[k]||0)+n);assert.deepEqual(e.actor.inventory,inv);});
test('Successful quest settlement grants prestige exactly once',()=>{const e=clean(),p=e.s.progression.prestige;quest(e);assert(e.returnQuest());assert.equal(e.s.progression.prestige,p+7);const after=snap(e);assert(!e.returnQuest());assert.equal(snap(e),after);});
test('Recalled quest yields no prestige and planner recall works without selected creature',()=>{const e=clean(),p=e.s.progression.prestige;quest(e,false);e.s.colony.selectedId=null;const row=P.rows(e).find(r=>r.type==='quest');assert(P.act(e,row.key,'cancel').ok);assert(e.creatures[0].activeQuest.aborted);assert.equal(e.selected,null);e.commandActor('c1',()=>e.returnQuest(),{away:true});assert.equal(e.s.progression.prestige,p);});
test('An away creature has no interactions and rejects normal tasks',()=>{const e=clean();quest(e,false);assert.deepEqual(e.interactions(e.actor),[]);noChange(e,()=>P.add(e,{actorId:'c1',type:'gather',id:'wood',quantity:1}));});

// Physical markets: assertions check each ownership boundary, not just final coins.
test('Listing without a market stall fails without spending or reserving goods',()=>{const e=clean();e.s.buildings=e.s.buildings.filter(b=>b.kind!=='market');noChange(e,()=>e.sellItem('wood',2));});
test('Listing makes a plan but does not pay or teleport any stock',()=>{const e=clean();openAll(e);const coins=e.s.player.coins,stock=copy(e.s.colony.warehouse.inventory);assert(e.sellItem('wood',3,'c1').ok);assert.equal(e.s.player.coins,coins);assert.deepEqual(e.s.colony.warehouse.inventory,stock);assert.equal(e.s.market.orders[0].remaining,3);});
test('Pending warehouse sale cannot promise the same stock twice',()=>{const e=marketFixture();noChange(e,()=>e.sellItem('wood',18,'c1'));});
test('Market pickup, delivery and sale each update the correct inventory',()=>{const e=marketFixture(),coins=e.s.player.coins;assert.equal(marketStep(e).kind,'market-pickup');assert.equal(e.s.colony.warehouse.inventory.wood,16);assert.equal(e.actor.inventory.wood,4);assert.equal(e.s.player.coins,coins);assert.equal(marketStep(e).kind,'market-deliver');assert.equal(e.actor.inventory.wood,0);const stall=e.s.buildings.find(b=>b.kind==='market');assert.equal(stall.marketInventory.wood,4);assert.equal(e.s.player.coins,coins);assert.equal(marketStep(e).kind,'market-sell');assert.equal(stall.marketInventory.wood,0);assert.equal(e.s.market.orders[0].status,'done');assert(e.s.player.coins>coins);});
test('Market task completion is idempotent and cannot cancel another task',()=>{const e=marketFixture();marketStep(e);marketStep(e);const t=marketStep(e),before=snap(e);e.finishTask(t);assert.equal(snap(e),before);});
test('Pause preserves carrying commitments and prevents departure work',()=>{const e=marketFixture();marketStep(e);const id=e.s.market.orders[0].id;assert(e.controlSale(id,'pause').ok);assert.equal(e.marketTask(),null);assert.equal(e.actor.inventory.wood,4);assert(e.controlSale(id,'resume').ok);assert.equal(e.marketTask().kind,'market-deliver');});
test('Sale reassignment is blocked while another creature carries goods',()=>{const e=marketFixture();marketStep(e);noChange(e,()=>e.controlSale(e.s.market.orders[0].id,'assign','c2'));});
test('Cancel in transit releases claims but preserves personally carried goods',()=>{const e=marketFixture();marketStep(e);assert(e.controlSale(e.s.market.orders[0].id,'cancel').ok);assert.equal(e.actor.inventory.wood,4);assert(e.actor.needsDeposit);assert.equal(e.s.market.orders[0].transit.c1,0);assert.doesNotThrow(()=>L.Engine.import(e.export()));});
test('Cancel at stall creates actual reclaim work, never a remote refund',()=>{const e=marketFixture();marketStep(e);marketStep(e);const wh=e.s.colony.warehouse.inventory.wood;assert(e.controlSale(e.s.market.orders[0].id,'cancel').ok);assert.equal(e.s.colony.warehouse.inventory.wood,wh);assert.equal(marketStep(e).kind,'market-reclaim');assert.equal(e.actor.inventory.wood,4);assert(e.actor.needsDeposit);assert.equal(e.s.market.orders[0].status,'cancelled');});
for(const n of[0,1,2,3])test('Exact market save/restore at ownership stage '+n,()=>{const e=marketFixture();for(let i=0;i<n;i++)marketStep(e);const out=e.export(),loaded=S.commit(S.inspect(S.encode(e)));assert.deepEqual(loaded.export(),out);});
test('Real autonomous market fulfillment survives needs and pays only at stall',()=>{const e=marketFixture(),start=e.s.player.coins;for(const c of e.creatures)c.learning.paused=true;let seenCarry=false,seenStall=false;for(let i=0;i<2400&&e.s.market.orders[0].status!=='done';i++){e.step(.1);const q=e.s.market.orders[0];seenCarry||=q.status==='carrying';seenStall||=q.status==='at-stall';if(e.s.player.coins>start)assert(q.sold>0||e.s.ledger?.length);}assert.equal(e.s.market.orders[0].status,'done');assert(seenCarry&&seenStall);});

// Real planner adapters, interruption, authorization and reassignment.
test('Reading planner rows never changes simulation or inventory',()=>{const e=clean(),before=snap(e);P.rows(e);P.rows(e);assert.equal(snap(e),before);});
test('Planner adds an assigned gathering order and derives its queue row',()=>{const e=clean();assert(P.add(e,{actorId:'c2',type:'gather',id:'stone',quantity:3}).ok);const r=P.rows(e).find(r=>r.type==='order');assert.equal(r.actorId,'c2');assert.equal(e.creatures[1].orders[0].amount,3);assert.equal(e.selected.id,'c1');});
test('Planner pause, stop and resume control the underlying order',()=>{const e=clean();P.add(e,{actorId:'c1',type:'gather',id:'wood',quantity:4});let r=P.rows(e).find(r=>r.type==='order');assert(P.act(e,r.key,'pause').ok);assert(e.actor.orders[0].paused);assert(P.act(e,r.key,'stop').ok);assert(P.rows(e).find(r=>r.key===r.key).stopped);assert(P.act(e,r.key,'resume').ok);assert(!e.actor.orders[0].paused);});
test('Priorities are real order priorities and do not force footsteps',()=>{const e=clean();P.add(e,{actorId:'c1',type:'gather',id:'wood',quantity:4});const r=P.rows(e).find(r=>r.type==='order'),where=copy(e.actor.creature);assert(P.act(e,r.key,'priority',2).ok);assert.equal(e.actor.orders[0].priority,2);assert.deepEqual(e.actor.creature,where);});
test('Reassigning an order preserves its ID, paused state and policy',()=>{const e=clean();P.add(e,{actorId:'c1',type:'gather',id:'wood',quantity:4});const r=P.rows(e).find(r=>r.type==='order');P.act(e,r.key,'stop');const id=e.actor.orders[0].id;assert(P.act(e,r.key,'assign','c2').ok);assert.equal(e.actor.orders.length,0);assert.equal(e.creatures[1].orders[0].id,id);assert(P.rows(e).find(r=>r.type==='order').stopped);assert.doesNotThrow(()=>L.Engine.import(e.export()));});
test('Cancel removes only the intended order',()=>{const e=clean();P.add(e,{actorId:'c1',type:'gather',id:'wood',quantity:4});P.add(e,{actorId:'c2',type:'gather',id:'stone',quantity:4});const r=P.rows(e).find(r=>r.actorId==='c1'&&r.type==='order');assert(P.act(e,r.key,'cancel').ok);assert.equal(e.actor.orders.length,0);assert.equal(e.creatures[1].orders.length,1);});
test('Unstarted lesson reassignment keeps tuition, progress and paused policy',()=>{const e=clean(),id='metalwork';delete e.creatures[0].skills[id];delete e.creatures[1].skills[id];e.actor.researched[id]=true;e.s.player.coins=500;assert(e.teach(id).ok);const r=P.rows(e).find(r=>r.type==='lesson'),coins=e.s.player.coins;P.act(e,r.key,'pause');assert(P.act(e,r.key,'assign','c2').ok);assert.equal(e.s.player.coins,coins);const row=P.rows(e).find(r=>r.type==='lesson');assert.equal(row.actorId,'c2');assert(row.paused);});
test('Workplace assignment and pause affect actual worker claims',()=>{const e=clean(),b=e.s.buildings.find(b=>b.kind==='bench');assert(P.add(e,{actorId:'c2',type:'workplace',id:b.id,recipe:'planks',quantity:2}).ok);const r=P.rows(e).find(r=>r.type==='workplace');assert.equal(b.planAssignee,'c2');assert.equal(e.productionTask(b,'planks'),null);assert(P.act(e,r.key,'pause').ok);assert(!b.storage.enabled);assert(P.act(e,r.key,'resume').ok);assert(b.storage.enabled);});
test('Essential care rows reject stop and cancel',()=>{const e=clean();e.actor.task={kind:'rest',need:'energy',target:e.home(),phase:'work',path:[],duration:10,elapsed:0,label:'Resting'};const r=P.rows(e).find(r=>r.type==='activity');assert(r.protected);noChange(e,()=>P.act(e,r.key,'stop'));});
test('Stale task controls cannot mutate a completed queue',()=>{const e=clean();noChange(e,()=>P.act(e,'order:c1:gone','cancel'));});
test('Planner rejects invalid assignee, quantity and task definition',()=>{const e=clean();for(const input of[{actorId:'other',type:'gather',id:'wood',quantity:1},{actorId:'c1',type:'gather',id:'wood',quantity:-1},{actorId:'c1',type:'explode',id:'wood',quantity:2}])noChange(e,()=>P.add(e,input));});

// Data-driven interaction and event lifetime.
test('Registered base interactions are generated without event-only actions',()=>{const e=clean();for(const c of e.creatures)c.eventInteractions=[];const a=e.interactions(e.actor);assert.equal(a.length,C.content.interactions.filter(x=>!x.eventOnly).length);assert(!a.some(d=>d.eventOnly));});
test('A home event adds one contextual, single-use interaction',()=>{const e=clean();e.actor.eventInteractions=[];e.grantInteractionEvent('home-assigned','c1');e.grantInteractionEvent('home-assigned','c1');const a=e.interactions(e.actor).filter(d=>d.eventOnly);assert.equal(a.length,1);const instance=a[0].instance;assert(e.interact('c1',instance).ok);assert(!e.interactions(e.actor).some(d=>d.instance===instance));noChange(e,()=>e.interact('c1',instance));});
test('Interaction recipient is explicit and cannot target a different selection',()=>{const e=clean();noChange(e,()=>e.interact('c2','feed'));});
test('Temporary event interactions expire in simulation time, not view time',()=>{const e=clean();e.actor.eventInteractions=[];e.grantInteractionEvent('temper','c1');const a=e.interactions(e.actor).find(d=>d.eventOnly);assert(a);const before=snap(e);e.interactions(e.actor);assert.equal(snap(e),before);e.s.simTime=a.expires+1;assert(!e.interactions(e.actor).some(d=>d.instance===a.instance));});
test('Interaction costs use carried stock, not warehouse goods',()=>{const pack=copy(C.content),d=pack.interactions.find(d=>d.id==='settle-in');d.cost={berries:1};C.withLibrary(pack,()=>{const e=clean();e.actor.inventory.berries=0;e.s.colony.warehouse.inventory.berries=99;e.actor.eventInteractions=[];e.grantInteractionEvent('home-assigned','c1');const id=e.interactions(e.actor).find(d=>d.id==='settle-in').instance;noChange(e,()=>e.interact('c1',id));e.actor.inventory.berries=1;assert(e.interact('c1',id).ok);assert.equal(e.actor.inventory.berries,0);assert.equal(e.s.colony.warehouse.inventory.berries,99);});});
test('Custom bounded event interaction is valid and actually appears',()=>{const pack=copy(C.content);pack.interactions.push({...copy(pack.interactions.find(d=>d.id==='settle-in')),id:'island-celebration',label:'Celebrate our new island'});pack.events.push({id:'new-shore',trigger:'island-purchased',interaction:'island-celebration',seconds:120});assert(C.validate(pack).ok);C.withLibrary(pack,()=>{const e=rich(clean());assert(e.buyIsland(1,0).ok);assert(e.interactions(e.actor).some(d=>d.id==='island-celebration'));});});

// Import validation and registry safety.
test('Growth JSON defaults round-trip and preserve tool-owned metadata',()=>{const pack=copy(C.content);pack.extensions={externalTool:{revision:17,reviewed:true}};assert(C.validate(pack).ok);C.withLibrary(pack,()=>assert.deepEqual(C.content.extensions,pack.extensions));});
test('Unknown interaction handler and unknown item cost are rejected',()=>{const pack=copy(C.content);pack.interactions[0].handler='eval';assert(!C.validate(pack).ok);pack.interactions[0].handler='care';pack.interactions[0].cost={missing:1};assert(!C.validate(pack).ok);});
test('Current story format binds all four exact libraries',()=>{const e=clean(),save=S.encode(e);assert.equal(save.version,10);assert(save.growth?.library||save.growth?.content||save.growth);assert.deepEqual(S.commit(S.inspect(save)).export(),e.export());});
const invalidCases=[
 ['duplicate island',s=>{s.estate.islands.push({...s.estate.islands[0]});s.estate.purchases++;}],
 ['disconnected land',s=>{s.estate.islands.push({ix:3,iy:3,name:'Bad',biome:'Meadow'});s.estate.purchases++;}],
 ['negative prestige',s=>s.progression.prestige=-1],
 ['slots below population',s=>s.progression.slots=1],
 ['unknown home',s=>s.colony.creatures[0].homeId='missing'],
 ['unknown feature',s=>s.progression.features.unknown=1],
 ['forged planner operation',s=>s.planning.controls['order:c1:o99']={run:'code'}],
 ['invalid temporary event',s=>s.colony.creatures[0].eventInteractions.push({id:'bad',definition:'settle-in',expires:30,created:null,trigger:'home-assigned'})],
 ['negative event clock',s=>s.colony.creatures[0].interactionCooldowns['settle-in']=-1],
 ['blocked doorway',s=>{const b=s.buildings.find(b=>b.kind==='storehouse');b.door={dx:0,dy:0};}]
];
for(const[name,mutate]of invalidCases)test('Reject '+name+' without replacing active content',()=>{const e=clean(),save=S.encode(e),hash=C.hash;mutate(save.state);assert.throws(()=>S.inspect(save));assert.equal(C.hash,hash);});
test('Live growth-library application is blocked around committed work',()=>{const e=clean();P.add(e,{actorId:'c1',type:'gather',id:'wood',quantity:2});const before=snap(e),pack=copy(C.content);pack.rules.landCoinsBase++;assert.throws(()=>S.applyGrowth(pack,e));assert.equal(snap(e),before);});
test('Rejected random commands preserve exact state across 100 variants',()=>{const e=clean();for(let i=0;i<100;i++){noChange(e,()=>e.buyIsland(20+i,20));noChange(e,()=>e.sellItem('wood',-i-1));}});
const passed=results.filter(r=>r.passed).length;fs.writeFileSync(__dirname+'/v10-domain-results.json',JSON.stringify({suite:'v10 domain',passed,total:results.length,results},null,2));console.log(passed+'/'+results.length+' v10 domain checks passed');if(passed!==results.length)process.exitCode=1;
