'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const source=path.resolve(__dirname,'../source'),creatureRoot=path.join(source,'creatures'),assetRoot=path.join(source,'assets'),results=[];
function test(name,fn){try{fn();results.push({name,passed:true});}catch(error){results.push({name,passed:false,error:error.stack});console.error('FAIL',name,error.message);}}
const Creatures=require('./creature-catalog.js');require('./content-runtime.js');require('./behavior-tree.js');const Adventure=require('./adventure-content.js'),Factory=require('./creature-factory.js'),ActorECS=require('./actor-ecs.js');
global.LWAssetDefinitions=[];for(const category of fs.readdirSync(assetRoot,{withFileTypes:true}).filter(x=>x.isDirectory()))for(const entry of fs.readdirSync(path.join(assetRoot,category.name),{withFileTypes:true}).filter(x=>x.isDirectory())){const file=path.join(assetRoot,category.name,entry.name,'asset.json');if(fs.existsSync(file))global.LWAssetDefinitions.push(JSON.parse(fs.readFileSync(file,'utf8')));}
const Assets=require('./asset-catalog.js');
test('Creature catalog loads every isolated definition folder',()=>{const folders=fs.readdirSync(creatureRoot,{withFileTypes:true}).filter(x=>x.isDirectory());assert.equal(Creatures.all().length,folders.length);for(const d of Creatures.all())assert(fs.existsSync(path.join(creatureRoot,d.id,'creature.json')),d.id);});
test('Creature definitions are immutable and executable-free',()=>{const forbidden=new Set(['script','callback','execute','eval','sourceCode','modulePath','handler','command']);const visit=(v,p)=>{if(Array.isArray(v))v.forEach((x,i)=>visit(x,p+'/'+i));else if(v&&typeof v==='object')for(const[k,x]of Object.entries(v)){assert(!forbidden.has(k),p+'/'+k);visit(x,p+'/'+k);}};assert(Object.isFrozen(Creatures.all()));assert.throws(()=>Creatures.all().push({}),TypeError);for(const d of Creatures.all()){assert(Object.isFrozen(d));assert(Object.isFrozen(d.state.defaults));visit(d,d.id);}});
test('Adventure personality definitions cover the reusable creature profile set',()=>{assert.deepEqual([...Creatures.personalities].sort(),Adventure.content.personalities.map(p=>p.id).sort());});
test('Factory creates explicit deterministic archetype/personality identities',()=>{const founder=Factory.create({id:'c1',archetype:'sproutling',personality:'curious',mode:'founder',sequence:0,day:1,simTime:0}),arrival=Factory.create({id:'c2',archetype:'sproutling',personality:'maker',mode:'arrival',sequence:1,day:4,simTime:123});assert.equal(founder.archetype,'sproutling');assert.equal(founder.name,'Pip');assert.equal(founder.creature.x,8);assert.equal(founder.creature.coins,6);assert.equal(founder.rpg.rng,4631);assert.equal(arrival.archetype,'sproutling');assert.equal(arrival.name,'Fern');assert.equal(arrival.creature.x,17);assert.equal(arrival.creature.coins,0);assert.equal(arrival.rpg.rng,6544);assert.equal(arrival.learning.practiceDay,4);assert.equal(arrival.feelings.causes[0].time,123);assert.notEqual(founder.inventory,arrival.inventory);});
test('Creature ECS bindings are definition-driven authoritative references',()=>{const c=Factory.create({id:'c1',archetype:'sproutling',personality:'curious',mode:'founder',sequence:0,day:1,simTime:0}),runtime=ActorECS.create();runtime.sync([c]);for(const {type,field} of runtime.componentBindings(c))assert.equal(runtime.world.get(c.id,type),c[field]);assert.deepEqual(runtime.world.get(c.id,'Creature'),{archetype:'sproutling',personality:'curious'});});
test('Archetype identity and personality are independent validated contracts',()=>{assert(Creatures.supports('sproutling','curious'));assert(!Creatures.supports('sproutling','missing'));assert.throws(()=>Factory.create({id:'c9',archetype:'missing',personality:'curious',mode:'arrival',sequence:9,day:1,simTime:0}),/unsupported/);});
test('Every creature binding references an object-valued state component',()=>{for(const d of Creatures.all())for(const {type,field} of d.ecs.components){assert.equal(typeof d.state.defaults[field],'object',d.id+'/'+type);assert(d.state.defaults[field]&&!Array.isArray(d.state.defaults[field]),d.id+'/'+type);}});
test('Every persistent creature default has explicit actor ownership',()=>{for(const d of Creatures.all())assert.deepEqual([...d.state.personalFields].sort(),Object.keys(d.state.defaults).sort(),d.id);});
test('Current captured actors are fully covered by the creature-owned state contract',()=>{const fields=new Set(Creatures.personalFields);for(const file of ['littlewild.pack.json','emberworks.pack.json']){const pack=JSON.parse(fs.readFileSync(path.join(source,'content',file),'utf8'));for(const scene of pack.scenes)for(const c of scene.initialState.colony.creatures){assert.equal(c.archetype,'sproutling',file+'/'+c.id);for(const key of Object.keys(c))if(key!=='id')assert(fields.has(key),file+'/'+c.id+'/'+key);}}});
test('Every creature has complete data-authored visual profiles',()=>{for(const d of Creatures.all()){const actor=Assets.actor(d.id);assert(actor,d.id);assert.deepEqual(Object.keys(actor.behaviors.appearances).sort(),[...d.personalities].sort());for(const personality of d.personalities){const view=actor.behaviors.appearances[personality];assert(actor.models[view.model],personality+'/'+view.model);assert.equal(view.scale.length,3);assert(view.labelHeight>0&&view.contextHeight>0&&view.bubbleHeight>0);}}});
test('Actor animation and expression tuning are data and remain finite',()=>{for(const d of Creatures.all()){const actor=Assets.actor(d.id),animation=actor.behaviors.animation,expression=actor.behaviors.expression;for(const [key,value] of Object.entries(animation))assert(Number.isFinite(value),key);for(const [key,value] of Object.entries(expression)){assert(Number.isFinite(value),key);assert(value>=0&&value<=100,key);}}});
test('Presentation code uses explicit creature archetype identity',()=>{for(const file of ['ui.ts','colony-ui.ts','world-fidelity.ts']){const text=fs.readFileSync(path.join(source,file),'utf8');assert(!text.includes('forPersonality('),file);}});
test('Recruitment and fidelity contain no hard-coded creature template or visual variant tables',()=>{const colony=fs.readFileSync(path.join(source,'colony.ts'),'utf8'),village=fs.readFileSync(path.join(source,'village-systems.ts'),'utf8'),fidelity=fs.readFileSync(path.join(source,'world-fidelity.ts'),'utf8'),renderer=fs.readFileSync(path.join(source,'asset-renderer.ts'),'utf8');assert(!colony.includes('decorateActor'));assert(!colony.includes("constructThrough('systems').s"));assert(!colony.includes("names = ['Pip'"));assert(!village.includes('eventInteractions||='));assert(!village.includes('interactionCooldowns||='));assert(!fidelity.includes('const swatches='));assert(!fidelity.includes("forPersonality("));assert(!fidelity.includes("'sproutling'"));assert(!fidelity.includes("'world-round'"));assert(!renderer.includes("id='sproutling'"));});
test('Creature catalog rejects nested schema drift, mismatched identity and invalid spawn modes',()=>{const raw=JSON.parse(fs.readFileSync(path.join(creatureRoot,'sproutling','creature.json'),'utf8')),bad=JSON.parse(JSON.stringify(raw));bad.movement.typo=1;assert.throws(()=>Creatures.validate(bad),/movement/);const identity=JSON.parse(JSON.stringify(raw));identity.state.defaults.archetype='other';assert.throws(()=>Creatures.validate(identity),/archetype/);const extra=JSON.parse(JSON.stringify(raw));extra.state.defaults.unowned={};assert.throws(()=>Creatures.validate(extra),/actor-scoped/);assert.throws(()=>Creatures.seed('sproutling','curious','sideways',0),/mode/);assert.throws(()=>Factory.create({id:'c9',archetype:'sproutling',personality:'curious',mode:'sideways',sequence:9,day:1,simTime:0}),/creation options/);});
test('Creature authoring schema is shipped beside the catalog',()=>{const schema=JSON.parse(fs.readFileSync(path.join(creatureRoot,'creature.schema.json'),'utf8'));assert.equal(schema.title,'Littlewild Creature Definition');assert.equal(schema.properties.format.const,'littlewild-creature');});
const passed=results.filter(r=>r.passed).length,report={passed,total:results.length,creatures:Creatures.all().length,results};fs.writeFileSync(__dirname+'/creature-catalog-results.json',JSON.stringify(report,null,2));console.log(passed+'/'+results.length);if(passed!==results.length)process.exitCode=1;
