'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const E=require('./economy-ecs.js');
const results=[];
function test(name,fn){try{fn();results.push({name,passed:true});}catch(error){results.push({name,passed:false,error:error.stack});console.error('FAIL',name,error.message);}}
function state(){return {player:{level:1,xp:0,coins:20},creature:{level:1,xp:0,coins:5},bond:10,rp:3,stats:{earned:0,researchEarned:0},completedQuests:[],ledger:[],log:[],progression:{prestige:4,earnedPrestige:4}};}
function actor(s){return {id:'c1',creature:s.creature,bond:s.bond,stats:s.stats,rpg:{cp:0}};}
test('Atomic settlement applies wallets, research, stats and prestige',()=>{const s=state(),a=actor(s),ecs=E.create();const r=ecs.settle(s,a,{id:'reward:all',guide:4,pocket:2,research:3,prestige:5,earnedPrestige:5,stats:{earned:6},actorCpPerLevel:2});assert.equal(r.state,'settled');assert.equal(s.player.coins,24);assert.equal(a.creature.coins,7);assert.equal(s.rp,6);assert.equal(a.stats.researchEarned,3);assert.equal(a.stats.earned,6);assert.equal(s.progression.prestige,9);assert.equal(s.progression.earnedPrestige,9);});
test('Insufficient balances block the entire settlement',()=>{const s=state(),a=actor(s),before=JSON.stringify(s),ecs=E.create();const r=ecs.settle(s,a,{id:'spend:blocked',guide:-21,pocket:4,research:2});assert.equal(r.state,'blocked');assert.equal(JSON.stringify(s),before);});
test('Explicit IDs settle once per runtime',()=>{const s=state(),a=actor(s),ecs=E.create(),spec={id:'reward:once',guide:5};assert.equal(ecs.settle(s,a,spec).state,'settled');assert.equal(ecs.settle(s,a,spec).state,'duplicate');assert.equal(s.player.coins,25);});
test('Chapter markers remain idempotent after ECS reconstruction',()=>{const s=state(),a=actor(s),spec={id:'chapter:first',chapterId:'first',guide:2};assert.equal(E.create().settle(s,a,spec).state,'settled');assert.deepEqual(s.completedQuests,['first']);assert.equal(E.create().settle(s,a,spec).state,'duplicate');assert.equal(s.player.coins,22);});
test('Player level-up applies research bonus and returns neutral outbox events',()=>{const s=state(),a=actor(s);s.player.xp=35;const r=E.create().settle(s,a,{id:'xp:player',playerXp:2});assert.equal(s.player.level,2);assert.equal(s.player.xp,1);assert.equal(s.rp,5);assert.equal(a.stats.researchEarned,2);assert.deepEqual(r.levelUps,[{who:'player',level:2}]);assert.equal(r.levelResearch,2);});
test('Actor level-up applies bond and configured character points',()=>{const s=state(),a=actor(s);a.creature.xp=35;const r=E.create().settle(s,a,{id:'xp:actor',actorXp:2,actorCpPerLevel:3});assert.equal(a.creature.level,2);assert.equal(a.creature.xp,1);assert.equal(a.bond,12);assert.equal(a.rpg.cp,3);assert.deepEqual(r.levelUps,[{who:'actor',level:2}]);assert.equal(r.actorCp,3);});
test('Prestige spending never reduces earned prestige',()=>{const s=state(),a=actor(s),r=E.create().settle(s,a,{id:'prestige:spend',prestige:-3});assert.equal(r.state,'settled');assert.equal(s.progression.prestige,1);assert.equal(s.progression.earnedPrestige,4);});
test('Missing prestige state blocks prestige mutations without wallet changes',()=>{const s=state(),a=actor(s);delete s.progression;const before=JSON.stringify(s);const r=E.create().settle(s,a,{id:'prestige:missing',prestige:1,guide:1});assert.equal(r.state,'blocked');assert.equal(JSON.stringify(s),before);});
test('Income split is deterministic and data driven',()=>{const ecs=E.create();assert.deepEqual(ecs.splitIncome(11),{guide:8,pocket:3});assert.throws(()=>ecs.splitIncome(-1),/income/);});
test('Settlement never writes presentation or journal records',()=>{const s=state(),a=actor(s);E.create().settle(s,a,{id:'reward:quiet',guide:1,research:1});assert.deepEqual(s.ledger,[]);assert.deepEqual(s.log,[]);});
test('Failed system execution rolls every authoritative record back',()=>{const rules=JSON.parse(JSON.stringify(require('./content/economy-rules.json')));rules.limits.level=1;const s=state(),a=actor(s),before=JSON.stringify({s,a});s.player.xp=35;const expected=JSON.stringify({s,a});assert.throws(()=>E.create(rules).settle(s,a,{id:'rollback:level',guide:3,research:2,playerXp:2}),/limit/);assert.equal(JSON.stringify({s,a}),expected);});
test('Actor wallets remain isolated while shared balances settle once',()=>{const s=state(),a=actor(s),b={id:'c2',creature:{level:1,xp:0,coins:9},bond:5,stats:{earned:0,researchEarned:0},rpg:{cp:0}},ecs=E.create();ecs.settle(s,a,{id:'actor:a',pocket:2,guide:1});ecs.settle(s,b,{id:'actor:b',pocket:3,research:1});assert.equal(a.creature.coins,7);assert.equal(b.creature.coins,12);assert.equal(s.player.coins,21);assert.equal(s.rp,4);});
const passed=results.filter(r=>r.passed).length;fs.writeFileSync(__dirname+'/economy-ecs-results.json',JSON.stringify({passed,total:results.length,failed:results.length-passed,results},null,2)+'\n');console.log(`${passed}/${results.length} economy ECS checks passed`);if(passed!==results.length)process.exitCode=1;
