'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const source=path.resolve(__dirname,'../source'),creatureRoot=path.join(source,'creatures'),assetRoot=path.join(source,'assets'),results=[];
function test(name,fn){try{fn();results.push({name,passed:true});}catch(error){results.push({name,passed:false,error:error.stack});console.error('FAIL',name,error.message);}}
const Creatures=require('./creature-catalog.js');require('./content-runtime.js');require('./behavior-tree.js');const Adventure=require('./adventure-content.js'),Factory=require('./creature-factory.js'),ActorECS=require('./actor-ecs.js');
global.LWAssetDefinitions=[];for(const category of fs.readdirSync(assetRoot,{withFileTypes:true}).filter(x=>x.isDirectory()))for(const entry of fs.readdirSync(path.join(assetRoot,category.name),{withFileTypes:true}).filter(x=>x.isDirectory())){const file=path.join(assetRoot,category.name,entry.name,'asset.json');if(fs.existsSync(file))global.LWAssetDefinitions.push(JSON.parse(fs.readFileSync(file,'utf8')));}
const Assets=require('./asset-catalog.js');
test('Creature catalog loads every isolated definition folder',()=>{const folders=fs.readdirSync(creatureRoot,{withFileTypes:true}).filter(x=>x.isDirectory());assert.equal(Creatures.all().length,folders.length);for(const d of Creatures.all())assert(fs.existsSync(path.join(creatureRoot,d.id,'creature.json')),d.id);});
test('Creature definitions are immutable and executable-free',()=>{const forbidden=new Set(['script','callback','execute','eval','sourceCode','modulePath','handler','command']);const visit=(v,p)=>{if(Array.isArray(v))v.forEach((x,i)=>visit(x,p+'/'+i));else if(v&&typeof v==='object')for(const[k,x]of Object.entries(v)){assert(!forbidden.has(k),p+'/'+k);visit(x,p+'/'+k);}};for(const d of Creatures.all()){assert(Object.isFrozen(d));assert(Object.isFrozen(d.state.defaults));visit(d,d.id);}});
test('Adventure personality IDs exactly match bundled creature profiles',()=>{assert.deepEqual([...Creatures.personalities].sort(),Adventure.content.personalities.map(p=>p.id).sort());});
test('Factory creates deterministic founder and arrival state without a template engine',()=>{const founder=Factory.create({id:'c1',personality:'curious',mode:'founder',sequence:0,day:1,simTime:0}),arrival=Factory.create({id:'c2',personality:'maker',mode:'arrival',sequence:1,day:4,simTime:123});assert.equal(founder.name,'Pip');assert.equal(founder.creature.x,8);assert.equal(founder.creature.coins,6);assert.equal(arrival.name,'Fern');assert.equal(arrival.creature.x,17);assert.equal(arrival.creature.coins,0);assert.equal(arrival.learning.practiceDay,4);assert.equal(arrival.feelings.causes[0].time,123);assert.notEqual(founder.inventory,arrival.inventory);});
test('Creature ECS bindings are definition-driven authoritative references',()=>{const c=Factory.create({id:'c1',personality:'curious',mode:'founder',sequence:0,day:1,simTime:0}),runtime=ActorECS.create();runtime.sync([c]);for(const {type,field} of runtime.componentBindings(c))assert.equal(runtime.world.get(c.id,type),c[field]);assert.deepEqual(runtime.world.get(c.id,'Creature'),{definitionId:'sproutling',personality:'curious'});});
test('Every creature binding references an object-valued state component',()=>{for(const d of Creatures.all())for(const {type,field} of d.ecs.components){assert.equal(typeof d.state.defaults[field],'object',d.id+'/'+type);assert(d.state.defaults[field]&&!Array.isArray(d.state.defaults[field]),d.id+'/'+type);}});
test('Every persistent creature default has explicit actor ownership',()=>{for(const d of Creatures.all())assert.deepEqual([...d.state.personalFields].sort(),Object.keys(d.state.defaults).sort(),d.id);});
test('Every creature has complete data-authored visual profiles',()=>{for(const d of Creatures.all()){const actor=Assets.actor(d.id);assert(actor,d.id);assert.deepEqual(Object.keys(actor.behaviors.appearances).sort(),[...d.personalities].sort());for(const personality of d.personalities){const view=actor.behaviors.appearances[personality];assert(actor.models[view.model],personality+'/'+view.model);assert.equal(view.scale.length,3);assert(view.labelHeight>0&&view.contextHeight>0&&view.bubbleHeight>0);}}});
test('Actor animation tuning is data and remains finite',()=>{for(const d of Creatures.all()){const animation=Assets.actor(d.id).behaviors.animation;for(const [key,value] of Object.entries(animation))assert(Number.isFinite(value),key);}});
test('Recruitment and fidelity contain no hard-coded creature template or visual variant tables',()=>{const colony=fs.readFileSync(path.join(source,'colony.ts'),'utf8'),fidelity=fs.readFileSync(path.join(source,'world-fidelity.ts'),'utf8'),renderer=fs.readFileSync(path.join(source,'asset-renderer.ts'),'utf8');assert(!colony.includes('decorateActor'));assert(!colony.includes("constructThrough('systems').s"));assert(!colony.includes("names = ['Pip'"));assert(!fidelity.includes('const swatches='));assert(!fidelity.includes("'sproutling'"));assert(!fidelity.includes("'world-round'"));assert(!renderer.includes("id='sproutling'"));});
test('Creature authoring schema is shipped beside the catalog',()=>{const schema=JSON.parse(fs.readFileSync(path.join(creatureRoot,'creature.schema.json'),'utf8'));assert.equal(schema.title,'Littlewild Creature Definition');assert.equal(schema.properties.format.const,'littlewild-creature');});
const passed=results.filter(r=>r.passed).length,report={passed,total:results.length,creatures:Creatures.all().length,results};fs.writeFileSync(__dirname+'/creature-catalog-results.json',JSON.stringify(report,null,2));console.log(passed+'/'+results.length);if(passed!==results.length)process.exitCode=1;
