/* Story, import-review and preference panels. Imported and authored text retains the shared escaping boundary. */
(function(root){
 'use strict';
 function create(shell){
    const {$,RECIPES,RES,SKILLS,allowanceMarkup,esc,forecastMarkup,icon,journalEntry,modalFooter,modalHead,pauseToggleMarkup,taskETA,timeLabel,ui}=shell;
    function extraModalMarkup() {
        const experienceMarkup=shell.scenarioUI?.render(ui.modal);if(experienceMarkup!=null)return experienceMarkup;
        if(ui.modal==='world-visuals')return modalHead('A world that feels at home.','Presentation preferences never change work, dice, rewards or saved content definitions.','GRAPHICS & INPUT')+`<div class="modal-body v12-visuals">${pauseToggleMarkup()}<h3>Rendering quality</h3><div class="v12-quality-options">${[['eco','Gentle','Lower rendering resolution; no WebGL shadows.'],['balanced','Balanced','Moderate resolution and a single shadow-casting light.'],['high','Detailed','Higher resolution and sharper WebGL shadows.']].map(([id,name,desc])=>`<button class="btn ${shell.world.quality===id?'primary':''}" data-act="v12-quality" data-id="${id}" ${shell.world.rendererId&&shell.world.rendererId!=='basic'||shell.world.rendererDimension==='2d'?'disabled title="Rendering quality is managed by the active renderer."':''} aria-pressed="${shell.world.quality===id}"><strong>${name}</strong><small>${desc}</small></button>`).join('')}</div><p>Active renderer: <strong>${esc(shell.world.mode)}</strong>. Software 3D uses simplified lighting and a bounded scenery cache. Hardware WebGL performance depends on your device.</p><button class="btn" data-act="v12-motion" aria-pressed="${shell.engine.s.settings.reducedMotion}">${shell.engine.s.settings.reducedMotion?'Enable':'Reduce'} motion</button><h3>Selection & companion labels</h3><p class="v14-selection-help">Names and ground rings follow the same rendered creature position. While the world runs, interaction controls stay where you opened them; use Locate to bring your companion back into view. Overlapping names separate into stable rows, and the roster remains available for off-screen companions.</p><h3>Hands on the world</h3><dl><dt>Inspect</dt><dd>Click a creature, building or resource.</dd><dt>Tile actions</dt><dd>Right-click, hold for a moment, or use the ⋯ camera button.</dd><dt>Keyboard</dt><dd>Focus the world. Shift + arrows selects a tile; Shift + F10 or Enter opens its actions. Arrows pan. + / − zoom. H recenters.</dd><dt>While a menu is open</dt><dd>Arrows move between actions, Enter activates, Escape closes. Time follows your pause-on-open preference. Use Pause time inside a panel whenever you need it.</dd></dl><p>Pausing freezes work and walking animations. Lower quality and reduced motion never reduce rewards.</p></div>`+modalFooter();
        const s = shell.engine.s, m = $('modal');
        const villageMarkup=shell.villageUI.render(ui.modal);if(villageMarkup!==null)return villageMarkup;
        const landMarkup=shell.worldExplorer.render(ui.modal);if(landMarkup!==null)return landMarkup;
        const colonyMarkup=shell.colonyUI.render(ui.modal,ui.modalId);
        if(colonyMarkup!==null)return colonyMarkup;
        const contentMarkup=shell.contentUI.render(ui.modal,ui.modalId);
        if(contentMarkup!==null)return contentMarkup;
        const featureMarkup=shell.progressionUI.render(ui.modal,ui.modalId);
        if(featureMarkup!==null) return featureMarkup;
        if (ui.modal === 'pantry')
            return modalHead('A little ready for tomorrow.', 'Set comfortable reserves, not chores. Pip replenishes them after needs, lessons and shared plans.', 'OUR PANTRY') + `<div class="modal-body"><div class="notice-box">${icon('leaf')}Targets are minimums, not limits. Small harvests and recipe batches can leave a little extra. A target of zero turns automatic stocking off.</div><div class="pantry-head"><span>Shared supplies</span><span>In store</span><span>Keep at least</span></div>${Object.entries(RES).map(([id, r]) => { const issue = shell.engine.assessResource(id, Math.max(1, s.stockTargets[id])); return `<div class="pantry-row"><div>${icon(r.icon)}<span><strong>${esc(r.name)}</strong><small>${issue ? esc(issue.text||issue) : RECIPES[id] ? 'Made in whole recipe batches' : id === 'meat' ? 'Tracking expeditions' : LWWorldContent.content.nodes.some(n=>n.resource===id&&n.mode==='finite')?'Finite deposits in the glade':'Infinite default source'}</small></span></div><strong>${s.inventory[id]}</strong><label><span class="sr-only">Keep ${esc(r.name)}</span><input type="number" min="0" max="24" step="1" value="${s.stockTargets[id]}" data-stock-target="${id}" aria-label="${esc(r.name)} stock target"></label></div>`; }).join('')}<div class="modal-actions"><button class="btn" data-act="stock-preset" data-id="essentials">Essentials only</button><button class="btn" data-act="stock-preset" data-id="builder">Prepared builder</button></div>${forecastMarkup()}</div>` + modalFooter();
        if (ui.modal === 'ledger')
            return modalHead('Two wallets. A little trust.', 'Follow the actual coins and research. Your allowance is a gift limit, never a leash.', 'OUR MONEY & CHOICES') + `<div class="modal-body"><div class="balance-cards"><div>${icon('coin')}<strong>${s.player.coins}</strong><span>Your guide coins</span></div><div>${icon('bag')}<strong>${s.creature.coins}</strong><span>${esc(s.name)}’s pocket coins</span></div><div>${icon('research')}<strong>${s.rp}</strong><span>Shared research</span></div></div><div class="economy-settings">${allowanceMarkup()}<section class="shopping-settings"><h3>Room to make choices</h3><label for="sourcing-select">For our plans, encourage…</label><select id="sourcing-select"><option value="balanced" ${s.allowance.sourcing === 'balanced' ? 'selected' : ''}>Make & gather; shop if a source is empty</option><option value="gather" ${s.allowance.sourcing === 'gather' ? 'selected' : ''}>Gather & make our own supplies</option><option value="shop" ${s.allowance.sourcing === 'shop' ? 'selected' : ''}>Use the market when affordable</option></select><label for="pocket-reserve">Keep some pocket savings</label><div class="reserve-control"><input id="pocket-reserve" type="number" min="0" max="30" step="1" value="${s.allowance.reserve}"><span>coins</span></div><p class="muted micro">Pip keeps this reserve when buying building supplies. Food and water can use it in an emergency. No preference forces a purchase or spends your guide coins. An empty wallet always has a free gathering fallback.</p></section></div><div class="section-heading"><h3>Our recent transactions</h3><span class="tiny-tag">Last 80 entries</span></div><div class="ledger-head"><span>Moment</span><span>You</span><span>${esc(s.name)}</span><span>Research</span></div>${s.ledger.length ? s.ledger.map(e => `<div class="ledger-row"><span>${esc(e.label)}<small>Day ${e.day} · ${timeLabel(e.hour)}</small></span>${[e.guide, e.pocket, e.research].map(n => `<strong class="${n > 0 ? 'income' : n < 0 ? 'expense' : 'muted'}">${n > 0 ? '+' : ''}${n || '—'}</strong>`).join('')}</div>`).join('') : '<p class="muted empty-state">New transactions will appear here. Earlier balances are carried forward; the ledger does not invent past transactions.</p>'}</div>` + modalFooter();
        if (ui.modal === 'decision') {
            const d = shell.engine.decisionSummary(), t = s.task;
            return modalHead('A mind of my own.', 'Suggestions matter. Pip’s needs and decisions still come first.', 'UNDERSTANDING ' + esc(s.name).toUpperCase()) + `<div class="modal-body"><div class="decision-hero"><span class="status-tag active">${d.source}</span><h3>${esc(t?.label || 'Thinking about my next step')}</h3><blockquote>“${esc(t?.thought || 'There’s a whole little world to notice.')}”</blockquote><p>${esc(t?.reason || 'I’m choosing what comes next.')}</p>${t ? `<div class="decision-timing">${icon('clock')} About ${taskETA(t)} left · ${t.phase === 'walk' ? 'walking there' : 'making progress'}</div>` : ''}</div><div class="decision-priorities">${[['1', 'Care comes first', 'Food, water, energy, warmth and joy. I can pause work without losing construction or lesson progress.'], ['2', 'A lesson, when I’m ready', s.training ? 'Learning ' + SKILLS[s.training.id].short + ' next.' : 'There is no lesson waiting right now.'], ['3', 'One shared plan at a time', s.orders.length ? s.orders.length + ' idea(s) to consider. Runnable ideas can pass a blocked plan.' : 'You haven’t suggested any work. There’s no need to invent chores.'], ['4', 'A life beyond our plans', 'Keep a few pantry reserves, follow curiosity, research or enjoy the glade.']].map(([n, h, p]) => `<div><span>${n}</span><section><h4>${h}</h4><p>${esc(p)}</p></section></div>`).join('')}</div><div class="modal-actions"><button class="btn" data-act="plans">${icon('plan')}Our plan board</button><button class="btn" data-act="pantry">${icon('bag')}Pantry reserves</button></div></div>` + modalFooter();
        }
        if (ui.modal === 'journal')
            return modalHead('The little moments add up.', 'Important memories stay separate from the day-to-day activity log.', 'OUR SHARED STORY') + `<div class="modal-body"><div class="filter-chips journal-filters" role="group" aria-label="Journal section">${[['memories', 'Memories to keep'], ['activity', 'Recent activity']].map(([id, label]) => `<button class="chip ${ui.journalTab === id ? 'active' : ''}" aria-pressed="${ui.journalTab === id}" data-act="journal-filter" data-id="${id}">${label}</button>`).join('')}</div>${ui.journalTab === 'memories' ? `<div class="memory-grid">${s.memories.length ? s.memories.map(e => `<article class="memory-card">${icon(e.icon)}<time>Day ${e.day} · ${timeLabel(e.hour)}</time><h3>${esc(e.title)}</h3><p>${esc(e.description)}</p></article>`).join('') : '<p class="muted">Our first wish, learned skill or finished home will become a memory here.</p>'}</div>` : `<div class="journal-full">${s.log.map(e => journalEntry(e)).join('') || '<p class="muted">A fresh page. A whole world ahead.</p>'}</div>`}</div>` + modalFooter();
        if (ui.modal === 'confirm-cancel') {
            m.classList.add('small-modal');
            const o = s.orders.find(o => o.id === ui.confirmOrder);
            if (!o)
                return modalHead('That idea is already complete.') + modalFooter();
            return modalHead('Set this idea aside?', 'Nothing needs to be rushed.', 'A CHANGE OF PLANS') + `<div class="modal-body"><h3>${esc(shell.engine.orderName(o))}</h3><p class="muted">${['build','upgrade'].includes(o.type) ? 'Current-stage supplies and half the earlier installed materials become salvage at the site, rounded down per material. The creature must collect and deposit that salvage before it is available in the warehouse.' : 'Materials already gathered or crafted stay in their current satchel or warehouse location.'}</p><div class="modal-actions"><button class="btn danger" data-act="confirm-cancel" data-id="${o.id}">Set aside</button><button class="btn" data-act="order" data-id="${o.id}">Keep our plan</button></div></div>` + modalFooter();
        }
        if (ui.modal === 'import-preview') {
            m.classList.add('small-modal');
            const incoming = ui.pendingImport?.engine.s;
            if (!incoming)
                return modalHead('No story selected.') + modalFooter();
            const profile=ui.pendingImport.experience?.simulation||ui.pendingImport.engine.simulationProfile;
            return modalHead('Bring this story home?', 'Review it before replacing the current glade.', 'IMPORT PREVIEW') + `<div class="modal-body"><div class="import-summary"><h3>${esc(incoming.name)} · Day ${incoming.day}</h3><p>${incoming.colony.creatures.length} companions · ${incoming.buildings.length} places · Guide level ${incoming.player.level}</p><p>${incoming.player.coins} guide coins · ${Object.values(incoming.colony.warehouse.inventory).reduce((a,b)=>a+b,0)} deposited items</p>${ui.pendingImport.migrationNotes?.length?'<div class="quality-notice"><strong>Compatibility changes</strong>'+ui.pendingImport.migrationNotes.map(n=>'<p>'+esc(n)+'</p>').join('')+'</div>':''}${incoming.colony.creatures.map(c=>`<p><strong>${esc(c.name)}</strong> · Level ${c.creature.level} · ${Object.values(c.skills).filter(Boolean).length} skills · ${c.activeQuest?'away on '+esc(c.activeQuest.name):c.questPlan?'preparing a quest':'in the glade'}</p>`).join('')}</div><div class="notice-box"><strong>Content library: ${esc(ui.pendingImport.library.library.name)} · v${esc(ui.pendingImport.library.library.version)}</strong><p>${ui.pendingImport.changesLibrary?'This story restores its own content definitions. The current library will change too.':'This story uses the same content definitions as your current library.'} Source save: v${ui.pendingImport.sourceVersion}.</p></div>${profile?`<div class="notice-box"><strong>Simulation profile: ${esc(profile.name)} · ${esc(profile.archetype.id)}</strong><p>${ui.pendingImport.changesSimulation?'This story restores its own validated actor/economy tuning.':'This story uses the same simulation profile as the current runtime.'} Imported JSON cannot add or reorder systems.</p></div>`:''}<div class="notice-box">${icon('book')}Your current story is still untouched. ${shell.saveAvailable ? 'A local recovery copy will be attempted when you confirm. Export first for a portable backup.' : 'Local saving is unavailable. Export your current story before replacing it.'}</div><div class="modal-actions"><button class="btn" data-act="export">${icon('download')}Export current story</button><button class="btn primary" data-act="confirm-import">Bring this story home</button></div></div>` + modalFooter();
        }
        if (ui.modal === 'tour') {
            const cards = [['You are a friend, not a cursor.', 'Clicking the ground never moves Pip. The thought card tells you the current activity. “Why this?” explains the decision.', 'paw'], ['First, check the little essentials.', 'Offer a snack, water or company from Care. A full tummy needs no extra food. Recent effort is a good time for praise.', 'heart'], ['Research opens a possibility.', 'Explore 28 lessons in four tiers. Research with shared points, then buy and queue up to four ready lessons. Practice uses real supplies; talents shape Pip’s strengths. Return to the glade to learn.', 'book'], ['Place the plan. Pip handles the how.', 'The atlas has 22 places. Each project has three stages and reserves only the current stage’s supplies. Choose a construction approach. Improve completed places through three levels; the old building stays usable.', 'home'], ['Plan tomorrow, without dictating today.', 'Pantry reserves let Pip keep essentials in stock. The plan board explains ready, active and blocked ideas. Give a quantity, not a movement command.', 'plan'], ['Let a little independence grow.', 'A market lets Pip spend pocket coins. Set daily allowance, savings and sourcing preferences in the ledger. Save export is your portable backup.', 'coin']];
            const card = cards[ui.tourStep];
            m.classList.add('small-modal');
            return modalHead('A little look around.', 'The world waits while you read.', 'FIELD NOTES · ' + (ui.tourStep + 1) + ' / ' + cards.length) + `<div class="modal-body tour-page"><div class="tour-icon">${icon(card[2])}</div><h3>${card[0]}</h3><p>${card[1]}</p><div class="tour-dots">${cards.map((_, i) => `<button data-act="tour-step" data-id="${i}" class="${i === ui.tourStep ? 'active' : ''}" aria-label="Tour step ${i + 1}" aria-current="${i === ui.tourStep ? 'step' : 'false'}">${i + 1}</button>`).join('')}</div><div class="modal-actions"><button class="btn" data-act="tour-step" data-id="${Math.max(0, ui.tourStep - 1)}" ${ui.tourStep === 0 ? 'disabled' : ''}>Back</button><button class="btn primary" data-act="${ui.tourStep === 5 ? 'close-modal' : 'tour-step'}" data-id="${ui.tourStep + 1}">${ui.tourStep === 5 ? 'Back to our glade' : 'Next little step'} ${icon('arrow')}</button></div></div>` + modalFooter();
        }
        return '';
    }
    return {extraModalMarkup};
 }
 const api={create};root.LWInterfaceStoryPanels=api;
 if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(globalThis);
