/* World-first village workspaces and a live, derived planner. No inventory changes
 * happen here: every action is routed through the authoritative domain command. */
(function(root){'use strict';const P=root.LWPlanner,C=root.LWGrowth,G=root.LWGeography,L=root.LW;
 function create(h){const $=id=>document.getElementById(id),esc=h.esc,ic=h.icon,E=h.engine;
  const state={open:false,filter:'all',search:'',system:'all',form:{type:'gather',actorId:'',id:'',quantity:3,recipe:''},pending:null,importPreview:null,readId:0,libraryHash:'',lastList:'',lastUpdate:0,researchTab:'available',lastEngine:null,island:'0,0',mapFilter:'all',mapShown:true};
  const button=(label,action,id='',cls='',disabled=false)=>`<button class="btn ${cls}" data-act="v10-${action}" data-id="${esc(id)}" ${disabled?'disabled':''}>${label}</button>`;
  const items=o=>Object.entries(o||{}).map(([id,n])=>`${n} ${esc(L.colony.item(id)?.name||id)}`).join(' · ');
  const note=(text,kind='')=>`<div class="v10-note ${kind}">${text}</div>`;
  const slots=()=>E().s.progression,available=()=>E().creatures.filter(c=>!c.activeQuest),labels={research:'Discoveries',homes:'Homes & companions',land:'World map',shop:'Prestige shop',market:'Market deliveries',guide:'Getting started',library:'Growth library'};
  const panel=document.createElement('aside');panel.id='v10-planner';panel.hidden=true;panel.setAttribute('aria-label','Creature planner');panel.innerHTML=`<header><div><span class="v10-eyebrow">A LITTLE DIRECTION</span><h2>Our plans <small id="v10-plan-count">0</small></h2></div>${button(ic('close'),'planner-close','','v10-icon')}</header><p class="v10-panel-intro">You choose the work. They choose their next step.</p><div class="v10-planner-top">${button(ic('plus')+' New task','new-task','','primary')}<span id="v10-planner-clock">World running</span></div><div class="v10-planner-filters"><label><span class="sr-only">Find a task</span><input id="v10-plan-search" placeholder="Find a task or creature…" type="search"></label><label><span class="sr-only">Filter by creature</span><select id="v10-plan-filter"><option value="all">Every creature</option></select></label></div><div id="v10-plan-list" tabindex="-1"></div><footer>Protected self-care comes first. “Stop” holds a plan and releases its worker; “Cancel” ends it safely.</footer>`;
  $('app').appendChild(panel);panel.querySelector('[data-act="v10-planner-close"]').setAttribute('aria-label','Close planner');
  const growth=document.createElement('button');growth.id='v10-growth-chip';growth.className='stat-pod wallet-button';growth.dataset.act='v10-open';growth.dataset.id='research';growth.title='Player progression and research';growth.innerHTML=`<span class="stat-icon">${ic('star')}</span><div><strong id="v10-prestige">0</strong><small>Prestige · <span id="v10-guide-level">Lv. 1</span></small></div>`;$('app').querySelector('.header-center').appendChild(growth);
  const more=$('world-more');for(const[id,name]of Object.entries(labels)){const b=document.createElement('button');b.dataset.act='v10-open';b.dataset.id=id;b.textContent=name;more.insertBefore(b,more.querySelector('.w7-fine'));}
  const landButton=document.createElement('button');landButton.dataset.act='v10-open';landButton.dataset.id='land';landButton.innerHTML=ic('route')+'<span>Islands</span>';landButton.title='Connected islands, bridges and room to grow';$('world-toolbar').insertBefore(landButton,$('world-more-button'));
  const planButton=$('world-toolbar').querySelector('[data-id="plans"]');planButton.dataset.act='v10-planner';planButton.id='v10-planner-toggle';planButton.setAttribute('aria-controls','v10-planner');planButton.setAttribute('aria-expanded','false');planButton.title='Open the live planner (P)';
  const fit=document.createElement('button');fit.className='icon-btn';fit.dataset.act='v10-fit';fit.innerHTML=ic('expand');fit.setAttribute('aria-label','Show all owned islands');fit.title='Fit all owned islands';document.querySelector('.world-tools').prepend(fit);
  const file=document.createElement('input');file.type='file';file.accept='.json,application/json';file.hidden=true;file.id='v10-growth-file';document.body.appendChild(file);
  function toggle(open=!state.open){state.open=open;panel.hidden=!open;document.body.classList.toggle('planner-open',open);planButton.setAttribute('aria-expanded',String(open));if(open){h.clearContext();update(true);panel.querySelector('[data-act="v10-new-task"]').focus({preventScroll:true});}else $('world').focus({preventScroll:true});}
  function routeVisible(id){const feature={shop:'prestige-shop',market:'trade'}[id];return !feature||E().unlocked('features',feature);}
  function nav(tab){return `<nav class="v10-tabs" aria-label="Village workspaces">${Object.entries(labels).filter(([id])=>id!=='library'&&routeVisible(id)).map(([id,label])=>button(label,'open',id,tab===id?'primary':'')).join('')}</nav>`;}
  function wrap(tab,title,description,body){$('modal').classList.add('v10-modal');return h.head(title,description,'LITTLEWILD · '+(labels[tab]||'PLANNER').toUpperCase())+`<div class="modal-body v10-body">${labels[tab]&&tab!=='land'?nav(tab):''}${body}</div>`+h.footer(button('Back to the world','close'));}
  function result(r,message){if(r?.ok){h.result(r,message);state.lastList='';if(h.modal())h.redraw();return true;}h.result(r);return false;}
  function pending(kind,id,summary,data={}){state.pending={kind,id,summary,data,engine:E()};h.open('v10-confirm');}
  function research(){const e=E(),p=slots(),defs=C.content.research;const ready=defs.filter(r=>!p.research[r.id]&&r.playerLevel<=e.s.player.level&&Object.entries(r.requires).every(([k,n])=>(p.features[k]||0)>=n));const learned=defs.filter(r=>p.research[r.id]);const list=state.researchTab==='learned'?learned:ready;
   return wrap('research','A little more possibility.','Your level opens research opportunities. Research reveals features, recipes and blueprints; creatures still need their own skills.',`<div class="v10-hero-stats"><div><b>${e.s.player.level}</b><span>Guide level · ${e.s.player.xp} / ${L.threshold(e.s.player.level)} XP</span></div><div><b>${e.s.rp}</b><span>Shared research points</span></div><div><b>${p.prestige}</b><span>Spendable prestige · ${p.earnedPrestige} earned</span></div></div><div class="v10-feature-ranks">${C.content.features.map(f=>`<span>${esc(f.name)} <b>${p.features[f.id]||0} / ${f.maxRank}</b></span>`).join('')}</div><div class="button-row">${button('Ready to discover · '+ready.length,'research-tab','available',state.researchTab==='available'?'primary':'')}${button('Our knowledge · '+learned.length,'research-tab','learned',state.researchTab==='learned'?'primary':'')}</div><div class="v10-card-grid">${list.map(r=>{const issue=e.researchIssue(r.id);return `<article class="v10-card"><span class="v10-eyebrow">GUIDE LEVEL ${r.playerLevel}${r.grants?' · FEATURE RANK '+r.grants.rank:''}</span><h3>${esc(r.name)}</h3><p>${esc(r.description)}</p><small>${Object.entries(r.requires).map(([k,n])=>esc(k)+' '+n).join(' · ')||'An opening discovery'}</small><footer>${button(p.research[r.id]?'Discovered':`Research · ${r.cost} points`,'research',r.id,p.research[r.id]?'':'primary',!!issue)}${issue&&!p.research[r.id]?`<small>${esc(issue)}</small>`:''}</footer></article>`;}).join('')||note('The next opportunities appear when you gain a guide level or discover a feature rank. Care, learning and useful work earn experience.')}</div>${note('Operational menus contain only your unlocked knowledge. The full definition catalog remains available in JSON authoring tools; it does not bypass progression.')}`);
  }
  function homes(){const e=E(),p=slots(),q=e.slotQuote(),hs=e.s.buildings.filter(b=>e.homeCapacity(b)>0),beds=hs.reduce((n,b)=>n+e.homeCapacity(b),0),issue=e.gateIssue('features','recruitment');
   return wrap('homes','Room for someone new.','A slot is permission to welcome a companion. A bed is a place to belong. You need both before recruitment.',`<div class="v10-hero-stats"><div><b>${e.creatures.length} / ${p.slots}</b><span>Creatures / unlocked slots</span></div><div><b>${beds-e.creatures.filter(c=>c.homeId).length} / ${beds}</b><span>Free / total beds</span></div><div><b>${C.content.rules.maxSlots}</b><span>Configured companion limit</span></div></div><section class="v10-card"><h3>The next companion slot</h3><p>${p.slots>=q.max?'Every configured slot is unlocked.':`Slot ${q.number} needs guide level <b>${q.level}</b> and <b>${q.prestige} prestige</b>. Prestige is earned on successful quest returns. Welcoming the creature then costs ${e.purchasePrice()} coins.`}</p>${issue?note(esc(issue)) : ''}${button('Unlock slot · '+q.prestige+' prestige','slot','','primary',!!issue||p.slots>=q.max||e.s.player.level<q.level||p.prestige<q.prestige)}</section><h3>Everyone has their own place</h3><div class="v10-home-list">${e.creatures.map(c=>{const b=e.home(c);return `<article class="v10-home-row"><div><strong>${esc(c.name)}</strong><small>${esc(L.colony.profile(c.personality).name)} · ${c.activeQuest?'Away':esc(c.task?.label||'Taking a moment')}</small></div><label><span class="sr-only">Home for ${esc(c.name)}</span><select data-v10-home="${esc(c.id)}" ${c.activeQuest?'disabled':''}><option value="">${b?'Choose a home':'Needs a home'}</option>${hs.map(x=>`<option value="${x.id}" ${b?.id===x.id?'selected':''} ${b?.id!==x.id&&e.residents(x.id).length>=e.homeCapacity(x)?'disabled':''}>${esc(L.BUILDINGS[x.kind].name)} · ${x.x},${x.y} · ${e.residents(x.id).length}/${e.homeCapacity(x)} beds</option>`).join('')}</select></label>${button('Find','find-creature',c.id)}</article>`;}).join('')}</div><div class="button-row">${button('Plan another home','build-home','','primary')}${button('Improve our places','places')}</div><div class="v10-card-grid">${hs.map(b=>`<article class="v10-card"><span class="v10-eyebrow">HOME · LEVEL ${b.level}</span><h3>${esc(L.BUILDINGS[b.kind].name)}</h3><p>${e.residents(b.id).map(c=>esc(c.name)).join(', ')||'Waiting for a resident'}</p><small>${e.residents(b.id).length} / ${e.homeCapacity(b)} places · tile ${b.x}, ${b.y}</small>${button('Find home','find-building',b.id)}</article>`).join('')}</div><h3>Welcome a companion · ${e.purchasePrice()} coins</h3><div class="v10-card-grid">${root.LWAdventure.content.personalities.map(d=>`<article class="v10-card"><span class="v10-person-mark" style="--person:${d.color}"></span><h3>${esc(d.name)}</h3><p>${esc(d.description)}</p><small>${d.traits.map(id=>esc(root.LWAdventure.content.traits.find(t=>t.id===id)?.name||id)).join(' · ')}</small>${button('Welcome · '+e.purchasePrice()+' coins','recruit',d.id,'primary',!!issue||e.creatures.length>=p.slots||!e.freeHome()||e.s.player.coins<e.purchasePrice())}</article>`).join('')}</div>`);
  }
  function land(){
   const en=E(),gate=en.mapAccessIssue(),table=en.mapTable();$('modal').classList.add('chart-modal');
   if(gate){
    const learned=en.unlocked('buildings','map_table'),plan=en.allOrders().find(o=>o.kind==='map_table'),def=L.BUILDINGS.map_table,discovery=C.content.research.find(r=>r.id===C.content.requirements.buildings.map_table.research);
    return wrap('land','Our next journey starts here.','Build a map table to chart the islands around your home.',`<section class="chart-gate"><div class="chart-table-art" aria-hidden="true"><span class="chart-paper">✧<i>╱</i>⌁</span></div><div><span class="v10-eyebrow">THE MAP TABLE</span><h3>A place for bigger plans.</h3><p>Discover the blueprint, let a companion make it, then open the world map from the table or toolbar.</p><div class="chart-steps"><p><b>${learned?'✓':'1'}</b><span><strong>Discover ${esc(discovery.name)}</strong><small>Guide level ${discovery.playerLevel} · ${Object.entries(discovery.requires).map(([id,rank])=>esc(C.content.features.find(f=>f.id===id)?.name||id)+' rank '+rank).join(' · ')} · ${discovery.cost} research points</small></span></p><p><b>${table?'✓':'2'}</b><span><strong>${plan?'Finish the current building plan':'Build the map table'}</strong><small>${items(def.cost)} · ${esc(L.SKILLS[def.skill].short)} skill · real gathering and construction</small></span></p><p><b>3</b><span><strong>Compare neighboring islands</strong><small>Land research, guide level, coins and prestige are checked for each purchase.</small></span></p></div><p class="chart-callout" role="status">${esc(gate)}</p><div class="button-row">${learned?button(plan?'Review the plan':'Plan a map table',plan?'planner':'build-table','','primary'):button('Open Discoveries','open','research','primary')}${button('Learning studio','learn')}</div></div></section>`);
   }
   const owned=en.s.estate.islands,frontier=G.frontier(en.s),all=[...owned,...frontier].map(i=>en.islandProfile(i.ix,i.iy));
   if(!all.some(i=>i.id===state.island))state.island='0,0';
   const selected=all.find(i=>i.id===state.island),isOwned=owned.some(i=>G.key(i.ix,i.iy)===selected.id),quote=en.landQuote(selected.ix,selected.iy),issue=isOwned?null:en.islandPurchaseIssue(selected.ix,selected.iy);
   const minX=Math.min(...all.map(i=>i.ix)),maxX=Math.max(...all.map(i=>i.ix)),minY=Math.min(...all.map(i=>i.iy)),maxY=Math.max(...all.map(i=>i.iy));
   const cols=maxX-minX+1,rows=maxY-minY+1;
   const map=all.map(i=>{const own=owned.some(v=>v.ix===i.ix&&v.iy===i.iy),blocked=!own&&!!en.islandPurchaseIssue(i.ix,i.iy);return `<button class="chart-island ${own?'owned':blocked?'locked':'available'} ${i.id===selected.id?'selected':''}" style="left:${(i.ix-minX)/cols*100}%;top:${(i.iy-minY)/rows*100}%;width:${100/cols}%;height:${100/rows}%" data-act="v10-island-select" data-id="${i.id}" aria-label="${esc(i.name)}, ${own?'owned':blocked?'requirements not met':'available to purchase'}, guide level ${i.minimumLevel}" aria-pressed="${i.id===selected.id}"><span class="chart-landmass" data-biome="${esc(i.biome)}"><i>${own?'⌂':blocked?'◇':'+'}</i><small>${own?'Owned':'Lv. '+i.minimumLevel}</small></span></button>`;}).join('');
   // Edges come from ownership, not visual proximity or purchase order.
   let edges='';for(const i of owned)for(const[dx,dy]of[[1,0],[0,1]])if(owned.some(o=>o.ix===i.ix+dx&&o.iy===i.iy+dy))edges+=`<line x1="${(i.ix-minX+.5)*100/cols}" y1="${(i.iy-minY+.5)*100/rows}" x2="${(i.ix+dx-minX+.5)*100/cols}" y2="${(i.iy+dy-minY+.5)*100/rows}"/>`;
   const filtered=all.filter(i=>state.mapFilter==='owned'?owned.some(o=>G.key(o.ix,o.iy)===i.id):state.mapFilter==='frontier'?!owned.some(o=>G.key(o.ix,o.iy)===i.id):true);
   const listed=filtered.sort((a,b)=>a.minimumLevel-b.minimumLevel||a.iy-b.iy||a.ix-b.ix).map(i=>{const own=owned.some(o=>G.key(o.ix,o.iy)===i.id);return `<button data-act="v10-island-select" data-id="${i.id}" aria-pressed="${i.id===selected.id}" class="chart-list-row ${i.id===selected.id?'selected':''}"><span><strong>${esc(i.name)}</strong><small>${own?'Owned':en.s.player.level<i.minimumLevel?'Level requirement':'Neighboring island'} · Guide Lv. ${i.minimumLevel}</small></span><b>${own?'✓':'→'}</b></button>`;}).join('');
   const quests=selected.questIds.map(id=>root.LWAdventure.content.quests.find(q=>q.id===id));
   const invitations=en.s.colony.board.offers.filter(o=>o.islandId===selected.id);
   const journey=en.creatures.find(c=>(c.activeQuest||c.questPlan)?.islandId===selected.id);
   const receipts=en.s.atlas.history.filter(q=>q.islandId===selected.id);
   const nodes=isOwned?en.s.nodes.filter(n=>G.cell(n.x,n.y).ix===selected.ix&&G.cell(n.x,n.y).iy===selected.iy):G.generatedNodes(selected.ix,selected.iy,root.LWWorldContent);
   const resourceCounts={};for(const n of nodes){const def=root.LWWorldContent.node(n.kind);if(def?.direct){const key=def.resource;if(!resourceCounts[key])resourceCounts[key]={count:0,infinite:false,stock:0};resourceCounts[key].count++;resourceCounts[key].infinite||=def.mode==='infinite';resourceCounts[key].stock+=n.stock;}}
   const resources=Object.entries(resourceCounts).slice(0,10).map(([id,v])=>`<span>${ic(L.colony.item(id)?.icon||'leaf')}<b>${esc(L.colony.item(id)?.name||id)}</b><small>${v.infinite?'Infinite source':v.stock+' remaining'} · ${v.count} node${v.count===1?'':'s'}</small></span>`).join('');
   const requirement=(label,value,met)=>`<div class="chart-requirement ${met?'met':'unmet'}"><span>${met?'✓':'○'} ${label}</span><b>${value}</b></div>`;
   const detail=`<section class="chart-detail" aria-labelledby="chart-detail-title" data-scroll-key="island-detail">${button("← All islands","island-list","","chart-back")}<span class="v10-eyebrow">${isOwned?'PART OF OUR HOME':'A NEIGHBORING SHORE'} · ${selected.ix}, ${selected.iy}</span><h3 id="chart-detail-title" tabindex="-1">${esc(selected.name)}</h3><p>${esc(selected.description)}</p>${isOwned?`<div class="chart-owned-note">✓ Owned and connected. Companions can walk here across your bridges.</div><div class="button-row">${button('Find this island','focus-island',selected.id,'primary')}${button('Island quests','island-quests',selected.id)}</div>`:`<div class="chart-requirements">${requirement('Guide level',en.s.player.level+' / '+quote.level,en.s.player.level>=quote.level)}${requirement('Land research',en.unlocked('features','land')?'Discovered':'Not discovered',en.unlocked('features','land'))}${requirement('Coins',quote.coins+' / '+en.s.player.coins+' held',en.s.player.coins>=quote.coins)}${requirement('Prestige',quote.prestige+' / '+en.s.progression.prestige+' held',en.s.progression.prestige>=quote.prestige)}</div>${button('Review purchase','buy-island',selected.id,'primary chart-buy',!!issue)}<p class="chart-callout">${esc(issue||'A permanent purchase. A bridge connects each shared, owned edge. No supplies or creatures move instantly.')}</p>`}<h4>On this island</h4><div class="chart-resources">${resources}</div><h4>Invitations from this shore</h4><p class="chart-small">${isOwned?journey?esc(journey.name)+' has an expedition preparing or underway here.':invitations.length?invitations.length+' invitation(s) waiting at the Quest Board.':'Next event check in '+Math.ceil(Math.max(0,en.s.atlas.clocks[selected.id].nextAt-en.s.simTime))+'s of game time.':'Buying this island opens its own invitation pool and independent cooldown.'} One active invitation cycle per island; the next may differ.</p><div class="chart-quest-pool">${quests.map(q=>`<div><span><strong>${esc(q.name)}</strong><small>Guide Lv. ${Math.max(selected.minimumLevel,q.tier)} · Creature Lv. ${q.tier} · ${q.duration}s base + return</small></span><b>${C.content.rules.questPrestigeBase+q.tier*C.content.rules.questPrestigePerTier}<small>prestige*</small></b></div>`).join('')}</div><small class="chart-small">*Only successful returns award prestige. Supplies, energy, skill checks, and equipment still matter. Island level requirements do not secretly change the dice.</small>${receipts.length?`<details class="chart-receipts"><summary>${receipts.length} recent journey receipt(s)</summary>${receipts.slice(0,6).map(r=>`<p>${esc(en.creatures.find(c=>c.id===r.actorId)?.name||'Companion')} · ${esc(r.outcome)} · +${r.prestige} prestige</p>`).join('')}</details>`:''}</section>`;
   return wrap('land','A map of small possibilities.','Compare an island, prepare your companions, then choose where your home grows.',`<div class="chart-summary"><span>${ic('compass')} Map table ready</span><span><b>${owned.length}</b> / ${C.content.rules.maxIslands} islands</span><span><b>${G.bridges(en.s).length}</b> walkable bridges</span><span>Guide <b>Lv. ${en.s.player.level}</b></span></div><div class="chart-workspace"><div class="chart-overview"><div class="chart-map-head"><h3>Connected shores</h3>${button(state.mapShown?'Hide diagram':'Show diagram','map-toggle','','small')}</div><div class="chart-map ${state.mapShown?'shown':''}" style="--map-ratio:${cols}/${rows}"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">${edges}</svg>${map}<span class="chart-north" aria-hidden="true">N ↑</span></div><div class="chart-legend"><span>✓ Owned</span><span>+ Available</span><span>◇ Requirements</span></div><label class="chart-filter">Island list<select id="v11-map-filter">${[['all','All visible islands'],['frontier','Neighbors to compare'],['owned','Owned islands']].map(([id,label])=>`<option value="${id}" ${state.mapFilter===id?'selected':''}>${label}</option>`).join('')}</select></label><div class="chart-list" data-scroll-key="island-list" aria-label="Islands">${listed||'<p>No islands in this view.</p>'}</div><p class="chart-small">Each edge leads to a neighboring island. Select to inspect, never to purchase immediately.</p></div>${detail}</div>`);
  }
  function shop(){const e=E(),issue=e.gateIssue('features','prestige-shop');return wrap('shop','Small gifts, earned together.','Spend quest prestige on supplies and equipment. Purchases enter the warehouse—not a creature’s satchel.',`${note('Available: <b>'+slots().prestige+' prestige</b>. Creatures must visit the warehouse to collect gifts. Buying equipment does not automatically equip it.')}${issue?note(esc(issue)):''}<div class="v10-card-grid">${C.content.shop.map(d=>`<article class="v10-card"><span class="v10-eyebrow">GUIDE LEVEL ${d.playerLevel}</span><h3>${esc(d.name)}</h3><p>${items(d.items)}</p><footer>${button('Buy · '+d.prestige+' prestige','shop-buy',d.id,'primary',!!issue||e.s.player.level<d.playerLevel||slots().prestige<d.prestige)}</footer></article>`).join('')}</div>${button('Inspect warehouse','warehouse')}`);}
  function market(){const e=E(),orders=e.s.market.orders.filter(q=>!['done','cancelled'].includes(q.status)),stalls=e.s.buildings.filter(b=>b.kind==='market'),issue=e.gateIssue('features','trade');return wrap('market','From the warehouse to the stall.','Listing goods creates a delivery plan. Coins arrive only after a creature brings the goods to the market and completes a sale.',`${!stalls.length?note('Build a market stall before listing anything. Warehouse storage and personal gathering continue normally.') : note(stalls.length+' market stall(s) · '+e.s.market.history.reduce((n,q)=>n+q.coins,0)+' coins in the recent sales ledger.')}${issue?note(esc(issue)):''}<div class="button-row">${button('Choose warehouse goods','warehouse','','primary')}${button('Open delivery planner','planner')}</div><div class="v10-market-flow"><span>Warehouse</span><b>→</b><span>Creature carries</span><b>→</b><span>Stall inventory</span><b>→</b><span>Sale & coins</span></div><div class="v10-card-grid">${orders.map(q=>`<article class="v10-card"><span class="v10-eyebrow">${esc(q.status)}${q.paused?' · PAUSED':''}</span><h3>${q.amount} ${esc(L.colony.item(q.item).name)}</h3><p>${q.remaining} to collect · ${Object.values(q.transit).reduce((n,x)=>n+x,0)} carried · ${Object.values(q.staged).reduce((n,x)=>n+x,0)} at stall · ${q.sold} sold.</p><small>${q.sold*q.unitPrice} coins earned / ${q.amount*q.unitPrice} potential</small><footer>${button(q.paused?'Resume':'Pause','task-'+(q.paused?'resume':'pause'),'sale:'+q.id)}${button('Cancel','task-cancel','sale:'+q.id)}</footer></article>`).join('')||note('No unfinished sale orders. Choose deposited items in the warehouse to start one.')}</div><h3>Recently sold</h3>${e.s.market.history.slice(0,12).map(q=>`<div class="v10-ledger"><span>${q.amount} ${esc(L.colony.item(q.item).name)} <small>Sold by ${esc(e.creatures.find(c=>c.id===q.actorId)?.name||'a companion')}</small></span><b>+${q.coins} coins</b></div>`).join('')||'<p>No completed sales yet.</p>'}`);}
  function form(){const e=E(),f=state.form;if(!P.availableTypes(e).some(t=>t.id===f.type))f.type='gather';if(!available().some(c=>c.id===f.actorId))f.actorId=e.selected&&!e.selected.activeQuest?e.selected.id:available()[0]?.id||'';const c=e.creatures.find(c=>c.id===f.actorId),options=P.taskOptions(e,f.type,c);if(!options.some(o=>o.id===f.id))f.id=options[0]?.id||'';const b=e.s.buildings.find(b=>b.id===f.id),recipes=f.type==='workplace'&&b?e.buildingRecipes(b).filter(r=>e.unlocked('recipes',r.id)):[];if(!recipes.some(r=>r.id===f.recipe))f.recipe=recipes[0]?.id||'';
   return wrap('task','An idea for a companion.','Assign an outcome, not footsteps. The creature will find supplies, choose a route and take care of their needs.',`<div class="v10-task-form"><label>Who is this for?<select id="v10-task-actor">${available().map(c=>`<option value="${c.id}" ${c.id===f.actorId?'selected':''}>${esc(c.name)} · ${esc(c.task?.label||'Available')}</option>`).join('')}</select></label><label>Kind of plan<select id="v10-task-type">${P.availableTypes(e).map(t=>`<option value="${t.id}" ${t.id===f.type?'selected':''}>${esc(t.name)} · ${esc(t.system)}</option>`).join('')}</select></label><label>What should they work on?<select id="v10-task-id">${options.map(o=>`<option value="${esc(o.id)}" ${o.id===f.id?'selected':''}>${esc(o.name)}</option>`).join('')||'<option>No unlocked choices yet</option>'}</select></label>${f.type==='workplace'?`<label>Recipe<select id="v10-task-recipe">${recipes.map(r=>`<option value="${r.id}" ${f.recipe===r.id?'selected':''}>${esc(L.colony.item(r.output)?.name||r.id)} · ${items(r.cost)}</option>`).join('')}</select></label>`:''}${['gather','craft','practice','workplace'].includes(f.type)?`<label>Quantity <input id="v10-task-qty" type="number" min="1" max="${f.type==='practice'?3:24}" step="1" value="${f.quantity}"></label>`:''}</div>${note(f.type==='build'?'Next, select the building tile in the world. Nothing is placed or paid for until you confirm a valid tile.':f.type==='lesson'?'Research the lesson in Learn first. Tuition is charged when this training is queued; paused training keeps progress.':'This plan uses existing systems and real inventories. Stop or pause retains committed supplies; cancellation follows the system’s salvage and return rules.')}<div id="v10-form-feedback" role="status"></div><div class="button-row">${button(f.type==='build'?'Choose a location':f.type==='lesson'?'Purchase & queue lesson':'Add plan','task-submit','','primary',!c||!options.length||(f.type==='workplace'&&!recipes.length))}${button('Learn & research skills','learn')}${button('Discoveries','open','research')}</div>`);
  }
  const guideSteps=[
   ['A buddy, not a cursor','Select Pip in the world or the roster. Their card opens beside them. You influence choices; you never move their paws.','select'],
   ['A small act of care','Offer water or a snack from Pip’s own satchel. Watch the response in the world. When supplies run out, Pip gathers or visits the warehouse.','care'],
   ['Give knowledge room to grow','Open Learn. Research and teach Woodland hands, then a first shelter lesson. Learning takes time and practice.','learn'],
   ['A place to belong','Open Build, place a leaf shelter on clear ground, then close the menu to let Pip gather and build. Completed homes are assigned automatically when a bed is available.','home'],
   ['Make a plan, not a chore','Open the planner. Add a gathering goal and assign Pip. Try pause and resume. Essential self-care is protected; no items disappear when work is interrupted.','planner'],
   ['Research a little further','Guide levels open discoveries. Feature ranks unlock new research choices. Only researched recipes, blueprints and features appear in their normal menus.','research'],
   ['A little adventure','Discover quests, prepare supplies and equipment, then send a companion. While away they leave the glade; only a recall is available. Successful returns earn prestige.','quests'],
   ['A shared home, a wider world','Spend prestige on a level-gated slot, prepare another bed, then welcome a friend with coins. Build a map table before buying adjacent islands. Each island shows its own level requirement and coin/prestige cost.','growth'],
   ['Let the world do the carrying','Only warehouse stock can be listed for sale. A creature carries it to a built market stall, then earns coins there. Workplace inputs and outputs also need physical trips.','market'],
   ['Keep your little world safe','Export a story from Settings. A save includes the exact content definitions, homes, islands and unfinished work. Pause at any time; nothing advances while the game is closed.','save']
   ,['Chart your next shore','Discover Shared cartography at guide level 3 with discovery rank 2. Build a map table, then use World map to compare island resources, level requirements and quests. Buying still needs land research, coins and prestige.','map']
  ];
  function guide(){const t=slots().tutorial;t.step=Math.min(t.step,guideSteps.length-1);const step=guideSteps[t.step];return wrap('guide','One little step at a time.','A resumable guide to the real game. You can leave this open to read, close it to play, or revisit any step.',`<div class="v10-guide-progress">${guideSteps.map((s,i)=>`<button aria-label="Guide step ${i+1}: ${esc(s[0])}" class="${i===t.step?'current':''}" data-act="v10-guide-step" data-id="${i}">${i+1}</button>`).join('')}</div><section class="v10-guide-card"><span class="v10-eyebrow">STEP ${t.step+1} OF ${guideSteps.length}</span><h2>${step[0]}</h2><p>${step[1]}</p>${button('Show me','guide-do',step[2],'primary')}</section><div class="button-row">${button('Previous','guide-step',String(Math.max(0,t.step-1)),'',t.step===0)}${t.step===guideSteps.length-1?button('Finish guide','guide-finish','','primary'):button('Next step','guide-step',String(t.step+1),'primary')}${button('Keep my place & explore','guide-dismiss')}</div>${note('This guide explains controls without granting items, completing quests, or silently changing your plans. It can be resumed from More → Getting started.')}`);}
  function library(){return wrap('library','The village’s component library.','Maintain progression, homes, economy and interactions in an external JSON tool. This is an inspector and exchange, not a second authoring app.',`<div class="v10-hero-stats"><div><b>${C.content.research.length}</b><span>Research definitions</span></div><div><b>${C.content.interactions.length}</b><span>Interaction definitions</span></div><div><b>${C.content.events.length}</b><span>Event hooks</span></div></div><div class="button-row">${button('Export library','library-export','','primary')}${button('Export schema','schema-export')}${button('Import JSON…','library-import')}</div>${note('The fourth library complements Base, Adventure and World. Interaction handlers are registered game commands: JSON supplies conditions, costs, cooldowns and bounded effects, never executable code.')}<div class="v10-card-grid">${C.content.interactions.map(i=>`<article class="v10-card"><span class="v10-eyebrow">${i.eventOnly?'EVENT INTERACTION':'EVERYDAY INTERACTION'} · ${esc(i.handler)}</span><h3>${esc(i.label)}</h3><p>${esc(i.description)}</p><code>${esc(i.id)}</code><small>${i.handler==='care'?'Native care rules · carried supplies when required':(items(i.cost)||'No supplies charged')+' · '+i.cooldown+'s cooldown'}</small></article>`).join('')}</div><details class="v10-json"><summary>Full current JSON · ${esc(C.hash)}</summary><pre>${esc(JSON.stringify(C.content,null,2))}</pre></details>`);}
  function render(type){if(type==='v10-confirm'){const p=state.pending;return wrap('confirmation','Review before committing.','Cancel leaves the current world unchanged.',`${note(esc(p?.summary||'This action has expired.'))}<div class="button-row">${button('Cancel','confirm-cancel')}${button('Confirm','confirm','','primary',!p)}</div>`);}
   if(type==='v10-task')return form();if(type==='v10-research')return research();if(type==='v10-homes'||type==='community')return homes();if(type==='v10-land')return land();if(type==='v10-shop')return shop();if(type==='v10-market'||type==='market')return market();if(type==='v10-guide')return guide();if(type==='v10-library')return library();
   if(type==='v10-growth-preview'){const p=state.importPreview;return wrap('library','Review growth definitions.','Validation and inspection do not change the current story.',!p?'No import waiting.':`${p.error?note(esc(p.error),'error'):note('Validated '+p.content.name+'. '+p.diff.length+' changed fields. Active library: '+p.base+'.')}<div class="v10-diff">${p.diff?.slice(0,80).map(d=>`<div><code>${esc(d.path)}</code><del>${esc(JSON.stringify(d.before)??'Not present')}</del><ins>${esc(JSON.stringify(d.after)??'Not present')}</ins></div>`).join('')||''}</div>${!p.error?`<label class="v10-check"><input type="checkbox" id="v10-growth-new" ${p.newStory?'checked':''}> Explicitly start a new story with this library. Export the current story first.</label><div class="button-row">${button('Cancel','import-cancel')}${button('Apply reviewed definitions','import-apply','','primary',!p.diff.length)}</div>`:''}`);}
   if(type==='adventures'&&!E().unlocked('features','quests'))return wrap('research','There are paths we haven’t discovered yet.',E().gateIssue('features','quests'),note('Discover the quest feature through player research. The quest catalog will appear here once unlocked.')+button('Open discoveries','open','research','primary'));
   return null;
  }
  function rowMarkup(r){const k=esc(r.key),hold=r.paused||r.stopped;return `<article class="v10-task-row ${r.protected?'protected':''}"><div class="v10-task-meta"><span>${esc(r.system)}</span><b>${esc(r.state||'Queued')}</b></div><h3>${esc(r.name)}</h3><div class="v10-assignee">${ic('paw')}<strong>${esc(r.assignee)}</strong>${r.priority===2?'<span>High priority</span>':''}</div>${r.detail?`<p>${esc(r.detail)}</p>`:''}<progress max="1" value="${Number.isFinite(r.progress)?Math.min(1,Math.max(0,r.progress)):0}" aria-label="${esc(r.name)} progress"></progress><div class="v10-task-actions">${r.protected?'<small>Self-care / essential logistics · protected</small>':r.away?r.type==='quest'?button('Recall…','task-cancel',r.key):'<small>Waiting for this creature to return</small>':r.type==='activity'?button('Stop once','task-stop',r.key):`${button(hold?'Resume':'Pause','task-'+(hold?'resume':'pause'),r.key)}${!hold&&r.type!=='activity'?button('Stop','task-stop',r.key):''}${button(r.priority===2?'Normal priority':'Prioritize','task-priority',r.key)}${button('Cancel…','task-cancel',r.key)}`}</div>${r.canAssign&&!r.away?`<label class="v10-reassign"><span>Assigned to</span><select data-v10-reassign="${k}">${['sale','workplace'].includes(r.type)?`<option value="" ${!r.actorId?'selected':''}>Any available creature</option>`:''}${available().map(c=>`<option value="${c.id}" ${r.actorId===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label>`:''}</article>`;}
  function update(force=false){const e=E();for(const b of more.querySelectorAll('[data-act="v10-open"]'))b.hidden=!routeVisible(b.dataset.id);if(state.lastEngine!==e){state.lastEngine=e;state.pending=null;state.lastList='';state.importPreview=null;state.readId++;}
   $('v10-prestige').textContent=slots().prestige;$('v10-guide-level').textContent='Lv. '+e.s.player.level;$('v10-planner-clock').textContent=e.s.paused||h.modal()?'World paused':'World running';panel.inert=!!h.modal();
   const locked={adventures:'quests'};for(const[id,feature]of Object.entries(locked)){const b=$('world-toolbar').querySelector('[data-id="'+id+'"]');if(b)b.hidden=!e.unlocked('features',feature);}landButton.hidden=!(e.mapTable()||e.unlocked('buildings','map_table')||e.unlocked('features','land'));landButton.title=e.mapAccessIssue()||'World map: compare and purchase neighboring islands';
   const objective=$('world-objective');objective.dataset.act='v10-open';objective.dataset.id=slots().tutorial.complete?'research':'guide';$('world-objective-title').textContent=slots().tutorial.complete?'The next discovery':guideSteps[Math.min(slots().tutorial.step,guideSteps.length-1)][0];$('world-objective-caption').textContent=slots().tutorial.complete?'Research & progression ↗':'Getting started · step '+(Math.min(slots().tutorial.step,guideSteps.length-1)+1)+' / '+guideSteps.length+' ↗';
   if(!state.open||h.modal())return;const now=performance.now();if(!force&&now-state.lastUpdate<800)return;state.lastUpdate=now;
   const list=P.rows(e),filter=$('v10-plan-filter'),opts='<option value="all">Every creature</option>'+e.creatures.map(c=>`<option value="${c.id}" ${state.filter===c.id?'selected':''}>${esc(c.name)}</option>`).join('')+'<option value="shared" '+(state.filter==='shared'?'selected':'')+'>Shared work</option>';if(filter.innerHTML!==opts&&filter!==document.activeElement)filter.innerHTML=opts;
   $('v10-plan-count').textContent=list.length;const rows=list.filter(r=>(state.filter==='all'||state.filter==='shared'&&!r.actorId||r.actorId===state.filter)&&[r.name,r.assignee,r.system,r.state].join(' ').toLowerCase().includes(state.search.toLowerCase()));
   const markup=rows.map(rowMarkup).join('')||`<div class="v10-empty">${ic('leaf')}<h3>${list.length?'No matching plans.':'A little breathing room.'}</h3><p>${list.length?'Clear the search or show every creature.':'No unfinished plans. Add an idea, or let your companions follow their own curiosity.'}</p>${button('Add an idea','new-task','','primary')}</div>`;
   const active=document.activeElement;if($('v10-plan-list').contains(active)&&active.tagName==='SELECT')return;if(markup!==state.lastList){const wasInside=panel.contains(active),a=active.dataset.act,id=active.dataset.id,scroll=$('v10-plan-list').scrollTop;$('v10-plan-list').innerHTML=markup;state.lastList=markup;$('v10-plan-list').scrollTop=scroll;if(a&&wasInside)(panel.querySelector(`[data-act="${CSS.escape(a)}"][data-id="${CSS.escape(id||'')}"]`)||panel.querySelector('[data-act="v10-new-task"]'))?.focus({preventScroll:true});}
  }
  function action(a,id,b){if((a==='w7-panel'||a==='workspace-go'||a==='cx-open')&&['plans','suggest'].includes(id)||a==='plans'||a==='suggest'){if(h.modal())h.close();h.clearContext();toggle(true);if(id==='suggest'||a==='suggest')h.open('v10-task');return true;}if(!a.startsWith('v10-'))return false;
   const e=E();if(a==='v10-planner'){if(h.modal())h.close();h.clearContext();toggle();return true;}if(a==='v10-planner-close'){toggle(false);return true;}if(a==='v10-open'){h.open('v10-'+(routeVisible(id)?id:'research'));return true;}if(a==='v10-close'){h.close();return true;}if(a==='v10-fit'){h.close();h.clearContext();h.world().fit?.();return true;}
   if(a==='v10-new-task'){state.form.origin=null;state.form.actorId=e.selected&&!e.selected.activeQuest?e.selected.id:available()[0]?.id||'';h.open('v10-task');return true;}
   if(a==='v10-task-submit'){const f=state.form;const qty=$('v10-task-qty');if(qty)f.quantity=Number(qty.value);const r=P.add(e,f);if(r.ok){h.result(r,r.placement?'Choose a tile for this plan.':'Plan added for '+e.creatures.find(c=>c.id===f.actorId).name+'.');h.close();h.clearContext();if(r.placement){toggle(false);e.selectCreature(r.actorId);h.blueprint(r.placement,f.origin);}else toggle(true);}else{$('v10-form-feedback').textContent=r.reason;h.toast(r.reason,true);}return true;}
   if(a.startsWith('v10-task-')){const cmd=a.slice(9),r=P.rows(e).find(r=>r.key===id);if(!r){h.toast('That task is no longer waiting.',true);return true;}if(cmd==='cancel')pending('task-cancel',id,r.away?'Recall '+r.assignee+'? The current quest loses completion rewards and charges the configured recall energy penalty.':'Cancel “'+r.name+'”? Unspent supplies stay physical; native construction salvage applies. Market goods at a stall must be carried back.');else result(P.act(e,id,cmd,cmd==='priority'?r.priority===2?1:2:undefined),'Plan '+(cmd==='priority'?'priority changed':cmd==='resume'?'resumed':cmd==='stop'?'stopped; commitments retained':'paused')+'.');update(true);return true;}
   if(a==='v10-research-tab'){state.researchTab=id;h.redraw();return true;}if(a==='v10-research'){result(e.researchFeature(id),'Discovery learned. New choices are now available.');return true;}
   if(a==='v10-slot'){const q=e.slotQuote();pending('slot','',`Unlock companion slot ${q.number} for ${q.prestige} prestige? You will still need a free bed and ${e.purchasePrice()} coins to welcome the creature.`,q);return true;}
   if(a==='v10-recruit'){pending('recruit',id,`Welcome a ${root.LWAdventure.content.personalities.find(x=>x.id===id)?.name||''} companion for ${e.purchasePrice()} coins? They need an unlocked slot and an available bed.`,{price:e.purchasePrice(),slots:slots().slots});return true;}
   if(a==='v10-island-select'){state.island=id;h.redraw();document.getElementById('chart-detail-title')?.focus({preventScroll:true});if(innerWidth<=720)document.querySelector('.chart-detail')?.scrollIntoView({block:'start'});return true;}
   if(a==='v10-island-list'){const row=document.querySelector('.chart-list-row[data-id="'+state.island+'"]');row?.scrollIntoView({block:'center'});row?.focus({preventScroll:true});return true;}
   if(a==='v10-map-toggle'){state.mapShown=!state.mapShown;h.redraw();return true;}
   if(a==='v10-build-table'){state.form={type:'build',id:'map_table',actorId:e.selected?.id||available()[0]?.id||'',quantity:1,recipe:''};h.open('v10-task');return true;}
   if(a==='v10-island-quests'){root.LWQuestDestination=id;h.open('adventures');return true;}
   if(a==='v10-buy-island'){const[ix,iy]=id.split(',').map(Number),q=e.landQuote(ix,iy),issue=e.islandPurchaseIssue(ix,iy);if(issue){h.toast(issue,true);return true;}pending('land',id,`Buy ${q.name} for ${q.coins} coins and ${q.prestige} prestige? Guide level ${q.level} is required. You will keep ${e.s.player.coins-q.coins} coins and ${slots().prestige-q.prestige} prestige. A bridge connects each owned neighboring edge and this island gains its own quests. This purchase is permanent.`,q);return true;}
   if(a==='v10-shop-buy'){const d=C.content.shop.find(x=>x.id===id);pending('shop',id,`Spend ${d.prestige} prestige on ${d.name}? Supplies arrive in the warehouse. Creatures must collect them.`,{price:d.prestige});return true;}
   if(a==='v10-confirm-cancel'){const p=state.pending;state.pending=null;if(p?.kind==='land'&&p.engine===e){state.island=p.id;h.open('v10-land');}else h.close();return true;}
   if(a==='v10-confirm'){const p=state.pending;if(!p||p.engine!==e){h.toast('This review is stale.',true);return true;}let r={ok:false,reason:'The price changed. Review again.'};if(p.kind==='slot'&&JSON.stringify(e.slotQuote())===JSON.stringify(p.data))r=e.unlockSlot();if(p.kind==='recruit'&&e.purchasePrice()===p.data.price&&slots().slots===p.data.slots)r=e.purchaseCreature(p.id);if(p.kind==='land')r=e.buyIsland(...p.id.split(',').map(Number),p.data);if(p.kind==='shop'&&C.content.shop.find(d=>d.id===p.id)?.prestige===p.data.price)r=e.buyPrestigeItem(p.id);if(p.kind==='task-cancel')r=P.act(e,p.id,'cancel');if(r.ok){state.pending=null;h.result(r,p.kind==='land'?'Island purchased. Your companions can use the new bridge.':'Confirmed.');h.close();h.clearContext();if(p.kind==='land'){state.island=p.id;h.open('v10-land');}update(true);}else h.result(r);return true;}
   if(a==='v10-find-creature'){h.close();h.clearContext();const c=e.creatures.find(c=>c.id===id);if(c){e.selectCreature(c.id);h.world().focus?.(c.creature.x,c.creature.y);h.selectCreature?.(c.id);}return true;}if(a==='v10-find-building'){h.close();h.clearContext();const building=e.s.buildings.find(b=>b.id===id);if(building)h.world().focus?.(building.x,building.y);return true;}if(a==='v10-focus-island'){h.close();h.clearContext();const[x,y]=id.split(',').map(Number);h.world().focus?.(x*23+9,y*23+9);return true;}
   if(a==='v10-build-home'){state.form={type:'build',id:'shelter',actorId:e.selected?.id||available()[0]?.id||'',quantity:1,recipe:''};h.open('v10-task');return true;}
   if(a==='v10-places'){h.open('construction');return true;}if(a==='v10-learn'){h.open('training');return true;}if(a==='v10-atlas'){h.open('land-atlas');return true;}if(a==='v10-warehouse'){h.open('warehouse');return true;}
   if(a==='v10-guide-step'){slots().tutorial.step=clampStep(+id);h.save();h.redraw();return true;}
   if(a==='v10-guide-dismiss'||a==='v10-guide-finish'){slots().tutorial.dismissed=true;if(a==='v10-guide-finish')slots().tutorial.complete=true;h.save();h.close();return true;}
   if(a==='v10-guide-do'){const routes={learn:'training',home:'construction',research:'v10-research',quests:'adventures',growth:'v10-homes',market:'v10-market',map:'v10-land',save:'settings'};if(id==='select'||id==='care'){h.close();h.clearContext();h.selectCreature?.(e.selected?.id||e.creatures[0].id);}else if(id==='planner'){h.close();h.clearContext();toggle(true);}else h.open(routes[id]||'v10-research');return true;}
   if(a==='v10-library-export'){root.LWFiles.downloadJSON(C.clone(C.content),'littlewild-v11-growth-library.json');return true;}if(a==='v10-schema-export'){root.LWFiles.downloadJSON(C.schema,'littlewild-v11-growth.schema.json');return true;}if(a==='v10-library-import'){file.click();return true;}
   if(a==='v10-import-cancel'){state.importPreview=null;state.readId++;h.open('v10-library');return true;}
   if(a==='v10-import-apply'){const p=state.importPreview;if(!p||p.error||p.base!==C.hash){h.toast('The library changed. Import and review again.',true);return true;}try{root.LWGrowth.withLibrary(p.content,()=>p.newStory?new L.Engine():L.Engine.import(e.export()));h.backup();const next=root.LWStory.applyGrowth(p.content,e,p.newStory);h.setEngine(next);state.importPreview=null;h.save();h.open(p.newStory?'welcome':'v10-library');h.toast('Growth definitions applied.');}catch(error){h.toast(error.message,true);}return true;}
   return false;
  }
  function clampStep(n){return Math.max(0,Math.min(guideSteps.length-1,Number.isInteger(n)?n:0));}
  document.addEventListener('input',event=>{if(event.target.id==='v10-plan-search'){state.search=event.target.value;update(true);}if(event.target.id==='v10-task-qty')state.form.quantity=Number(event.target.value);});
  document.addEventListener('change',event=>{const el=event.target;if(el.id==='v11-map-filter'){state.mapFilter=el.value;h.redraw();return;}if(el.id==='v10-plan-filter'){state.filter=el.value;update(true);}else if(el.id.startsWith('v10-task-')){const field={actor:'actorId',type:'type',id:'id',recipe:'recipe',qty:'quantity'}[el.id.slice(9)];if(field){state.form[field]=field==='quantity'?Number(el.value):el.value;if(field!=='quantity')h.redraw();}}else if(el.dataset.v10Home){const r=E().assignHome(el.dataset.v10Home,el.value);result(r,'Home assigned.');}else if(el.dataset.v10Reassign){result(P.act(E(),el.dataset.v10Reassign,'assign',el.value),'Plan reassigned.');update(true);}else if(el.id==='v10-growth-new'&&state.importPreview)state.importPreview.newStory=el.checked;});
  document.addEventListener('keydown',event=>{if(event.target.closest('#tile-context'))return;if(event.ctrlKey||event.metaKey||event.altKey||/INPUT|SELECT|TEXTAREA/.test(event.target.tagName)||event.target.isContentEditable)return;if(event.key.toLowerCase()==='p'&&!h.modal()){event.preventDefault();event.stopImmediatePropagation();h.clearContext();toggle();}if(event.key==='Escape'&&state.open&&!h.modal()){event.preventDefault();event.stopImmediatePropagation();toggle(false);}},true);
  file.addEventListener('change',async()=>{const f=file.files?.[0];if(!f)return;const read=++state.readId;try{if(f.size>1024*1024)throw Error('Growth library must be under 1 MiB.');const text=await f.text();if(read!==state.readId)return;const candidate=C.validate(text);if(!candidate.ok)throw Error(candidate.errors.join('\n'));state.importPreview={content:candidate.content,diff:diff(C.content,candidate.content),base:C.hash,newStory:false};h.open('v10-growth-preview');}catch(error){if(read===state.readId){state.importPreview={error:error.message};h.open('v10-growth-preview');}}finally{file.value='';}});
  function diff(a,b,path=''){if(JSON.stringify(a)===JSON.stringify(b))return[];if(!a||!b||typeof a!=='object'||typeof b!=='object'||Array.isArray(a)!==Array.isArray(b))return[{path:path||'/',before:a,after:b}];return [...new Set([...Object.keys(a),...Object.keys(b)])].flatMap(k=>diff(a[k],b[k],path+'/'+k.replace(/~/g,'~0').replace(/\//g,'~1')));}
  return{render,action,update,toggle,state,cancelRead(){state.readId++;},diff};
 }
 root.LWVillageUI={create};
})(typeof globalThis!=='undefined'?globalThis:this);
