/* A Wider Home: owned island graph, homes, progression and physical market service.
 * This domain layer extends the proven production engine. It owns no DOM or wall clock.
 * Commands validate before mutation; carriers and workplaces remain the inventory authority. */
(function(root){'use strict';
 const L=root.LW,Composition=L.EngineComposition,G=root.LWGeography,C=root.LWGrowth,W=root.LWWorldContent,A=root.LWAdventure;
 const copy=C.clone,fail=reason=>({ok:false,reason}),ok=(extra={})=>({ok:true,...extra}),int=(n,a,b)=>Number.isInteger(n)&&n>=a&&n<=b;
 const indoor=new Set(['shelter','cottage','storehouse','workshop','bakery','study','herbarium','observatory','mill','loom','greenhouse','smelter']);
 const marketKinds=['market-pickup','market-deliver','market-sell','market-reclaim'];
 L.worldTaskKinds=[...L.worldTaskKinds,...marketKinds];
 function initializeVillage(self,state){
  self.s.estate ||= {version:1,islands:[{ix:0,iy:0,...G.describe(0,0)}],purchases:0};
  if(!self.s.progression){
   self.s.progression={version:1,research:{},features:{},prestige:0,earnedPrestige:0,slots:Math.max(C.content.rules.initialSlots,self.creatures.length),tutorial:{step:0,dismissed:false,complete:false},interactionSequence:1};
   for(const r of C.content.research)if(r.initial){self.s.progression.research[r.id]=true;if(r.grants)self.s.progression.features[r.grants.feature]=Math.max(self.s.progression.features[r.grants.feature]||0,r.grants.rank);}
  }
  self.s.market ||= {sequence:1,orders:[],history:[]};
  self.s.planning ||= {controls:{},history:[]};
  self.ensureDoors();for(const c of self.creatures){c.homeId??=null;c.eventInteractions||=[];c.interactionCooldowns||={};}
  self.assignUnhoused(false);self.s.version=7;
 }
 function defineLayer(Base){return class VillageLayer extends Base{
  interactionIssue(){if(this._authorizedActorId===this.actor?.id)return this.actor.activeQuest?'This creature is away. Only recall is possible.':null;return super.interactionIssue();}
  commandActor(id,fn,{away=false}={}){const c=this.creatures.find(c=>c.id===id);if(!c)return fail('Select a known creature.');if(c.activeQuest&&!away)return fail(c.name+' is away. Only recalling the quest is possible.');const old=this._authorizedActorId;try{this._authorizedActorId=id;return this.withActor(c,fn);}finally{this._authorizedActorId=old;}}
  requirement(category,id){return C.content.requirements[category]?.[id]||{playerLevel:1,features:{}};}
  gateIssue(category,id){if(category==='recipes'&&L.RES[id]){const itemIssue=this.gateIssue('items',id);if(itemIssue)return itemIssue;}const p=this.s.progression;if(!p)return null;const r=this.requirement(category,id);if(this.s.player.level<r.playerLevel)return 'Reach guide level '+r.playerLevel+' first.';for(const[k,n]of Object.entries(r.features||{}))if((p.features[k]||0)<n)return 'Research '+(C.content.features.find(f=>f.id===k)?.name||k)+' '+n+' first.';if(r.research&&!p.research[r.research])return 'Research '+(C.content.research.find(r0=>r0.id===r.research)?.name||r.research)+' first.';return null;}
  unlocked(category,id){return !this.gateIssue(category,id);}
  researchIssue(id){const r=C.content.research.find(x=>x.id===id);if(!r)return 'Unknown research.';const p=this.s.progression;if(p.research[id])return 'Already researched.';if(this.s.player.level<r.playerLevel)return 'Guide level '+r.playerLevel+' required.';for(const[k,n]of Object.entries(r.requires))if((p.features[k]||0)<n)return 'Requires '+(C.content.features.find(f=>f.id===k)?.name||k)+' '+n+'.';if(this.s.rp<r.cost)return 'Need '+r.cost+' shared research points.';return null;}
  researchFeature(id){const issue=this.researchIssue(id);if(issue)return fail(issue);const r=C.content.research.find(r=>r.id===id),settlement=this.settleEconomy({id:this.economySettlementId('growth-research',id),research:-r.cost,playerXp:2},'Researched '+r.name);if(!settlement.ok)return fail('The research cost could not be settled.');this.s.progression.research[id]=true;if(r.grants)this.s.progression.features[r.grants.feature]=r.grants.rank;this.log('New knowledge: '+r.name+'.','research');this.emit('celebrate',r.name+' unlocked.');return ok();}
  research(id){const issue=this.gateIssue('skills',id);return issue?fail(issue):super.research(id);}
  teach(id){const issue=this.gateIssue('skills',id);return issue?fail(issue):super.teach(id);}
  request(type,id,qty){const issue=type==='gather'?this.gateIssue('items',id):type==='craft'?this.gateIssue('recipes',id):type==='deliver'?this.gateIssue('features','trade'):null;return issue?fail(issue):super.request(type,id,qty);}
  requestEquipment(id){const issue=this.gateIssue('items',id);return issue?fail(issue):super.requestEquipment(id);}
  acceptQuest(id){const issue=this.gateIssue('features','quests');return issue?fail(issue):super.acceptQuest(id);}
  depart(){if(this.actor.questPlan?.paused||this.gateIssue('features','quests'))return false;return super.depart();}
  resourceTask(id,...args){if(this.s.progression&&L.RES[id]&&this.gateIssue('items',id))return null;if(this.s.progression&&L.RECIPES[id]&&this.gateIssue('recipes',id))return null;return super.resourceTask(id,...args);}
  productionTask(b,id,...args){if(this.s.progression&&L.RECIPES[id]&&this.gateIssue('recipes',id))return null;if(b.planAssignee&&b.planAssignee!==this.actor.id)return null;return super.productionTask(b,id,...args);}
  configureBuilding(id,command,value){if(['batch','target'].includes(command)&&L.RECIPES[value?.recipe]){const issue=this.gateIssue('recipes',value.recipe);if(issue)return fail(issue);}return super.configureBuilding(id,command,value);}
  abortQuest(){
   if(this._authorizedActorId!==this.actor.id)return super.abortQuest();
   const q=this.actor.activeQuest;if(!q)return fail('This creature is not away.');if(q.status==='returning')return fail('Already returning home.');
   q.status='returning';q.aborted=true;q.outcome='Recalled';q.returnRemaining=A.content.rules.abortReturnSeconds;this.actor.needs.energy=L.clamp(this.actor.needs.energy-A.content.rules.abortEnergy,0,100);this.changeFeeling('Our expedition was recalled',-2,3);this.log(this.actor.name+' is returning. '+A.content.rules.abortEnergy+' energy recall cost; no completion reward.','compass');return ok();
  }
  questRewardSpec(q,completed){const spec=super.questRewardSpec(q,completed);if(!completed)return spec;const tier=A.content.quests.find(t=>t.id===q.questId)?.tier||1,amount=C.content.rules.questPrestigeBase+tier*C.content.rules.questPrestigePerTier;return {...spec,prestige:amount,earnedPrestige:amount};}
  returnQuest(){const q=this.actor.activeQuest;if(!q)return false;const success=!q.aborted&&q.successes>=q.required,result=super.returnQuest();if(result&&success){const amount=this.actor.questHistory[0]?.prestigeReward||0;this.emit('celebrate','+'+amount+' prestige · A successful adventure.');this.grantInteractionEvent('quest-success',this.actor.id);}return result;}
  slotQuote(){const r=C.content.rules,n=this.s.progression.slots;return {number:n+1,prestige:Math.ceil(r.slotPrestigeBase*Math.pow(r.slotGrowth,n-r.initialSlots)),level:r.slotLevelBase+Math.max(0,n-r.initialSlots)*r.slotLevelStep,max:r.maxSlots};}
  unlockSlot(){const q=this.slotQuote(),p=this.s.progression;const issue=this.gateIssue('features','recruitment');if(issue)return fail(issue);if(p.slots>=q.max)return fail('All configured companion slots are unlocked.');if(this.s.player.level<q.level)return fail('Guide level '+q.level+' required.');if(p.prestige<q.prestige)return fail('Need '+q.prestige+' prestige earned from successful quests.');const settlement=this.settleEconomy({id:this.economySettlementId('slot-unlock',String(q.number)),prestige:-q.prestige});if(!settlement.ok)return fail('The prestige cost could not be settled.');p.slots++;this.emit('celebrate','Companion slot '+p.slots+' unlocked.');return ok();}
  homeCapacity(b){const d=C.content.homes[b.kind];return d?d.places+(b.level-1)*d.perLevel:0;}
  residents(id){return this.creatures.filter(c=>c.homeId===id);}
  home(c=this.actor){return this.s.buildings.find(b=>b.id===c.homeId)||null;}
  freeHome(c=null){return this.s.buildings.find(b=>this.homeCapacity(b)>this.residents(b.id).length&&(!c||this.withActor(c,()=>this.findPath(b,true)!==null)));}
  assignUnhoused(events=true){for(const c of this.creatures)if(!this.home(c)){const b=this.freeHome(c);if(b){c.homeId=b.id;if(events)this.grantInteractionEvent('home-assigned',c.id);}}}
  assignHome(actorId,buildingId){const c=this.creatures.find(c=>c.id===actorId),b=this.s.buildings.find(b=>b.id===buildingId);if(!c||!b||!this.homeCapacity(b))return fail('Choose a creature and a completed home.');if(c.activeQuest)return fail('Wait until this creature returns.');if(c.homeId===b.id)return ok();if(this.residents(b.id).length>=this.homeCapacity(b))return fail('Every place in this home is assigned.');if(!this.withActor(c,()=>this.findPath(b,true)))return fail('This home needs a reachable doorway.');c.homeId=b.id;if(c.task?.kind==='rest')this.interruptActor(c);this.grantInteractionEvent('home-assigned',c.id);this.emit('notice',c.name+' has a place in '+L.BUILDINGS[b.kind].name+'.',{actorId:c.id});return ok();}
  purchaseCreature(personality){if(!this.s.progression)return super.purchaseCreature(personality);const issue=this.gateIssue('features','recruitment');if(issue)return fail(issue);if(this.creatures.length>=this.s.progression.slots)return fail('Unlock the next companion slot with prestige first.');const home=this.freeHome();if(!home)return fail('Build or improve a home with an unassigned place first.');const r=super.purchaseCreature(personality);if(r.ok){r.creature.homeId=home.id;r.creature.eventInteractions=[];r.creature.interactionCooldowns={};this.grantInteractionEvent('arrival',r.creature.id);this.grantInteractionEvent('home-assigned',r.creature.id);}return r;}
  landQuote(){const r=C.content.rules,n=this.s.estate.purchases;return {coins:Math.ceil(r.landCoinsBase*Math.pow(r.landGrowth,n)),prestige:Math.ceil(r.landPrestigeBase*Math.pow(r.landGrowth,n)),level:r.landLevel};}
  buyIsland(ix,iy){const issue=this.gateIssue('features','land');if(issue)return fail(issue);const q=this.landQuote();if(this.s.player.level<q.level)return fail('Guide level '+q.level+' is required for buying land.');if(!int(ix,-48,48)||!int(iy,-48,48)||!G.frontier(this.s).some(i=>i.ix===ix&&i.iy===iy))return fail('Choose an unowned island sharing an edge with your land.');if(this.s.estate.islands.length>=C.content.rules.maxIslands)return fail('The configured island limit is reached.');if(this.s.player.coins<q.coins||this.s.progression.prestige<q.prestige)return fail('Need '+q.coins+' coins and '+q.prestige+' prestige.');
   const nodes=G.generatedNodes(ix,iy,W),candidate={...this.s,estate:copy(this.s.estate),nodes:[...this.s.nodes,...nodes]};candidate.estate.islands.push({ix,iy,...G.describe(ix,iy)});const grid=new G.Grid(candidate),seen=grid.flood({x:9,y:9});if(seen.size!==grid.cells.size)return fail('This island cannot yet be connected safely.');
   const settlement=this.settleEconomy({id:this.economySettlementId('island',ix+':'+iy),guide:-q.coins,prestige:-q.prestige},'Purchased '+G.describe(ix,iy).name);if(!settlement.ok)return fail('The land purchase could not be settled.');this.s.estate=candidate.estate;this.s.estate.purchases++;this.s.nodes=candidate.nodes;this.log('A bridge connects '+G.describe(ix,iy).name+'. Creatures can walk there.','route');this.emit('land','A new island, a wider home.');for(const c of this.creatures)this.grantInteractionEvent('island-purchased',c.id);return ok({island:{ix,iy},quote:q});
  }
  isIndoor(b){return !!b&&indoor.has(b.kind);}
  ensureDoors(){for(const b of this.s.buildings)if(this.isIndoor(b)&&!b.door){const choices=[[0,1],[1,0],[0,-1],[-1,0]];const d=choices.find(([dx,dy])=>this.walkable(b.x+dx,b.y+dy));b.door={dx:d?.[0]??0,dy:d?.[1]??1};}}
  doorway(b){return{x:b.x+(b.door?.dx??0),y:b.y+(b.door?.dy??1)};}
  findPath(target,adjacent=false){if(this.s.estate&&target){const b=this.s.buildings.find(b=>b.x===target.x&&b.y===target.y);if(this.isIndoor(b)&&b.door)return root.LWNavigation.path(this.s,this.doorway(b),false);}return super.findPath(target,adjacent);}
  placementIssue(kind,x,y){if(!this.s.estate)return super.placementIssue(kind,x,y);const issue=this.gateIssue('buildings',kind);if(issue)return issue;const cell=G.cell(x,y);if(!int(x,-1200,1200)||!int(y,-1200,1200)||!G.available(this.s,x,y)||cell.x<2||cell.y<2||cell.x>16||cell.y>16)return 'Choose owned, buildable ground, two tiles back from a shore or bridge.';
   if(this.s.buildings.some(b=>b.x===x&&b.y===y)||this.allOrders().some(o=>o.type==='build'&&o.x===x&&o.y===y))return 'This plot already has a building or plan.';
   if(this.creatures.some(c=>!c.activeQuest&&Math.hypot(c.creature.x-x,c.creature.y-y)<.7))return 'Wait until the creature has left this plot.';
   const required=W.building(kind)?.requiresNode,n=this.nodeAt(x,y);if(required&&n?.kind!==required)return 'Requires '+W.node(required).name.toLowerCase()+' on this exact tile.';if(required&&!this.nodeAvailable(n))return 'This site is exhausted.';if(n&&!required)return 'Keep this resource node accessible. Choose clear ground.';
   const plans=this.allOrders().filter(o=>o.type==='build'),grid=new G.Grid(this.s,[...plans,{x,y}]);
   for(const b of [...this.s.buildings,...plans])if(this.isIndoor(b)){const d=this.doorway(b);if(!grid.pass(d.x,d.y))return 'Keep the doorway of '+L.BUILDINGS[b.kind].name+' clear.';}
   if(indoor.has(kind)&&!grid.pass(x,y+1))return 'This building needs an open front doorway on its south edge.';
   for(const n of this.s.nodes)if(W.node(n.kind)?.direct&&this.nodeAvailable(n)&&!this.s.buildings.some(b=>b.x===n.x&&b.y===n.y)&&!grid.approach(n))return 'Keep an approach to '+W.node(n.kind).name+'.';
   const seed=this.creatures.find(c=>!c.activeQuest)?.creature||{x:9,y:9},seen=grid.flood({x:Math.round(seed.x),y:Math.round(seed.y)});if(seen.size!==grid.cells.size)return 'Keep paths connected around the settlement.';return null;
  }
  canBuild(x,y,kind=null){if(!this.s.estate)return super.canBuild(x,y,kind);return !this.placementIssue(kind||this._placementKind||'shelter',x,y);}
  place(kind,x,y){if(!this.s.estate)return super.place(kind,x,y);const issue=this.interactionIssue()||(!L.BUILDINGS[kind]?'Unknown blueprint.':this.placementIssue(kind,x,y));if(issue)return fail(issue);if(this.actor.orders.length>=12)return fail('This creature has twelve plans. Finish or cancel one first.');const b=L.BUILDINGS[kind];if(b.unique&&!C.content.homes[kind]&&(this.has(kind)||this.allOrders().some(o=>o.type==='build'&&o.kind===kind)))return fail('This unique building is already built or planned.');const order={id:'o'+this.s.nextId++,type:'build',kind,x,y,progress:0,stage:0,legacy:false,paid:false,paused:false,priority:0,created:this.s.simTime,approach:this.s.buildPolicy.approach};this.actor.orders.push(order);this.log(this.actor.name+' will look after the '+b.name+' plan.','plan');return ok({order});}
  createNeedTask(which){const t=super.createNeedTask(which);if(which==='energy'&&t&&this.home()){t.target=this.home();t.label='Resting at my '+L.BUILDINGS[this.home().kind].name.toLowerCase();t.reason='My assigned home is a place to recover.';}return t;}
  interruptActor(c){const t=c.task;if(!t)return;const b=this.s.buildings.find(b=>b.storage?.job?.id===t.jobId);if(t.buffered&&b){b.storage.job.progress=Math.min(t.duration,t.elapsed);b.storage.job.workerId=null;}this.withActor(c,()=>this.releaseSocial(t));c.task=null;c.worldSupply=null;this.releaseDetachedWork();}
  startTask(t){if(t&&marketKinds.includes(t.kind)){if(this.actor.activeQuest)return false;const path=this.findPath(t.target,true);if(path===null)return false;t.path=path;t.phase=path.length?'walk':'work';t.elapsed=0;t.duration=Math.max(1,t.duration||2);this.actor.task=t;return true;}const result=super.startTask(t);if(result){const b=this.s.buildings.find(b=>b.x===t.target?.x&&b.y===t.target?.y);if(this.isIndoor(b))t.insideBuildingId=b.id;}return result;}
  stepWorld(){super.stepWorld();if(!this.s.estate)return;this.ensureDoors();this.assignUnhoused();for(const c of this.creatures)c.eventInteractions=(c.eventInteractions||[]).filter(e=>e.expires>this.s.simTime);this.reconcileCargo();if(this.s.market.orders.length>120)this.s.market.orders=this.s.market.orders.filter(q=>!['done','cancelled'].includes(q.status));}
  finishTask(t){if(!t||this.actor.task!==t)return; if(marketKinds.includes(t.kind)){this.finishMarketTask(t);return;}super.finishTask(t);this.ensureDoors();this.assignUnhoused();}
  emit(type,text,extra={}){super.emit(type,text,extra);if(this.s.progression&&type==='temper')this.grantInteractionEvent('temper',extra.actorId||this.actor.id);}
  grantInteractionEvent(trigger,actorId){const c=this.creatures.find(c=>c.id===actorId);if(!c)return;c.eventInteractions||=[];for(const rule of C.content.events.filter(e=>e.trigger===trigger)){if(c.eventInteractions.some(e=>e.definition===rule.interaction&&e.expires>this.s.simTime))continue;c.eventInteractions.push({id:'event-'+this.s.progression.interactionSequence++,definition:rule.interaction,trigger,created:this.s.simTime,expires:this.s.simTime+rule.seconds});}c.eventInteractions=c.eventInteractions.slice(-16);}
  interactions(c=this.selected){if(!c||c.activeQuest)return [];return C.content.interactions.flatMap(d=>d.eventOnly?(c.eventInteractions||[]).filter(e=>e.definition===d.id&&e.expires>this.s.simTime).map(e=>({...d,instance:e.id,expires:e.expires})): [{...d,instance:d.id}]);}
  interactionReason(c,id){if(!c)return 'Select a creature.';if(c.activeQuest)return 'This creature is away.';const d=this.interactions(c).find(d=>d.instance===id);if(!d)return 'This interaction has expired or is unavailable.';if(d.handler==='care'){const issue=this.withActor(c,()=>this.careIssue(d.action));return issue?String(issue).replaceAll('Pip',c.name).replace('No stored water.',c.name+' carries no water.').replace('No snack in the pantry.',c.name+' has no food in their satchel.'):null;}if((c.interactionCooldowns[d.id]||0)>this.s.simTime)return 'Let the last moment settle.';for(const[id,n]of Object.entries(d.cost))if((c.inventory[id]||0)<n)return 'Needs '+n+' '+L.colony.item(id).name+' in this creature’s satchel.';return null;}
  interact(actorId,instance){if(this.selected?.id!==actorId)return fail('Select this creature before interacting.');const c=this.selected,reason=this.interactionReason(c,instance);if(reason)return fail(reason);const d=this.interactions(c).find(d=>d.instance===instance);return this.commandActor(c.id,()=>{if(d.handler==='care')return this.care(d.action);for(const[id,n]of Object.entries(d.cost))c.inventory[id]-=n;c.bond=L.clamp(c.bond+(d.effects.bond||0),0,100);this.changeFeeling(d.label,d.effects.joy||0,d.effects.anger||0);c.feelings.social=L.clamp(c.feelings.social+(d.effects.social||0),0,100);c.interactionCooldowns[d.id]=this.s.simTime+d.cooldown;if(d.eventOnly)c.eventInteractions=c.eventInteractions.filter(e=>e.id!==instance);this.visual('bond');this.log(c.name+' · '+d.label+'.','heart');return ok();});}
  buyPrestigeItem(id){const issue=this.gateIssue('features','prestige-shop');if(issue)return fail(issue);const d=C.content.shop.find(d=>d.id===id);if(!d)return fail('Unknown prestige offer.');if(this.s.player.level<d.playerLevel)return fail('Guide level '+d.playerLevel+' required.');for(const id of Object.keys(d.items)){const itemIssue=this.gateIssue('items',id);if(itemIssue)return fail(itemIssue);}if(this.s.progression.prestige<d.prestige)return fail('Need '+d.prestige+' prestige.');if(!this.warehouse())return fail('A warehouse must be available for delivery.');for(const[id,n]of Object.entries(d.items))if((this.s.colony.warehouse.inventory[id]||0)+n>1000000)return fail('Warehouse item limit reached.');const settlement=this.settleEconomy({id:this.economySettlementId('prestige-shop',id),prestige:-d.prestige});if(!settlement.ok)return fail('The prestige cost could not be settled.');for(const[id,n]of Object.entries(d.items))this.s.colony.warehouse.inventory[id]=(this.s.colony.warehouse.inventory[id]||0)+n;this.log(d.name+' delivered to the warehouse. Creatures collect items in person.','bag');return ok();}
  sellItem(id,qty=1,assignedId=null){const issue=this.gateIssue('features','trade');if(issue)return fail(issue);if(!this.has('market'))return fail('Build a market stall before listing warehouse goods.');if(!L.colony.item(id)||!int(qty,1,99))return fail('Choose an item and quantity from 1 to 99.');if(assignedId&&!this.creatures.some(c=>c.id===assignedId&&!c.activeQuest))return fail('Choose an available carrier.');const pending=this.s.market.orders.filter(o=>!['done','cancelled'].includes(o.status)&&o.item===id).reduce((n,o)=>n+o.remaining,0);if((this.s.colony.warehouse.inventory[id]||0)-pending<qty)return fail('Only deposited stock not already listed may be queued for sale.');if(this.s.market.orders.filter(o=>!['done','cancelled'].includes(o.status)).length>=24)return fail('Finish existing market orders first.');const order={id:'sale-'+this.s.market.sequence++,item:id,amount:qty,remaining:qty,sold:0,transit:{},staged:{},assignedId,status:'queued',paused:false,priority:1,unitPrice:Math.max(1,Math.floor(L.colony.item(id).price*.65)),created:this.s.simTime};this.s.market.orders.push(order);this.log('Listed '+qty+' '+L.colony.item(id).name+'. A creature must carry and sell them at the market.','market');return ok({order,amount:qty*order.unitPrice});}
  depositKeep(c=this.actor){const keep=super.depositKeep(c);for(const q of this.s.market?.orders||[])if(q.transit[c.id]>0)keep[q.item]=Math.max(keep[q.item]||0,q.transit[c.id]);return keep;}
  reconcileCargo(){for(const c of this.creatures){const available={...c.inventory};for(const q of this.s.market.orders){const n=q.transit[c.id]||0;if(n){const held=Math.min(n,available[q.item]||0);available[q.item]=(available[q.item]||0)-held;q.transit[c.id]=held;if(!['cancelling','cancelled'].includes(q.status))q.remaining+=n-held;}}}}
  marketTask(){const c=this.actor,orders=this.s.market?.orders||[];for(const q of orders.slice().sort((a,b)=>b.priority-a.priority||a.created-b.created)){
    if(q.status==='cancelled'||q.status==='done')continue;
    if(q.status==='cancelling'){const at=Object.entries(q.staged).find(([,n])=>n>0);if(at){const b=this.s.buildings.find(b=>b.id===at[0]);if(b&&this.room(q.item)>0)return this.marketJob('market-reclaim',q,b,Math.min(at[1],this.room(q.item),C.content.rules.marketBatch));}else q.status='cancelled';continue;}
    if(q.paused||q.assignedId&&q.assignedId!==c.id)continue;
    const staged=Object.entries(q.staged).find(([,n])=>n>0);if(staged){const b=this.s.buildings.find(b=>b.id===staged[0]);if(b)return this.marketJob('market-sell',q,b,Math.min(staged[1],C.content.rules.marketBatch));}
    const held=q.transit[c.id]||0;if(held){const market=this.nearest(this.s.buildings.filter(b=>b.kind==='market'&&this.reachable(b)&&this.marketRoom(b)>0));if(market)return this.marketJob('market-deliver',q,market,Math.min(held,this.marketRoom(market)));continue;}
    if(q.remaining>0&&(this.s.colony.warehouse.inventory[q.item]||0)>0){const n=Math.min(q.remaining,this.s.colony.warehouse.inventory[q.item],C.content.rules.marketBatch,this.room(q.item));if(n>0)return this.marketJob('market-pickup',q,this.warehouse(),n);}
   }return null;}
  marketRoom(b){return C.content.rules.marketCapacity-Object.values(b.marketInventory||{}).reduce((n,x)=>n+x,0);}
  marketJob(kind,q,b,amount){return {kind,saleId:q.id,resource:q.item,buildingId:b.id,amount,target:{x:b.x,y:b.y},duration:kind==='market-sell'?C.content.rules.marketSeconds:2,label:({'market-pickup':'Collecting for sale','market-deliver':'Delivering to the market','market-sell':'Selling at the stall','market-reclaim':'Returning unsold stock'})[kind]+' · '+L.colony.item(q.item).name,reason:'Only a completed sale at the stall earns coins.',thought:'A little delivery, a useful exchange.'};}
  finishMarketTask(t){const q=this.s.market.orders.find(q=>q.id===t.saleId),c=this.actor,b=this.s.buildings.find(b=>b.id===t.buildingId);if(!q||!b||!this.at(b)){c.task=null;return;}const inv=c.inventory; b.marketInventory ||= {};
   if(t.kind==='market-reclaim'&&q.status==='cancelling'){const n=Math.min(t.amount,q.staged[b.id]||0,b.marketInventory[q.item]||0,this.room(q.item));if(n){q.staged[b.id]-=n;b.marketInventory[q.item]-=n;inv[q.item]=(inv[q.item]||0)+n;c.needsDeposit=true;}if(!Object.values(q.staged).some(n=>n>0))q.status='cancelled';}
   else if(!q.paused&&!['done','cancelled','cancelling'].includes(q.status)){
    if(t.kind==='market-pickup'){const w=this.s.colony.warehouse.inventory,n=Math.min(t.amount,q.remaining,w[q.item]||0,this.room(q.item));if(n){w[q.item]-=n;inv[q.item]=(inv[q.item]||0)+n;q.remaining-=n;q.transit[c.id]=(q.transit[c.id]||0)+n;this.recordTransfer('out',{[q.item]:n});q.status='carrying';}}
    if(t.kind==='market-deliver'){const n=Math.min(t.amount,q.transit[c.id]||0,inv[q.item]||0,this.marketRoom(b));if(n){inv[q.item]-=n;q.transit[c.id]-=n;q.staged[b.id]=(q.staged[b.id]||0)+n;b.marketInventory[q.item]=(b.marketInventory[q.item]||0)+n;q.status='at-stall';this.emit('transfer',c.name+' delivered to the market.');}}
    if(t.kind==='market-sell'){const n=Math.min(t.amount,q.staged[b.id]||0,b.marketInventory[q.item]||0);if(n){const cash=n*q.unitPrice,settlement=this.settleEconomy({id:'market:'+q.id+':'+(q.sold+n),guide:cash,playerXp:1,actorXp:1},'Market sale: '+L.colony.item(q.item).name);if(!settlement.ok){c.task=null;return;}b.marketInventory[q.item]-=n;q.staged[b.id]-=n;q.sold+=n;this.emit('sale','+'+cash+' coins · sold at the market.');if(q.sold>=q.amount){q.status='done';this.s.market.history.unshift({id:q.id,item:q.item,amount:q.sold,coins:q.sold*q.unitPrice,time:this.s.simTime,actorId:c.id});this.s.market.history=this.s.market.history.slice(0,40);}}}
   }c.task=null;}
  controlSale(id,command,value){const q=this.s.market.orders.find(q=>q.id===id);if(!q||['done','cancelled'].includes(q.status))return fail('This sale is already settled.');if(command==='cancel'){q.status='cancelling';q.remaining=0;for(const c of this.creatures)if(q.transit[c.id]){q.transit[c.id]=0;c.needsDeposit=true;}if(!Object.values(q.staged).some(n=>n>0))q.status='cancelled';}
   else if(command==='pause'||command==='stop')q.paused=true;
   else if(command==='resume')q.paused=false;
   else if(command==='priority'){if(!int(value,0,2))return fail('Choose a priority from 0 to 2.');q.priority=value;}
   else if(command==='assign'){if(value&&!this.creatures.some(c=>c.id===value&&!c.activeQuest))return fail('Choose an available creature.');if(Object.values(q.transit).some(n=>n>0))return fail('Wait until the current carrier has delivered the goods.');q.assignedId=value||null;}
   else return fail('Unknown market command.');for(const c of this.creatures)if(c.task?.saleId===id)this.interruptActor(c);return ok();}
  handlers(){const h=super.handlers();const oldPlans=h.plans;h.plans=()=>{const t=this.marketTask();if(t&&this.startTask(t))return 'running';return oldPlans();};const quest=h.quest;h.quest=()=>this.actor.questPlan?.paused?'failure':quest();return h;}
  export(){const out=super.export();out.version=7;out.state.version=7;return out;}
  static import(doc){if(doc?.version!==7){const base=super.import(doc);return Composition.constructThrough('village',base.export().state,{migrate:true});}const raw=copy(doc);validateVillage(raw.state);root.LWVillageValidation.validate(raw.state);raw.version=6;raw.state.version=6;const base=super.import(raw);const e=Composition.constructThrough('village',base.export().state);validateVillage(e.export().state);root.LWVillageValidation.validate(e.export().state);return e;}
 };}
 function validateVillage(s){const bad=m=>{throw Error('Village save: '+m);};if(!s?.estate||!Array.isArray(s.estate.islands)||!int(s.estate.purchases,0,48)||s.estate.islands.length!==s.estate.purchases+1||s.estate.islands.length>C.content.rules.maxIslands)bad('invalid islands');const owned=G.ownedSet?G.ownedSet(s):new Set(s.estate.islands.map(i=>G.key(i.ix,i.iy)));if(owned.size!==s.estate.islands.length||!owned.has('0,0'))bad('duplicate islands or missing homeland');for(const i of s.estate.islands)if(!int(i.ix,-48,48)||!int(i.iy,-48,48))bad('invalid island coordinate');const reached=new Set(['0,0']),q=[{ix:0,iy:0}];for(let h=0;h<q.length;h++)for(const[dx,dy]of G.DIRS){const p={ix:q[h].ix+dx,iy:q[h].iy+dy},k=G.key(p.ix,p.iy);if(owned.has(k)&&!reached.has(k)){reached.add(k);q.push(p);}}if(reached.size!==owned.size)bad('islands must share connected edges');
  const p=s.progression;if(!p||p.version!==1||!int(p.prestige,0,1e12)||!int(p.earnedPrestige,p.prestige,1e12)||!int(p.slots,s.colony.creatures.length,C.content.rules.maxSlots)||!int(p.interactionSequence,1,1e9))bad('invalid player progression');if(!p.research||Object.entries(p.research).some(([id,v])=>v!==true||!C.content.research.some(r=>r.id===id)))bad('unknown research');if(!p.features||Object.entries(p.features).some(([id,v])=>!int(v,0,4)||!C.content.features.some(f=>f.id===id)))bad('invalid feature rank');for(const[id,rank]of Object.entries(p.features))if(!C.content.research.some(r=>r.grants?.feature===id&&r.grants.rank===rank&&p.research[r.id]))bad('feature rank lacks research');if(!p.tutorial||!int(p.tutorial.step,0,30)||typeof p.tutorial.dismissed!=='boolean'||typeof p.tutorial.complete!=='boolean')bad('invalid onboarding');
  for(const b of s.buildings){if(!G.available(s,b.x,b.y))bad('building on unowned ground');if(b.door&&(!int(b.door.dx,-1,1)||!int(b.door.dy,-1,1)||Math.abs(b.door.dx)+Math.abs(b.door.dy)!==1))bad('invalid doorway');if(b.planAssignee&&!s.colony.creatures.some(c=>c.id===b.planAssignee))bad('unknown workplace assignee');}
  const eventIds=new Set();for(const c of s.colony.creatures){if(c.homeId&&!s.buildings.some(b=>b.id===c.homeId&&C.content.homes[b.kind]))bad('unknown assigned home');if(!G.available(s,Math.round(c.creature.x),Math.round(c.creature.y))&&!c.activeQuest)bad('creature on unowned ground');if(!Array.isArray(c.eventInteractions)||c.eventInteractions.length>16)bad('invalid event interactions');for(const e of c.eventInteractions){if(eventIds.has(e.id)||!C.content.interactions.some(d=>d.id===e.definition&&d.eventOnly)||!Number.isFinite(e.expires)||e.expires<e.created)bad('invalid event interaction');eventIds.add(e.id);}if(c.task?.path?.some(v=>!G.available(s,v.x,v.y)))bad('path outside owned land');}
  for(const b of s.buildings){const d=C.content.homes[b.kind];if(d&&s.colony.creatures.filter(c=>c.homeId===b.id).length>d.places+(b.level-1)*d.perLevel)bad('home over capacity');}
  const market=s.market;if(!market||!int(market.sequence,1,1e9)||!Array.isArray(market.orders)||market.orders.length>1000||!Array.isArray(market.history)||market.history.length>40)bad('invalid market');const ids=new Set();let max=0;const stocks={};for(const o of market.orders){if(ids.has(o.id)||!/^sale-\d+$/.test(o.id)||!L.colony.item(o.item)||!int(o.amount,1,99)||!int(o.remaining,0,99)||!int(o.sold,0,o.amount)||!int(o.unitPrice,1,10000)||!['queued','carrying','at-stall','cancelling','cancelled','done'].includes(o.status)||typeof o.paused!=='boolean'||!int(o.priority,0,2))bad('invalid sale order');ids.add(o.id);max=Math.max(max,+o.id.slice(5));if(o.assignedId&&!s.colony.creatures.some(c=>c.id===o.assignedId))bad('unknown sale assignee');let unsold=o.remaining;for(const[id,n]of Object.entries(o.transit)){const c=s.colony.creatures.find(c=>c.id===id);if(!c||!int(n,0,99)||n>(c.inventory[o.item]||0))bad('invalid market cargo');unsold+=n;}for(const[id,n]of Object.entries(o.staged)){const b=s.buildings.find(b=>b.id===id&&b.kind==='market');if(!b||!int(n,0,99))bad('invalid market stall');unsold+=n;stocks[id]||={};stocks[id][o.item]=(stocks[id][o.item]||0)+n;}if(!['cancelled','cancelling'].includes(o.status)&&unsold+o.sold!==o.amount)bad('sale quantities do not reconcile');}if(market.sequence<=max)bad('sale sequence collision');for(const b of s.buildings){for(const[id,n]of Object.entries(b.marketInventory||{}))if(!int(n,0,C.content.rules.marketCapacity)||n!==(stocks[b.id]?.[id]||0))bad('stall inventory does not reconcile');for(const[id,n]of Object.entries(stocks[b.id]||{}))if(n!==(b.marketInventory?.[id]||0))bad('missing physical stall inventory');}for(const c of s.colony.creatures)if(marketKinds.includes(c.task?.kind)&&!ids.has(c.task.saleId))bad('orphaned market task');
 }
 L.Village={validate:validateVillage,indoor,marketKinds};
 function installFactories(){
  const oldDemo=L.createWorldDemo;
  L.createWorldDemo=()=>{const e=Composition.constructThrough('village',oldDemo().export().state,{demo:true});e.s.progression.prestige=52;e.s.progression.earnedPrestige=52;e.s.player.level=Math.max(e.s.player.level,5);e.s.progression.tutorial.dismissed=true;for(const c of e.creatures)c.homeId=null;const home=e.s.buildings.find(b=>b.kind==='cottage');if(!home){const b=e.s.buildings.find(b=>b.kind==='shelter');if(b)b.level=3;}e.assignUnhoused();return e;};
 }
 Composition.register({id:'village',order:40,define:defineLayer,initialize:initializeVillage,installFactories});
 if(typeof module!=='undefined'&&module.exports)module.exports=L;
})(typeof globalThis!=='undefined'?globalThis:this);
