/** The executable: deterministic bytes, no absolute paths or packages, and a confined standalone smoke run. */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {bundle, PROJECT, REPOSITORY} from '../scripts/bundle.cjs';
import {smoke} from '../scripts/smoke.cjs';
import {candidate, CHECKED_IN, execute, temporaryDirectory} from './support.cjs';

test('two builds of the same sources are byte-identical', async () => {
 const first = (await candidate()).result, second = await bundle();
 assert.ok(first.bytes.equals(second.bytes));
 assert.equal(first.sha256, second.sha256);
 assert.equal(first.sourceIdentity, second.sourceIdentity);
});

test('the bundle has a shebang, its banner and no absolute path, package or source map', async () => {
 const text = (await candidate()).result.bytes.toString('utf8');
 assert.ok(text.startsWith('#!/usr/bin/env node\n// Generated by source/process-studio/scripts/bundle.cts - do not edit.\n'));
 assert.ok(!text.includes(PROJECT) && !text.includes(REPOSITORY));
 assert.doesNotMatch(text, /node_modules/);
 assert.doesNotMatch(text, /sourceMappingURL/);
 assert.match(text, /\/\/ \.\.\/wildlands\/source\/process-sdk\.cts/);
});

test('it runs standalone from an empty directory with file access confined to it', async () => {
 const {result} = await candidate();
 smoke(result.bytes, result.engine);
 const directory = temporaryDirectory('process-studio-standalone-');
 fs.writeFileSync(directory + '/process-studio', result.bytes, {mode: 0o755});
 const outcome = execute(directory + '/process-studio', ['--compact', 'discover'], directory);
 assert.equal(outcome.status, 0);
 assert.equal(outcome.stderr, '');
});

test('the checked-in executable exists, is executable and is a Process Studio bundle', () => {
 const bytes = fs.readFileSync(CHECKED_IN);
 assert.ok(bytes.subarray(0, 20).toString('utf8').startsWith('#!/usr/bin/env node\n'));
 if (process.platform !== 'win32') assert.equal(fs.statSync(CHECKED_IN).mode & 0o111, 0o111);
});
