const escapeHtml = (s: string) =>
  s.replace(
    /[&<>"']/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!,
  );
export function previewTemplate(
  name: string,
  css: string,
  script: string,
  payload: string,
  version: string,
) {
  const vectors = ['position', 'rotation', 'scale']
    .map(
      (key) =>
        `<fieldset><legend>${key === 'position' ? 'Position · m' : key === 'rotation' ? 'Rotation · °' : 'Scale'}</legend><div class="vector">${['x', 'y', 'z'].map((axis) => `<label><span>${axis.toUpperCase()}</span><input type="number" id="${key}-${axis}" aria-label="${key} ${axis}" step="${key === 'rotation' ? 5 : 0.1}" inputmode="decimal"></label>`).join('')}</div></fieldset>`,
    )
    .join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>${escapeHtml(name)} · Scene Forge</title><style>${css}</style></head>
<body><header><div class="brand"><strong>Scene Forge <small>${escapeHtml(version)}</small></strong><div><h1 id="scene-name"></h1><p class="muted" id="scene-meta"></p><select id="scene-chooser" aria-label="Example scene" hidden></select></div></div><div class="actions"><button id="undo" title="Undo (Ctrl/⌘ Z)" disabled>Undo</button><button id="redo" title="Redo (Ctrl/⌘ Shift Z)" disabled>Redo</button><button id="recipe" aria-expanded="false" aria-controls="source-panel">View recipe</button><button id="save-bundle" title="Download scene and model recipes">Save bundle</button><button id="png">Save PNG</button><button id="glb">Export GLB</button><button id="save-edits" class="primary" disabled>Save edits</button></div></header>
<main class="workspace"><aside class="navigator" aria-label="Scene and model library"><div class="navigator-head"><div class="tabs" role="tablist" aria-label="Browse"><button id="scene-tab" role="tab" aria-selected="true" aria-controls="scene-list">Scene</button><button id="models-tab" role="tab" aria-selected="false" aria-controls="model-list">Models <span id="model-count"></span></button></div><label class="search-label"><span id="filter-label">Find an object</span><input id="filter" type="search" placeholder="Filter by name" autocomplete="off"></label></div><section id="scene-list" role="tabpanel" aria-labelledby="scene-tab"><div class="list-heading"><span>Objects</span><span id="node-count"></span></div><div id="objects"></div></section><section id="model-list" role="tabpanel" aria-labelledby="models-tab" hidden><p class="library-help">Add a model, then move it into place.</p><label class="category-label">Category<select id="asset-category" aria-label="Category"><option value="">All models</option></select></label><div id="models"></div></section><div class="navigator-bottom"><p class="muted">Reusable models stay linked to their recipes.</p><details id="warning-panel" hidden><summary id="warning-summary">Build notes</summary><p id="warnings"></p></details></div></aside>
<section class="viewport" aria-label="Scene composer"><div class="toolbar"><div class="views" aria-label="Camera views"><button data-view="iso" aria-pressed="true">Perspective</button><button data-view="front" aria-pressed="false">Front</button><button data-view="side" aria-pressed="false">Side</button><button data-view="top" aria-pressed="false">Top</button></div><div class="views"><button id="fit" title="Frame selection or scene (F)">Frame</button><button id="fit-all" title="Frame all objects (Shift+F)">Fit all</button><button id="grid" aria-pressed="true">Grid</button><button id="wireframe" aria-pressed="false">Wireframe</button></div></div><div class="edit-toolbar"><div class="views" aria-label="Transform tool"><button data-mode="select" aria-pressed="true" title="Select (Q)">Select</button><button data-mode="translate" aria-pressed="false" title="Move (W)">Move</button><button data-mode="rotate" aria-pressed="false" title="Rotate (E)">Rotate</button><button data-mode="scale" aria-pressed="false" title="Scale (R)">Scale</button></div><label class="inline-check"><input id="snap" type="checkbox"> Snap <span class="muted">0.25 m / 15°</span></label><span id="edit-state" class="muted">Saved scene</span></div><div id="stage"><span class="stage-label" id="view-label">Perspective</span><span class="stage-help">Drag to orbit · Right-drag to pan · Scroll to zoom · F to frame</span><div id="loading" role="status">Loading scene…</div><section id="source-panel" hidden aria-label="Scene recipe"><div><h2 id="source-title">Current scene recipe</h2><button id="close-source">Close</button></div><pre id="source"></pre></section><div id="toast" role="status" aria-live="polite" hidden></div></div></section>
<aside class="inspector" aria-label="Object inspector"><div class="inspector-title"><h2 id="selection-title">Scene composition</h2><span id="selection-kind" class="muted"></span></div><div id="empty-selection"><p>Select an object to position it, or add a reusable model from the library.</p><button id="browse-models">Browse models</button><div class="help-block"><h3>Make it reusable</h3><p>Capture an assembly with <code>model capture</code>, then compose scenes with its instances.</p></div><div class="help-block"><h3>Keep your work</h3><p>Download edits, then apply the JSON batch to your project with the CLI.</p></div></div><form id="transform-form" hidden><label class="field">Name<input id="node-name" maxlength="120"></label><p class="node-id" id="selected-id"></p>${vectors}<label class="inline-check"><input type="checkbox" id="node-visible"> Visible in scene</label><div class="object-actions"><button type="button" id="duplicate">Duplicate</button><button type="button" id="ground">Ground</button><button type="button" id="remove" class="danger">Remove</button></div></form><div id="editor-tools"></div><details class="node-json"><summary>Node details</summary><pre id="details">Select an object to inspect its source and dimensions.</pre></details><div class="object-actions"><button id="copy-camera">Copy review plan</button><button id="save-review">Save review plan</button></div></aside></main>
<footer><span id="stats"></span><span id="bounds"></span><span class="accent">Offline · Three.js</span></footer><script>window.__FORGE__=${payload};</script><script>${script.replace(/<\/script/gi, '<\\/script')}</script></body></html>`;
}
