import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import type {Page} from 'playwright';
import {launchBrowser,monitorContext} from './browser-harness';
const ROOT=path.resolve(__dirname,'../..'),OUT=path.join(ROOT,'verification','v15'),SHOTS=process.env.LITTLEWILD_SCREENSHOT_DIR||'/tmp/littlewild-building-interiors';
const results:{name:string;passed:boolean;error?:string}[]=[];
async function check(name:string,work:()=>Promise<void>):Promise<void>{try{await work();results.push({name,passed:true});}catch(error){results.push({name,passed:false,error:String(error)});console.error(name,error);}}
async function shot(p:Page,name:string):Promise<void>{await p.waitForFunction(()=>{const canvas=document.querySelector<HTMLCanvasElement>('.building-interior-stage canvas');if(!canvas||!canvas.width)return false;const sample=document.createElement('canvas');sample.width=sample.height=1;const context=sample.getContext('2d',{willReadFrequently:true})!;context.drawImage(canvas,0,0,1,1,0,0,1,1);return context.getImageData(0,0,1,1).data[0]!>100;},{},{timeout:15000});if(process.env.LITTLEWILD_CAPTURE_SCREENSHOTS==='1'){fs.mkdirSync(SHOTS,{recursive:true});await p.screenshot({path:path.join(SHOTS,name+'.png'),animations:'disabled',timeout:30000});}}
async function scene(p:Page,pack:string,id:string):Promise<void>{
 await p.evaluate("Littlewild.interiors.close(false);Littlewild.open('scenarios')");await p.locator('[data-scenario=select]').filter({hasText:pack}).click();await p.locator('[data-scenario=review][data-id='+id+']').click();await p.locator('[data-scenario=launch]').click();await p.evaluate('Littlewild.engine.s.paused=true;Littlewild.refresh()');
}
async function inspect(p:Page,id:string):Promise<void>{await p.evaluate(id=>{const w=window as unknown as {Littlewild:{land:{show(type:string,id:string):void}}};w.Littlewild.land.show('building',id);},id);await p.locator('[data-act=land-visit]').click();}
async function main():Promise<void>{
 const browser=await launchBrowser(),context=await browser.newContext({viewport:{width:1440,height:900}}),diagnostics=monitorContext(context);
 try{
  const p=await context.newPage();p.setDefaultTimeout(5000);await p.setContent(fs.readFileSync(process.env.LITTLEWILD_BROWSER_ARTIFACT||path.join(ROOT,'littlewild.html'),'utf8'),{waitUntil:'load',timeout:30000});await p.waitForFunction(()=>!!(window as unknown as {Littlewild?:unknown}).Littlewild);await p.locator('[data-act=begin]').click();
  await check('Default building inspector enters a detached floor view and Escape restores exact map camera',async()=>{
   await scene(p,'Littlewild','charted-home');assert.equal(await p.locator('#building-interior').isVisible(),false);await p.evaluate("Littlewild.land.show('building','b2')");const before=await p.evaluate('JSON.stringify(Littlewild.engine.export())'),camera=await p.evaluate('JSON.stringify(Littlewild.world.camera)');await p.locator('[data-act=land-visit]').click();assert.equal(await p.locator('#building-interior').isVisible(),true);assert.equal(await p.evaluate('JSON.stringify(Littlewild.engine.export())'),before);assert.equal(await p.evaluate('Littlewild.pauseStatus().kind'),'manual');await p.locator('[data-interior=floor][data-floor=upper]').click();assert.equal(await p.evaluate('Littlewild.interiors.state.floorId'),'upper');await shot(p,'default-upper-desktop');await p.keyboard.press('Escape');assert.equal(await p.locator('#building-interior').isVisible(),false);assert.equal(await p.evaluate('JSON.stringify(Littlewild.world.camera)'),camera);assert.equal(await p.evaluate('document.activeElement.id'),'world');
  });
  await check('Visiting and selecting floors keeps the simulation running unless manually paused',async()=>{
   await inspect(p,'b2');await p.evaluate('Littlewild.engine.s.paused=false;Littlewild.refresh()');const before=await p.evaluate<number>('Littlewild.engine.s.simTime');await p.waitForFunction(previous=>(window as unknown as {Littlewild:{engine:{s:{simTime:number}}}}).Littlewild.engine.s.simTime>previous,before,{timeout:15000});assert(await p.evaluate<number>('Littlewild.engine.s.simTime')>before);assert.equal(await p.evaluate('Littlewild.pauseStatus().running'),true);await p.locator('[data-interior=floor][data-floor=upper]').click();assert.equal(await p.evaluate('Littlewild.pauseStatus().running'),true);await p.evaluate('Littlewild.engine.s.paused=true;Littlewild.refresh()');
  });
  await check('Interior production form binds items and equipment to this exact upper workstation',async()=>{
   await p.locator('#interior-production [name=recipe]').selectOption('planks');await p.locator('#interior-production [name=batches]').fill('2');await p.locator('#interior-production button[type=submit]').click();assert.deepEqual(await p.evaluate("Littlewild.engine.s.interiors.production.b2.find(q=>q.recipe==='planks')"),{floorId:'upper',stationId:'work',recipe:'planks',remaining:2});await p.locator('#interior-production [name=recipe]').selectOption('friendship_charm');await p.locator('#interior-production [name=batches]').fill('1');await p.locator('#interior-production button[type=submit]').click();assert.match(await p.locator('.building-interior-status').innerText(),/placed/);assert.equal(await p.evaluate("Littlewild.engine.s.interiors.production.b2.find(q=>q.recipe==='friendship_charm').floorId"),'upper');
  });
  await check('Actual worker progress and task names appear on the visited floor after physical travel',async()=>{
   await p.evaluate("Littlewild.engine.s.paused=false;for(let i=0;i<1200;i++){Littlewild.engine.step(.1);const v=Littlewild.engine.buildingInterior('b2');if(v.actors.some(a=>a.floorId==='upper'&&a.progress>0))break;}Littlewild.engine.s.paused=true;Littlewild.refresh()");const actors=await p.evaluate<{name:string;floorId:string;progress:number|null}[]>("Littlewild.engine.buildingInterior('b2').actors");assert(actors.some(a=>a.floorId==='upper'&&a.progress!>0));assert.match(await p.locator('.building-interior-details').innerText(),/remaining/);await shot(p,'default-upper-working-desktop');
  });
  await check('Companion floor visit form creates a real saved walking intent without moving immediately',async()=>{
   await p.locator('[data-interior=floor][data-floor=ground]').click();await p.locator('#interior-visit [name=actor]').selectOption('c3');const position=await p.evaluate('JSON.stringify(Littlewild.engine.creatures.find(c=>c.id===\'c3\').creature)');await p.locator('#interior-visit button[type=submit]').click();assert.equal(await p.evaluate('JSON.stringify(Littlewild.engine.creatures.find(c=>c.id===\'c3\').creature)'),position);assert.equal(await p.evaluate("Littlewild.engine.s.interiors.visits.find(v=>v.actorId==='c3').floorId"),'ground');
  });
  await check('Office building visit uses its installed furniture and actual team tasks without scenario-specific UI branches',async()=>{
   await scene(p,'Office','operations-shift');await p.evaluate("Littlewild.engine.s.paused=false;for(let i=0;i<150;i++){Littlewild.engine.step(.1);if(Littlewild.engine.creatures.find(c=>c.id==='c2').activeQuest)break;}Littlewild.engine.step(.1);Littlewild.engine.s.paused=true;Littlewild.refresh()");await inspect(p,'office-sales');assert.match(await p.locator('.building-interior-details').innerText(),/Phil[\s\S]*Customer discovery call/);assert.equal(await p.evaluate("Littlewild.engine.buildingInterior('office-sales').actors.find(a=>a.id==='c2').floorId"),'ground');await shot(p,'office-sales-actual-call');await p.keyboard.press('Escape');await inspect(p,'office-packing');assert.match(await p.locator('#building-interior-title').innerText(),/Packing/);assert.deepEqual(await p.evaluate("(()=>{const v=Littlewild.engine.buildingInterior('office-packing');return [v.fixtureAsset,v.fixtureModel]})()"),['bench','world']);await p.evaluate("Littlewild.engine.s.paused=false;Littlewild.engine.advance(55);Littlewild.engine.s.paused=true;Littlewild.refresh()");await shot(p,'office-packing-desktop');assert.equal(await p.evaluate('Littlewild.interiors.state.buildingId'),'office-packing');await p.keyboard.press('Escape');await inspect(p,'office-sales');assert.match(await p.locator('#building-interior-title').innerText(),/Sales/);await shot(p,'office-sales-desktop');
  });
  for(const viewport of [{width:1440,height:900},{width:390,height:844}]){
   await p.setViewportSize(viewport);await p.waitForTimeout(100);
   await check('Floor selection, return navigation and shared clock fit '+viewport.width+'px without horizontal overflow',async()=>{
    assert.equal(await p.evaluate('document.documentElement.scrollWidth<=innerWidth'),true);assert.equal(await p.locator('#pause-button').isVisible(),true);for(const selector of ['[data-interior=back]','[data-interior=floor][data-floor=upper]']){const box=await p.locator(selector).first().boundingBox();assert(box&&box.width>=44&&box.height>=44&&box.x>=0&&box.x+box.width<=viewport.width);}await p.locator('[data-interior=floor][data-floor=upper]').click();const title=await p.locator('#building-interior-title').boundingBox(),stage=await p.locator('.building-interior-stage').boundingBox(),header=await p.locator('.building-interior-header').boundingBox(),footer=await p.locator('.building-interior-footer').boundingBox();assert(title&&title.width>=180&&title.height<=65,'Building title must remain readable');assert(stage&&stage.height>=170&&header&&stage.y>=header.y+header.height,'Room must fit below the controls');assert(footer&&footer.y+footer.height<=viewport.height,'Leave and clock status must fit the viewport');await shot(p,'office-upper-'+viewport.width);await p.locator('[data-interior=back]').first().focus();await p.keyboard.press('Enter');assert.equal(await p.locator('#building-interior').isVisible(),false);await inspect(p,'office-sales');
   });
  }
  await check('Current standalone HTML has no runtime errors or external requests',async()=>{assert.deepEqual(diagnostics.errors,[]);assert.deepEqual(diagnostics.requests,[]);assert.deepEqual(diagnostics.consoleProblems.filter(v=>!v.includes('No available adapters')&&!v.includes('GPU stall')),[]);});
 }finally{await browser.close();}
 fs.mkdirSync(OUT,{recursive:true});const report={suite:'building-interiors-browser',passed:results.filter(r=>r.passed).length,total:results.length,results};fs.writeFileSync(path.join(OUT,'building-interiors-browser.json'),JSON.stringify(report,null,2)+'\n');console.log(`${report.passed}/${report.total} building interior browser checks passed`);if(report.passed!==report.total)process.exitCode=1;
}
main().catch(error=>{console.error(error);process.exitCode=1;});
