/// <reference path="../storytelling-ui-contracts.d.ts" />
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import type {Page} from 'playwright';
import {launchBrowser,monitorContext} from './browser-harness';
const ROOT=path.resolve(__dirname,'../..'),ARTIFACT=process.env.LITTLEWILD_BROWSER_ARTIFACT||path.join(ROOT,'littlewild.html'),OUT=process.env.LITTLEWILD_STORYTELLING_OUT||path.join(ROOT,'verification/v15');
const results:{name:string;passed:boolean;error?:string}[]=[];
async function test(name:string,work:()=>Promise<void>):Promise<void>{try{await work();results.push({name,passed:true});console.log('PASS '+name);}catch(error){results.push({name,passed:false,error:String(error)});console.error(name,error);}}
async function value<T=unknown>(page:Page,expression:string):Promise<T>{return page.evaluate(expression) as Promise<T>;}
const snapshot=(page:Page):Promise<string>=>value<string>(page,'JSON.stringify(Littlewild.engine.export())');
const revision=(page:Page):Promise<number>=>value<number>(page,'Littlewild.scenarioUI.editor.session.revision');
async function fill(page:Page,form:string,values:Record<string,string>):Promise<void>{for(const [name,v] of Object.entries(values))await page.locator(`[data-story-form="${form}"] [name="${name}"]`).fill(v);}
async function submit(page:Page,form:string):Promise<void>{await page.locator(`[data-story-form="${form}"] button[type="submit"]`).click();}
async function select(page:Page,form:string,name:string,v:string):Promise<void>{await page.locator(`[data-story-form="${form}"] [name="${name}"]`).selectOption(v);}
async function details(page:Page,title:string):Promise<void>{const summary=page.locator('.storytelling-event-panel summary').filter({hasText:title}).first();if(!await summary.evaluate(el=>(el.parentElement as HTMLDetailsElement).open))await summary.click();}
async function seek(page:Page,seconds:number):Promise<void>{await page.locator('[data-story-seek]').evaluate((el,time)=>{const input=el as HTMLInputElement;input.value=String(time);input.dispatchEvent(new Event('input',{bubbles:true}));},seconds);await page.waitForFunction(time=>document.querySelector('[data-story-time]')?.textContent?.startsWith(Number(time).toFixed(2)),seconds);}
async function pixels(page:Page,selector:string):Promise<string>{return page.locator(selector).evaluate(canvas=>{const root=window as unknown as {Littlewild:{scenarioUI:{editor:{storytelling:LWStorytellingUI.Surface}}}};root.Littlewild.scenarioUI.editor.storytelling.draw(0);return (canvas as HTMLCanvasElement).toDataURL();});}
async function ready(page:Page):Promise<void>{await page.waitForFunction(()=>document.querySelector('[data-story-preview-notice]')?.textContent?.includes('Detached scene ready'),{},{timeout:20000});}
async function main():Promise<void>{
 fs.mkdirSync(OUT,{recursive:true});const browser=await launchBrowser(),context=await browser.newContext({acceptDownloads:true}),diagnostics=monitorContext(context);
 try{for(const width of [1440,390]){
  const page=await context.newPage();page.setDefaultTimeout(20000);await page.setViewportSize({width,height:width===390?844:1000});await page.setContent(fs.readFileSync(ARTIFACT,'utf8'),{waitUntil:'load',timeout:30000});await page.waitForFunction(()=>!!(window as unknown as {Littlewild?:unknown}).Littlewild);await page.locator('[data-act="begin"]').click();await page.evaluate('Littlewild.engine.s.paused=true;Littlewild.open("scenarios")');await page.locator('[data-scenario="editor"]').click();
  // Explicit synthetic authoring fixture: existing native scene plus another world.
  await page.evaluate('(()=>{const editor=Littlewild.scenarioUI.editor,p=editor.session.snapshot(),first=p.scenes[0];for(const scene of p.scenes)delete scene.initialState.scenarioResources;first.graph={...first.graph,kind:"level",rendering:{dimension:"3d",rendererId:"basic"},connections:[{id:"story-travel",targetSceneId:"story-remote",label:"Travel to story world"}]};p.worlds.push({...structuredClone(p.worlds[0]),id:"story-world",name:"Second story world"});p.scenes.push({...structuredClone(first),id:"story-remote",name:"Remote story scene",worldId:"story-world",graph:{kind:"level",rendering:{dimension:"2d",rendererId:"basic"}}});editor.session.replace(p);Littlewild.open("scene-editor")})()');
  const active=await snapshot(page),first=await value<string>(page,'Littlewild.scenarioUI.editor.session.snapshot().scenes[0].id'),entity=await value<LWSceneGraph.Entity>(page,'Littlewild.scenarioUI.editor.session.entities(Littlewild.scenarioUI.editor.session.snapshot().scenes[0].id).find(e=>e.category==="creatures")');
  await page.locator('[data-story="open"]').click();
  await test('Storyboard shot authoring links normal scenes across worlds with visible narrative and shared history at '+width+'px',async()=>{
   await page.locator('[data-story="new-board"]').first().click();await fill(page,'create',{id:'journey-board',name:'Across two worlds'});await submit(page,'create');
   await fill(page,'shot',{id:'opening-shot',name:'Meet the guide',narrative:'Our guide opens the story in the first world.'});await select(page,'shot','scene',first);await submit(page,'shot');await page.locator('[data-story="add-shot"]').click();await fill(page,'shot',{id:'remote-shot',name:'Another world',narrative:'Continue the same story across the world connection.'});await select(page,'shot','scene','story-remote');await submit(page,'shot');
   assert.equal(await page.locator('.storytelling-shot').count(),2);assert((await page.locator('.storytelling-shot').last().textContent())?.includes('Second story world'));const before=await revision(page);await page.locator('[data-story="shot-earlier"]').click();assert.equal(await value<string>(page,'Littlewild.scenarioUI.editor.session.snapshot().storytelling.storyboards[0].shots[0].id'),'remote-shot');await page.locator('[data-story="undo"]').click();assert.equal(await value<string>(page,'Littlewild.scenarioUI.editor.session.snapshot().storytelling.storyboards[0].shots[0].id'),'opening-shot');assert.equal(await revision(page),before+2);assert.equal(await snapshot(page),active);const retained=await revision(page);await page.locator('[data-story=confirm-board]').click();assert.equal(await page.evaluate(()=>(document.activeElement as HTMLElement).dataset.story),'cancel-delete');await page.locator('[data-story=cancel-delete]').click();assert.equal(await revision(page),retained);assert.equal(await page.evaluate(()=>(document.activeElement as HTMLElement).dataset.story),'confirm-board');
   if(process.env.LITTLEWILD_CAPTURE_SCREENSHOTS==='1'){await page.locator('.storytelling-section-head').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(OUT,'storytelling-board-'+width+'.png'),animations:'disabled'});}
  });
  await test('Actual 3D cinematic timeline animates creature position without changing native state; play/pause/seek/stop/replay at '+width+'px',async()=>{
   assert.equal(await value<unknown>(page,'Littlewild.scenarioUI.editor.session.snapshot().resources'),undefined,'This regression must use a native draft without explicit resource catalogs.');const catalogs=await value<string>(page,'JSON.stringify([LWAssets.all(),LWCreatures.all()])');
   await page.locator('[data-story="timeline"]').click();await page.locator('[data-story="new-clip"]').first().click();await fill(page,'create',{id:'opening-clip',name:'Guide arrival',duration:'5'});await select(page,'create','scene',first);await submit(page,'create');await ready(page);
   await fill(page,'track',{id:'guide-position',first:String(entity.x),last:String(entity.x+4)});await select(page,'track','target','creatures:'+entity.id);await select(page,'track','property','x');await submit(page,'track');await ready(page);const native=await value<string>(page,'JSON.stringify(Littlewild.scenarioUI.editor.session.snapshot().scenes[0].initialState)');
   const before=await pixels(page,'[data-story-preview]');await page.locator('[data-story="play"]').click();await page.waitForFunction(()=>{const text=document.querySelector('[data-story-time]')?.textContent??'';return text.includes('playing')&&!text.startsWith('0.00');});await page.locator('[data-story="pause"]').click();assert((await page.locator('[data-story-time]').textContent())?.includes('paused'));await seek(page,2.5);const after=await pixels(page,'[data-story-preview]');assert.notDeepEqual(after,before,'The actual 3D preview canvas must change after seeking actor animation.');assert.equal(await value<string>(page,'JSON.stringify(Littlewild.scenarioUI.editor.session.snapshot().scenes[0].initialState)'),native);assert.equal(await snapshot(page),active);assert.equal(await value<string>(page,'JSON.stringify([LWAssets.all(),LWCreatures.all()])'),catalogs,'Detached default asset preview must retain active catalog values.');
   await page.locator('[data-story="stop"]').click();assert((await page.locator('[data-story-time]').textContent())?.includes('0.00'));await page.locator('[data-story="replay"]').click();await page.waitForFunction(()=>document.querySelector('[data-story-time]')?.textContent?.includes('playing'));await page.locator('[data-story="pause"]').click();await seek(page,2.5);
   if(process.env.LITTLEWILD_CAPTURE_SCREENSHOTS==='1'){await page.locator('.storytelling-preview').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(OUT,'storytelling-timeline-3d-'+width+'.png'),animations:'disabled'});}
  });
  await test('Keyboard keyframe selection, actual property edit and invalid duplicate time retain the draft at '+width+'px',async()=>{
   const keys=page.locator('.storytelling-key');await keys.first().focus();await keys.first().press('ArrowRight');assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('data-index')),'1');await page.keyboard.press('Enter');await fill(page,'key',{time:'4',value:String(entity.x+3)});await submit(page,'key');assert.equal(await value<number>(page,'Littlewild.scenarioUI.editor.session.snapshot().storytelling.cutscenes[0].tracks[0].keyframes[1].time'),4);
   const before=await revision(page),draft=await value<string>(page,'JSON.stringify(Littlewild.scenarioUI.editor.session.snapshot())');await fill(page,'key',{time:'0'});await submit(page,'key');await page.locator('.storytelling-feedback.is-error').waitFor();assert((await page.locator('.storytelling-feedback.is-error').textContent())?.includes('Keyframe times'));assert.equal(await revision(page),before);assert.equal(await value<string>(page,'JSON.stringify(Littlewild.scenarioUI.editor.session.snapshot())'),draft);assert.equal(await page.locator('[data-story-form=key] [name=time]').inputValue(),'0');assert.equal(await snapshot(page),active);
  });
  await test('Typed p5 preset, creature pose and scene entry/completion events remain portable data at '+width+'px',async()=>{
   await page.locator('[data-story="new-track"]').click();await fill(page,'track',{id:'guide-gesture',first:'0',last:'1'});await select(page,'track','target','creatures:'+entity.id);await select(page,'track','property','pose');await submit(page,'track');
   await page.evaluate('LWAnimationExample.register();Littlewild.open("scene-editor")');await details(page,'p5 animation presets');assert.equal(await page.locator('[data-story-form=animation] [name=preset] option[value=gentle-pulse]').count(),1);await fill(page,'animation',{id:'arrival-sparkles',x:String(entity.x),y:String(entity.y),radius:'55',count:'24'});await select(page,'animation','preset','sparkles');await submit(page,'animation');await ready(page);await seek(page,2.5);assert.equal(await value<string>(page,'Littlewild.scenarioUI.editor.session.snapshot().storytelling.cutscenes[0].animations[0].presetId'),'sparkles');assert.equal(await page.locator('[data-p5-animation]').count(),1);const overlay=await pixels(page,'[data-p5-animation]');await seek(page,1.5);assert.notDeepEqual(await pixels(page,'[data-p5-animation]'),overlay,'The actual p5 preset must draw its sampled phase.');
   await details(page,'p5 animation presets');await fill(page,'animation',{id:'arrival-pulse',seed:'42',x:String(entity.x),y:String(entity.y)});await select(page,'animation','preset','gentle-pulse');await submit(page,'animation');assert.equal(await value<number>(page,'Littlewild.scenarioUI.editor.session.snapshot().storytelling.cutscenes[0].animations[1].seed'),42);
   await details(page,'Scene entry events');await select(page,'entry','event-type','play-cutscene');await select(page,'entry','event-clip','opening-clip');await submit(page,'entry');await details(page,'Timed cues & completion events');await select(page,'finish','event-type','scene-switch');await select(page,'finish','event-connection','story-travel');await submit(page,'finish');await details(page,'Scene triggers');await fill(page,'trigger',{id:'guide-ready',minimum:'1'});await select(page,'trigger','event-type','play-cutscene');await select(page,'trigger','event-clip','opening-clip');await submit(page,'trigger');const authored=await value<LWContentPorts.ScenarioPack>(page,'Littlewild.scenarioUI.editor.session.export()');assert.equal(authored.scenes[0]!.graph!.triggers![0]!.id,'guide-ready');assert(authored.scenes[0]!.graph!.events!.some(e=>e.type==='play-cutscene'));assert(authored.storytelling!.cutscenes[0]!.onFinish!.some(e=>e.type==='scene-switch'));assert.equal(await snapshot(page),active);
  });
  await test('Actual 2D preview renderer, storyboard cutscene ranges and full storytelling file review/cancellation at '+width+'px',async()=>{
   await page.locator('[data-story="new-clip"]').first().click();await fill(page,'create',{id:'remote-clip',name:'Remote arrival',duration:'5'});await select(page,'create','scene','story-remote');await submit(page,'create');await ready(page);await details(page,'Scene renderer & dimension');await select(page,'rendering','dimension','2d');await select(page,'rendering','renderer','pixi-2d');await submit(page,'rendering');await ready(page);
   await fill(page,'track',{id:'remote-guide',first:String(entity.x),last:String(entity.x+3)});await select(page,'track','target','creatures:'+entity.id);await select(page,'track','property','x');await submit(page,'track');await ready(page);const before=await pixels(page,'[data-story-preview]');await seek(page,2.5);assert.notDeepEqual(await pixels(page,'[data-story-preview]'),before,'PixiJS must draw the selected animation pose.');
   if(process.env.LITTLEWILD_CAPTURE_SCREENSHOTS==='1'){await page.locator('.storytelling-preview').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(OUT,'storytelling-timeline-2d-'+width+'.png'),animations:'disabled'});}
   await page.locator('[data-story="boards"]').click();await page.locator('[data-story="select-shot"][data-id="remote-shot"]').click();await select(page,'shot','cutscene','remote-clip');await fill(page,'shot',{start:'1',end:'4'});await submit(page,'shot');assert((await page.locator('.storytelling-shot').last().textContent())?.includes('1–4s'));await page.locator('[data-story="shot-timeline"][data-id="remote-clip"]').click();await ready(page);
   const event=page.waitForEvent('download');await page.locator('[data-story="export"]').click();const download=await event,location=await download.path();assert(location);assert(download.suggestedFilename().endsWith('.storytelling.json'));const bytes=fs.readFileSync(location),draft=await value<string>(page,'JSON.stringify(Littlewild.scenarioUI.editor.session.snapshot())'),current=await revision(page);
   await page.locator('#storytelling-import').setInputFiles({name:download.suggestedFilename(),mimeType:'application/json',buffer:bytes});await page.locator('[data-story="apply-import"]').waitFor();assert.equal(await page.evaluate(()=>(document.activeElement as HTMLElement).dataset.story),'cancel-import');await page.locator('[data-story="cancel-import"]').click();assert.equal(await revision(page),current);assert.equal(await value<string>(page,'JSON.stringify(Littlewild.scenarioUI.editor.session.snapshot())'),draft);assert.equal(await snapshot(page),active);
   await page.locator('#storytelling-import').setInputFiles({name:'malformed.storytelling.json',mimeType:'application/json',buffer:Buffer.from('{"version":1,"cutscenes":[{"callback":"alert(1)"}],"storyboards":[]}')});await page.locator('.storytelling-feedback.is-error').waitFor();assert.equal(await revision(page),current);assert.equal(await value<string>(page,'JSON.stringify(Littlewild.scenarioUI.editor.session.snapshot())'),draft);assert.equal(await snapshot(page),active);
   const imported=JSON.parse(bytes.toString()) as LWStorytelling.Data;imported.cutscenes.find(c=>c.id==='remote-clip')!.name='Remote arrival revised';await page.locator('#storytelling-import').setInputFiles({name:'revised.storytelling.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});await page.locator('[data-story=apply-import]').click();assert.equal(await revision(page),current+1);assert.equal(await value<string>(page,'Littlewild.scenarioUI.editor.session.snapshot().storytelling.cutscenes.find(c=>c.id==="remote-clip").name'),'Remote arrival revised');assert.equal(await snapshot(page),active);await ready(page);
  });
  await test('Mobile reflow, 44px controls and preview cleanup when returning to scenes at '+width+'px',async()=>{
   const metrics=await page.locator('.storytelling-workspace').evaluate(el=>({width:el.getBoundingClientRect().width,document:document.documentElement.scrollWidth,viewport:innerWidth,buttons:Array.from(el.querySelectorAll<HTMLButtonElement>('.btn,.storytelling-key')).filter(b=>b.getBoundingClientRect().height>0).map(b=>b.getBoundingClientRect().height)}));assert(metrics.width<=width);assert(metrics.document<=width);if(width===390)assert(metrics.buttons.every(h=>h>=44));await page.locator('[data-story="close"]').click();assert.equal(await page.locator('[data-p5-animation]').count(),0);assert(await page.locator('.scene-editor-layout').isVisible());assert.equal(await snapshot(page),active);
  });
  await test('Selection retains detached preview mounts and pending readiness; revision, clip, session and close dispose exact instances at '+width+'px',async()=>{
   await page.evaluate(async()=>{
    const root=window as unknown as {Littlewild:{open(id:string):void;scenarioUI:{editor:{session:LWSceneEditor.Session}}};LWSceneEditor:LWSceneEditor.Api;LWStorytellingUI:LWStorytellingUI.Api};
    const original=root.Littlewild.scenarioUI.editor.session.snapshot();root.Littlewild.open('scenarios');
    let session=root.LWSceneEditor.create(original),modal:string|null='scene-editor',surface:LWStorytellingUI.Surface;
    const mount=document.createElement('section');document.body.append(mount);
    const records:{canvas:HTMLCanvasElement;overlay:HTMLCanvasElement;disposed:number;resolve:(result:LittlewildRenderer.SwitchResult)=>void;status:LWStorytelling.Status}[]=[];
    const ensure=(condition:unknown,message:string)=>{if(!condition)throw Error(message);};
    const redraw=()=>{mount.innerHTML=surface.render();};
    surface=root.LWStorytellingUI.create({session:()=>session,sceneId:()=>original.scenes[0]!.id,modal:()=>modal,redraw,esc:value=>String(value).replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]!)),toast(){},preview(canvas,pack,id){
     ensure(canvas.isConnected&&canvas.parentElement,'Preview requires a connected mount');const clip=pack.storytelling!.cutscenes.find(clip=>clip.id===id)!,overlay=document.createElement('canvas');overlay.dataset.p5Animation='';canvas.parentElement!.append(overlay);
     let resolve:(result:LittlewildRenderer.SwitchResult)=>void=()=>{};const ready=new Promise<LittlewildRenderer.SwitchResult>(done=>{resolve=done;});
     const record={canvas,overlay,disposed:0,resolve,status:{cutsceneId:id,sceneId:clip.sceneId,state:'paused' as LWStorytelling.State,time:2.5,duration:clip.duration,completion:.5,generation:0}};records.push(record);
     return {ready,status:()=>record.status,draw(){},play(){record.status.state='playing';},pause(){record.status.state='paused';},stop(){record.status.time=0;},replay(){record.status.generation++;},seek(time){record.status.time=time;},dispose(){record.disposed++;overlay.remove();canvas.remove();}};
    }});
    const click=(action:string,id?:string)=>{const button=mount.querySelector<HTMLButtonElement>('[data-story="'+action+'"]'+(id?'[data-id="'+id+'"]':''));ensure(button,'Missing lifecycle control '+action);button!.click();surface.draw(0);};
    try{
     redraw();click('open');click('timeline');ensure(records.length===1,'First timeline prepares once');const first=records[0]!,wrapper=first.canvas.parentElement;click('select-track','guide-position');
     click('new-track');ensure(records.length===1&&first.canvas.isConnected&&first.overlay.isConnected&&first.canvas.parentElement===wrapper,'Selection retains exact wrapper and both canvases');ensure((document.activeElement as HTMLInputElement).name==='id','New track retains intended form focus');
     click('select-key','guide-position');ensure(records.length===1&&first.status.time===2.5,'Key selection retains paused sample');ensure((document.activeElement as HTMLInputElement).name==='time','Key selection focuses its new form');
     first.resolve({ok:true});await Promise.resolve();click('new-track');ensure(mount.querySelector('[data-story-preview-notice]')?.textContent?.includes('Detached scene ready'),'Readiness notice survives a selection redraw');
     session.replace(session.snapshot());surface.draw(0);ensure(first.disposed===1&&records.length===2&&!first.canvas.isConnected,'External revision rebuilds a connected mount once');const revised=records[1]!;
     click('select-clip','remote-clip');ensure(revised.disposed===1&&records.length===3,'Clip selection replaces the preview once');revised.resolve({ok:false,reason:'stale readiness'});await Promise.resolve();ensure(!mount.textContent?.includes('stale readiness'),'Disposed readiness cannot update the active mount');
     const prior=records[2]!,other=root.LWSceneEditor.create(session.snapshot());other.replace(other.snapshot());ensure(other.revision===session.revision,'Session identity probe holds revision equal');session=other;surface.draw(0);ensure(prior.disposed===1&&records.length===4,'Equal revision and clip on a different session invalidate');
     click('boards');ensure(records[3]!.disposed===1,'Leaving the timeline disposes once');click('timeline');ensure(records.length===5,'Returning prepares a fresh mount');click('close');ensure(records[4]!.disposed===1,'Closing disposes pending preparation once');records[4]!.resolve({ok:true});await Promise.resolve();ensure(!mount.querySelector('[data-story-preview]'),'Late readiness cannot restore a closed canvas');
     ensure(records.every(record=>record.disposed===1),'Every invalidated preview is disposed exactly once');
    }finally{modal=null;surface.cancel();mount.remove();}
   });assert.equal(await snapshot(page),active);
  });
  await page.close();
 }}finally{await context.close();await browser.close();}
 await test('Storytelling browser proof has no page/console errors or external requests',async()=>{assert.deepEqual(diagnostics.errors,[]);assert.deepEqual(diagnostics.consoleProblems,[]);assert.deepEqual(diagnostics.requests,[]);});
 fs.writeFileSync(path.join(OUT,'storytelling-browser-results.json'),JSON.stringify({suite:'storytelling-browser',passed:results.filter(r=>r.passed).length,total:results.length,results,diagnostics},null,2)+'\n');
}
main().catch(error=>{results.push({name:'Storytelling browser setup',passed:false,error:String(error)});console.error(error);}).finally(()=>{console.log(`Storytelling browser: ${results.filter(r=>r.passed).length}/${results.length} passed.`);if(results.some(r=>!r.passed))process.exitCode=1;});
